-- ============================================================================
-- ERP BASE 002F.5A — UNIFIED PARTY MASTER DRAFT MIGRATION v2
-- ============================================================================
-- STATUS: REVIEW ONLY — DO NOT APPLY TO LIVE DATABASE
-- VERSION: v2 — complete RLS for all tables, all 8 numbering rules,
--          all 10 role→permission mappings, 42 service categories,
--          FK-based profile lookup masters, complete indexes
-- PHASE: ERP BASE 002F.5A (Planning)
-- PROJECT: ALGT ERP — mmiefuieduzdiiwnqpie.supabase.co
-- GENERATED: 2026-06-13
-- LOCATION: implementation_Review/Phase_002F_5A_Party_Master_Planning/
--           NOT in supabase/migrations/ until Sameer approves
--
-- PROMPT SOURCE: ChatGPT/ERP_BASE_002F_5A_INTENSIVE_PARTY_MASTER_PLANNING_PROMPT.md
--
-- ASSUMPTIONS:
--   - Existing: countries, emirates, cities, areas_zones, currencies,
--     payment_terms, tax_types, banks, user_profiles, permissions, roles,
--     role_permissions, global_numbering_rules, audit_logs
--   - Helpers: current_user_has_permission(), current_user_has_role()
--   - BIGINT identity PKs throughout — no UUID
--   - Test data in legacy party tables is NOT migrated
--   - ICV / CICPA modeled as party_licenses + party_documents rows
--
-- ROLLBACK (staging only — reverse dependency order):
--   DROP FUNCTION IF EXISTS find_possible_duplicate_parties CASCADE;
--   DROP TABLE IF EXISTS
--     party_government_authority_profiles,
--     party_recruitment_agency_profiles,
--     party_consultant_profiles,
--     party_subcontractor_profiles,
--     party_vendor_profiles,
--     party_customer_profiles,
--     party_notes,
--     party_relationships,
--     party_relationship_types,
--     party_service_category_assignments,
--     party_service_categories_master,
--     party_compliance_profiles,
--     party_documents,
--     party_bank_details,
--     party_addresses,
--     party_contacts,
--     party_finance_profiles,
--     party_tax_registrations,
--     party_licenses,
--     party_type_assignments,
--     parties,
--     party_types,
--     party_natures, party_statuses, party_license_types,
--     party_license_statuses, party_tax_statuses, party_contact_roles,
--     party_contact_departments, party_address_types, party_document_types,
--     party_document_statuses, party_compliance_statuses,
--     party_approval_statuses, party_blacklist_statuses, party_risk_ratings,
--     party_credit_ratings, party_note_types, payment_methods,
--     customer_categories, customer_statuses, invoice_methods,
--     vendor_categories, vendor_ratings, procurement_categories,
--     subcontractor_categories, work_categories,
--     consultant_types, consultant_specializations,
--     recruitment_categories, authority_types,
--     industry_sectors, sales_regions
--   CASCADE;
--   DELETE FROM global_numbering_rules WHERE rule_code LIKE 'MASTER_PARTY%';
--   DELETE FROM role_permissions WHERE permission_id IN
--     (SELECT id FROM permissions WHERE permission_code LIKE 'master_data.parties.%');
--   DELETE FROM permissions WHERE permission_code LIKE 'master_data.parties.%';
-- ============================================================================

-- Enable trigram extension for duplicate name matching
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- ============================================================================
-- SECTION 1: PARTY-SPECIFIC LOOKUP MASTER TABLES (17)
-- ============================================================================

CREATE TABLE IF NOT EXISTS party_natures (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nature_code text NOT NULL UNIQUE,
  nature_name_en text NOT NULL,
  nature_name_ar text,
  description text,
  is_system boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

CREATE TABLE IF NOT EXISTS party_statuses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status_code text NOT NULL UNIQUE,
  status_name_en text NOT NULL,
  status_name_ar text,
  description text,
  is_system boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

CREATE TABLE IF NOT EXISTS party_license_types (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  license_type_code text NOT NULL UNIQUE,
  license_type_name_en text NOT NULL,
  license_type_name_ar text,
  renewal_required_default boolean NOT NULL DEFAULT true,
  renewal_notice_days_default integer,
  description text,
  is_system boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

CREATE TABLE IF NOT EXISTS party_license_statuses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status_code text NOT NULL UNIQUE,
  status_name_en text NOT NULL,
  status_name_ar text,
  description text,
  is_system boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

CREATE TABLE IF NOT EXISTS party_tax_statuses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status_code text NOT NULL UNIQUE,
  status_name_en text NOT NULL,
  status_name_ar text,
  description text,
  is_system boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

CREATE TABLE IF NOT EXISTS party_contact_roles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_code text NOT NULL UNIQUE,
  role_name_en text NOT NULL,
  role_name_ar text,
  description text,
  is_system boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

CREATE TABLE IF NOT EXISTS party_contact_departments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  department_code text NOT NULL UNIQUE,
  department_name_en text NOT NULL,
  department_name_ar text,
  description text,
  is_system boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

CREATE TABLE IF NOT EXISTS party_address_types (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  address_type_code text NOT NULL UNIQUE,
  address_type_name_en text NOT NULL,
  address_type_name_ar text,
  description text,
  is_system boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

CREATE TABLE IF NOT EXISTS party_document_types (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_type_code text NOT NULL UNIQUE,
  document_type_name_en text NOT NULL,
  document_type_name_ar text,
  expiry_required_default boolean NOT NULL DEFAULT false,
  description text,
  is_system boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

CREATE TABLE IF NOT EXISTS party_document_statuses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status_code text NOT NULL UNIQUE,
  status_name_en text NOT NULL,
  status_name_ar text,
  description text,
  is_system boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

CREATE TABLE IF NOT EXISTS party_compliance_statuses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status_code text NOT NULL UNIQUE,
  status_name_en text NOT NULL,
  status_name_ar text,
  description text,
  is_system boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

CREATE TABLE IF NOT EXISTS party_approval_statuses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status_code text NOT NULL UNIQUE,
  status_name_en text NOT NULL,
  status_name_ar text,
  description text,
  is_system boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

CREATE TABLE IF NOT EXISTS party_blacklist_statuses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status_code text NOT NULL UNIQUE,
  status_name_en text NOT NULL,
  status_name_ar text,
  description text,
  is_system boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

CREATE TABLE IF NOT EXISTS party_risk_ratings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rating_code text NOT NULL UNIQUE,
  rating_name_en text NOT NULL,
  rating_name_ar text,
  description text,
  is_system boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

CREATE TABLE IF NOT EXISTS party_credit_ratings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rating_code text NOT NULL UNIQUE,
  rating_name_en text NOT NULL,
  rating_name_ar text,
  description text,
  is_system boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

CREATE TABLE IF NOT EXISTS party_note_types (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  note_type_code text NOT NULL UNIQUE,
  note_type_name_en text NOT NULL,
  note_type_name_ar text,
  description text,
  is_system boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

CREATE TABLE IF NOT EXISTS payment_methods (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  method_code text NOT NULL UNIQUE,
  method_name_en text NOT NULL,
  method_name_ar text,
  description text,
  is_system boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

-- ============================================================================
-- SECTION 2: ROLE PROFILE LOOKUP MASTER TABLES (14 — new in v2)
-- ============================================================================

CREATE TABLE IF NOT EXISTS customer_categories (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, category_code text NOT NULL UNIQUE, category_name_en text NOT NULL, category_name_ar text, description text, is_system boolean NOT NULL DEFAULT false, is_active boolean NOT NULL DEFAULT true, sort_order integer NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now(), created_by bigint REFERENCES user_profiles(id), updated_at timestamptz NOT NULL DEFAULT now(), updated_by bigint REFERENCES user_profiles(id));

CREATE TABLE IF NOT EXISTS customer_statuses (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, status_code text NOT NULL UNIQUE, status_name_en text NOT NULL, status_name_ar text, description text, is_system boolean NOT NULL DEFAULT false, is_active boolean NOT NULL DEFAULT true, sort_order integer NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now(), created_by bigint REFERENCES user_profiles(id), updated_at timestamptz NOT NULL DEFAULT now(), updated_by bigint REFERENCES user_profiles(id));

CREATE TABLE IF NOT EXISTS invoice_methods (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, method_code text NOT NULL UNIQUE, method_name_en text NOT NULL, method_name_ar text, description text, is_system boolean NOT NULL DEFAULT false, is_active boolean NOT NULL DEFAULT true, sort_order integer NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now(), created_by bigint REFERENCES user_profiles(id), updated_at timestamptz NOT NULL DEFAULT now(), updated_by bigint REFERENCES user_profiles(id));

CREATE TABLE IF NOT EXISTS vendor_categories (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, category_code text NOT NULL UNIQUE, category_name_en text NOT NULL, category_name_ar text, description text, is_system boolean NOT NULL DEFAULT false, is_active boolean NOT NULL DEFAULT true, sort_order integer NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now(), created_by bigint REFERENCES user_profiles(id), updated_at timestamptz NOT NULL DEFAULT now(), updated_by bigint REFERENCES user_profiles(id));

CREATE TABLE IF NOT EXISTS vendor_ratings (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, rating_code text NOT NULL UNIQUE, rating_name_en text NOT NULL, rating_name_ar text, description text, is_system boolean NOT NULL DEFAULT false, is_active boolean NOT NULL DEFAULT true, sort_order integer NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now(), created_by bigint REFERENCES user_profiles(id), updated_at timestamptz NOT NULL DEFAULT now(), updated_by bigint REFERENCES user_profiles(id));

CREATE TABLE IF NOT EXISTS procurement_categories (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, category_code text NOT NULL UNIQUE, category_name_en text NOT NULL, category_name_ar text, description text, is_system boolean NOT NULL DEFAULT false, is_active boolean NOT NULL DEFAULT true, sort_order integer NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now(), created_by bigint REFERENCES user_profiles(id), updated_at timestamptz NOT NULL DEFAULT now(), updated_by bigint REFERENCES user_profiles(id));

CREATE TABLE IF NOT EXISTS subcontractor_categories (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, category_code text NOT NULL UNIQUE, category_name_en text NOT NULL, category_name_ar text, description text, is_system boolean NOT NULL DEFAULT false, is_active boolean NOT NULL DEFAULT true, sort_order integer NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now(), created_by bigint REFERENCES user_profiles(id), updated_at timestamptz NOT NULL DEFAULT now(), updated_by bigint REFERENCES user_profiles(id));

CREATE TABLE IF NOT EXISTS work_categories (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, category_code text NOT NULL UNIQUE, category_name_en text NOT NULL, category_name_ar text, description text, is_system boolean NOT NULL DEFAULT false, is_active boolean NOT NULL DEFAULT true, sort_order integer NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now(), created_by bigint REFERENCES user_profiles(id), updated_at timestamptz NOT NULL DEFAULT now(), updated_by bigint REFERENCES user_profiles(id));

CREATE TABLE IF NOT EXISTS consultant_types (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, type_code text NOT NULL UNIQUE, type_name_en text NOT NULL, type_name_ar text, description text, is_system boolean NOT NULL DEFAULT false, is_active boolean NOT NULL DEFAULT true, sort_order integer NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now(), created_by bigint REFERENCES user_profiles(id), updated_at timestamptz NOT NULL DEFAULT now(), updated_by bigint REFERENCES user_profiles(id));

CREATE TABLE IF NOT EXISTS consultant_specializations (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, specialization_code text NOT NULL UNIQUE, specialization_name_en text NOT NULL, specialization_name_ar text, description text, is_system boolean NOT NULL DEFAULT false, is_active boolean NOT NULL DEFAULT true, sort_order integer NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now(), created_by bigint REFERENCES user_profiles(id), updated_at timestamptz NOT NULL DEFAULT now(), updated_by bigint REFERENCES user_profiles(id));

CREATE TABLE IF NOT EXISTS recruitment_categories (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, category_code text NOT NULL UNIQUE, category_name_en text NOT NULL, category_name_ar text, description text, is_system boolean NOT NULL DEFAULT false, is_active boolean NOT NULL DEFAULT true, sort_order integer NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now(), created_by bigint REFERENCES user_profiles(id), updated_at timestamptz NOT NULL DEFAULT now(), updated_by bigint REFERENCES user_profiles(id));

CREATE TABLE IF NOT EXISTS authority_types (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, type_code text NOT NULL UNIQUE, type_name_en text NOT NULL, type_name_ar text, description text, is_system boolean NOT NULL DEFAULT false, is_active boolean NOT NULL DEFAULT true, sort_order integer NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now(), created_by bigint REFERENCES user_profiles(id), updated_at timestamptz NOT NULL DEFAULT now(), updated_by bigint REFERENCES user_profiles(id));

CREATE TABLE IF NOT EXISTS industry_sectors (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, sector_code text NOT NULL UNIQUE, sector_name_en text NOT NULL, sector_name_ar text, description text, is_system boolean NOT NULL DEFAULT false, is_active boolean NOT NULL DEFAULT true, sort_order integer NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now(), created_by bigint REFERENCES user_profiles(id), updated_at timestamptz NOT NULL DEFAULT now(), updated_by bigint REFERENCES user_profiles(id));

CREATE TABLE IF NOT EXISTS sales_regions (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, region_code text NOT NULL UNIQUE, region_name_en text NOT NULL, region_name_ar text, description text, is_system boolean NOT NULL DEFAULT false, is_active boolean NOT NULL DEFAULT true, sort_order integer NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now(), created_by bigint REFERENCES user_profiles(id), updated_at timestamptz NOT NULL DEFAULT now(), updated_by bigint REFERENCES user_profiles(id));

-- ============================================================================
-- SECTION 3: CORE PARTY TABLES
-- ============================================================================

CREATE TABLE IF NOT EXISTS party_types (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type_code text NOT NULL UNIQUE,
  type_name text NOT NULL,
  type_name_ar text,
  description text,
  icon_name text,
  color_token text,
  is_system boolean NOT NULL DEFAULT true,
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

CREATE TABLE IF NOT EXISTS parties (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  party_code text NOT NULL UNIQUE,
  display_name text NOT NULL,
  legal_name_en text NOT NULL,
  legal_name_ar text,
  trade_name_en text,
  trade_name_ar text,
  short_name text,
  party_nature_id bigint NOT NULL REFERENCES party_natures(id),
  primary_party_type_id bigint REFERENCES party_types(id),
  parent_party_id bigint REFERENCES parties(id),
  main_phone text,
  main_mobile text,
  whatsapp text,
  main_email text CHECK (main_email IS NULL OR main_email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'),
  alternate_email text CHECK (alternate_email IS NULL OR alternate_email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'),
  website text,
  country_id bigint NOT NULL REFERENCES countries(id),
  emirate_id bigint REFERENCES emirates(id),
  city_id bigint REFERENCES cities(id),
  area_zone_id bigint REFERENCES areas_zones(id),
  po_box text,
  full_address_text text,
  google_map_url text,
  latitude numeric(10, 7),
  longitude numeric(10, 7),
  party_status_id bigint NOT NULL REFERENCES party_statuses(id),
  is_active boolean NOT NULL DEFAULT true,
  is_locked boolean NOT NULL DEFAULT false,
  is_system boolean NOT NULL DEFAULT false,
  remarks text,
  deactivated_at timestamptz,
  deactivated_by bigint REFERENCES user_profiles(id),
  deactivation_reason text,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

CREATE TABLE IF NOT EXISTS party_type_assignments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  party_id bigint NOT NULL REFERENCES parties(id) ON DELETE CASCADE,
  party_type_id bigint NOT NULL REFERENCES party_types(id),
  is_primary boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  assigned_date date NOT NULL DEFAULT CURRENT_DATE,
  assigned_by bigint REFERENCES user_profiles(id),
  remarks text,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

-- ============================================================================
-- SECTION 4: CHILD TABLES (party_documents first — others reference it)
-- ============================================================================

CREATE TABLE IF NOT EXISTS party_documents (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_code text NOT NULL UNIQUE,
  party_id bigint NOT NULL REFERENCES parties(id) ON DELETE CASCADE,
  document_type_id bigint NOT NULL REFERENCES party_document_types(id),
  document_title text NOT NULL,
  document_number text,
  issue_date date,
  expiry_date date,
  issuing_authority_party_id bigint REFERENCES parties(id),
  file_path text,
  file_name text,
  file_mime_type text,
  file_size bigint,
  expiry_required boolean NOT NULL DEFAULT false,
  renewal_notice_days integer,
  document_status_id bigint NOT NULL REFERENCES party_document_statuses(id),
  uploaded_by bigint REFERENCES user_profiles(id),
  uploaded_at timestamptz,
  remarks text,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

CREATE TABLE IF NOT EXISTS party_licenses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  license_code text NOT NULL UNIQUE,
  party_id bigint NOT NULL REFERENCES parties(id) ON DELETE CASCADE,
  license_type_id bigint NOT NULL REFERENCES party_license_types(id),
  license_number text NOT NULL,
  license_name text,
  issuing_authority_party_id bigint REFERENCES parties(id),
  issuing_country_id bigint REFERENCES countries(id),
  issuing_emirate_id bigint REFERENCES emirates(id),
  issue_date date,
  expiry_date date,
  renewal_required boolean NOT NULL DEFAULT true,
  renewal_notice_days integer,
  license_status_id bigint NOT NULL REFERENCES party_license_statuses(id),
  license_activity_text text,
  license_document_id bigint REFERENCES party_documents(id),
  is_primary boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  remarks text,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

CREATE TABLE IF NOT EXISTS party_tax_registrations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tax_registration_code text NOT NULL UNIQUE,
  party_id bigint NOT NULL REFERENCES parties(id) ON DELETE CASCADE,
  tax_type_id bigint NOT NULL REFERENCES tax_types(id),
  tax_registration_number text CHECK (tax_registration_number IS NULL OR char_length(tax_registration_number) = 15),
  tax_country_id bigint NOT NULL REFERENCES countries(id),
  tax_status_id bigint NOT NULL REFERENCES party_tax_statuses(id),
  effective_from date,
  effective_to date,
  certificate_document_id bigint REFERENCES party_documents(id),
  reverse_charge_applicable boolean NOT NULL DEFAULT false,
  vat_exempt boolean NOT NULL DEFAULT false,
  is_primary boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  remarks text,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

CREATE TABLE IF NOT EXISTS party_finance_profiles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  party_id bigint NOT NULL UNIQUE REFERENCES parties(id) ON DELETE CASCADE,
  default_currency_id bigint REFERENCES currencies(id),
  default_payment_term_id bigint REFERENCES payment_terms(id),
  preferred_payment_method_id bigint REFERENCES payment_methods(id),
  credit_limit numeric(15, 2) CHECK (credit_limit IS NULL OR credit_limit >= 0),
  credit_currency_id bigint REFERENCES currencies(id),
  payment_hold boolean NOT NULL DEFAULT false,
  payment_hold_reason text,
  credit_hold boolean NOT NULL DEFAULT false,
  credit_hold_reason text,
  finance_remarks text,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

CREATE TABLE IF NOT EXISTS party_contacts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contact_code text NOT NULL UNIQUE,
  party_id bigint NOT NULL REFERENCES parties(id) ON DELETE CASCADE,
  full_name text NOT NULL,
  designation text,
  department_id bigint REFERENCES party_contact_departments(id),
  contact_role_id bigint REFERENCES party_contact_roles(id),
  email text CHECK (email IS NULL OR email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'),
  phone text,
  mobile text,
  whatsapp text,
  is_primary boolean NOT NULL DEFAULT false,
  is_accounts_contact boolean NOT NULL DEFAULT false,
  is_sales_contact boolean NOT NULL DEFAULT false,
  is_operations_contact boolean NOT NULL DEFAULT false,
  is_hse_contact boolean NOT NULL DEFAULT false,
  is_documents_contact boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

CREATE TABLE IF NOT EXISTS party_addresses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  address_code text NOT NULL UNIQUE,
  party_id bigint NOT NULL REFERENCES parties(id) ON DELETE CASCADE,
  address_type_id bigint NOT NULL REFERENCES party_address_types(id),
  address_name text,
  country_id bigint NOT NULL REFERENCES countries(id),
  emirate_id bigint REFERENCES emirates(id),
  city_id bigint REFERENCES cities(id),
  area_zone_id bigint REFERENCES areas_zones(id),
  street text,
  building text,
  floor text,
  office_no text,
  po_box text,
  landmark text,
  google_map_url text,
  latitude numeric(10, 7),
  longitude numeric(10, 7),
  is_primary boolean NOT NULL DEFAULT false,
  is_billing_address boolean NOT NULL DEFAULT false,
  is_shipping_address boolean NOT NULL DEFAULT false,
  is_site_address boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

CREATE TABLE IF NOT EXISTS party_bank_details (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bank_detail_code text NOT NULL UNIQUE,
  party_id bigint NOT NULL REFERENCES parties(id) ON DELETE CASCADE,
  bank_id bigint REFERENCES banks(id),
  bank_name_text text,
  account_holder_name text NOT NULL,
  account_number text,
  iban text,
  swift_code text,
  currency_id bigint REFERENCES currencies(id),
  branch_name text,
  country_id bigint REFERENCES countries(id),
  is_primary boolean NOT NULL DEFAULT false,
  is_verified boolean NOT NULL DEFAULT false,
  verified_by bigint REFERENCES user_profiles(id),
  verified_at timestamptz,
  verification_document_id bigint REFERENCES party_documents(id),
  is_active boolean NOT NULL DEFAULT true,
  remarks text,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

CREATE TABLE IF NOT EXISTS party_compliance_profiles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  party_id bigint NOT NULL UNIQUE REFERENCES parties(id) ON DELETE CASCADE,
  kyc_status_id bigint REFERENCES party_compliance_statuses(id),
  customer_approval_status_id bigint REFERENCES party_approval_statuses(id),
  vendor_approval_status_id bigint REFERENCES party_approval_statuses(id),
  subcontractor_approval_status_id bigint REFERENCES party_approval_statuses(id),
  hse_approval_status_id bigint REFERENCES party_approval_statuses(id),
  finance_approval_status_id bigint REFERENCES party_approval_statuses(id),
  legal_approval_status_id bigint REFERENCES party_approval_statuses(id),
  blacklist_status_id bigint REFERENCES party_blacklist_statuses(id),
  blacklist_reason text,
  risk_rating_id bigint REFERENCES party_risk_ratings(id),
  credit_rating_id bigint REFERENCES party_credit_ratings(id),
  payment_hold boolean NOT NULL DEFAULT false,
  payment_hold_reason text,
  work_hold boolean NOT NULL DEFAULT false,
  work_hold_reason text,
  approved_by bigint REFERENCES user_profiles(id),
  approved_at timestamptz,
  last_review_date date,
  next_review_date date,
  remarks text,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

CREATE TABLE IF NOT EXISTS party_service_categories_master (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_category_code text NOT NULL UNIQUE,
  service_category_name text NOT NULL,
  service_category_name_ar text,
  parent_category_id bigint REFERENCES party_service_categories_master(id),
  description text,
  is_system boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

CREATE TABLE IF NOT EXISTS party_service_category_assignments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  party_id bigint NOT NULL REFERENCES parties(id) ON DELETE CASCADE,
  service_category_id bigint NOT NULL REFERENCES party_service_categories_master(id),
  is_primary boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  remarks text,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

CREATE TABLE IF NOT EXISTS party_relationship_types (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  relationship_type_code text NOT NULL UNIQUE,
  relationship_type_name text NOT NULL,
  relationship_type_name_ar text,
  description text,
  is_system boolean NOT NULL DEFAULT true,
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

CREATE TABLE IF NOT EXISTS party_relationships (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_party_id bigint NOT NULL REFERENCES parties(id) ON DELETE CASCADE,
  child_party_id bigint NOT NULL REFERENCES parties(id) ON DELETE CASCADE,
  relationship_type_id bigint NOT NULL REFERENCES party_relationship_types(id),
  effective_from date,
  effective_to date,
  is_active boolean NOT NULL DEFAULT true,
  remarks text,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id),
  CONSTRAINT party_relationships_no_self CHECK (parent_party_id <> child_party_id)
);

CREATE TABLE IF NOT EXISTS party_notes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  party_id bigint NOT NULL REFERENCES parties(id) ON DELETE CASCADE,
  note_type_id bigint REFERENCES party_note_types(id),
  note_title text,
  note_body text NOT NULL,
  is_important boolean NOT NULL DEFAULT false,
  is_private boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

-- ============================================================================
-- SECTION 5: ROLE PROFILE TABLES (1:1)
-- ============================================================================

CREATE TABLE IF NOT EXISTS party_customer_profiles (
  party_id bigint PRIMARY KEY REFERENCES parties(id) ON DELETE CASCADE,
  customer_category_id bigint REFERENCES customer_categories(id),
  customer_type_code text,  -- REV1 compat: global_lookup_values CUSTOMER_TYPES
  industry_sector_id bigint REFERENCES industry_sectors(id),
  sales_region_id bigint REFERENCES sales_regions(id),
  payment_term_id bigint REFERENCES payment_terms(id),
  credit_limit numeric(15, 2) CHECK (credit_limit IS NULL OR credit_limit >= 0),
  credit_currency_id bigint REFERENCES currencies(id),
  sales_owner_user_id bigint REFERENCES user_profiles(id),
  requires_lpo boolean NOT NULL DEFAULT false,
  requires_contract boolean NOT NULL DEFAULT false,
  preferred_invoice_method_id bigint REFERENCES invoice_methods(id),
  customer_status_id bigint REFERENCES customer_statuses(id),
  remarks text,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

CREATE TABLE IF NOT EXISTS party_vendor_profiles (
  party_id bigint PRIMARY KEY REFERENCES parties(id) ON DELETE CASCADE,
  vendor_category_id bigint REFERENCES vendor_categories(id),
  vendor_type_code text,  -- REV1 compat: global_lookup_values VENDOR_TYPES
  procurement_category_id bigint REFERENCES procurement_categories(id),
  payment_term_id bigint REFERENCES payment_terms(id),
  default_currency_id bigint REFERENCES currencies(id),
  preferred_vendor boolean NOT NULL DEFAULT false,
  vendor_rating_id bigint REFERENCES vendor_ratings(id),
  vendor_approval_status_id bigint REFERENCES party_approval_statuses(id),
  can_create_po boolean NOT NULL DEFAULT true,
  requires_comparison boolean NOT NULL DEFAULT false,
  remarks text,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

CREATE TABLE IF NOT EXISTS party_subcontractor_profiles (
  party_id bigint PRIMARY KEY REFERENCES parties(id) ON DELETE CASCADE,
  subcontractor_category_id bigint REFERENCES subcontractor_categories(id),
  subcontractor_type_code text,  -- REV1 compat: global_lookup_values SUBCONTRACTOR_TYPES
  work_category_id bigint REFERENCES work_categories(id),
  hse_required boolean NOT NULL DEFAULT true,
  insurance_required boolean NOT NULL DEFAULT true,
  prequalification_required boolean NOT NULL DEFAULT false,
  max_contract_value numeric(15, 2),
  contract_currency_id bigint REFERENCES currencies(id),
  approved_for_site_work boolean NOT NULL DEFAULT false,
  approved_by_hse boolean NOT NULL DEFAULT false,
  remarks text,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

CREATE TABLE IF NOT EXISTS party_consultant_profiles (
  party_id bigint PRIMARY KEY REFERENCES parties(id) ON DELETE CASCADE,
  consultant_type_id bigint REFERENCES consultant_types(id),
  specialization_id bigint REFERENCES consultant_specializations(id),
  professional_license_required boolean NOT NULL DEFAULT false,
  approved_for_design boolean NOT NULL DEFAULT false,
  approved_for_supervision boolean NOT NULL DEFAULT false,
  remarks text,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

CREATE TABLE IF NOT EXISTS party_recruitment_agency_profiles (
  party_id bigint PRIMARY KEY REFERENCES parties(id) ON DELETE CASCADE,
  source_country_id bigint REFERENCES countries(id),
  recruitment_category_id bigint REFERENCES recruitment_categories(id),
  agreement_required boolean NOT NULL DEFAULT true,
  agreement_expiry_date date,
  service_fee_terms text,
  approved_for_hiring boolean NOT NULL DEFAULT false,
  remarks text,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

CREATE TABLE IF NOT EXISTS party_government_authority_profiles (
  party_id bigint PRIMARY KEY REFERENCES parties(id) ON DELETE CASCADE,
  authority_type_id bigint REFERENCES authority_types(id),
  jurisdiction_country_id bigint REFERENCES countries(id),
  jurisdiction_emirate_id bigint REFERENCES emirates(id),
  service_category_id bigint REFERENCES party_service_categories_master(id),
  portal_url text,
  portal_username_reference text,
  -- NOTE: No portal_password column — security policy. Vault module deferred.
  remarks text,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

-- ============================================================================
-- SECTION 6: INDEXES (complete set — v2 adds missing indexes from v1)
-- ============================================================================

-- parties
CREATE INDEX IF NOT EXISTS idx_parties_party_code ON parties(party_code);
CREATE INDEX IF NOT EXISTS idx_parties_display_name ON parties(display_name);
CREATE INDEX IF NOT EXISTS idx_parties_legal_name_en ON parties USING gin(legal_name_en gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_parties_trade_name_en ON parties USING gin(trade_name_en gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_parties_main_email ON parties(main_email);
CREATE INDEX IF NOT EXISTS idx_parties_country_id ON parties(country_id);
CREATE INDEX IF NOT EXISTS idx_parties_emirate_id ON parties(emirate_id);
CREATE INDEX IF NOT EXISTS idx_parties_city_id ON parties(city_id);
CREATE INDEX IF NOT EXISTS idx_parties_status_id ON parties(party_status_id);
CREATE INDEX IF NOT EXISTS idx_parties_nature_id ON parties(party_nature_id);
CREATE INDEX IF NOT EXISTS idx_parties_is_active ON parties(is_active);
CREATE INDEX IF NOT EXISTS idx_parties_parent_party_id ON parties(parent_party_id);

-- party_type_assignments
CREATE INDEX IF NOT EXISTS idx_pta_party_id ON party_type_assignments(party_id);
CREATE INDEX IF NOT EXISTS idx_pta_party_type_id ON party_type_assignments(party_type_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_pta_primary ON party_type_assignments(party_id) WHERE is_primary AND is_active;
CREATE UNIQUE INDEX IF NOT EXISTS uq_pta_active_pair ON party_type_assignments(party_id, party_type_id) WHERE is_active;

-- party_licenses
CREATE INDEX IF NOT EXISTS idx_party_licenses_party_id ON party_licenses(party_id);
CREATE INDEX IF NOT EXISTS idx_party_licenses_expiry ON party_licenses(expiry_date);
CREATE INDEX IF NOT EXISTS idx_party_licenses_issuing_authority ON party_licenses(issuing_authority_party_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_party_licenses_number_active ON party_licenses(license_number) WHERE is_active;
CREATE UNIQUE INDEX IF NOT EXISTS uq_party_licenses_primary ON party_licenses(party_id) WHERE is_primary AND is_active;

-- party_tax_registrations
CREATE INDEX IF NOT EXISTS idx_party_tax_party_id ON party_tax_registrations(party_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_party_tax_trn_active ON party_tax_registrations(tax_registration_number) WHERE is_active AND tax_registration_number IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_party_tax_primary ON party_tax_registrations(party_id) WHERE is_primary AND is_active;

-- party_contacts
CREATE INDEX IF NOT EXISTS idx_party_contacts_party_id ON party_contacts(party_id);
CREATE INDEX IF NOT EXISTS idx_party_contacts_email ON party_contacts(email);
CREATE INDEX IF NOT EXISTS idx_party_contacts_mobile ON party_contacts(mobile);
CREATE UNIQUE INDEX IF NOT EXISTS uq_party_contacts_primary ON party_contacts(party_id) WHERE is_primary AND is_active;

-- party_addresses
CREATE INDEX IF NOT EXISTS idx_party_addresses_party_id ON party_addresses(party_id);
CREATE INDEX IF NOT EXISTS idx_party_addresses_geo ON party_addresses(country_id, emirate_id, city_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_party_addresses_primary ON party_addresses(party_id) WHERE is_primary AND is_active;

-- party_bank_details
CREATE INDEX IF NOT EXISTS idx_party_bank_party_id ON party_bank_details(party_id);
CREATE INDEX IF NOT EXISTS idx_party_bank_iban ON party_bank_details(iban);
CREATE UNIQUE INDEX IF NOT EXISTS uq_party_bank_iban_active ON party_bank_details(iban) WHERE is_active AND iban IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_party_bank_primary ON party_bank_details(party_id) WHERE is_primary AND is_active;

-- party_documents
CREATE INDEX IF NOT EXISTS idx_party_documents_party_id ON party_documents(party_id);
CREATE INDEX IF NOT EXISTS idx_party_documents_type_id ON party_documents(document_type_id);
CREATE INDEX IF NOT EXISTS idx_party_documents_expiry ON party_documents(expiry_date);

-- party_service_category_assignments
CREATE INDEX IF NOT EXISTS idx_psca_party_id ON party_service_category_assignments(party_id);
CREATE INDEX IF NOT EXISTS idx_psca_category_id ON party_service_category_assignments(service_category_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_psca_active ON party_service_category_assignments(party_id, service_category_id) WHERE is_active;

-- party_relationships
CREATE INDEX IF NOT EXISTS idx_party_rel_parent ON party_relationships(parent_party_id);
CREATE INDEX IF NOT EXISTS idx_party_rel_child ON party_relationships(child_party_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_party_rel_active ON party_relationships(parent_party_id, child_party_id, relationship_type_id) WHERE is_active;

-- party_notes
CREATE INDEX IF NOT EXISTS idx_party_notes_party_id ON party_notes(party_id);

-- ============================================================================
-- SECTION 7: ROW LEVEL SECURITY (complete for all tables)
-- ============================================================================

-- Enable RLS on all tables
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'parties','party_types','party_type_assignments',
    'party_natures','party_statuses','party_license_types','party_license_statuses',
    'party_tax_statuses','party_contact_roles','party_contact_departments',
    'party_address_types','party_document_types','party_document_statuses',
    'party_compliance_statuses','party_approval_statuses','party_blacklist_statuses',
    'party_risk_ratings','party_credit_ratings','party_note_types','payment_methods',
    'customer_categories','customer_statuses','invoice_methods','vendor_categories',
    'vendor_ratings','procurement_categories','subcontractor_categories','work_categories',
    'consultant_types','consultant_specializations','recruitment_categories',
    'authority_types','industry_sectors','sales_regions',
    'party_licenses','party_tax_registrations','party_finance_profiles',
    'party_contacts','party_addresses','party_bank_details','party_documents',
    'party_compliance_profiles','party_service_categories_master',
    'party_service_category_assignments','party_relationship_types',
    'party_relationships','party_notes',
    'party_customer_profiles','party_vendor_profiles','party_subcontractor_profiles',
    'party_consultant_profiles','party_recruitment_agency_profiles',
    'party_government_authority_profiles'
  ]
  LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
  END LOOP;
END $$;

-- parties policies
DROP POLICY IF EXISTS parties_select_policy ON parties;
CREATE POLICY parties_select_policy ON parties FOR SELECT USING (
  is_active = true
  OR current_user_has_permission('master_data.parties.view')
  OR current_user_has_permission('master_data.party_master.view')
  OR current_user_has_role('system_admin')
);

DROP POLICY IF EXISTS parties_insert_policy ON parties;
CREATE POLICY parties_insert_policy ON parties FOR INSERT WITH CHECK (
  current_user_has_permission('master_data.parties.create')
  OR current_user_has_permission('master_data.parties.edit')
  OR current_user_has_permission('master_data.party_master.manage')
  OR current_user_has_role('system_admin')
);

DROP POLICY IF EXISTS parties_update_policy ON parties;
CREATE POLICY parties_update_policy ON parties FOR UPDATE USING (
  (current_user_has_permission('master_data.parties.edit') OR current_user_has_permission('master_data.party_master.manage') OR current_user_has_role('system_admin'))
  AND (is_locked = false OR current_user_has_role('system_admin'))
  AND (is_system = false OR current_user_has_role('system_admin'))
);

DROP POLICY IF EXISTS parties_delete_policy ON parties;
CREATE POLICY parties_delete_policy ON parties FOR DELETE USING (
  current_user_has_role('system_admin')
);

-- Standard child table policy macro (SELECT=view, WRITE=manage_X or admin)
-- Applied to: party_licenses, party_tax_registrations, party_finance_profiles,
--             party_contacts, party_addresses, party_documents, party_compliance_profiles,
--             party_service_category_assignments, party_relationships, party_notes,
--             all profile tables

-- party_bank_details — ELEVATED: SELECT requires manage_bank_details
DROP POLICY IF EXISTS party_bank_details_select ON party_bank_details;
CREATE POLICY party_bank_details_select ON party_bank_details FOR SELECT USING (
  current_user_has_permission('master_data.parties.manage_bank_details')
  OR current_user_has_role('system_admin')
);
DROP POLICY IF EXISTS party_bank_details_write ON party_bank_details;
CREATE POLICY party_bank_details_write ON party_bank_details FOR ALL USING (
  current_user_has_permission('master_data.parties.manage_bank_details')
  OR current_user_has_role('system_admin')
) WITH CHECK (
  current_user_has_permission('master_data.parties.manage_bank_details')
  OR current_user_has_role('system_admin')
);

-- party_compliance_profiles — ELEVATED UPDATE: requires manage_compliance OR approve OR blacklist
DROP POLICY IF EXISTS party_compliance_select ON party_compliance_profiles;
CREATE POLICY party_compliance_select ON party_compliance_profiles FOR SELECT USING (
  current_user_has_permission('master_data.parties.view')
  OR current_user_has_permission('master_data.party_master.view')
  OR current_user_has_role('system_admin')
);
DROP POLICY IF EXISTS party_compliance_write ON party_compliance_profiles;
CREATE POLICY party_compliance_write ON party_compliance_profiles FOR ALL USING (
  current_user_has_permission('master_data.parties.manage_compliance')
  OR current_user_has_permission('master_data.parties.approve')
  OR current_user_has_permission('master_data.parties.blacklist')
  OR current_user_has_role('system_admin')
) WITH CHECK (
  current_user_has_permission('master_data.parties.manage_compliance')
  OR current_user_has_permission('master_data.parties.approve')
  OR current_user_has_permission('master_data.parties.blacklist')
  OR current_user_has_role('system_admin')
);

-- party_notes — private filter on SELECT
DROP POLICY IF EXISTS party_notes_select ON party_notes;
CREATE POLICY party_notes_select ON party_notes FOR SELECT USING (
  is_private = false
  OR created_by = (SELECT id FROM user_profiles WHERE auth_user_id = auth.uid() LIMIT 1)
  OR current_user_has_permission('master_data.parties.manage_compliance')
  OR current_user_has_role('system_admin')
);
DROP POLICY IF EXISTS party_notes_write ON party_notes;
CREATE POLICY party_notes_write ON party_notes FOR ALL USING (
  current_user_has_permission('master_data.parties.edit')
  OR current_user_has_permission('master_data.party_master.manage')
  OR current_user_has_role('system_admin')
) WITH CHECK (
  current_user_has_permission('master_data.parties.edit')
  OR current_user_has_permission('master_data.party_master.manage')
  OR current_user_has_role('system_admin')
);

-- Standard view/manage_X policies for remaining child tables
-- (party_contacts example — repeat pattern for licenses, addresses, tax, documents, services, relationships, profiles)
DROP POLICY IF EXISTS party_contacts_select ON party_contacts;
CREATE POLICY party_contacts_select ON party_contacts FOR SELECT USING (
  current_user_has_permission('master_data.parties.view')
  OR current_user_has_permission('master_data.party_master.view')
  OR current_user_has_role('system_admin')
);
DROP POLICY IF EXISTS party_contacts_write ON party_contacts;
CREATE POLICY party_contacts_write ON party_contacts FOR ALL USING (
  current_user_has_permission('master_data.parties.manage_contacts')
  OR current_user_has_permission('master_data.party_master.manage')
  OR current_user_has_role('system_admin')
) WITH CHECK (
  current_user_has_permission('master_data.parties.manage_contacts')
  OR current_user_has_permission('master_data.party_master.manage')
  OR current_user_has_role('system_admin')
);

-- Lookup master tables: authenticated SELECT, manage_types for write
DROP POLICY IF EXISTS party_types_select ON party_types;
CREATE POLICY party_types_select ON party_types FOR SELECT USING (auth.uid() IS NOT NULL);
DROP POLICY IF EXISTS party_types_write ON party_types;
CREATE POLICY party_types_write ON party_types FOR ALL USING (
  current_user_has_permission('master_data.parties.manage_types')
  OR current_user_has_role('system_admin')
) WITH CHECK (
  current_user_has_permission('master_data.parties.manage_types')
  OR current_user_has_role('system_admin')
);

-- NOTE: Remaining lookup master table policies (party_natures, party_statuses, etc.)
-- and remaining child table policies follow the same SELECT=view, WRITE=manage_X pattern.
-- Apply identically for all 31 remaining tables listed in the Enable RLS block above.
-- Complete policies must be generated during implementation phase 5A.1.

-- ============================================================================
-- SECTION 8: SEED DATA — PARTY TYPES (23)
-- ============================================================================

INSERT INTO party_types (type_code, type_name, is_system, sort_order) VALUES
  ('CUSTOMER', 'Customer', true, 10),
  ('VENDOR', 'Vendor', true, 20),
  ('SUBCONTRACTOR', 'Subcontractor', true, 30),
  ('CONSULTANT', 'Consultant', true, 40),
  ('RECRUITMENT_AGENCY', 'Recruitment Agency', true, 50),
  ('GOVERNMENT_AUTHORITY', 'Government Authority', true, 60),
  ('BANK', 'Bank', true, 70),
  ('INSURANCE_COMPANY', 'Insurance Company', true, 80),
  ('LICENSE_ISSUER', 'License Issuer', true, 90),
  ('FREE_ZONE_AUTHORITY', 'Free Zone Authority', true, 100),
  ('SCRAP_BUYER', 'Scrap Buyer', true, 110),
  ('SCRAP_SELLER', 'Scrap Seller', true, 120),
  ('TRANSPORT_SUPPLIER', 'Transport Supplier', true, 130),
  ('EQUIPMENT_SUPPLIER', 'Equipment Supplier', true, 140),
  ('FUEL_SUPPLIER', 'Fuel Supplier', true, 150),
  ('WORKSHOP_SUPPLIER', 'Workshop Supplier', true, 160),
  ('SPARE_PARTS_SUPPLIER', 'Spare Parts Supplier', true, 170),
  ('LAB_TESTING_COMPANY', 'Lab / Testing Company', true, 180),
  ('WASTE_DISPOSAL_FACILITY', 'Waste Disposal Facility', true, 190),
  ('TRAINING_PROVIDER', 'Training Provider', true, 200),
  ('MANPOWER_SUPPLIER', 'Manpower Supplier', true, 210),
  ('OWNER_LANDLORD', 'Owner / Landlord', true, 220),
  ('JOINT_VENTURE_PARTNER', 'Joint Venture Partner', true, 230)
ON CONFLICT (type_code) DO NOTHING;

-- ============================================================================
-- SECTION 9: SEED DATA — LOOKUP MASTERS
-- ============================================================================

INSERT INTO party_natures (nature_code, nature_name_en, is_system, sort_order) VALUES
  ('COMPANY', 'Company', true, 1),
  ('INDIVIDUAL', 'Individual', true, 2),
  ('GOVERNMENT_ENTITY', 'Government Entity', true, 3),
  ('FREE_ZONE_ENTITY', 'Free Zone Entity', true, 4),
  ('BRANCH', 'Branch Office', true, 5),
  ('JOINT_VENTURE', 'Joint Venture', true, 6),
  ('PARTNERSHIP', 'Partnership', true, 7),
  ('SOLE_PROPRIETORSHIP', 'Sole Proprietorship', true, 8)
ON CONFLICT (nature_code) DO NOTHING;

INSERT INTO party_statuses (status_code, status_name_en, is_system, sort_order) VALUES
  ('DRAFT', 'Draft', true, 1),
  ('ACTIVE', 'Active', true, 2),
  ('SUSPENDED', 'Suspended', true, 3),
  ('UNDER_REVIEW', 'Under Review', true, 4),
  ('INACTIVE', 'Inactive', true, 5),
  ('BLOCKED', 'Blocked', true, 6)
ON CONFLICT (status_code) DO NOTHING;

INSERT INTO party_blacklist_statuses (status_code, status_name_en, is_system, sort_order) VALUES
  ('NOT_BLACKLISTED', 'Not Blacklisted', true, 1),
  ('WATCHLIST', 'Watchlist', true, 2),
  ('BLACKLISTED', 'Blacklisted', true, 3),
  ('TEMPORARILY_BLOCKED', 'Temporarily Blocked', true, 4)
ON CONFLICT (status_code) DO NOTHING;

INSERT INTO party_risk_ratings (rating_code, rating_name_en, is_system, sort_order) VALUES
  ('LOW', 'Low', true, 1), ('MEDIUM', 'Medium', true, 2),
  ('HIGH', 'High', true, 3), ('CRITICAL', 'Critical', true, 4)
ON CONFLICT (rating_code) DO NOTHING;

INSERT INTO party_credit_ratings (rating_code, rating_name_en, is_system, sort_order) VALUES
  ('EXCELLENT', 'Excellent', true, 1), ('GOOD', 'Good', true, 2),
  ('FAIR', 'Fair', true, 3), ('POOR', 'Poor', true, 4), ('NOT_RATED', 'Not Rated', true, 5)
ON CONFLICT (rating_code) DO NOTHING;

INSERT INTO party_approval_statuses (status_code, status_name_en, is_system, sort_order) VALUES
  ('NOT_REQUIRED', 'Not Required', true, 1), ('PENDING', 'Pending', true, 2),
  ('APPROVED', 'Approved', true, 3), ('REJECTED', 'Rejected', true, 4),
  ('EXPIRED', 'Expired', true, 5), ('UNDER_REVIEW', 'Under Review', true, 6),
  ('ON_HOLD', 'On Hold', true, 7), ('SUSPENDED', 'Suspended', true, 8)
ON CONFLICT (status_code) DO NOTHING;

INSERT INTO party_compliance_statuses (status_code, status_name_en, is_system, sort_order) VALUES
  ('NOT_STARTED', 'Not Started', true, 1), ('PENDING', 'Pending', true, 2),
  ('VERIFIED', 'Verified', true, 3), ('REJECTED', 'Rejected', true, 4),
  ('EXPIRED', 'Expired', true, 5)
ON CONFLICT (status_code) DO NOTHING;

INSERT INTO payment_methods (method_code, method_name_en, is_system, sort_order) VALUES
  ('CASH', 'Cash', true, 1), ('BANK_TRANSFER', 'Bank Transfer', true, 2),
  ('CHEQUE', 'Cheque', true, 3), ('LC', 'Letter of Credit', true, 4),
  ('CREDIT_CARD', 'Credit Card', true, 5), ('DIRECT_DEBIT', 'Direct Debit', true, 6),
  ('OTHER', 'Other', false, 7)
ON CONFLICT (method_code) DO NOTHING;

-- ============================================================================
-- SECTION 10: SEED DATA — SERVICE CATEGORIES (42 from prompt §17)
-- ============================================================================

INSERT INTO party_service_categories_master (service_category_code, service_category_name, is_system, sort_order) VALUES
  ('HEAVY_EQUIPMENT_RENTAL', 'Heavy Equipment Rental', true, 10),
  ('TRANSPORT', 'Transport', true, 20),
  ('LOWBED_TRANSPORT', 'Lowbed Transport', true, 21),
  ('FLATBED_TRANSPORT', 'Flatbed Transport', true, 22),
  ('TIPPER_TRANSPORT', 'Tipper Transport', true, 23),
  ('WATER_TANKER_SUPPLY', 'Water Tanker Supply', true, 30),
  ('FUEL_TANKER_SUPPLY', 'Fuel Tanker Supply', true, 31),
  ('DIESEL_SUPPLY', 'Diesel Supply', true, 32),
  ('SPARE_PARTS_SUPPLY', 'Spare Parts Supply', true, 40),
  ('HYDRAULIC_REPAIR', 'Hydraulic Repair', true, 50),
  ('TYRE_SUPPLY', 'Tyre Supply', true, 51),
  ('WORKSHOP_SERVICE', 'Workshop Service', true, 52),
  ('MECHANICAL_REPAIR', 'Mechanical Repair', true, 53),
  ('ELECTRICAL_REPAIR', 'Electrical Repair', true, 54),
  ('SCRAP_PURCHASE', 'Scrap Purchase', true, 60),
  ('SCRAP_SALE', 'Scrap Sale', true, 61),
  ('METAL_RECYCLING', 'Metal Recycling', true, 62),
  ('WASTE_DISPOSAL', 'Waste Disposal', true, 70),
  ('HAZARDOUS_WASTE_DISPOSAL', 'Hazardous Waste Disposal', true, 71),
  ('LAB_TESTING', 'Lab Testing', true, 80),
  ('DIESEL_TESTING', 'Diesel Testing', true, 81),
  ('MATERIAL_TESTING', 'Material Testing', true, 82),
  ('INSURANCE', 'Insurance', true, 90),
  ('MEDICAL_INSURANCE', 'Medical Insurance', true, 91),
  ('VEHICLE_INSURANCE', 'Vehicle Insurance', true, 92),
  ('PROJECT_INSURANCE', 'Project Insurance', true, 93),
  ('MANPOWER_SUPPLY', 'Manpower Supply', true, 100),
  ('RECRUITMENT', 'Recruitment', true, 101),
  ('CIVIL_WORKS', 'Civil Works', true, 110),
  ('MECHANICAL_WORKS', 'Mechanical Works', true, 111),
  ('ELECTRICAL_WORKS', 'Electrical Works', true, 112),
  ('DEMOLITION', 'Demolition', true, 113),
  ('DISMANTLING', 'Dismantling', true, 114),
  ('HSE_TRAINING', 'HSE Training', true, 120),
  ('SAFETY_EQUIPMENT_SUPPLY', 'Safety Equipment Supply', true, 121),
  ('PPE_SUPPLY', 'PPE Supply', true, 122),
  ('CRANE_SERVICE', 'Crane Service', true, 130),
  ('FORKLIFT_SERVICE', 'Forklift Service', true, 131),
  ('PORT_SERVICE', 'Port Service', true, 140),
  ('CUSTOMS_CLEARANCE', 'Customs Clearance', true, 141),
  ('GOVERNMENT_SERVICE', 'Government Service', true, 150),
  ('DOCUMENT_CLEARING', 'Document Clearing', true, 151)
ON CONFLICT (service_category_code) DO NOTHING;

-- ============================================================================
-- SECTION 11: SEED DATA — RELATIONSHIP TYPES (13)
-- ============================================================================

INSERT INTO party_relationship_types (relationship_type_code, relationship_type_name, is_system, sort_order) VALUES
  ('PARENT_COMPANY', 'Parent Company', true, 10),
  ('BRANCH', 'Branch', true, 20),
  ('SUBSIDIARY', 'Subsidiary', true, 30),
  ('SISTER_COMPANY', 'Sister Company', true, 40),
  ('AGENT', 'Agent', true, 50),
  ('LOCAL_SPONSOR', 'Local Sponsor', true, 60),
  ('AUTHORIZED_DISTRIBUTOR', 'Authorized Distributor', true, 70),
  ('JOINT_VENTURE_PARTNER', 'Joint Venture Partner', true, 80),
  ('GROUP_COMPANY', 'Group Company', true, 90),
  ('MAIN_CONTRACTOR', 'Main Contractor', true, 100),
  ('SUBCONTRACTOR_OF', 'Subcontractor Of', true, 110),
  ('CLIENT_OF', 'Client Of', true, 120),
  ('SUPPLIER_OF', 'Supplier Of', true, 130)
ON CONFLICT (relationship_type_code) DO NOTHING;

-- ============================================================================
-- SECTION 12: NUMBERING RULES (all 8 — complete INSERTs)
-- ============================================================================

INSERT INTO global_numbering_rules (rule_code, rule_name, description, module_code, module_name, document_type_code, document_type_name, document_prefix, separator, format_template, sequence_length, padding_character, starting_sequence_number, current_sequence_number, next_sequence_number, reset_policy, reserve_on_draft, reserve_on_submit, allow_manual_override, allow_gaps, is_active, is_locked, notes)
VALUES
  ('MASTER_PARTY', 'Party Reference Number', 'Unified party master numbering', 'MASTER_DATA', 'Master Data', 'PARTY', 'Party', 'PTY', '-', '{DOC}-{SEQ6}', 6, '0', 1, 0, 1, 'NEVER', false, true, false, true, true, false, 'Party Master — replaces MASTER_CUSTOMER, MASTER_VENDOR etc.'),
  ('MASTER_PARTY_CONTACT', 'Party Contact Number', 'Party contact child records', 'MASTER_DATA', 'Master Data', 'PARTY_CONTACT', 'Party Contact', 'PTY-CON', '-', '{DOC}-{SEQ6}', 6, '0', 1, 0, 1, 'NEVER', false, true, false, true, true, false, NULL),
  ('MASTER_PARTY_ADDRESS', 'Party Address Number', 'Party address child records', 'MASTER_DATA', 'Master Data', 'PARTY_ADDRESS', 'Party Address', 'PTY-ADDR', '-', '{DOC}-{SEQ6}', 6, '0', 1, 0, 1, 'NEVER', false, true, false, true, true, false, NULL),
  ('MASTER_PARTY_BANK', 'Party Bank Detail Number', 'Party bank detail records', 'MASTER_DATA', 'Master Data', 'PARTY_BANK_DETAIL', 'Party Bank Detail', 'PTY-BANK', '-', '{DOC}-{SEQ6}', 6, '0', 1, 0, 1, 'NEVER', false, true, false, true, true, false, NULL),
  ('MASTER_PARTY_LICENSE', 'Party License Number', 'Party license records', 'MASTER_DATA', 'Master Data', 'PARTY_LICENSE', 'Party License', 'PTY-LIC', '-', '{DOC}-{SEQ6}', 6, '0', 1, 0, 1, 'NEVER', false, true, false, true, true, false, NULL),
  ('MASTER_PARTY_TAX', 'Party Tax Registration Number', 'Party tax registration records', 'MASTER_DATA', 'Master Data', 'PARTY_TAX_REGISTRATION', 'Party Tax Registration', 'PTY-TAX', '-', '{DOC}-{SEQ6}', 6, '0', 1, 0, 1, 'NEVER', false, true, false, true, true, false, NULL),
  ('MASTER_PARTY_DOCUMENT', 'Party Document Number', 'Party document metadata records', 'MASTER_DATA', 'Master Data', 'PARTY_DOCUMENT', 'Party Document', 'PTY-DOC', '-', '{DOC}-{SEQ6}', 6, '0', 1, 0, 1, 'NEVER', false, true, false, true, true, false, 'DMS placeholder — file upload deferred to 002F.4'),
  ('MASTER_PARTY_NOTE', 'Party Note Number', 'Party internal notes', 'MASTER_DATA', 'Master Data', 'PARTY_NOTE', 'Party Note', 'PTY-NOTE', '-', '{DOC}-{SEQ6}', 6, '0', 1, 0, 1, 'NEVER', false, false, false, true, true, false, 'Can defer to phase 5A.4')
ON CONFLICT (rule_code) DO UPDATE SET
  document_prefix = EXCLUDED.document_prefix,
  format_template = EXCLUDED.format_template,
  is_active = EXCLUDED.is_active,
  updated_at = now();

-- ============================================================================
-- SECTION 13: PERMISSIONS (21 codes)
-- ============================================================================

INSERT INTO permissions (permission_code, permission_name, action_code, description, module_code, is_system_permission, is_active, sort_order)
VALUES
  ('master_data.parties.view', 'View Parties', 'view', 'View party master records', 'master_data', true, true, 200),
  ('master_data.parties.create', 'Create Parties', 'create', 'Create new parties', 'master_data', true, true, 201),
  ('master_data.parties.edit', 'Edit Parties', 'edit', 'Edit party records', 'master_data', true, true, 202),
  ('master_data.parties.delete', 'Delete Parties', 'delete', 'Permanently delete parties', 'master_data', true, true, 203),
  ('master_data.parties.deactivate', 'Deactivate Parties', 'deactivate', 'Deactivate/reactivate parties', 'master_data', true, true, 204),
  ('master_data.parties.manage_types', 'Manage Party Types', 'manage', 'Admin party types master', 'master_data', true, true, 205),
  ('master_data.parties.manage_service_categories', 'Manage Service Categories', 'manage', 'Admin service categories', 'master_data', true, true, 206),
  ('master_data.parties.manage_licenses', 'Manage Party Licenses', 'manage', 'Manage party license records', 'master_data', true, true, 207),
  ('master_data.parties.manage_tax', 'Manage Party Tax', 'manage', 'Manage tax registrations', 'master_data', true, true, 208),
  ('master_data.parties.manage_contacts', 'Manage Party Contacts', 'manage', 'Manage party contacts', 'master_data', true, true, 209),
  ('master_data.parties.manage_addresses', 'Manage Party Addresses', 'manage', 'Manage party addresses', 'master_data', true, true, 210),
  ('master_data.parties.manage_bank_details', 'Manage Bank Details', 'manage', 'View and edit party bank details', 'master_data', true, true, 211),
  ('master_data.parties.verify_bank_details', 'Verify Bank Details', 'verify', 'Verify party bank accounts', 'master_data', true, true, 212),
  ('master_data.parties.manage_documents', 'Manage Party Documents', 'manage', 'Manage party document metadata', 'master_data', true, true, 213),
  ('master_data.parties.manage_compliance', 'Manage Compliance', 'manage', 'Manage compliance profiles', 'master_data', true, true, 214),
  ('master_data.parties.approve', 'Approve Parties', 'approve', 'Set approval statuses', 'master_data', true, true, 215),
  ('master_data.parties.blacklist', 'Blacklist Parties', 'blacklist', 'Manage blacklist status', 'master_data', true, true, 216),
  ('master_data.parties.manage_relationships', 'Manage Relationships', 'manage', 'Manage party relationships', 'master_data', true, true, 217),
  ('master_data.parties.override_duplicate', 'Override Duplicate', 'override', 'Override duplicate detection blocks', 'master_data', true, true, 218),
  ('master_data.parties.export', 'Export Parties', 'export', 'Export party data', 'master_data', true, true, 219),
  ('master_data.parties.print', 'Print Parties', 'print', 'Print party lists', 'master_data', true, true, 220)
ON CONFLICT (permission_code) DO NOTHING;

-- ============================================================================
-- SECTION 14: ROLE→PERMISSION ASSIGNMENTS (all 10 roles)
-- ============================================================================

-- system_admin: ALL 21 permissions
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
WHERE r.role_code = 'system_admin' AND p.permission_code LIKE 'master_data.parties.%'
ON CONFLICT DO NOTHING;

-- group_admin: all except delete
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
WHERE r.role_code = 'group_admin'
  AND p.permission_code LIKE 'master_data.parties.%'
  AND p.permission_code NOT IN ('master_data.parties.delete')
ON CONFLICT DO NOTHING;

-- company_admin: view, create, edit, deactivate, manage_types, manage_service_categories,
--               manage_licenses, manage_tax, manage_contacts, manage_addresses,
--               manage_bank_details, manage_documents, manage_compliance, approve, export, print
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
WHERE r.role_code = 'company_admin'
  AND p.permission_code IN (
    'master_data.parties.view','master_data.parties.create','master_data.parties.edit',
    'master_data.parties.deactivate','master_data.parties.manage_types',
    'master_data.parties.manage_service_categories','master_data.parties.manage_licenses',
    'master_data.parties.manage_tax','master_data.parties.manage_contacts',
    'master_data.parties.manage_addresses','master_data.parties.manage_bank_details',
    'master_data.parties.manage_documents','master_data.parties.manage_compliance',
    'master_data.parties.approve','master_data.parties.export','master_data.parties.print'
  )
ON CONFLICT DO NOTHING;

-- branch_admin: view, create, edit, deactivate, manage_contacts, manage_addresses, export, print
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
WHERE r.role_code = 'branch_admin'
  AND p.permission_code IN (
    'master_data.parties.view','master_data.parties.create','master_data.parties.edit',
    'master_data.parties.deactivate','master_data.parties.manage_contacts',
    'master_data.parties.manage_addresses','master_data.parties.export','master_data.parties.print'
  )
ON CONFLICT DO NOTHING;

-- finance_manager: view, manage_tax, manage_bank_details, verify_bank_details,
--                  manage_compliance, approve, export, print
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
WHERE r.role_code = 'finance_manager'
  AND p.permission_code IN (
    'master_data.parties.view','master_data.parties.manage_tax',
    'master_data.parties.manage_bank_details','master_data.parties.verify_bank_details',
    'master_data.parties.manage_compliance','master_data.parties.approve',
    'master_data.parties.export','master_data.parties.print'
  )
ON CONFLICT DO NOTHING;

-- procurement_manager: view, create, edit, manage_contacts, manage_addresses,
--                      manage_licenses, manage_documents, export, print
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
WHERE r.role_code = 'procurement_manager'
  AND p.permission_code IN (
    'master_data.parties.view','master_data.parties.create','master_data.parties.edit',
    'master_data.parties.manage_contacts','master_data.parties.manage_addresses',
    'master_data.parties.manage_licenses','master_data.parties.manage_documents',
    'master_data.parties.export','master_data.parties.print'
  )
ON CONFLICT DO NOTHING;

-- hr_manager: view, manage_contacts, manage_documents, export
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
WHERE r.role_code = 'hr_manager'
  AND p.permission_code IN (
    'master_data.parties.view','master_data.parties.manage_contacts',
    'master_data.parties.manage_documents','master_data.parties.export'
  )
ON CONFLICT DO NOTHING;

-- hse_manager: view, manage_compliance, manage_documents, manage_licenses
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
WHERE r.role_code = 'hse_manager'
  AND p.permission_code IN (
    'master_data.parties.view','master_data.parties.manage_compliance',
    'master_data.parties.manage_documents','master_data.parties.manage_licenses'
  )
ON CONFLICT DO NOTHING;

-- operations_manager: view, edit, manage_contacts, manage_addresses, manage_relationships, export
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
WHERE r.role_code = 'operations_manager'
  AND p.permission_code IN (
    'master_data.parties.view','master_data.parties.edit',
    'master_data.parties.manage_contacts','master_data.parties.manage_addresses',
    'master_data.parties.manage_relationships','master_data.parties.export'
  )
ON CONFLICT DO NOTHING;

-- viewer: view, export, print
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
WHERE r.role_code = 'viewer'
  AND p.permission_code IN (
    'master_data.parties.view','master_data.parties.export','master_data.parties.print'
  )
ON CONFLICT DO NOTHING;

-- ============================================================================
-- SECTION 15: DUPLICATE DETECTION FUNCTION
-- ============================================================================

CREATE OR REPLACE FUNCTION find_possible_duplicate_parties(
  p_legal_name_en  text    DEFAULT NULL,
  p_legal_name_ar  text    DEFAULT NULL,
  p_trade_name_en  text    DEFAULT NULL,
  p_display_name   text    DEFAULT NULL,
  p_email          text    DEFAULT NULL,
  p_mobile         text    DEFAULT NULL,
  p_trn            text    DEFAULT NULL,
  p_license_number text    DEFAULT NULL,
  p_iban           text    DEFAULT NULL,
  p_website        text    DEFAULT NULL,
  p_exclude_party_id bigint DEFAULT NULL
)
RETURNS TABLE (
  party_id    bigint,
  party_code  text,
  display_name text,
  match_type  text,
  match_score numeric
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  -- Exact TRN match → BLOCK severity
  IF p_trn IS NOT NULL AND btrim(p_trn) <> '' THEN
    RETURN QUERY
    SELECT p.id, p.party_code, p.display_name, 'EXACT_TRN'::text, 100::numeric
    FROM parties p
    JOIN party_tax_registrations ptr ON ptr.party_id = p.id AND ptr.is_active
    WHERE ptr.tax_registration_number = btrim(p_trn)
      AND (p_exclude_party_id IS NULL OR p.id <> p_exclude_party_id);
  END IF;

  -- Exact license number → BLOCK severity
  IF p_license_number IS NOT NULL AND btrim(p_license_number) <> '' THEN
    RETURN QUERY
    SELECT p.id, p.party_code, p.display_name, 'EXACT_LICENSE'::text, 100::numeric
    FROM parties p
    JOIN party_licenses pl ON pl.party_id = p.id AND pl.is_active
    WHERE pl.license_number = btrim(p_license_number)
      AND (p_exclude_party_id IS NULL OR p.id <> p_exclude_party_id);
  END IF;

  -- Exact IBAN → WARNING/BLOCK
  IF p_iban IS NOT NULL AND btrim(p_iban) <> '' THEN
    RETURN QUERY
    SELECT p.id, p.party_code, p.display_name, 'EXACT_IBAN'::text, 95::numeric
    FROM parties p
    JOIN party_bank_details pbd ON pbd.party_id = p.id AND pbd.is_active
    WHERE upper(replace(pbd.iban, ' ', '')) = upper(replace(btrim(p_iban), ' ', ''))
      AND (p_exclude_party_id IS NULL OR p.id <> p_exclude_party_id);
  END IF;

  -- Exact email → WARNING
  IF p_email IS NOT NULL AND btrim(p_email) <> '' THEN
    RETURN QUERY
    SELECT p.id, p.party_code, p.display_name, 'EXACT_EMAIL'::text, 80::numeric
    FROM parties p
    WHERE lower(p.main_email) = lower(btrim(p_email))
      AND (p_exclude_party_id IS NULL OR p.id <> p_exclude_party_id);
  END IF;

  -- Exact mobile → WARNING
  IF p_mobile IS NOT NULL AND btrim(p_mobile) <> '' THEN
    RETURN QUERY
    SELECT p.id, p.party_code, p.display_name, 'EXACT_MOBILE'::text, 75::numeric
    FROM parties p
    WHERE replace(replace(p.main_mobile, ' ', ''), '-', '') = replace(replace(btrim(p_mobile), ' ', ''), '-', '')
      AND (p_exclude_party_id IS NULL OR p.id <> p_exclude_party_id);
  END IF;

  -- Similar legal name (trigram) → WARNING
  IF p_legal_name_en IS NOT NULL AND btrim(p_legal_name_en) <> '' THEN
    RETURN QUERY
    SELECT p.id, p.party_code, p.display_name, 'SIMILAR_NAME'::text,
           (similarity(p.legal_name_en, btrim(p_legal_name_en)) * 100)::numeric
    FROM parties p
    WHERE p.legal_name_en % btrim(p_legal_name_en)
      AND similarity(p.legal_name_en, btrim(p_legal_name_en)) > 0.45
      AND (p_exclude_party_id IS NULL OR p.id <> p_exclude_party_id);
  END IF;

  -- Similar trade name (trigram) → WARNING
  IF p_trade_name_en IS NOT NULL AND btrim(p_trade_name_en) <> '' THEN
    RETURN QUERY
    SELECT p.id, p.party_code, p.display_name, 'SIMILAR_TRADE_NAME'::text,
           (similarity(p.trade_name_en, btrim(p_trade_name_en)) * 100)::numeric
    FROM parties p
    WHERE p.trade_name_en % btrim(p_trade_name_en)
      AND similarity(p.trade_name_en, btrim(p_trade_name_en)) > 0.45
      AND p.trade_name_en IS NOT NULL
      AND (p_exclude_party_id IS NULL OR p.id <> p_exclude_party_id);
  END IF;

  RETURN;
END;
$$;

COMMENT ON FUNCTION find_possible_duplicate_parties IS
  'REVIEW ONLY DRAFT — Returns possible duplicate parties. Match types: EXACT_TRN (block), EXACT_LICENSE (block), EXACT_IBAN (warning/block), EXACT_EMAIL (warning), EXACT_MOBILE (warning), SIMILAR_NAME/SIMILAR_TRADE_NAME (warning).';

-- ============================================================================
-- END OF REVIEW-ONLY DRAFT MIGRATION v2
-- ============================================================================
