/**
 * ERP Export Menu Component
 * Phase 002E.2  - Export Engine Foundation
 * Phase 002E.3D - Email Integration
 * Phase REPORT.3 - Template / Branding / Output Adapter Engine
 *
 * Reusable dropdown menu for Print, PDF, Excel, CSV, and Email exports.
 * REPORT.3 adds optional branding/template props — all existing callers remain unaffected.
 */

"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuGroup,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { Download, FileDown, FileSpreadsheet, FileText, Printer, Loader2, MailPlus } from "lucide-react";
import { toast } from "sonner";
import {
  exportToCSV,
  exportToExcel,
  exportToPDF,
  exportToPrint,
  generateCSVAttachment,
  generateExcelAttachment,
  generatePDFAttachment,
  type ERPExportColumn,
  type ERPExportOptions,
  type ExportBrandingContext,
} from "@/lib/export";
import { ERPSendEmailDialog } from "@/components/erp/email/erp-send-email-dialog";
import type { AttachmentOption, PreparedEmailInput } from "@/components/erp/email/email-types-ui";
import { sendExportEmail } from "@/server/actions/email";
import { format } from "date-fns";

export interface ERPExportMenuProps<T = any> {
  /** Report title */
  title: string;
  /** Filename base (without extension) */
  filename: string;
  /** Data to export */
  data: T[];
  /** Column definitions */
  columns: ERPExportColumn<T>[];
  /** Optional subtitle */
  subtitle?: string;
  /** Optional filters display */
  filters?: Record<string, unknown>;
  /** Disable export menu */
  disabled?: boolean;
  /** Optional user name for "Generated by" */
  generatedBy?: string;
  /** Button variant */
  variant?: "default" | "outline" | "ghost";
  /** Button size */
  size?: "default" | "sm" | "lg" | "icon";
  /** Show button text or icon only */
  showText?: boolean;
  /** Page orientation */
  orientation?: "portrait" | "landscape";
  /** Module code for permission checks and audit logging (Phase 002E.3D) */
  moduleCode?: string;
  /** Export mode for tracking (Phase 002E.3D) */
  exportMode?: "selected" | "filtered" | "all";
  // ── REPORT.3: optional branding/template props ──────────────────────────────
  /** Report code from the global registry (e.g. "HR_EMPLOYEE_LIST") */
  reportCode?: string;
  /** Resolved branding context — when present, output is branded */
  resolvedTemplate?: ExportBrandingContext | null;
  /** Owner company IDs present in the data set */
  ownerCompanyIds?: number[];
  /**
   * When true, PDF/Print/Excel/Email export is blocked until the caller
   * provides a template selection. Call `onRequireTemplateSelection` before proceeding.
   */
  requiresTemplateSelection?: boolean;
  /** Called when export is triggered but requires a template to be selected first */
  onRequireTemplateSelection?: () => void;
  /** ID of the currently selected template (used for audit) */
  selectedTemplateId?: number;
}

export function ERPExportMenu<T = any>({
  title,
  filename,
  data,
  columns,
  subtitle,
  filters,
  disabled = false,
  generatedBy,
  variant = "outline",
  size = "sm",
  showText = true,
  orientation = "portrait",
  moduleCode,
  exportMode = "all",
  reportCode,
  resolvedTemplate,
  requiresTemplateSelection = false,
  onRequireTemplateSelection,
  selectedTemplateId,
}: ERPExportMenuProps<T>) {
  const [isExporting, setIsExporting] = useState(false);
  const [exportType, setExportType] = useState<string | null>(null);
  
  // Email dialog state (Phase 002E.3D)
  const [isEmailDialogOpen, setIsEmailDialogOpen] = useState(false);
  const [isSendingEmail, setIsSendingEmail] = useState(false);

  // Check if data is available
  const hasData = data && data.length > 0;
  const isDisabled = disabled || !hasData || isExporting || isSendingEmail;

  /**
   * Handle export action.
   * If requiresTemplateSelection=true and the export format requires branding
   * (pdf / print / excel / email), we block and call onRequireTemplateSelection instead.
   */
  const handleExport = async (type: "csv" | "excel" | "pdf" | "print") => {
    if (isDisabled) return;

    // REPORT.3: block branded exports when template selection is required
    const templateRequiredFormats: Array<typeof type> = ["pdf", "print", "excel"];
    if (requiresTemplateSelection && templateRequiredFormats.includes(type)) {
      onRequireTemplateSelection?.();
      return;
    }

    setIsExporting(true);
    setExportType(type);

    try {
      // Prepare export options (branding forwarded if present)
      const options: ERPExportOptions<T> = {
        title,
        subtitle,
        filename,
        columns,
        data,
        generatedBy,
        generatedAt: new Date(),
        filters: filters as any,
        orientation,
        exportMode,
        rowCount: data.length,
        branding: resolvedTemplate ? { ...resolvedTemplate, reportCode } : undefined,
      };

      // Execute export based on type
      let result;
      switch (type) {
        case "csv":
          result = exportToCSV(options);
          break;
        case "excel":
          result = exportToExcel(options);
          break;
        case "pdf":
          result = exportToPDF(options);
          break;
        case "print":
          result = exportToPrint(options);
          break;
      }

      // Show result toast
      if (result.success) {
        if (type === "print") {
          toast.success("Print dialog opened");
        } else {
          toast.success(`${type.toUpperCase()} file downloaded: ${result.filename}`);
        }
      } else {
        toast.error(result.error || `Failed to export ${type.toUpperCase()}`);
      }
    } catch (error) {
      console.error(`Export error (${type}):`, error);
      toast.error(`An error occurred during ${type.toUpperCase()} export`);
    } finally {
      setIsExporting(false);
      setExportType(null);
    }
  };
  
  /**
   * Handle send email (Phase 002E.3D)
   * 
   * Calls server action to send email via Microsoft Graph
   */
  const handleSendEmail = async (input: PreparedEmailInput): Promise<{ success: boolean; error?: string }> => {
    if (!input.attachment) {
      toast.error("No attachment generated");
      return { success: false, error: "No attachment" };
    }
    
    setIsSendingEmail(true);
    
    try {
      // Parse email strings to arrays
      const toEmails = input.to
        .split(/[,;\n]/)
        .map((e) => e.trim())
        .filter((e) => e);
      
      const ccEmails = input.cc
        ? input.cc
            .split(/[,;\n]/)
            .map((e) => e.trim())
            .filter((e) => e)
        : undefined;
      
      const bccEmails = input.bcc
        ? input.bcc
            .split(/[,;\n]/)
            .map((e) => e.trim())
            .filter((e) => e)
        : undefined;
      
      // Call server action
      const result = await sendExportEmail({
        to: toEmails,
        cc: ccEmails,
        bcc: bccEmails,
        subject: input.subject,
        body: input.body,
        attachment: input.attachment,
        context: {
          moduleCode,
          recordCount: data.length,
          exportMode,
        },
      });
      
      if (result.success) {
        toast.success("Email sent successfully!");
        setIsEmailDialogOpen(false);
      } else {
        toast.error(result.error || "Failed to send email");
      }
      
      return result;
    } catch (error) {
      console.error("[ERPExportMenu] Send email error:", error);
      const errorMessage = error instanceof Error ? error.message : "Failed to send email. Please try again.";
      toast.error(errorMessage);
      return { success: false, error: errorMessage };
    } finally {
      setIsSendingEmail(false);
    }
  };

  return (
    <>
      <DropdownMenu>
        <DropdownMenuTrigger
          disabled={isDisabled}
          className={`inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:size-4 [&_svg]:shrink-0 ${variant === "outline" ? "border border-input bg-background hover:bg-accent hover:text-accent-foreground" : ""} ${size === "sm" ? "h-9 px-3 text-xs gap-1.5" : "h-10 px-4 py-2 gap-2"}`}
        >
          {isExporting || isSendingEmail ? (
            <Loader2 className="h-3.5 w-3.5 animate-spin" />
          ) : (
            <Download className="h-3.5 w-3.5" />
          )}
          {showText && (
            <span>
              {isSendingEmail 
                ? "Sending..." 
                : isExporting 
                  ? `Exporting ${exportType}...` 
                  : "Export"}
            </span>
          )}
        </DropdownMenuTrigger>
        <DropdownMenuContent align="end" className="w-48">
          <DropdownMenuGroup>
            <DropdownMenuLabel className="text-xs font-semibold text-muted-foreground">
              Export Options
            </DropdownMenuLabel>
            <DropdownMenuSeparator />
            <DropdownMenuItem
              onClick={() => handleExport("print")}
              disabled={isExporting || isSendingEmail}
              className="cursor-pointer"
            >
              <Printer className="mr-2 h-4 w-4" />
              <span>Print</span>
            </DropdownMenuItem>
            <DropdownMenuItem
              onClick={() => handleExport("pdf")}
              disabled={isExporting || isSendingEmail}
              className="cursor-pointer"
            >
              <FileText className="mr-2 h-4 w-4" />
              <span>Export to PDF</span>
            </DropdownMenuItem>
            <DropdownMenuItem
              onClick={() => handleExport("excel")}
              disabled={isExporting || isSendingEmail}
              className="cursor-pointer"
            >
              <FileSpreadsheet className="mr-2 h-4 w-4" />
              <span>Export to Excel</span>
            </DropdownMenuItem>
            <DropdownMenuItem
              onClick={() => handleExport("csv")}
              disabled={isExporting || isSendingEmail}
              className="cursor-pointer"
            >
              <FileDown className="mr-2 h-4 w-4" />
              <span>Export to CSV</span>
            </DropdownMenuItem>
            <DropdownMenuSeparator />
            <DropdownMenuItem
              onClick={() => {
                if (requiresTemplateSelection) {
                  onRequireTemplateSelection?.();
                  return;
                }
                setIsEmailDialogOpen(true);
              }}
              disabled={isExporting || isSendingEmail}
              className="cursor-pointer"
            >
              <MailPlus className="mr-2 h-4 w-4" />
              <span>Send by Email</span>
            </DropdownMenuItem>
          </DropdownMenuGroup>
        </DropdownMenuContent>
      </DropdownMenu>

      {/* Email Dialog (Phase 002E.3D) */}
      <ERPSendEmailDialog
        open={isEmailDialogOpen}
        onOpenChange={setIsEmailDialogOpen}
        title={title}
        subtitle={subtitle}
        defaultSubject={`${title} - ${format(new Date(), "yyyy-MM-dd")}`}
        defaultBody={`Dear Sir/Madam,

Please find attached the ${title.toLowerCase()} report.

${subtitle ? `${subtitle}\n` : ""}
Total Records: ${data.length}
Export Mode: ${exportMode === "selected" ? "Selected Rows" : exportMode === "filtered" ? "Filtered Rows" : "All Rows"}
Generated: ${format(new Date(), "yyyy-MM-dd HH:mm")}
${generatedBy ? `Generated By: ${generatedBy}` : ""}

Best Regards`}
        attachmentOptions={[
          {
            type: "pdf",
            label: "PDF",
            filename,
            generateAttachment: () =>
              generatePDFAttachment({
                title,
                subtitle,
                filename,
                columns,
                data,
                generatedBy,
                generatedAt: new Date(),
                filters: filters as any,
                orientation,
                exportMode,
                rowCount: data.length,
                branding: resolvedTemplate ? { ...resolvedTemplate, reportCode } : undefined,
              }),
          },
          {
            type: "excel",
            label: "Excel",
            filename,
            generateAttachment: () =>
              generateExcelAttachment({
                title,
                subtitle,
                filename,
                columns,
                data,
                generatedBy,
                generatedAt: new Date(),
                filters: filters as any,
                orientation,
                exportMode,
                rowCount: data.length,
                branding: resolvedTemplate ? { ...resolvedTemplate, reportCode } : undefined,
              }),
          },
          {
            type: "csv",
            label: "CSV",
            filename,
            generateAttachment: () =>
              generateCSVAttachment({
                title,
                subtitle,
                filename,
                columns,
                data,
                generatedBy,
                generatedAt: new Date(),
                filters: filters as any,
                orientation,
                exportMode,
                rowCount: data.length,
              }),
          },
        ]}
        defaultAttachmentType="pdf"
        generatedBy={generatedBy}
        recordCount={data.length}
        exportMode={exportMode}
        moduleCode={moduleCode}
        onPreparedSend={handleSendEmail}
      />
    </>
  );
}

/**
 * Get current user display name from auth context
 * This is a helper that can be used to pass generatedBy prop
 */
export function getExportUserName(userProfile?: { full_name?: string; display_name?: string; email?: string } | null): string {
  if (!userProfile) return "System User";
  return userProfile.full_name || userProfile.display_name || userProfile.email || "System User";
}
