/**
 * Excel Export Utility
 * Phase 002E.2 - Export Engine Foundation
 * 
 * Uses xlsx (SheetJS) package for .xlsx generation
 */

import * as XLSX from "xlsx";
import type { ERPExportOptions, ERPExportResult } from "./export-types";
import { getColumnValue, generateFilename, formatFilters } from "./format-export-data";
import { format } from "date-fns";

/**
 * Export data to Excel format and trigger download
 */
export function exportToExcel<T>(options: ERPExportOptions<T>): ERPExportResult {
  try {
    const { columns, data, filename, title, subtitle, generatedBy, generatedAt, filters } = options;

    // Create workbook
    const workbook = XLSX.utils.book_new();

    // Prepare metadata rows
    const metadataRows: any[][] = [];
    
    if (title) {
      metadataRows.push([title]);
    }
    if (subtitle) {
      metadataRows.push([subtitle]);
    }
    if (generatedBy) {
      metadataRows.push(["Generated by:", generatedBy]);
    }
    if (generatedAt) {
      metadataRows.push(["Generated at:", format(generatedAt, "yyyy-MM-dd HH:mm:ss")]);
    }
    if (filters && Object.keys(filters).length > 0) {
      metadataRows.push(["Filters:", formatFilters(filters)]);
    }
    
    // Add empty row after metadata
    if (metadataRows.length > 0) {
      metadataRows.push([]);
    }

    // Prepare header row
    const headers = columns.map((col) => col.header);

    // Prepare data rows
    const dataRows = data.map((row) => {
      return columns.map((col) => {
        const value = getColumnValue(row, col);
        // Try to preserve numbers
        const num = Number(value);
        if (!isNaN(num) && value.trim() !== "") {
          return num;
        }
        return value;
      });
    });

    // Combine all rows
    const allRows = [...metadataRows, headers, ...dataRows];

    // Create worksheet
    const worksheet = XLSX.utils.aoa_to_sheet(allRows);

    // Set column widths
    const columnWidths = columns.map((col) => ({
      wch: col.width || 20, // default width: 20 characters
    }));
    worksheet["!cols"] = columnWidths;

    // Add worksheet to workbook
    XLSX.utils.book_append_sheet(workbook, worksheet, "Data");

    // Generate download filename
    const downloadFilename = generateFilename(filename, "xlsx");

    // Write file and trigger download
    XLSX.writeFile(workbook, downloadFilename);

    return {
      success: true,
      filename: downloadFilename,
    };
  } catch (error) {
    console.error("Excel export error:", error);
    return {
      success: false,
      error: error instanceof Error ? error.message : "Failed to export Excel",
    };
  }
}
