/**
 * Excel Export Utility
 * Migrated from xlsx (SheetJS 0.18.5 — CVE-2023-30533, CVE-2024-22363)
 * to exceljs (4.x — no known CVEs, actively maintained).
 */

import ExcelJS from "exceljs";
import type { ERPExportOptions, ERPExportResult } from "./export-types";
import { getColumnValue, generateFilename, formatFilters } from "./format-export-data";
import { format } from "date-fns";

/** Trigger a browser file download from a Uint8Array buffer */
function triggerDownload(buffer: ArrayBuffer, filename: string) {
  const blob = new Blob([buffer], {
    type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Export data to Excel format and trigger download.
 * Must be called from a browser context (client component or event handler).
 */
export async function exportToExcel<T>(options: ERPExportOptions<T>): Promise<ERPExportResult> {
  try {
    const { columns, data, filename, title, subtitle, generatedBy, generatedAt, filters, branding } = options;

    const workbook = new ExcelJS.Workbook();
    workbook.creator = generatedBy ?? "ERP";
    workbook.created = generatedAt ?? new Date();

    const worksheet = workbook.addWorksheet("Data");

    // ── Metadata / branding rows ──────────────────────────────────────────
    const metadataRows: (string | number | null)[][] = [];

    if (branding?.companyNameEn) {
      metadataRows.push([branding.companyNameEn]);
      if (branding.addressBlockEn && branding.showAddress) {
        metadataRows.push([branding.addressBlockEn]);
      }
      if (branding.trn && branding.showTrn) {
        metadataRows.push(["TRN:", branding.trn]);
      }
      if (branding.tradeLicenseNo && branding.showLicense) {
        metadataRows.push(["License:", branding.tradeLicenseNo]);
      }
      metadataRows.push([]);
    }

    if (title)                    metadataRows.push([title]);
    if (subtitle)                 metadataRows.push([subtitle]);
    if (branding?.reportCode)     metadataRows.push(["Report Code:", branding.reportCode]);
    if (branding?.templateName)   metadataRows.push(["Template:", branding.templateName]);
    if (generatedBy)              metadataRows.push(["Generated by:", generatedBy]);
    if (generatedAt)              metadataRows.push(["Generated at:", format(generatedAt, "yyyy-MM-dd HH:mm:ss")]);
    if (filters && Object.keys(filters).length > 0) {
      metadataRows.push(["Filters:", formatFilters(filters)]);
    }
    if (metadataRows.length > 0)  metadataRows.push([]);

    for (const row of metadataRows) {
      worksheet.addRow(row);
    }

    // ── Header row ────────────────────────────────────────────────────────
    const headerRow = worksheet.addRow(columns.map((col) => col.header));
    headerRow.font = { bold: true };
    headerRow.fill = {
      type: "pattern",
      pattern: "solid",
      fgColor: { argb: "FFE9ECEF" },
    };

    // ── Data rows ─────────────────────────────────────────────────────────
    for (const row of data) {
      const values = columns.map((col) => {
        const value = getColumnValue(row, col);
        const num = Number(value);
        if (!isNaN(num) && typeof value === "string" && value.trim() !== "") {
          return num;
        }
        return value;
      });
      worksheet.addRow(values);
    }

    // ── Column widths ─────────────────────────────────────────────────────
    worksheet.columns = columns.map((col) => ({ width: col.width ?? 20 }));

    // ── Generate & download ───────────────────────────────────────────────
    const downloadFilename = generateFilename(filename, "xlsx");
    const buffer = await workbook.xlsx.writeBuffer();
    // exceljs returns Buffer (Node) or ArrayBuffer (browser) — coerce to ArrayBuffer
    const ab = buffer instanceof ArrayBuffer ? buffer : (buffer as Buffer).buffer.slice(
      (buffer as Buffer).byteOffset,
      (buffer as Buffer).byteOffset + (buffer as Buffer).byteLength
    );
    triggerDownload(ab as ArrayBuffer, downloadFilename);

    return { success: true, filename: downloadFilename };
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : "Failed to export Excel",
    };
  }
}
