/**
 * Email Attachment Generation from Export Engine
 * Phase 002E.3B - Attachment Generation
 * Phase REPORT.3 - Template / Branding / Output Adapter Engine
 *
 * Bridges existing export engine to email system by generating base64 attachments
 * instead of triggering downloads.
 * Branding is forwarded via ExportBrandingContext (optional, backward-compatible).
 */

import * as XLSX from "xlsx";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { format } from "date-fns";

import type { ERPExportOptions } from "./export-types";
import type { EmailAttachment } from "../email/email-types";
import {
  getColumnValue,
  escapeCsvField,
  generateFilename,
  formatFilters,
} from "./format-export-data";
import {
  stringToBase64Utf8,
  arrayBufferToBase64,
} from "../email/attachment-utils";

/**
 * Generate CSV attachment for email
 * 
 * Same CSV generation logic as exportToCSV() but returns EmailAttachment
 * instead of triggering download.
 * 
 * Features:
 * - UTF-8 BOM for Excel compatibility
 * - Proper escaping of commas, quotes, newlines
 * - Supports Arabic/Unicode text
 * 
 * @param options - Export options (same as exportToCSV)
 * @returns EmailAttachment object with base64 content
 * 
 * @example
 * ```typescript
 * const attachment = generateCSVAttachment({
 *   title: "Organizations",
 *   filename: "organizations",
 *   data: organizations,
 *   columns: [{ key: "id", header: "ID" }, ...],
 * });
 * // attachment = { filename: "organizations_2026-05-28.csv", contentType: "text/csv", base64Content: "...", sizeBytes: 1234 }
 * ```
 */
export function generateCSVAttachment<T>(
  options: ERPExportOptions<T>
): EmailAttachment {
  const { columns, data, filename } = options;

  // Generate header row (same logic as exportToCSV lines 18-20)
  const headers = columns.map((col) => escapeCsvField(col.header));
  const headerRow = headers.join(",");

  // Generate data rows (same logic as exportToCSV lines 22-29)
  const dataRows = data.map((row) => {
    const values = columns.map((col) => {
      const value = getColumnValue(row, col);
      return escapeCsvField(value);
    });
    return values.join(",");
  });

  // Combine header and data (same logic as exportToCSV line 32)
  const csvContent = [headerRow, ...dataRows].join("\n");

  // Add UTF-8 BOM for Excel compatibility (same as exportToCSV lines 34-36)
  const BOM = "\uFEFF";
  const csvWithBOM = BOM + csvContent;

  // Convert to base64 (NEW: for email attachment)
  const base64Content = stringToBase64Utf8(csvWithBOM);

  // Calculate size in bytes (NEW: for email attachment)
  const sizeBytes = new Blob([csvWithBOM]).size;

  // Generate filename with timestamp
  const fullFilename = generateFilename(filename, "csv");

  return {
    filename: fullFilename,
    contentType: "text/csv",
    base64Content,
    sizeBytes,
  };
}

/**
 * Generate Excel attachment for email
 * 
 * Same Excel workbook generation logic as exportToExcel() but returns EmailAttachment
 * instead of triggering download.
 * 
 * Features:
 * - Metadata rows (title, subtitle, generated by, date, filters)
 * - Column widths
 * - Number formatting
 * 
 * @param options - Export options (same as exportToExcel)
 * @returns EmailAttachment object with base64 content
 * 
 * @example
 * ```typescript
 * const attachment = generateExcelAttachment({
 *   title: "Organizations Master Data",
 *   subtitle: "2 selected records",
 *   filename: "organizations",
 *   data: organizations,
 *   columns: [{ key: "id", header: "ID" }, ...],
 *   generatedBy: "John Doe",
 *   generatedAt: new Date(),
 * });
 * ```
 */
export function generateExcelAttachment<T>(
  options: ERPExportOptions<T>
): EmailAttachment {
  const { columns, data, filename, title, subtitle, generatedBy, generatedAt, filters, branding } = options;

  const workbook = XLSX.utils.book_new();

  const metadataRows: unknown[][] = [];

  // REPORT.3: branded company header rows
  if (branding?.companyNameEn) {
    metadataRows.push([branding.companyNameEn]);
    if (branding.addressBlockEn && branding.showAddress) metadataRows.push([branding.addressBlockEn]);
    if (branding.trn && branding.showTrn) metadataRows.push(["TRN:", branding.trn]);
    metadataRows.push([]);
  }

  if (title) metadataRows.push([title]);
  if (subtitle) metadataRows.push([subtitle]);
  if (branding?.reportCode) metadataRows.push(["Report Code:", branding.reportCode]);
  if (generatedBy) metadataRows.push(["Generated by:", generatedBy]);
  if (generatedAt) metadataRows.push(["Generated at:", format(generatedAt, "yyyy-MM-dd HH:mm:ss")]);
  if (filters && Object.keys(filters).length > 0) metadataRows.push(["Filters:", formatFilters(filters)]);

  if (metadataRows.length > 0) {
    metadataRows.push([]);
  }

  // Prepare header row (same logic as exportToExcel line 48)
  const headers = columns.map((col) => col.header);

  // Prepare data rows (same logic as exportToExcel lines 50-61)
  const dataRows = data.map((row) => {
    return columns.map((col) => {
      const value = getColumnValue(row, col);
      // Try to preserve numbers
      const num = Number(value);
      if (!isNaN(num) && value.trim() !== "") {
        return num;
      }
      return value;
    });
  });

  // Combine all rows (same logic as exportToExcel line 64)
  const allRows = [...metadataRows, headers, ...dataRows];

  // Create worksheet (same logic as exportToExcel line 67)
  const worksheet = XLSX.utils.aoa_to_sheet(allRows);

  // Set column widths (same logic as exportToExcel lines 69-73)
  const columnWidths = columns.map((col) => ({
    wch: col.width || 20, // default width: 20 characters
  }));
  worksheet["!cols"] = columnWidths;

  // Add worksheet to workbook (same logic as exportToExcel line 76)
  XLSX.utils.book_append_sheet(workbook, worksheet, "Data");

  // Generate ArrayBuffer (NEW: for email attachment, instead of writeFile())
  const arrayBuffer = XLSX.write(workbook, {
    type: "array",
    bookType: "xlsx",
  });

  // Convert ArrayBuffer to base64 (NEW: for email attachment)
  const base64Content = arrayBufferToBase64(arrayBuffer);

  // Calculate size in bytes (NEW: for email attachment)
  const sizeBytes = arrayBuffer.byteLength;

  // Generate filename with timestamp
  const fullFilename = generateFilename(filename, "xlsx");

  return {
    filename: fullFilename,
    contentType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    base64Content,
    sizeBytes,
  };
}

/**
 * Generate PDF attachment for email
 * 
 * Same PDF document generation logic as exportToPDF() but returns EmailAttachment
 * instead of triggering download.
 * 
 * Features:
 * - Title, subtitle, metadata
 * - jspdf-autotable for table rendering
 * - Portrait/landscape orientation
 * - Page numbers and footer
 * 
 * @param options - Export options (same as exportToPDF)
 * @returns EmailAttachment object with base64 content
 * 
 * @example
 * ```typescript
 * const attachment = generatePDFAttachment({
 *   title: "Organizations Master Data",
 *   subtitle: "2 selected records",
 *   filename: "organizations",
 *   data: organizations,
 *   columns: [{ key: "id", header: "ID" }, ...],
 *   orientation: "landscape",
 * });
 * ```
 */
export function generatePDFAttachment<T>(
  options: ERPExportOptions<T>
): EmailAttachment {
  const {
    columns,
    data,
    filename,
    title,
    subtitle,
    generatedBy,
    generatedAt,
    filters,
    orientation = "portrait",
    branding,
  } = options;

  const doc = new jsPDF({
    orientation: branding?.templateOrientation ?? orientation,
    unit: "mm",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  let currentY = 15;

  // Reuse same header logic as exportToPDF
  if (branding?.companyNameEn) {
    // Branded header bar
    const headerBgRaw = branding.themeHeaderBgColor ?? branding.themePrimaryColor ?? "#1e293b";
    const cleanHex = headerBgRaw.replace("#", "");
    const r = parseInt(cleanHex.substring(0, 2), 16) || 30;
    const g = parseInt(cleanHex.substring(2, 4), 16) || 41;
    const b = parseInt(cleanHex.substring(4, 6), 16) || 59;
    doc.setFillColor(r, g, b);
    doc.rect(0, 0, pageWidth, 20, "F");
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(255, 255, 255);
    doc.text(branding.companyNameEn, 15, 13);
    currentY = 25;
    doc.setTextColor(0, 0, 0);
  }

  if (title) {
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text(title, pageWidth / 2, currentY, { align: "center" });
    currentY += 8;
  }
  if (subtitle) {
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(subtitle, pageWidth / 2, currentY, { align: "center" });
    currentY += 7;
  }

  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(80, 80, 80);

  if (generatedBy) { doc.text(`Generated by: ${generatedBy}`, 15, currentY); currentY += 4; }
  if (generatedAt) { doc.text(`Generated at: ${format(generatedAt, "yyyy-MM-dd HH:mm:ss")}`, 15, currentY); currentY += 4; }
  if (branding?.reportCode) { doc.text(`Report: ${branding.reportCode}`, 15, currentY); currentY += 4; }
  if (filters && Object.keys(filters).length > 0) { doc.text(`Filters: ${formatFilters(filters)}`, 15, currentY); currentY += 4; }

  currentY += 5;

  const headers = columns.map((col) => col.header);
  const rows = data.map((row) => columns.map((col) => getColumnValue(row, col)));

  const footerText = branding?.footerTextEn ?? "ERP Report";

  autoTable(doc, {
    head: [headers],
    body: rows,
    startY: currentY,
    styles: { fontSize: 8, cellPadding: 2 },
    headStyles: { fillColor: [66, 66, 66], textColor: [255, 255, 255], fontStyle: "bold" },
    alternateRowStyles: { fillColor: [245, 245, 245] },
    margin: { left: 15, right: 15 },
    didDrawPage: (pageData) => {
      const pageCount = doc.getNumberOfPages();
      doc.setFontSize(8);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(80, 80, 80);
      doc.text(`Page ${pageData.pageNumber} of ${pageCount}`, pageWidth / 2, pageHeight - 10, { align: "center" });
      doc.setFontSize(7);
      doc.setTextColor(150, 150, 150);
      doc.text(footerText, pageWidth / 2, pageHeight - 5, { align: "center" });
    },
  });

  // Generate ArrayBuffer (NEW: for email attachment, instead of doc.save())
  const arrayBuffer = doc.output("arraybuffer");

  // Convert ArrayBuffer to base64 (NEW: for email attachment)
  const base64Content = arrayBufferToBase64(arrayBuffer as ArrayBuffer);

  // Calculate size in bytes (NEW: for email attachment)
  const sizeBytes = (arrayBuffer as ArrayBuffer).byteLength;

  // Generate filename with timestamp
  const fullFilename = generateFilename(filename, "pdf");

  return {
    filename: fullFilename,
    contentType: "application/pdf",
    base64Content,
    sizeBytes,
  };
}

/**
 * Generate attachment by type (helper function)
 * 
 * Convenience function to generate attachment based on format type.
 * Useful for dynamic attachment generation based on user selection.
 * 
 * @param type - Attachment format type
 * @param options - Export options
 * @returns EmailAttachment object
 * 
 * @example
 * ```typescript
 * const format = "pdf"; // From user selection
 * const attachment = generateAttachmentByType(format, {
 *   title: "Report",
 *   data: [...],
 *   columns: [...],
 * });
 * ```
 */
export function generateAttachmentByType<T>(
  type: "csv" | "excel" | "pdf",
  options: ERPExportOptions<T>
): EmailAttachment {
  switch (type) {
    case "csv":
      return generateCSVAttachment(options);
    case "excel":
      return generateExcelAttachment(options);
    case "pdf":
      return generatePDFAttachment(options);
    default:
      // TypeScript exhaustiveness check
      const _exhaustive: never = type;
      throw new Error(`Unknown attachment type: ${_exhaustive}`);
  }
}
