/**
 * Email Attachment Generation from Export Engine
 * Phase 002E.3B - Attachment Generation
 * Phase REPORT.3 - Template / Branding / Output Adapter Engine
 *
 * Bridges existing export engine to email system by generating base64 attachments
 * instead of triggering downloads.
 *
 * Arabic support: same bidi-shaper + Noto Sans Arabic TTF approach as pdf.ts.
 * All PDF output is vector text — < 300 KB regardless of content language.
 */

import ExcelJS from "exceljs";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { installJsPdfShaper } from "bidi-shaper/jspdf";
import { format } from "date-fns";

import type { ERPExportOptions } from "./export-types";
import type { EmailAttachment } from "../email/email-types";
import {
  getColumnValue,
  escapeCsvField,
  generateFilename,
  formatFilters,
} from "./format-export-data";
import {
  stringToBase64Utf8,
  arrayBufferToBase64,
} from "../email/attachment-utils";

// Install bidi-shaper plugin (idempotent — safe to call in both pdf.ts and here)
installJsPdfShaper(jsPDF.API as Parameters<typeof installJsPdfShaper>[0]);

// ─────────────────────────────────────────────────────────────────────────────
// Arabic detection + font loader (same logic as pdf.ts, local copy avoids
// circular import and allows this module to run independently)
// ─────────────────────────────────────────────────────────────────────────────

function containsArabic(text: string): boolean {
  return /[\u0600-\u06FF\u0750-\u077F\u08A0-\u08FF\uFB50-\uFDFF\uFE70-\uFEFF]/.test(text);
}

function exportDataHasArabic<T>(options: ERPExportOptions<T>): boolean {
  if (containsArabic(options.title ?? "")) return true;
  if (containsArabic(options.subtitle ?? "")) return true;
  return options.data.some((row) =>
    options.columns.some((col) => {
      const val = getColumnValue(row, col);
      return typeof val === "string" && containsArabic(val);
    })
  );
}

let _arabicFontData: string | null = null;
let _arabicFontPromise: Promise<string | null> | null = null;

async function loadArabicFont(): Promise<string | null> {
  if (_arabicFontData) return _arabicFontData;
  if (_arabicFontPromise) return _arabicFontPromise;

  _arabicFontPromise = (async () => {
    try {
      const res = await fetch("/fonts/noto-sans-arabic-400.ttf");
      if (!res.ok) return null;
      const buf = await res.arrayBuffer();
      const bytes = new Uint8Array(buf);
      const CHUNK = 0x8000;
      const parts: string[] = [];
      for (let i = 0; i < bytes.length; i += CHUNK) {
        parts.push(String.fromCharCode(...bytes.subarray(i, i + CHUNK)));
      }
      _arabicFontData = parts.join("");
      return _arabicFontData;
    } catch {
      return null;
    }
  })();

  return _arabicFontPromise;
}

async function registerArabicFont(doc: jsPDF): Promise<boolean> {
  const data = await loadArabicFont();
  if (!data) return false;
  doc.addFileToVFS("NotoSansArabic.ttf", data);
  doc.addFont("NotoSansArabic.ttf", "NotoSansArabic", "normal");
  return true;
}

// ─────────────────────────────────────────────────────────────────────────────
// CSV
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Generate CSV attachment for email.
 * UTF-8 BOM included for Excel compatibility. Supports Arabic/Unicode text.
 */
export function generateCSVAttachment<T>(
  options: ERPExportOptions<T>
): EmailAttachment {
  const { columns, data, filename } = options;

  const headers = columns.map((col) => escapeCsvField(col.header));
  const dataRows = data.map((row) =>
    columns.map((col) => escapeCsvField(getColumnValue(row, col))).join(",")
  );

  const BOM = "\uFEFF";
  const csvContent = BOM + [headers.join(","), ...dataRows].join("\n");

  return {
    filename: generateFilename(filename, "csv"),
    contentType: "text/csv",
    base64Content: stringToBase64Utf8(csvContent),
    sizeBytes: new Blob([csvContent]).size,
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// Excel
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Generate Excel attachment for email.
 * Includes metadata rows (title, subtitle, generated by, date, filters).
 */
export async function generateExcelAttachment<T>(
  options: ERPExportOptions<T>
): Promise<EmailAttachment> {
  const { columns, data, filename, title, subtitle, generatedBy, generatedAt, filters, branding } = options;

  const workbook = new ExcelJS.Workbook();
  if (generatedBy) workbook.creator = generatedBy;
  if (generatedAt) workbook.created = generatedAt;

  const worksheet = workbook.addWorksheet("Data");
  const metadataRows: (string | number | null)[][] = [];

  if (branding?.companyNameEn) {
    metadataRows.push([branding.companyNameEn]);
    if (branding.addressBlockEn && branding.showAddress) metadataRows.push([branding.addressBlockEn]);
    if (branding.trn && branding.showTrn) metadataRows.push(["TRN:", branding.trn]);
    metadataRows.push([]);
  }

  if (title) metadataRows.push([title]);
  if (subtitle) metadataRows.push([subtitle]);
  if (branding?.reportCode) metadataRows.push(["Report Code:", branding.reportCode]);
  if (generatedBy) metadataRows.push(["Generated by:", generatedBy]);
  if (generatedAt) metadataRows.push(["Generated at:", format(generatedAt, "yyyy-MM-dd HH:mm:ss")]);
  if (filters && Object.keys(filters).length > 0) metadataRows.push(["Filters:", formatFilters(filters)]);
  if (metadataRows.length > 0) metadataRows.push([]);

  for (const row of metadataRows) worksheet.addRow(row);

  const headerRow = worksheet.addRow(columns.map((col) => col.header));
  headerRow.font = { bold: true };

  for (const row of data) {
    const values = columns.map((col) => {
      const value = getColumnValue(row, col);
      const num = Number(value);
      if (!isNaN(num) && typeof value === "string" && value.trim() !== "") return num;
      return value;
    });
    worksheet.addRow(values);
  }

  worksheet.columns = columns.map((col) => ({ width: col.width ?? 20 }));

  const buffer = await workbook.xlsx.writeBuffer();
  const ab = buffer instanceof ArrayBuffer
    ? buffer
    : (buffer as Buffer).buffer.slice((buffer as Buffer).byteOffset, (buffer as Buffer).byteOffset + (buffer as Buffer).byteLength);

  return {
    filename: generateFilename(filename, "xlsx"),
    contentType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    base64Content: arrayBufferToBase64(ab as ArrayBuffer),
    sizeBytes: (ab as ArrayBuffer).byteLength,
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// PDF
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Generate PDF attachment for email.
 * Uses jsPDF + autoTable + bidi-shaper + Noto Sans Arabic TTF.
 * Produces a vector PDF (< 300 KB) with correct Arabic shaping and RTL layout.
 */
export async function generatePDFAttachment<T>(
  options: ERPExportOptions<T>
): Promise<EmailAttachment> {
  const {
    columns,
    data,
    filename,
    title,
    subtitle,
    generatedBy,
    generatedAt,
    filters,
    orientation = "portrait",
    branding,
  } = options;

  const hasArabic = exportDataHasArabic(options);

  const doc = new jsPDF({
    orientation: branding?.templateOrientation ?? orientation,
    unit: "mm",
    format: "a4",
  });

  let bodyFont = "helvetica";
  if (hasArabic) {
    const ok = await registerArabicFont(doc);
    if (ok) bodyFont = "NotoSansArabic";
  }

  const pageWidth  = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  let currentY = 15;

  if (branding?.companyNameEn) {
    const headerBgRaw = branding.themeHeaderBgColor ?? branding.themePrimaryColor ?? "#1e293b";
    const cleanHex = headerBgRaw.replace("#", "");
    const r = parseInt(cleanHex.substring(0, 2), 16) || 30;
    const g = parseInt(cleanHex.substring(2, 4), 16) || 41;
    const b = parseInt(cleanHex.substring(4, 6), 16) || 59;
    doc.setFillColor(r, g, b);
    doc.rect(0, 0, pageWidth, 20, "F");
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(255, 255, 255);
    doc.text(branding.companyNameEn, 15, 13);
    currentY = 25;
    doc.setTextColor(0, 0, 0);
  }

  if (title) {
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text(title, pageWidth / 2, currentY, { align: "center" });
    currentY += 8;
  }
  if (subtitle) {
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(subtitle, pageWidth / 2, currentY, { align: "center" });
    currentY += 7;
  }

  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(80, 80, 80);

  if (generatedBy) { doc.text(`Generated by: ${generatedBy}`, 15, currentY); currentY += 4; }
  if (generatedAt) { doc.text(`Generated at: ${format(generatedAt, "yyyy-MM-dd HH:mm:ss")}`, 15, currentY); currentY += 4; }
  if (branding?.reportCode) { doc.text(`Report: ${branding.reportCode}`, 15, currentY); currentY += 4; }
  if (filters && Object.keys(filters).length > 0) { doc.text(`Filters: ${formatFilters(filters)}`, 15, currentY); currentY += 4; }

  currentY += 5;

  const headers = columns.map((col) => col.header);
  const rows = data.map((row) => columns.map((col) => getColumnValue(row, col)));
  const footerText = branding?.footerTextEn ?? "ERP Report";

  autoTable(doc, {
    head: [headers],
    body: rows,
    startY: currentY,
    styles: { fontSize: 8, cellPadding: 2, font: bodyFont },
    headStyles: { fillColor: [66, 66, 66], textColor: [255, 255, 255], fontStyle: "bold", font: "helvetica" },
    alternateRowStyles: { fillColor: [245, 245, 245] },
    margin: { left: 15, right: 15 },
    didDrawPage: (pageData) => {
      const pageCount = doc.getNumberOfPages();
      doc.setFontSize(8);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(80, 80, 80);
      doc.text(`Page ${pageData.pageNumber} of ${pageCount}`, pageWidth / 2, pageHeight - 10, { align: "center" });
      doc.setFontSize(7);
      doc.setTextColor(150, 150, 150);
      doc.text(footerText, pageWidth / 2, pageHeight - 5, { align: "center" });
    },
  });

  const arrayBuffer = doc.output("arraybuffer") as ArrayBuffer;

  return {
    filename: generateFilename(filename, "pdf"),
    contentType: "application/pdf",
    base64Content: arrayBufferToBase64(arrayBuffer),
    sizeBytes: arrayBuffer.byteLength,
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// Convenience wrapper
// ─────────────────────────────────────────────────────────────────────────────

export async function generateAttachmentByType<T>(
  type: "csv" | "excel" | "pdf",
  options: ERPExportOptions<T>
): Promise<EmailAttachment> {
  switch (type) {
    case "csv":
      return generateCSVAttachment(options);
    case "excel":
      return await generateExcelAttachment(options);
    case "pdf":
      return await generatePDFAttachment(options);
    default: {
      const _exhaustive: never = type;
      throw new Error(`Unknown attachment type: ${_exhaustive}`);
    }
  }
}
