/**
 * PDF Export Utility
 * Phase 002E.2 - Export Engine Foundation
 * 
 * Uses jspdf and jspdf-autotable for PDF generation
 */

import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import type { ERPExportOptions, ERPExportResult } from "./export-types";
import { getColumnValue, generateFilename, formatFilters } from "./format-export-data";
import { format } from "date-fns";

/**
 * Export data to PDF format and trigger download
 */
export function exportToPDF<T>(options: ERPExportOptions<T>): ERPExportResult {
  try {
    const {
      columns,
      data,
      filename,
      title,
      subtitle,
      generatedBy,
      generatedAt,
      filters,
      orientation = "portrait",
    } = options;

    // Create PDF document
    const doc = new jsPDF({
      orientation,
      unit: "mm",
      format: "a4",
    });

    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    let currentY = 15;

    // Add title
    if (title) {
      doc.setFontSize(16);
      doc.setFont("helvetica", "bold");
      doc.text(title, pageWidth / 2, currentY, { align: "center" });
      currentY += 8;
    }

    // Add subtitle
    if (subtitle) {
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.text(subtitle, pageWidth / 2, currentY, { align: "center" });
      currentY += 7;
    }

    // Add metadata
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    
    if (generatedBy) {
      doc.text(`Generated by: ${generatedBy}`, 15, currentY);
      currentY += 4;
    }
    
    if (generatedAt) {
      doc.text(`Generated at: ${format(generatedAt, "yyyy-MM-dd HH:mm:ss")}`, 15, currentY);
      currentY += 4;
    }

    if (filters && Object.keys(filters).length > 0) {
      doc.text(`Filters: ${formatFilters(filters)}`, 15, currentY);
      currentY += 4;
    }

    currentY += 5;

    // Prepare table data
    const headers = columns.map((col) => col.header);
    const rows = data.map((row) => {
      return columns.map((col) => getColumnValue(row, col));
    });

    // Add table
    autoTable(doc, {
      head: [headers],
      body: rows,
      startY: currentY,
      styles: {
        fontSize: 8,
        cellPadding: 2,
      },
      headStyles: {
        fillColor: [66, 66, 66],
        textColor: [255, 255, 255],
        fontStyle: "bold",
      },
      alternateRowStyles: {
        fillColor: [245, 245, 245],
      },
      margin: { left: 15, right: 15 },
      didDrawPage: (data) => {
        // Add page numbers
        const pageCount = doc.getNumberOfPages();
        doc.setFontSize(8);
        doc.setFont("helvetica", "normal");
        doc.text(
          `Page ${data.pageNumber} of ${pageCount}`,
          pageWidth / 2,
          pageHeight - 10,
          { align: "center" }
        );

        // Add footer text
        doc.setFontSize(7);
        doc.setTextColor(128, 128, 128);
        doc.text(
          "Alliance Gulf ERP - Enterprise Report",
          pageWidth / 2,
          pageHeight - 5,
          { align: "center" }
        );
        // TODO: Phase 002F will connect this template to App Settings and selected company letterhead
      },
    });

    // Generate download filename
    const downloadFilename = generateFilename(filename, "pdf");

    // Save PDF
    doc.save(downloadFilename);

    return {
      success: true,
      filename: downloadFilename,
    };
  } catch (error) {
    console.error("PDF export error:", error);
    return {
      success: false,
      error: error instanceof Error ? error.message : "Failed to export PDF",
    };
  }
}
