/**
 * Print Export Utility
 * Phase 002E.2 - Export Engine Foundation
 * 
 * Browser print with clean printable view
 */

import type { ERPExportOptions, ERPExportResult } from "./export-types";
import { getColumnValue, formatFilters } from "./format-export-data";
import { format } from "date-fns";

/**
 * Open print preview window with formatted data
 */
export function exportToPrint<T>(options: ERPExportOptions<T>): ERPExportResult {
  try {
    const {
      columns,
      data,
      title,
      subtitle,
      generatedBy,
      generatedAt,
      filters,
    } = options;

    // Generate HTML for print window
    const html = generatePrintHTML(options);

    // Open new window
    const printWindow = window.open("", "_blank", "width=900,height=700");
    
    if (!printWindow) {
      return {
        success: false,
        error: "Failed to open print window. Please allow popups for this site.",
      };
    }

    // Write HTML to window
    printWindow.document.open();
    printWindow.document.write(html);
    printWindow.document.close();

    // Wait for content to load, then print
    printWindow.onload = () => {
      printWindow.print();
    };

    return {
      success: true,
    };
  } catch (error) {
    console.error("Print export error:", error);
    return {
      success: false,
      error: error instanceof Error ? error.message : "Failed to open print view",
    };
  }
}

/**
 * Generate HTML for print window
 */
function generatePrintHTML<T>(options: ERPExportOptions<T>): string {
  const {
    columns,
    data,
    title,
    subtitle,
    generatedBy,
    generatedAt,
    filters,
  } = options;

  // Generate table headers
  const headerCells = columns
    .map((col) => `<th style="text-align: left; padding: 8px; border-bottom: 2px solid #ddd; background-color: #f5f5f5;">${col.header}</th>`)
    .join("");

  // Generate table rows
  const dataRows = data
    .map((row, index) => {
      const cells = columns
        .map((col) => {
          const value = getColumnValue(row, col);
          return `<td style="padding: 8px; border-bottom: 1px solid #eee;">${value}</td>`;
        })
        .join("");
      const bgColor = index % 2 === 0 ? "#ffffff" : "#fafafa";
      return `<tr style="background-color: ${bgColor};">${cells}</tr>`;
    })
    .join("");

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${title || "Print"}</title>
  <style>
    @media print {
      @page {
        size: auto;
        margin: 15mm;
      }
      body {
        margin: 0;
      }
      .no-print {
        display: none;
      }
    }
    
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
      font-size: 12px;
      color: #333;
      line-height: 1.6;
      padding: 20px;
    }
    
    .header {
      text-align: center;
      margin-bottom: 30px;
      padding-bottom: 15px;
      border-bottom: 2px solid #333;
    }
    
    .header h1 {
      margin: 0 0 5px 0;
      font-size: 20px;
      font-weight: bold;
      color: #000;
    }
    
    .header .subtitle {
      margin: 0 0 10px 0;
      font-size: 14px;
      color: #666;
    }
    
    .metadata {
      margin-bottom: 20px;
      font-size: 10px;
      color: #666;
    }
    
    .metadata p {
      margin: 3px 0;
    }
    
    table {
      width: 100%;
      border-collapse: collapse;
      margin-bottom: 20px;
    }
    
    th {
      font-weight: bold;
      text-transform: uppercase;
      font-size: 10px;
      letter-spacing: 0.5px;
    }
    
    td {
      font-size: 11px;
    }
    
    .footer {
      text-align: center;
      margin-top: 30px;
      padding-top: 15px;
      border-top: 1px solid #ddd;
      font-size: 10px;
      color: #999;
    }
  </style>
</head>
<body>
  <div class="header">
    ${title ? `<h1>${title}</h1>` : ""}
    ${subtitle ? `<div class="subtitle">${subtitle}</div>` : ""}
  </div>
  
  <div class="metadata">
    ${generatedBy ? `<p><strong>Generated by:</strong> ${generatedBy}</p>` : ""}
    ${generatedAt ? `<p><strong>Generated at:</strong> ${format(generatedAt, "yyyy-MM-dd HH:mm:ss")}</p>` : ""}
    ${filters && Object.keys(filters).length > 0 ? `<p><strong>Filters:</strong> ${formatFilters(filters)}</p>` : ""}
  </div>
  
  <table>
    <thead>
      <tr>${headerCells}</tr>
    </thead>
    <tbody>
      ${dataRows}
    </tbody>
  </table>
  
  <div class="footer">
    <p>Alliance Gulf ERP - Enterprise Report</p>
    <p>Printed on ${format(new Date(), "yyyy-MM-dd HH:mm:ss")}</p>
    <!-- TODO: Phase 002F will connect this template to App Settings and selected company letterhead -->
  </div>
</body>
</html>
  `;
}
