/**
 * Executive Ledger Template Engine — Core Types
 * Phase: BRANDING.5 — Executive Ledger Template Engine
 *
 * Generic, module-agnostic types for all formal ERP outputs:
 * HR letters, certificates, forms, weighbridge tickets, delivery notes, etc.
 *
 * Branding is consumed from ExportBrandingContext (already resolved by the server).
 * The renderer never resolves assets or calls Supabase directly.
 */

import type { ExportBrandingContext } from "@/lib/export/export-types";

// ─────────────────────────────────────────────────────────────────────────────
// Top-level document
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Complete definition for an Executive Ledger document.
 * Passed to the HTML renderer to produce a print-ready A4 output.
 */
export interface ExecutiveLedgerDocument {
  // ── Identity ───────────────────────────────────────────────────────────────
  /** Main document title, e.g. "Experience Letter", "Salary Certificate" */
  documentTitle: string;
  /** Hide the colored title band entirely (Report Designer root setting) */
  hideTitleBlock?: boolean;
  /** Title band color overrides (safe hex, validated upstream). Empty = branding theme */
  titleBlockStyle?: { bgColor?: string; textColor?: string };
  /** Optional subtitle or document type descriptor */
  documentSubtitle?: string;
  /** Document reference number, e.g. "EXP/2026/000042" */
  documentRef?: string;
  /** Human-readable issue date string (pre-formatted) */
  issuedDate?: string;
  /** Issued by location / office / city */
  issuedAt?: string;

  // ── Branding ───────────────────────────────────────────────────────────────
  /**
   * Already-resolved branding context from BRANDING.4 `resolveTemplatePreview()`.
   * The renderer never calls storage or resolves URLs — consume only what is here.
   */
  branding?: ExportBrandingContext;

  // ── Addressee / Subject ────────────────────────────────────────────────────
  /** Addressee block — TO / ATTN / EMPLOYEE */
  addressee?: ExecutiveLedgerParty;
  /** FROM / Issuing party, if different from company header */
  issuer?: ExecutiveLedgerParty;
  /** RE / SUBJECT line */
  subject?: string;

  // ── Body sections ──────────────────────────────────────────────────────────
  /**
   * Ordered content sections. Can mix body text, key-value tables, and ledger tables.
   */
  sections: ExecutiveLedgerSection[];

  // ── Notes / Terms ──────────────────────────────────────────────────────────
  /** Free-form notes at the end of the document body */
  notes?: string;
  /** Numbered terms and conditions items */
  terms?: string[];

  // ── Signatory override ─────────────────────────────────────────────────────
  /**
   * Override the signatory block (overrides branding context signatory fields).
   * When absent, the signatory from `branding` is used if `branding.showSignatory`.
   */
  signatoryOverride?: {
    name: string;
    titleEn?: string;
    titleAr?: string;
  };

  // ── Footer override ────────────────────────────────────────────────────────
  /** Override the footer text (falls back to branding.footerTextEn) */
  footerOverride?: string;

  // ── Public Verification / QR ──────────────────────────────────────────────
  /**
   * Public verification / QR block (BRANDING.6).
   *
   * - When `qrDataUrl` is provided, renders a real QR image in the bottom-right.
   * - When only `publicUrl` is provided, renders a text URL.
   * - When absent or only `qrPlaceholder: true`, renders a placeholder box.
   * - `qrDataUrl` must pass `isValidQrDataUrl()` — only PNG/SVG from local QR helper allowed.
   * - Internal link IDs are never embedded in the renderer; only the public URL is used.
   */
  verification?: {
    /** Full public verification URL: https://...app.com/verify/TOKEN */
    publicUrl?: string | null;
    /**
     * QR code as a data URL (data:image/png;base64,...).
     * Must be generated by `generateQrDataUrl()` — no external service URLs.
     * Validated by `isValidQrDataUrl()` before rendering.
     */
    qrDataUrl?: string | null;
    /** Label shown below the QR (default: "Scan to verify") */
    label?: string;
  };

  /**
   * Legacy placeholder flag — kept for backward compatibility.
   * When `verification` is not provided and this is true, renders a placeholder box.
   * @deprecated Use `verification` prop instead.
   */
  qrPlaceholder?: boolean;

  // ── Print options ──────────────────────────────────────────────────────────
  /** Override language direction (default: ltr) */
  direction?: "ltr" | "rtl" | "auto";
  /** Override page orientation (default: portrait) */
  orientation?: "portrait" | "landscape";
  /**
   * When true, the html-renderer's built-in signatory/stamp block is suppressed.
   * Set to true when the visual template already renders a signatory via a
   * ColumnStripBlock signatory slot, to prevent double-rendering.
   */
  suppressBuiltinSignatory?: boolean;
}

// ─────────────────────────────────────────────────────────────────────────────
// Party block
// ─────────────────────────────────────────────────────────────────────────────

/**
 * A named party block — addressee, issuer, recipient, or employee.
 * Used in the TO / FROM / CC / ATTN header strips.
 */
export interface ExecutiveLedgerParty {
  /** Block label, e.g. "TO", "EMPLOYEE", "RECIPIENT", "ATTN" */
  label?: string;
  /** Full name */
  name: string;
  /** Job title / designation */
  title?: string;
  /** Company or department */
  company?: string;
  /** Reference ID — employee number, passport, trade licence, etc. */
  idRef?: string;
  /** Additional lines — address, email, phone */
  lines?: string[];
}

// ─────────────────────────────────────────────────────────────────────────────
// Section types
// ─────────────────────────────────────────────────────────────────────────────

/** Union type for all body section variants */
export type ExecutiveLedgerSection =
  | ExecutiveLedgerBodySection
  | ExecutiveLedgerKeyValueSection
  | ExecutiveLedgerTableSection
  | ExecutiveLedgerDividerSection
  | ExecutiveLedgerColumnSection;

/**
 * Free-form body text section (letter body, certifications, declarations).
 * Text must be pre-formatted; the renderer HTML-escapes it.
 *
 * REPORT DESIGNER UX.1: When `richHtml` is present, it is used instead of `content`.
 * `richHtml` is ONLY set by our server-side ProseMirror renderer — never user input.
 */
export interface ExecutiveLedgerBodySection {
  type: "body";
  /** Optional section heading */
  title?: string;
  /** Multi-line body text. Each newline becomes a paragraph. */
  content: string;
  language?: "en" | "ar" | "bilingual";
  /**
   * REPORT DESIGNER UX.1: Pre-rendered safe HTML from the ProseMirror renderer.
   * When present, this is used directly instead of `content`.
   * Set ONLY by layout-to-executive-ledger.ts, never from user props.
   */
  richHtml?: string;
}/**
 * Key-value detail section — dotted rows style.
 * Used for employee details, salary components, item lists.
 */
export interface ExecutiveLedgerKeyValueSection {
  type: "key_value";
  /** Optional section heading */
  title?: string;
  rows: ExecutiveLedgerKeyValueRow[];
}

/**
 * A single key → value row inside a key-value section.
 */
export interface ExecutiveLedgerKeyValueRow {
  /** Field label */
  label: string;
  /** Display value (pre-formatted string) */
  value: string;
  /** Render value in bold — used for totals/summary rows */
  emphasized?: boolean;
  /** Render as a sub-header row (no value, just a visual divider within the section) */
  isSubHeader?: boolean;
}

/**
 * Ledger table section — formal table with headers and optional totals.
 * Used for itemized lists, salary breakdowns, PPE items, etc.
 */
export interface ExecutiveLedgerTableSection {
  type: "table";
  /** Optional section heading */
  title?: string;
  headers: string[];
  /** Each row is an array of pre-formatted strings, one per header */
  rows: string[][];
  /** Summary / totals rows displayed below the table with bold formatting */
  totals?: ExecutiveLedgerKeyValueRow[];
  /**
   * REPORT DESIGNER.9: When false, the table header row is omitted.
   * Default: true (header visible).
   */
  showHeader?: boolean;
  /**
   * REPORT DESIGNER.9: Optional column width hints (e.g. "80px", "15%").
   * Array length must match `headers`. If shorter or absent, columns size naturally.
   * Width values are passed only as safe inline CSS — no HTML injection.
   */
  columnWidths?: string[];
}

/**
 * Visual horizontal divider between sections.
 */
export interface ExecutiveLedgerDividerSection {
  type: "divider";
  /** Optional short label centered in the divider line */
  label?: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// Column section (REPORT DESIGNER UX.1)
// ─────────────────────────────────────────────────────────────────────────────

/**
 * A single slot inside an ExecutiveLedgerColumnSection.
 * Contains either a regular section OR pre-rendered trusted HTML (for logo/stamp/sig/qr).
 * The `html` field is ONLY set by our server-side mapper code, never from user input.
 */
export interface ExecutiveLedgerColumnSlot {
  /** A regular EL section rendered by the section renderer */
  section?: ExecutiveLedgerBodySection | ExecutiveLedgerKeyValueSection;
  /**
   * Pre-rendered trusted HTML for special content (logo, signatory, stamp, QR).
   * Set exclusively by layout-to-executive-ledger.ts mapper — never user input.
   */
  html?: string;
}

/**
 * Multi-column layout section — 2-col or 3-col.
 * Maps from ColumnStripBlock in REPORT DESIGNER UX.1.
 *
 * Rendered using CSS flexbox with controlled safe width presets.
 * No arbitrary CSS from user props.
 */
export interface ExecutiveLedgerColumnSection {
  type: "column";
  /** Layout width preset */
  layout: "equal" | "left-wide" | "right-wide" | "2-col" | "3-col";
  /** Vertical alignment of slot contents */
  verticalAlign?: "top" | "middle" | "bottom";
  /** Gap size between columns */
  gap?: "sm" | "md" | "lg";
  /** Column slot contents */
  slots: {
    left?: ExecutiveLedgerColumnSlot;
    center?: ExecutiveLedgerColumnSlot;
    right?: ExecutiveLedgerColumnSlot;
  };
}
