/**
 * Executive Ledger Template Engine — Core Types
 * Phase: BRANDING.5 — Executive Ledger Template Engine
 *
 * Generic, module-agnostic types for all formal ERP outputs:
 * HR letters, certificates, forms, weighbridge tickets, delivery notes, etc.
 *
 * Branding is consumed from ExportBrandingContext (already resolved by the server).
 * The renderer never resolves assets or calls Supabase directly.
 */

import type { ExportBrandingContext } from "@/lib/export/export-types";

// ─────────────────────────────────────────────────────────────────────────────
// Top-level document
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Complete definition for an Executive Ledger document.
 * Passed to the HTML renderer to produce a print-ready A4 output.
 */
export interface ExecutiveLedgerDocument {
  // ── Identity ───────────────────────────────────────────────────────────────
  /** Main document title, e.g. "Experience Letter", "Salary Certificate" */
  documentTitle: string;
  /** Optional subtitle or document type descriptor */
  documentSubtitle?: string;
  /** Document reference number, e.g. "EXP/2026/000042" */
  documentRef?: string;
  /** Human-readable issue date string (pre-formatted) */
  issuedDate?: string;
  /** Issued by location / office / city */
  issuedAt?: string;

  // ── Branding ───────────────────────────────────────────────────────────────
  /**
   * Already-resolved branding context from BRANDING.4 `resolveTemplatePreview()`.
   * The renderer never calls storage or resolves URLs — consume only what is here.
   */
  branding?: ExportBrandingContext;

  // ── Addressee / Subject ────────────────────────────────────────────────────
  /** Addressee block — TO / ATTN / EMPLOYEE */
  addressee?: ExecutiveLedgerParty;
  /** FROM / Issuing party, if different from company header */
  issuer?: ExecutiveLedgerParty;
  /** RE / SUBJECT line */
  subject?: string;

  // ── Body sections ──────────────────────────────────────────────────────────
  /**
   * Ordered content sections. Can mix body text, key-value tables, and ledger tables.
   */
  sections: ExecutiveLedgerSection[];

  // ── Notes / Terms ──────────────────────────────────────────────────────────
  /** Free-form notes at the end of the document body */
  notes?: string;
  /** Numbered terms and conditions items */
  terms?: string[];

  // ── Signatory override ─────────────────────────────────────────────────────
  /**
   * Override the signatory block (overrides branding context signatory fields).
   * When absent, the signatory from `branding` is used if `branding.showSignatory`.
   */
  signatoryOverride?: {
    name: string;
    titleEn?: string;
    titleAr?: string;
  };

  // ── Footer override ────────────────────────────────────────────────────────
  /** Override the footer text (falls back to branding.footerTextEn) */
  footerOverride?: string;

  // ── Public Verification / QR ──────────────────────────────────────────────
  /**
   * Public verification / QR block (BRANDING.6).
   *
   * - When `qrDataUrl` is provided, renders a real QR image in the bottom-right.
   * - When only `publicUrl` is provided, renders a text URL.
   * - When absent or only `qrPlaceholder: true`, renders a placeholder box.
   * - `qrDataUrl` must pass `isValidQrDataUrl()` — only PNG/SVG from local QR helper allowed.
   * - Internal link IDs are never embedded in the renderer; only the public URL is used.
   */
  verification?: {
    /** Full public verification URL: https://...app.com/verify/TOKEN */
    publicUrl?: string | null;
    /**
     * QR code as a data URL (data:image/png;base64,...).
     * Must be generated by `generateQrDataUrl()` — no external service URLs.
     * Validated by `isValidQrDataUrl()` before rendering.
     */
    qrDataUrl?: string | null;
    /** Label shown below the QR (default: "Scan to verify") */
    label?: string;
  };

  /**
   * Legacy placeholder flag — kept for backward compatibility.
   * When `verification` is not provided and this is true, renders a placeholder box.
   * @deprecated Use `verification` prop instead.
   */
  qrPlaceholder?: boolean;

  // ── Print options ──────────────────────────────────────────────────────────
  /** Override language direction (default: ltr) */
  direction?: "ltr" | "rtl" | "auto";
  /** Override page orientation (default: portrait) */
  orientation?: "portrait" | "landscape";
}

// ─────────────────────────────────────────────────────────────────────────────
// Party block
// ─────────────────────────────────────────────────────────────────────────────

/**
 * A named party block — addressee, issuer, recipient, or employee.
 * Used in the TO / FROM / CC / ATTN header strips.
 */
export interface ExecutiveLedgerParty {
  /** Block label, e.g. "TO", "EMPLOYEE", "RECIPIENT", "ATTN" */
  label?: string;
  /** Full name */
  name: string;
  /** Job title / designation */
  title?: string;
  /** Company or department */
  company?: string;
  /** Reference ID — employee number, passport, trade licence, etc. */
  idRef?: string;
  /** Additional lines — address, email, phone */
  lines?: string[];
}

// ─────────────────────────────────────────────────────────────────────────────
// Section types
// ─────────────────────────────────────────────────────────────────────────────

/** Union type for all body section variants */
export type ExecutiveLedgerSection =
  | ExecutiveLedgerBodySection
  | ExecutiveLedgerKeyValueSection
  | ExecutiveLedgerTableSection
  | ExecutiveLedgerDividerSection;

/**
 * Free-form body text section (letter body, certifications, declarations).
 * Text must be pre-formatted; the renderer HTML-escapes it.
 */
export interface ExecutiveLedgerBodySection {
  type: "body";
  /** Optional section heading */
  title?: string;
  /** Multi-line body text. Each newline becomes a paragraph. */
  content: string;
  language?: "en" | "ar" | "bilingual";
}

/**
 * Key-value detail section — dotted rows style.
 * Used for employee details, salary components, item lists.
 */
export interface ExecutiveLedgerKeyValueSection {
  type: "key_value";
  /** Optional section heading */
  title?: string;
  rows: ExecutiveLedgerKeyValueRow[];
}

/**
 * A single key → value row inside a key-value section.
 */
export interface ExecutiveLedgerKeyValueRow {
  /** Field label */
  label: string;
  /** Display value (pre-formatted string) */
  value: string;
  /** Render value in bold — used for totals/summary rows */
  emphasized?: boolean;
  /** Render as a sub-header row (no value, just a visual divider within the section) */
  isSubHeader?: boolean;
}

/**
 * Ledger table section — formal table with headers and optional totals.
 * Used for itemized lists, salary breakdowns, PPE items, etc.
 */
export interface ExecutiveLedgerTableSection {
  type: "table";
  /** Optional section heading */
  title?: string;
  headers: string[];
  /** Each row is an array of pre-formatted strings, one per header */
  rows: string[][];
  /** Summary / totals rows displayed below the table with bold formatting */
  totals?: ExecutiveLedgerKeyValueRow[];
}

/**
 * Visual horizontal divider between sections.
 */
export interface ExecutiveLedgerDividerSection {
  type: "divider";
  /** Optional short label centered in the divider line */
  label?: string;
}
