import type { DataQualityRuleDefinition } from './types';

export const DATA_QUALITY_RULES: DataQualityRuleDefinition[] = [
  // --- Organization / owner_companies ---
  {
    rule_code: 'ORG_MISSING_LEGAL_NAME',
    label: 'Organization Missing Legal Name',
    category: 'completeness',
    severity: 'high',
    entity_types: ['organization'],
    description: 'Organization record has no legal name (EN).',
    recommendation_template: 'Add the legal name to the organization record.',
    permission_required: 'organizations.view',
    is_enabled: true,
  },
  {
    rule_code: 'ORG_MISSING_STATUS',
    label: 'Organization Missing Status',
    category: 'completeness',
    severity: 'medium',
    entity_types: ['organization'],
    description: 'Organization has no status value set.',
    recommendation_template: 'Set the status field on the organization record.',
    permission_required: 'organizations.view',
    is_enabled: true,
  },
  {
    rule_code: 'ORG_MISSING_COMPANY_CODE',
    label: 'Organization Missing Company Code',
    category: 'completeness',
    severity: 'low',
    entity_types: ['organization'],
    description: 'Organization has no company code assigned.',
    recommendation_template: 'Assign a unique company code to the organization.',
    permission_required: 'organizations.view',
    is_enabled: true,
  },
  {
    rule_code: 'ORG_HIGH_RISK_NOT_REVIEWED',
    label: 'Organization High Risk Score — Not Reviewed',
    category: 'ai_health',
    severity: 'high',
    entity_types: ['organization'],
    description: 'Organization has a high or critical AI risk score with no review recorded.',
    recommendation_template: 'Review the risk score and document findings in the AI Risk section.',
    permission_required: 'ai.risk.view',
    is_enabled: true,
  },

  // --- Branches ---
  {
    rule_code: 'BRANCH_MISSING_NAME',
    label: 'Branch Missing Name',
    category: 'completeness',
    severity: 'high',
    entity_types: ['branch'],
    description: 'Branch has no name (EN) set.',
    recommendation_template: 'Add the branch name to the record.',
    permission_required: 'branches.view',
    is_enabled: true,
  },
  {
    rule_code: 'BRANCH_MISSING_OWNER_COMPANY',
    label: 'Branch Missing Owner Company',
    category: 'relationship',
    severity: 'critical',
    entity_types: ['branch'],
    description: 'Branch is not linked to any owner company.',
    recommendation_template: 'Assign an owner company to the branch.',
    permission_required: 'branches.view',
    is_enabled: true,
  },
  {
    rule_code: 'BRANCH_MISSING_EMIRATE',
    label: 'Branch Missing Emirate/Location',
    category: 'completeness',
    severity: 'low',
    entity_types: ['branch'],
    description: 'Branch has no emirate or location data.',
    recommendation_template: 'Add location information to the branch record.',
    permission_required: 'branches.view',
    is_enabled: true,
  },

  // --- Parties ---
  {
    rule_code: 'PARTY_MISSING_DISPLAY_NAME',
    label: 'Party Missing Display Name',
    category: 'completeness',
    severity: 'high',
    entity_types: ['party'],
    description: 'Party record has no display name set.',
    recommendation_template: 'Add a display name to the party record.',
    permission_required: 'master_data.party_master.view',
    is_enabled: true,
  },
  {
    rule_code: 'PARTY_MISSING_TYPE_ASSIGNMENT',
    label: 'Party Missing Type Assignment',
    category: 'completeness',
    severity: 'high',
    entity_types: ['party'],
    description: 'Party has no active type assignment (customer, supplier, etc.).',
    recommendation_template: 'Assign at least one party type to this record.',
    permission_required: 'master_data.party_master.view',
    is_enabled: true,
  },
  {
    rule_code: 'PARTY_LICENSE_EXPIRED_WITH_ACTIVE_PARTY',
    label: 'Party License Expired',
    category: 'staleness',
    severity: 'high',
    entity_types: ['party'],
    description: 'Party has one or more active licenses that have expired.',
    recommendation_template: 'Renew or archive expired licenses on the party record.',
    permission_required: 'master_data.party_master.view',
    is_enabled: true,
  },
  {
    rule_code: 'PARTY_LICENSE_EXPIRING_SOON',
    label: 'Party License Expiring Soon (30 days)',
    category: 'staleness',
    severity: 'medium',
    entity_types: ['party'],
    description: 'Party has one or more active licenses expiring within 30 days.',
    recommendation_template: 'Initiate renewal process for expiring licenses.',
    permission_required: 'master_data.party_master.view',
    is_enabled: true,
  },
  {
    rule_code: 'PARTY_OPEN_DUPLICATE_CANDIDATES',
    label: 'Party Has Open Duplicate Candidates',
    category: 'ai_health',
    severity: 'medium',
    entity_types: ['party'],
    description: 'Party has unresolved AI duplicate/conflict candidates pending review.',
    recommendation_template: 'Review and resolve duplicate candidates in the AI Duplicates section.',
    permission_required: 'ai.duplicates.view',
    is_enabled: true,
  },
  {
    rule_code: 'PARTY_HIGH_RISK_NOT_REVIEWED',
    label: 'Party High Risk Score — Not Reviewed',
    category: 'ai_health',
    severity: 'high',
    entity_types: ['party'],
    description: 'Party has a high or critical AI risk score with no review recorded.',
    recommendation_template: 'Review the risk score in the AI Risk section.',
    permission_required: 'ai.risk.view',
    is_enabled: true,
  },
  {
    rule_code: 'PARTY_PENDING_FIELD_SUGGESTIONS_TOO_OLD',
    label: 'Party Field Suggestions Pending Too Long',
    category: 'ai_health',
    severity: 'low',
    entity_types: ['party'],
    description: 'Party has AI field suggestions pending for more than 14 days.',
    recommendation_template: 'Review and apply or dismiss pending field suggestions.',
    permission_required: 'ai.common.view',
    is_enabled: true,
  },

  // --- Work Sites ---
  {
    rule_code: 'SITE_MISSING_NAME',
    label: 'Work Site Missing Name',
    category: 'completeness',
    severity: 'high',
    entity_types: ['work_site'],
    description: 'Work site has no site name set.',
    recommendation_template: 'Add a site name to the work site record.',
    permission_required: 'common_md.work_sites.view',
    is_enabled: true,
  },
  {
    rule_code: 'SITE_MISSING_BRANCH',
    label: 'Work Site Not Linked to Branch',
    category: 'relationship',
    severity: 'medium',
    entity_types: ['work_site'],
    description: 'Work site is not linked to any branch.',
    recommendation_template: 'Assign a branch to the work site record.',
    permission_required: 'common_md.work_sites.view',
    is_enabled: true,
  },

  // --- DMS ---
  {
    rule_code: 'DMS_DOCUMENT_MISSING_CONTENT',
    label: 'DMS Document Missing Extracted Content',
    category: 'dms_health',
    severity: 'medium',
    entity_types: ['dms_document'],
    description: 'DMS document has no extracted content record.',
    recommendation_template: 'Re-process the document through the DMS pipeline to extract content.',
    permission_required: 'dms.documents.view',
    is_enabled: true,
  },
  {
    rule_code: 'DMS_DOCUMENT_EXPIRED',
    label: 'DMS Document Expired',
    category: 'staleness',
    severity: 'high',
    entity_types: ['dms_document'],
    description: 'DMS document has passed its expiry date.',
    recommendation_template: 'Review and renew or archive the expired document.',
    permission_required: 'dms.documents.view',
    is_enabled: true,
  },
  {
    rule_code: 'DMS_DOCUMENT_EXPIRING_SOON',
    label: 'DMS Document Expiring Soon (30 days)',
    category: 'staleness',
    severity: 'medium',
    entity_types: ['dms_document'],
    description: 'DMS document expires within 30 days.',
    recommendation_template: 'Initiate renewal process for this document.',
    permission_required: 'dms.documents.view',
    is_enabled: true,
  },
  {
    rule_code: 'DMS_ORPHANED_DOCUMENT_LINK',
    label: 'DMS Document Link — Unknown Entity',
    category: 'relationship',
    severity: 'low',
    entity_types: ['dms_document'],
    description: 'DMS document is linked to an entity type with no valid ID reference.',
    recommendation_template: 'Review orphaned document links and remove or correct them.',
    permission_required: 'dms.documents.view',
    is_enabled: true,
  },

  // --- AI Health ---
  {
    rule_code: 'AI_FIELD_SUGGESTION_PENDING_TOO_LONG',
    label: 'AI Field Suggestion Pending Too Long',
    category: 'ai_health',
    severity: 'low',
    entity_types: ['ai_field_suggestion'],
    description: 'AI field suggestions have been pending for more than 14 days without action.',
    recommendation_template: 'Review and apply or dismiss stale field suggestions.',
    permission_required: 'ai.common.view',
    is_enabled: true,
  },
  {
    rule_code: 'AI_DUPLICATE_CANDIDATE_OPEN_TOO_LONG',
    label: 'AI Duplicate Candidate Open Too Long',
    category: 'ai_health',
    severity: 'medium',
    entity_types: ['ai_duplicate_candidate'],
    description: 'Duplicate/conflict candidates have been open for more than 21 days without review.',
    recommendation_template: 'Review open duplicate candidates in the AI Duplicates section.',
    permission_required: 'ai.duplicates.view',
    is_enabled: true,
  },
  {
    rule_code: 'AI_COMPLIANCE_FINDING_CRITICAL_OPEN',
    label: 'AI Compliance Finding — Critical, Open',
    category: 'ai_health',
    severity: 'critical',
    entity_types: ['ai_compliance_finding'],
    description: 'Critical AI compliance finding has not been resolved.',
    recommendation_template: 'Address the critical compliance finding immediately.',
    permission_required: 'ai.compliance.view',
    is_enabled: true,
  },
  {
    rule_code: 'AI_COMPLIANCE_FINDING_OPEN_TOO_LONG',
    label: 'AI Compliance Finding Open Too Long',
    category: 'ai_health',
    severity: 'medium',
    entity_types: ['ai_compliance_finding'],
    description: 'AI compliance findings have been open for more than 30 days.',
    recommendation_template: 'Review and resolve stale compliance findings.',
    permission_required: 'ai.compliance.view',
    is_enabled: true,
  },
  {
    rule_code: 'AI_RISK_SCORE_HIGH_UNREVIEWED',
    label: 'AI Risk Score High — Not Reviewed',
    category: 'ai_health',
    severity: 'high',
    entity_types: ['ai_risk_score'],
    description: 'High or critical risk scores exist with no recorded review.',
    recommendation_template: 'Review high-risk entities in the AI Risk section.',
    permission_required: 'ai.risk.view',
    is_enabled: true,
  },
  {
    rule_code: 'AI_ASSISTANT_DRAFT_PENDING_REVIEW_TOO_LONG',
    label: 'AI Assistant Draft Pending Review Too Long',
    category: 'ai_health',
    severity: 'low',
    entity_types: ['ai_assistant_draft'],
    description: 'AI assistant action drafts have been pending review for more than 7 days.',
    recommendation_template: 'Review and approve or dismiss stale assistant drafts.',
    permission_required: 'ai.common.view',
    is_enabled: true,
  },
  {
    rule_code: 'AI_AUDIT_EXPLANATION_SOURCE_MISSING',
    label: 'AI Audit Explanation — Source Event Missing',
    category: 'ai_health',
    severity: 'low',
    entity_types: ['ai_audit_explanation'],
    description: 'AI audit explanation exists but the original audit log entry cannot be located.',
    recommendation_template: 'Review and remove orphaned audit explanations if source is permanently gone.',
    permission_required: 'ai.common.view',
    is_enabled: true,
  },

  // --- Permission Health ---
  {
    rule_code: 'PERMISSION_ACTIVE_WITH_NO_ROLE_MAPPING',
    label: 'Permission With No Role Mapping',
    category: 'permission_health',
    severity: 'low',
    entity_types: ['permission'],
    description: 'A permission exists with no role assignment, making it effectively inaccessible.',
    recommendation_template: 'Map this permission to at least one role or mark it as deprecated.',
    permission_required: 'ai.data_quality.admin',
    is_enabled: true,
  },
];

export function getRuleByCode(code: string): DataQualityRuleDefinition | undefined {
  return DATA_QUALITY_RULES.find((r) => r.rule_code === code);
}

export function getEnabledRules(): DataQualityRuleDefinition[] {
  return DATA_QUALITY_RULES.filter((r) => r.is_enabled);
}
