INSERT INTO public.banks (
  bank_code, bank_name_en, bank_name_ar, short_name, country_id, 
  bank_type_code, swift_code, website_url, contact_phone, contact_email, is_system, is_locked, sort_order
) VALUES
  ('FAB', 'First Abu Dhabi Bank', 'بنك أبوظبي الأول', 'FAB', 1, 'COMMERCIAL', 'FABUAEAA', 'https://www.bankfab.com', '+971 600 525500', 'support@bankfab.com', true, true, 10),
  ('ENBD', 'Emirates NBD', 'بنك الإمارات دبي الوطني', 'ENBD', 1, 'COMMERCIAL', 'EBILAEAD', 'https://www.emiratesnbd.com', '+971 600 540000', 'customersupport@emiratesnbd.com', true, true, 20),
  ('ADCB', 'Abu Dhabi Commercial Bank', 'بنك أبوظبي التجاري', 'ADCB', 1, 'COMMERCIAL', 'ADCBADAA', 'https://www.adcb.com', '+971 600 502030', 'customercare@adcb.com', true, true, 30),
  ('DIB', 'Dubai Islamic Bank', 'بنك دبي الإسلامي', 'DIB', 1, 'ISLAMIC', 'DIBUAEAD', 'https://www.dib.ae', '+971 4 609 2222', 'contactus@dib.ae', true, true, 40),
  ('MASHREQ', 'Mashreq Bank', 'بنك المشرق', 'Mashreq', 1, 'COMMERCIAL', 'MSHQAEAD', 'https://www.mashreqbank.com', '+971 4 424 4444', 'support@mashreq.com', true, true, 50),
  ('ADIB', 'Abu Dhabi Islamic Bank', 'بنك أبوظبي الإسلامي', 'ADIB', 1, 'ISLAMIC', 'ADIBADAA', 'https://www.adib.ae', '+971 600 543216', 'customerservice@adib.ae', false, false, 60),
  ('CBD', 'Commercial Bank of Dubai', 'بنك دبي التجاري', 'CBD', 1, 'COMMERCIAL', 'COBADEAD', 'https://www.cbd.ae', '+971 600 575556', 'customercare@cbd.ae', false, false, 70),
  ('RAKBANK', 'National Bank of Ras Al Khaimah', 'بنك رأس الخيمة الوطني', 'RAKBANK', 1, 'COMMERCIAL', 'NARAADAA', 'https://rakbank.ae', '+971 4 213 0000', 'service@rakbank.ae', false, false, 80),
  ('NBF', 'National Bank of Fujairah', 'بنك الفجيرة الوطني', 'NBF', 1, 'COMMERCIAL', 'NBFUADAA', 'https://www.nbf.ae', '+971 600 565551', 'reachus@nbf.ae', false, false, 90),
  ('NBQ', 'National Bank of Umm Al-Qaiwain', 'بنك أم القيوين الوطني', 'NBQ', 1, 'COMMERCIAL', 'NBUQADAA', 'https://www.nbq.ae', '+971 600 565656', 'info@nbq.ae', false, false, 100),
  ('SIB', 'Sharjah Islamic Bank', 'بنك الشارقة الإسلامي', 'SIB', 1, 'ISLAMIC', 'NBSHAEAA', 'https://www.sib.ae', '+971 6 599 9999', 'customercare@sib.ae', false, false, 110),
  ('CBI', 'Commercial Bank International', 'البنك التجاري الدولي', 'CBI', 1, 'COMMERCIAL', 'CBINADAA', 'https://www.cbiuae.com', '+971 600 522264', 'customercare@cbi.ae', false, false, 120),
  ('BOS', 'Bank of Sharjah', 'بنك الشارقة', 'BOS', 1, 'COMMERCIAL', 'BOSHAEAA', 'https://www.bankofsharjah.com', '+971 6 569 4444', 'info@bankofsharjah.com', false, false, 130),
  ('INVESTBANK', 'Invest Bank', 'بنك الاستثمار', 'Invest Bank', 1, 'COMMERCIAL', 'INVEAEAA', 'https://www.investbank.ae', '+971 6 598 0555', 'info@investbank.ae', false, false, 140),
  ('UAB', 'United Arab Bank', 'البنك العربي المتحد', 'UAB', 1, 'COMMERCIAL', 'UARBAEAA', 'https://www.uab.ae', '+971 600 540000', 'info@uab.ae', false, false, 150),
  ('AJMAN', 'Ajman Bank', 'بنك عجمان', 'Ajman Bank', 1, 'ISLAMIC', 'AJMNADAA', 'https://www.ajmanbank.ae', '+971 600 555522', 'info@ajmanbank.ae', false, false, 160),
  ('EIB', 'Emirates Islamic Bank', 'الإمارات الإسلامي', 'EIB', 1, 'ISLAMIC', 'EIBIADAA', 'https://www.emiratesislamic.ae', '+971 600 599995', 'customercare@emiratesislamic.ae', false, false, 170),
  ('ALMASRAF', 'Arab Bank for Investment and Foreign Trade (Al Masraf)', 'المصرف', 'Al Masraf', 1, 'COMMERCIAL', 'ALMAADAA', 'https://almasraf.ae', '+971 600 529999', 'info@almasraf.ae', false, false, 180),
  ('ALHILAL', 'Al Hilal Bank', 'بنك الهلال', 'Al Hilal Bank', 1, 'ISLAMIC', 'HILAAEAA', 'https://www.alhilalbank.ae', '+971 600 522229', 'customercare@alhilalbank.ae', false, false, 190),
  ('WIO', 'Wio Bank', 'بنك ويو', 'Wio', 1, 'COMMERCIAL', 'WIOBAEAA', 'https://wio.io', '+971 600 503000', 'support@wio.io', false, false, 200),
  ('HSBC', 'HSBC Bank Middle East Limited', 'بنك إتش إس بي سي الشرق الأوسط المحدود', 'HSBC', 1, 'COMMERCIAL', 'BBMEADAA', 'https://www.hsbc.ae', '+971 600 554722', 'customerrelations@hsbc.com', false, false, 210),
  ('SCB', 'Standard Chartered Bank', 'بنك ستاندرد تشارترد', 'Standard Chartered', 1, 'COMMERCIAL', 'SCBLADAA', 'https://www.sc.com/ae', '+971 600 522588', 'customer.care@sc.com', false, false, 220),
  ('CITI', 'Citibank N.A.', 'سيتي بنك', 'Citibank', 1, 'COMMERCIAL', 'CITIADAA', 'https://www.citibank.ae', '+971 4 311 4000', 'uae.service@citi.com', false, false, 230),
  ('HBL', 'Habib Bank Limited', 'حبيب بنك المحدود', 'HBL', 1, 'COMMERCIAL', 'HABBADEAD', 'https://www.hbl.com/uae', '+971 600 522228', 'customer.careuae@hbl.com', false, false, 240),
  ('UBL', 'United Bank Limited', 'يونايتد بنك المحدود', 'UBL', 1, 'COMMERCIAL', 'UNILADAA', 'https://www.ubldirect.com/corporate/uae', '+971 600 533335', 'customer.serviceuae@ubldirect.com', false, false, 250),
  ('NBK', 'National Bank of Kuwait', 'بنك الكويت الوطني', 'NBK', 1, 'COMMERCIAL', 'NBOKADAA', 'https://www.nbk.com/uae', '+971 4 316 1600', 'nbkuae@nbk.com', false, false, 260),
  ('NBB', 'National Bank of Bahrain', 'بنك البحرين الوطني', 'NBB', 1, 'COMMERCIAL', 'NBBHADAA', 'https://www.nbbonline.com', '+971 4 378 8600', 'contactcenter@nbbonline.com', false, false, 270),
  ('AB', 'Arab Bank plc', 'البنك العربي', 'Arab Bank', 1, 'COMMERCIAL', 'ARABAEAA', 'https://www.arabbank.ae', '+971 600 544004', 'arabbank.uae@arabbank.ae', false, false, 280),
  ('BM', 'Banque Misr', 'بنك مصر', 'Banque Misr', 1, 'COMMERCIAL', 'BMISADAA', 'https://www.banquemisr.com/en-ae', '+971 4 295 9555', 'banquemisr.uae@banquemisr.com', false, false, 290),
  ('BOB', 'Bank of Baroda', 'بنك بارودا', 'Bank of Baroda', 1, 'COMMERCIAL', 'BARBADEAD', 'https://www.bankofbaroda.ae', '+971 4 313 6666', 'uae@bankofbaroda.com', false, false, 300),
  ('SBI', 'State Bank of India', 'بنك الهند الحكومي', 'SBI', 1, 'COMMERCIAL', 'SBINADAA', 'https://ae.statebank', '+971 4 353 3555', 'sbi.uae@statebank', false, false, 310),
  ('SADERAT', 'Bank Saderat Iran', 'بنك صادرات إيران', 'Bank Saderat', 1, 'COMMERCIAL', 'SADEADAA', 'https://www.bsi.ir', '+971 4 228 1781', 'dubai@bsi.ir', false, false, 320),
  ('MELLI', 'Bank Melli Iran', 'بنك ملي إيران', 'Bank Melli', 1, 'COMMERCIAL', 'MELIADAA', 'https://www.bmi.ir', '+971 4 228 2171', 'dubai@bmi.ir', false, false, 330),
  ('ABK', 'Al Ahli Bank of Kuwait', 'البنك الأهلي الكويتي', 'ABK', 1, 'COMMERCIAL', 'ABKOADAA', 'https://www.abkuae.com', '+971 4 506 8300', 'info@abkuae.com', false, false, 340),
  ('ICICI', 'ICICI Bank Limited', 'آي سي آي سي آي بنك المحدود', 'ICICI', 1, 'COMMERCIAL', 'ICICADAA', 'https://www.icicibank.ae', '+971 4 369 6400', 'dxb.corporate@icicibank.com', false, false, 350)
ON CONFLICT (bank_code) DO UPDATE SET
  bank_name_en = EXCLUDED.bank_name_en,
  bank_name_ar = COALESCE(banks.bank_name_ar, EXCLUDED.bank_name_ar),
  short_name = COALESCE(banks.short_name, EXCLUDED.short_name),
  country_id = EXCLUDED.country_id,
  bank_type_code = EXCLUDED.bank_type_code,
  swift_code = COALESCE(banks.swift_code, EXCLUDED.swift_code),
  website_url = COALESCE(banks.website_url, EXCLUDED.website_url),
  contact_phone = COALESCE(banks.contact_phone, EXCLUDED.contact_phone),
  contact_email = COALESCE(banks.contact_email, EXCLUDED.contact_email),
  is_system = EXCLUDED.is_system,
  is_locked = EXCLUDED.is_locked,
  updated_at = now();