-- DIAGNOSTIC TEST: Apply this first to find the error
-- This will test each section independently

-- ============================================================================
-- TEST 1: Verify helper functions exist
-- ============================================================================
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_proc WHERE proname = 'current_user_has_permission') THEN
    RAISE EXCEPTION 'Function current_user_has_permission() does not exist';
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM pg_proc WHERE proname = 'current_user_has_role') THEN
    RAISE EXCEPTION 'Function current_user_has_role() does not exist';
  END IF;
  
  RAISE NOTICE 'Helper functions exist ✓';
END $$;

-- ============================================================================
-- TEST 2: Verify global_lookup_categories schema
-- ============================================================================
DO $$
DECLARE
  col_exists boolean;
BEGIN
  SELECT EXISTS (
    SELECT 1
    FROM information_schema.columns 
    WHERE table_name = 'global_lookup_categories' 
      AND column_name = 'is_locked'
  ) INTO col_exists;
  
  IF NOT col_exists THEN
    RAISE EXCEPTION 'Column is_locked does not exist in global_lookup_categories';
  END IF;
  
  RAISE NOTICE 'global_lookup_categories.is_locked exists ✓';
END $$;

-- ============================================================================
-- TEST 3: Try creating a minimal test table with is_locked
-- ============================================================================
DROP TABLE IF EXISTS test_is_locked CASCADE;

CREATE TABLE test_is_locked (
  id bigint generated by default as identity primary key,
  name text not null,
  is_locked boolean not null default false,
  is_active boolean not null default true
);

-- Try creating a simple RLS policy on it
ALTER TABLE test_is_locked ENABLE ROW LEVEL SECURITY;

CREATE POLICY test_select_policy ON test_is_locked FOR SELECT
  USING (is_active = true);

-- Clean up
DROP TABLE test_is_locked CASCADE;

RAISE NOTICE 'Test table with is_locked created and dropped successfully ✓';

-- ============================================================================
-- TEST 4: Test inserting into global_lookup_categories
-- ============================================================================
INSERT INTO global_lookup_categories (
  category_code, category_name_en, category_name_ar, description, 
  module_code, category_scope, supports_hierarchy, supports_color, 
  supports_icon, supports_effective_dates, supports_metadata, 
  is_system, is_locked, is_active, sort_order
) VALUES (
  'TEST_DIAGNOSTIC', 'Test Diagnostic', 'اختبار تشخيصي',
  'Temporary test category for diagnostic purposes',
  'SYSTEM', 'GLOBAL', false, false, false, false, false, false, false, true, 9999
)
ON CONFLICT (category_code) DO UPDATE SET
  updated_at = now();

-- Clean up
DELETE FROM global_lookup_categories WHERE category_code = 'TEST_DIAGNOSTIC';

RAISE NOTICE 'global_lookup_categories INSERT test successful ✓';

-- ============================================================================
-- ALL TESTS PASSED
-- ============================================================================
DO $$
BEGIN
  RAISE NOTICE '========================================';
  RAISE NOTICE 'ALL DIAGNOSTIC TESTS PASSED';
  RAISE NOTICE 'Your database schema is ready for the migration';
  RAISE NOTICE '========================================';
END $$;
