-- ============================================================
-- ERP DMS 12.1 — AI CONTENT INTELLIGENCE PROPOSED SCHEMA
-- REVIEW ONLY — DO NOT RUN WITHOUT SAMEER APPROVAL
-- ============================================================
--
-- This file was generated by Cursor AI on 2026-06-15 during
-- planning phase ERP DMS 12.1 (no implementation).
--
-- Live DB was audited. dms_documents has NO content_text,
-- ai_summary, content_tsv, ai_risk_score, or completeness_score
-- columns as of this date. All changes below are NEW additions.
--
-- All DMS tables confirmed: RLS ENABLED + FORCED (27 tables).
-- Existing RLS policies automatically cover new columns — no new
-- policy statements needed.
--
-- Before running: confirm with Sameer, test on staging, run in
-- a transaction with explicit ROLLBACK if anything fails.
-- ============================================================


-- ════════════════════════════════════════════════════════════
-- SECTION 1: PHASE 12.1 — CONTENT TEXT FOUNDATION
-- Adds full readable text storage to dms_documents.
-- Depends on: nothing (can run standalone)
-- ════════════════════════════════════════════════════════════

-- 1a. Content text columns
ALTER TABLE public.dms_documents
  ADD COLUMN IF NOT EXISTS content_text          TEXT,
  ADD COLUMN IF NOT EXISTS content_text_updated_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS content_text_source   TEXT,      -- 'ocr' | 'ai_intake' | 'manual_override' | 'truncated'
  ADD COLUMN IF NOT EXISTS content_text_hash     TEXT,      -- djb2 hash for change detection
  ADD COLUMN IF NOT EXISTS content_text_char_count INTEGER; -- char length for monitoring

COMMENT ON COLUMN public.dms_documents.content_text
  IS 'Consolidated full readable text of the current document version. Max 100,000 characters. Denormalised from dms_document_files.ocr_text for fast full-text search.';
COMMENT ON COLUMN public.dms_documents.content_text_source
  IS 'Source of content_text: ocr | ai_intake | manual_override | truncated';


-- ════════════════════════════════════════════════════════════
-- SECTION 2: PHASE 12.1 — FULL-TEXT SEARCH INDEX (tsvector)
-- Uses GENERATED ALWAYS AS STORED — auto-updated on any row change.
-- Combines: document_no, title, description, content_text, ai_summary.
-- NOTE: ai_summary column (Section 3) must exist before this runs.
-- Option: Run without ai_summary first and ALTER later to add it.
-- ════════════════════════════════════════════════════════════

-- 2a. Add tsvector generated column
-- ⚠ Run AFTER ai_summary column is added (Section 3) OR remove coalesce(ai_summary,'') for now.
ALTER TABLE public.dms_documents
  ADD COLUMN IF NOT EXISTS content_tsv TSVECTOR
    GENERATED ALWAYS AS (
      to_tsvector(
        'english',
        coalesce(document_no,   '') || ' ' ||
        coalesce(title,         '') || ' ' ||
        coalesce(description,   '') || ' ' ||
        coalesce(content_text,  '') || ' ' ||
        coalesce(ai_summary,    '')
      )
    ) STORED;

COMMENT ON COLUMN public.dms_documents.content_tsv
  IS 'Auto-generated tsvector for GIN full-text search. Covers document_no, title, description, content_text, ai_summary.';

-- 2b. GIN index for full-text search performance
CREATE INDEX IF NOT EXISTS idx_dms_documents_content_tsv
  ON public.dms_documents USING GIN (content_tsv);

-- 2c. Optional: standard BTREE indexes for content_text_source and char_count filtering
CREATE INDEX IF NOT EXISTS idx_dms_documents_content_text_source
  ON public.dms_documents (content_text_source)
  WHERE content_text_source IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_dms_documents_no_content_text
  ON public.dms_documents (id)
  WHERE content_text IS NULL AND deleted_at IS NULL;  -- for bulk backfill queries


-- ════════════════════════════════════════════════════════════
-- SECTION 3: PHASE 12.2 — AI SUMMARY COLUMNS
-- Must be added before Section 2 if content_tsv includes ai_summary.
-- ════════════════════════════════════════════════════════════

-- 3a. AI summary columns
ALTER TABLE public.dms_documents
  ADD COLUMN IF NOT EXISTS ai_summary            TEXT,
  ADD COLUMN IF NOT EXISTS ai_summary_updated_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS ai_summary_model      TEXT,      -- e.g. 'gpt-4o', 'gpt-4-turbo'
  ADD COLUMN IF NOT EXISTS ai_summary_status     TEXT       -- 'pending' | 'complete' | 'failed' | 'skipped'
                           DEFAULT 'pending',
  ADD COLUMN IF NOT EXISTS ai_summary_error      TEXT;      -- error message if failed

COMMENT ON COLUMN public.dms_documents.ai_summary
  IS '3-5 sentence AI-generated summary. Plain text, no markdown. Stored for display and search.';
COMMENT ON COLUMN public.dms_documents.ai_summary_status
  IS 'pending | complete | failed | skipped';


-- ════════════════════════════════════════════════════════════
-- SECTION 4: PHASE 12.3 — COMPLETENESS AND RISK SCORE COLUMNS
-- ════════════════════════════════════════════════════════════

-- 4a. Completeness scoring
ALTER TABLE public.dms_documents
  ADD COLUMN IF NOT EXISTS completeness_score    NUMERIC(5,4),  -- 0.0000–1.0000
  ADD COLUMN IF NOT EXISTS missing_fields_json   JSONB,         -- array of {field_code, field_label}
  ADD COLUMN IF NOT EXISTS ai_warnings_json      JSONB;         -- array of warning strings from AI

COMMENT ON COLUMN public.dms_documents.completeness_score
  IS 'Computed 0.0–1.0 score. Based on required metadata fields, issue_date, expiry_date, content_text, ai_summary.';
COMMENT ON COLUMN public.dms_documents.missing_fields_json
  IS 'JSON array: [{field_code, field_label_en}] for required fields with no value.';
COMMENT ON COLUMN public.dms_documents.ai_warnings_json
  IS 'JSON array of warning strings captured from AI extraction (e.g. "Low image quality", "Only one date visible").';

-- 4b. Risk scoring
ALTER TABLE public.dms_documents
  ADD COLUMN IF NOT EXISTS ai_risk_score         NUMERIC(5,4),  -- 0.0000–1.0000
  ADD COLUMN IF NOT EXISTS ai_risk_level         TEXT,          -- none | low | medium | high | critical
  ADD COLUMN IF NOT EXISTS ai_risk_reasons_json  JSONB,         -- array of reason strings
  ADD COLUMN IF NOT EXISTS ai_risk_updated_at    TIMESTAMPTZ;

COMMENT ON COLUMN public.dms_documents.ai_risk_level
  IS 'none | low | medium | high | critical. Computed from expiry, missing fields, classification confidence.';

-- 4c. Index on risk level for dashboard filtering
CREATE INDEX IF NOT EXISTS idx_dms_documents_ai_risk_level
  ON public.dms_documents (ai_risk_level)
  WHERE ai_risk_level IS NOT NULL AND deleted_at IS NULL;

-- 4d. Index on completeness score
CREATE INDEX IF NOT EXISTS idx_dms_documents_completeness
  ON public.dms_documents (completeness_score)
  WHERE completeness_score IS NOT NULL AND deleted_at IS NULL;


-- ════════════════════════════════════════════════════════════
-- SECTION 5: PHASE 12.3 — AI_EXTRACTION_RESULTS NEW COLUMNS
-- Adds permanent storage for additional_fields and detected_entities
-- (currently only in raw_response_json).
-- ════════════════════════════════════════════════════════════

ALTER TABLE public.dms_ai_extraction_results
  ADD COLUMN IF NOT EXISTS additional_fields_json  JSONB,   -- parsed from raw_response_json.additional_fields
  ADD COLUMN IF NOT EXISTS detected_entities_json  JSONB;   -- parsed from raw_response_json.detected_entities

COMMENT ON COLUMN public.dms_ai_extraction_results.additional_fields_json
  IS 'Parsed additional_fields from AI JSON response. [{label, value, confidence_score}]';
COMMENT ON COLUMN public.dms_ai_extraction_results.detected_entities_json
  IS 'Parsed detected_entities from AI JSON response. [{entity_type, name, name_ar, identifier, role}]';


-- ════════════════════════════════════════════════════════════
-- SECTION 6: PHASE 12.4 — NEW erp_ai_feature_flags ROWS
-- Data-only. No schema change needed (feature_code already has UNIQUE).
-- ════════════════════════════════════════════════════════════
-- ⚠ Confirm feature_code is UNIQUE before running.
-- Run as: ON CONFLICT (feature_code) DO NOTHING

INSERT INTO public.erp_ai_feature_flags
  (feature_code, feature_name, description, is_enabled, requires_human_review, min_confidence_threshold)
VALUES
  ('DMS_CONTENT_TEXT_SYNC',
   'DMS Content Text Sync',
   'Auto-sync document OCR text to content_text on dms_documents after OCR or AI intake.',
   true, false, 0.000),

  ('DMS_AI_SUMMARY',
   'DMS AI Document Summary',
   'Generate and store 3-5 sentence AI summary for each document.',
   true, false, 0.000),

  ('DMS_AI_SEARCH',
   'DMS AI Natural Language Search',
   'Use LLM intent extraction to convert user questions into SQL document searches.',
   true, false, 0.000),

  ('DMS_AUTO_TAGS',
   'DMS AI Auto-Tag Suggestion',
   'AI suggests tags based on document content. User must approve before saving.',
   true, true, 0.700),

  ('DMS_SMART_LINKS',
   'DMS AI Smart ERP Linking',
   'AI suggests ERP record links (party, employee, etc.). User must approve.',
   true, true, 0.750),

  ('DMS_RISK_SCORE',
   'DMS AI Risk Scoring',
   'Compute ai_risk_score and ai_risk_level from expiry, completeness, and AI warnings.',
   true, false, 0.000),

  ('DMS_COMPLETENESS',
   'DMS AI Completeness Check',
   'Compute completeness_score and missing_fields_json based on required metadata.',
   true, false, 0.000),

  ('DMS_DUPLICATE_DETECT',
   'DMS Duplicate Document Detection',
   'Detect similar documents by sha256, extracted identifiers, and content similarity.',
   true, true, 0.800),

  ('DMS_EXPIRY_INTEL',
   'DMS AI Expiry Intelligence',
   'AI classifies expiry state (has_expiry, no_expiry, expiry_unclear, renewal_required).',
   true, false, 0.000),

  ('DMS_DOCUMENT_QA',
   'DMS Ask About Document',
   'Allow users to ask natural language questions about a specific document.',
   true, false, 0.000),

  ('DMS_CROSS_DOC_SEARCH',
   'DMS Cross-Document AI Search',
   'Allow users to ask questions across all accessible documents.',
   true, false, 0.000)

ON CONFLICT (feature_code) DO NOTHING;


-- ════════════════════════════════════════════════════════════
-- SECTION 7: PHASE 12.5 (FUTURE) — pgvector EMBEDDINGS
-- ⚠ DO NOT RUN — Future phase, requires pgvector extension.
-- Included here for review and discussion only.
-- ════════════════════════════════════════════════════════════

-- -- Step 1: Enable pgvector extension (requires Supabase support)
-- CREATE EXTENSION IF NOT EXISTS vector;

-- -- Step 2: Add embedding column to dms_documents
-- ALTER TABLE public.dms_documents
--   ADD COLUMN IF NOT EXISTS summary_embedding VECTOR(1536);
-- -- Uses OpenAI text-embedding-3-small (1536 dimensions, ~$0.02/1M tokens)
-- -- Alternative: text-embedding-ada-002 (also 1536 dim, legacy)

-- -- Step 3: ivfflat index for approximate nearest-neighbor search
-- CREATE INDEX IF NOT EXISTS idx_dms_documents_embedding
--   ON public.dms_documents USING ivfflat (summary_embedding vector_cosine_ops)
--   WITH (lists = 100);
-- -- lists = sqrt(num_rows). With 100 documents: lists=10. With 10,000: lists=100.
-- -- Re-run REINDEX after significant data growth.

-- -- Step 4: Chunked content storage (for large document embeddings)
-- CREATE TABLE IF NOT EXISTS public.dms_document_content_chunks (
--   id            BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
--   document_id   BIGINT NOT NULL REFERENCES public.dms_documents(id) ON DELETE CASCADE,
--   chunk_index   INTEGER NOT NULL,
--   chunk_text    TEXT NOT NULL,
--   chunk_tokens  INTEGER,
--   embedding     VECTOR(1536),
--   created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
--   UNIQUE (document_id, chunk_index)
-- );
-- -- RLS: Must add ENABLE ROW LEVEL SECURITY + FORCE ROW LEVEL SECURITY
-- -- Policy: Same as dms_documents SELECT policy.

-- -- Step 5: Semantic search query example
-- -- SELECT d.id, d.title, d.document_no, d.ai_summary,
-- --        1 - (d.summary_embedding <=> $query_embedding) AS similarity
-- -- FROM dms_documents d
-- -- WHERE d.deleted_at IS NULL
-- --   AND d.summary_embedding IS NOT NULL
-- -- ORDER BY d.summary_embedding <=> $query_embedding
-- -- LIMIT 20;


-- ════════════════════════════════════════════════════════════
-- SECTION 8: RLS REVIEW NOTES
-- No RLS policy changes are needed.
-- ════════════════════════════════════════════════════════════

-- ✅ All new columns on dms_documents inherit existing RLS policies:
--    SELECT: auth.uid() IS NOT NULL AND dms.documents.view permission
--    UPDATE: dms.documents.edit permission
--    DELETE: dms.documents.delete permission
--
-- ✅ content_text confidentiality note (enforce in server actions, not SQL policy):
--    For confidentiality_level IN ('hr', 'legal', 'executive'):
--    Server actions returning content_text must check dms.admin permission.
--    The existing RLS SELECT policy allows any dms.documents.view user to read
--    all columns including content_text — confidentiality filtering is in the
--    application layer (hasPermission check in server actions), same as ai_status.
--
-- ⚠ dms_intake_review_values: RLS enabled but NOT forced.
--    Recommendation: Add ALTER TABLE dms_intake_review_values FORCE ROW LEVEL SECURITY
--    in a future cleanup migration. Low risk (review drafts only).
--
-- ⚠ dms_party_document_migration_map: No RLS.
--    Legacy migration tracking table. No sensitive data. Low risk.
--    Recommendation: Leave as-is (migration is complete).


-- ════════════════════════════════════════════════════════════
-- SECTION 9: VERIFICATION QUERIES (run before and after)
-- ════════════════════════════════════════════════════════════

-- Verify new columns on dms_documents after running Sections 1-4:
SELECT column_name, data_type, is_nullable, column_default
FROM information_schema.columns
WHERE table_name = 'dms_documents'
  AND table_schema = 'public'
  AND column_name IN (
    'content_text', 'content_text_updated_at', 'content_text_source',
    'content_text_hash', 'content_text_char_count', 'content_tsv',
    'ai_summary', 'ai_summary_updated_at', 'ai_summary_model',
    'ai_summary_status', 'ai_summary_error',
    'completeness_score', 'missing_fields_json', 'ai_warnings_json',
    'ai_risk_score', 'ai_risk_level', 'ai_risk_reasons_json', 'ai_risk_updated_at'
  )
ORDER BY column_name;

-- Verify GIN index:
SELECT indexname, indexdef
FROM pg_indexes
WHERE tablename = 'dms_documents'
  AND indexname LIKE '%content_tsv%';

-- Verify new feature flags:
SELECT feature_code, is_enabled, requires_human_review
FROM erp_ai_feature_flags
WHERE feature_code LIKE 'DMS_%'
ORDER BY feature_code;

-- Test tsvector content (after adding at least one document with content_text):
-- SELECT id, title, ts_rank(content_tsv, plainto_tsquery('english', 'offshore medical')) as rank
-- FROM dms_documents
-- WHERE content_tsv @@ plainto_tsquery('english', 'offshore medical')
--   AND deleted_at IS NULL
-- ORDER BY rank DESC
-- LIMIT 10;

-- ============================================================
-- END OF REVIEW SQL
-- REVIEW ONLY — DO NOT RUN WITHOUT SAMEER APPROVAL
-- ============================================================
