/**
 * Public Verification — QR Code Generation
 * Phase: BRANDING.6
 *
 * Generates QR codes as data URLs for embedding in Executive Ledger HTML output.
 * Uses the `qrcode` npm package — local generation, no external services.
 *
 * Security rules:
 * - Only generates QR for /verify/ paths or https:// URLs
 * - Returns data:image/png;base64,... URLs (safe for img src)
 * - Never uses external QR services (api.qrserver.com etc.)
 * - Never embeds internal IDs in QR content
 */

import QRCode from "qrcode";

/**
 * Generate a QR code as a base64 PNG data URL.
 *
 * @param url - The full verification URL to encode (must be /verify/... path or https://)
 * @returns data:image/png;base64,... string, or null if generation fails
 */
export async function generateQrDataUrl(url: string): Promise<string | null> {
  if (!url) return null;

  // Only generate QR for verification paths or https URLs — never for arbitrary input
  const isVerifyPath = url.startsWith("/verify/") || url.startsWith("https://");
  if (!isVerifyPath) return null;

  try {
    const dataUrl = await QRCode.toDataURL(url, {
      errorCorrectionLevel: "M",
      margin: 1,
      width: 120,
      color: {
        dark: "#1e293b",  // ERP primary color
        light: "#ffffff",
      },
    });
    return dataUrl;
  } catch {
    return null;
  }
}

/**
 * Validate that a data URL is a safe QR image data URL.
 * Only allows PNG or SVG images generated by our trusted QR helper.
 * Prevents arbitrary data URLs from user input being injected into the renderer.
 */
export function isValidQrDataUrl(url: string | null | undefined): boolean {
  if (!url) return false;
  return (
    url.startsWith("data:image/png;base64,") ||
    url.startsWith("data:image/svg+xml;base64,")
  );
}
