// @vitest-environment jsdom
import './setup';
import { afterEach, beforeEach, expect, it, vi } from 'vitest';
import { cleanup, fireEvent, render, screen } from '@testing-library/react';
import { FluentProvider, webLightTheme } from '@fluentui/react-components';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { WorkspaceUiMemoryProvider } from '@/hooks/use-persistent-ui-state';
import { DmsDocumentLinksSection } from '@/features/dms/documents/sections/dms-document-links-section';
const mocks=vi.hoisted(()=>({list:vi.fn(),add:vi.fn(),entities:vi.fn()}));
vi.mock('@/server/actions/dms/document-links',()=>({getDmsDocumentLinks:mocks.list,addDmsDocumentLink:mocks.add,updateDmsDocumentLink:vi.fn(),removeDmsDocumentLink:vi.fn(),searchDmsLinkEntityOptions:mocks.entities}));
vi.mock('@/server/actions/dms/ai-links',()=>({getDmsLinkSuggestions:async()=>({success:true,data:[]}),suggestDmsDocumentLinks:vi.fn(),applyDmsLinkSuggestions:vi.fn(),rejectDmsLinkSuggestions:vi.fn()}));
beforeEach(()=>{vi.resetAllMocks();mocks.list.mockResolvedValue({success:true,data:[]});mocks.entities.mockResolvedValue({success:true,data:[]});});afterEach(cleanup);
function mount(isViewing=false){return render(<FluentProvider theme={webLightTheme}><WorkspaceUiMemoryProvider><QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><DmsDocumentLinksSection documentId={71} isViewing={isViewing}/></QueryClientProvider></WorkspaceUiMemoryProvider></FluentProvider>);}
it('link read failures offer retry instead of inventing an empty list',async()=>{mocks.list.mockRejectedValueOnce(new Error('private detail'));mount();await screen.findByRole('alert');expect(screen.queryByText('No entity links yet')).toBeNull();fireEvent.click(screen.getByRole('button',{name:'Retry'}));await screen.findByText('No entity links yet');expect(screen.queryByText('private detail')).toBeNull();});
it('Add Link uses the global child dialog and linked entity validation',async()=>{mount();fireEvent.click(await screen.findByRole('button',{name:'Add Link'}));expect(screen.getByRole('dialog').textContent).toContain('Add Entity Link');await screen.findByRole('combobox',{name:'Linked employee'});fireEvent.click(screen.getByRole('button',{name:'Add',exact:true}));expect(screen.getByRole('alert').textContent).toContain('required');expect(mocks.add).not.toHaveBeenCalled();expect(screen.getByRole('combobox',{name:'Linked employee'})).toBeTruthy();});
it('view-only links expose no add or row edit/remove controls',async()=>{mocks.list.mockResolvedValue({success:true,data:[{id:1,entity_type:'employee',entity_type_label:'Employee',entity_id:900301,entity_display_name:'Synthetic employee',linked_at:'2026-09-30T08:00:00Z',is_primary:false}]});mount(true);await screen.findByText('Synthetic employee');expect(screen.queryByRole('button',{name:'Add Link'})).toBeNull();expect(screen.queryByRole('button',{name:'Edit link'})).toBeNull();expect(screen.queryByRole('button',{name:'Remove link'})).toBeNull();});
it('related list filters do not send unrelated values into storage or expose mutation columns',async()=>{mount(true);await screen.findByText('No entity links yet');fireEvent.click(screen.getByRole('button',{name:'Edit columns'}));expect(screen.queryByRole('checkbox',{name:'Actions'})).toBeNull();expect((screen.getByRole('checkbox',{name:'Entity (required)'}) as HTMLInputElement).disabled).toBe(true);});
it('confirmed discard clears the unsaved Add Link values for the next opening',async()=>{mount();fireEvent.click(await screen.findByRole('button',{name:'Add Link'}));await screen.findByRole('combobox',{name:'Linked employee'});fireEvent.change(screen.getByLabelText('Role (optional)'),{target:{value:'Discard this draft'}});fireEvent.click(screen.getByRole('button',{name:'Cancel',exact:true}));fireEvent.click(screen.getByRole('button',{name:'Discard changes'}));fireEvent.click(screen.getByRole('button',{name:'Add Link'}));expect((screen.getByLabelText('Role (optional)') as HTMLInputElement).value).toBe('');expect(mocks.add).not.toHaveBeenCalled();});
