// @vitest-environment jsdom
import './setup';
import { afterEach, beforeEach, expect, it, vi } from 'vitest';
import { act, cleanup, fireEvent, render, screen, waitFor, within } from '@testing-library/react';
import { FluentProvider, webLightTheme } from '@fluentui/react-components';
import { WorkspaceUiMemoryProvider } from '@/hooks/use-persistent-ui-state';
import { DmsReviewQueuePageClient } from '@/features/dms/review-queue/dms-review-queue-page-client';
import { DmsReviewQueueItemDrawer } from '@/features/dms/review-queue/dms-review-queue-item-drawer';
import type { ReviewQueueItem } from '@/server/actions/dms/review-queue';
const mocks=vi.hoisted(()=>({list:vi.fn(),counts:vi.fn(),detail:vi.fn(),action:vi.fn()}));
vi.mock('@/server/actions/dms/review-queue',()=>({getDmsReviewQueueItems:mocks.list,getDmsReviewQueueCounts:mocks.counts,getDmsReviewQueueItem:mocks.detail,assignDmsReviewQueueItem:mocks.action,startDmsReviewQueueItem:mocks.action,resolveDmsReviewQueueItem:mocks.action,dismissDmsReviewQueueItem:mocks.action}));
vi.mock('@/server/actions/dms/validation',()=>({reviewDmsValidationFinding:mocks.action,markDmsValidationFindingFalsePositive:mocks.action}));
vi.mock('@/server/actions/dms/entity-matching',()=>({reviewDmsEntityMatchCandidate:mocks.action}));
vi.mock('@/features/dms/apply-to-erp',()=>({DmsApplyToErpPreview:()=>null,DmsPartyTargetSelector:()=>null}));
vi.mock('@/features/dms/admin/dms-ai-metadata-suggestions-dialog',()=>({DmsAiMetadataSuggestionsDialog:()=>null}));
const item={id:17,reviewType:'ocr_failure_review',status:'open',priority:'normal',reasonMessage:'Synthetic first',queuedAt:'2026-09-30T08:00:00Z',createdAt:'2026-09-30T08:00:00Z',updatedAt:'2026-09-30T08:00:00Z',confidence:null,payloadJson:null} as ReviewQueueItem;
beforeEach(()=>{vi.resetAllMocks();mocks.list.mockResolvedValue({success:true,data:{items:[],total:0}});mocks.counts.mockResolvedValue({success:false});mocks.detail.mockResolvedValue({success:true,data:item});});afterEach(()=>{cleanup();vi.restoreAllMocks();});
function page(canManage=true,items=[item]){return render(<FluentProvider theme={webLightTheme}><WorkspaceUiMemoryProvider><DmsReviewQueuePageClient initialItems={items} initialTotal={items.length} initialCounts={null} canManage={canManage} canAdmin={false}/></WorkspaceUiMemoryProvider></FluentProvider>);}
it('unavailable summary is explicitly different from zero',()=>{page();expect(screen.getByText(/unavailable counts are not zero/)).toBeTruthy();expect(screen.getByText('Synthetic first')).toBeTruthy();});
it('rejected queue refresh offers retry and does not show stale rows as current',async()=>{mocks.list.mockRejectedValueOnce(new Error('private'));page();fireEvent.click(screen.getByRole('button',{name:'Refresh',exact:true}));await screen.findByRole('alert');expect(screen.queryByText('Synthetic first')).toBeNull();expect(screen.queryByText('private')).toBeNull();fireEvent.click(await screen.findByRole('button',{name:'Retry',exact:true}));await waitFor(()=>expect(screen.queryByRole('alert')).toBeNull());expect(mocks.list).toHaveBeenCalledTimes(2);});
it('server review multi-select criteria reset the page and preserve their array semantics',async()=>{page();fireEvent.click(screen.getByRole('button',{name:'Edit filters'}));fireEvent.click(screen.getByRole('checkbox',{name:'Open',exact:true}));fireEvent.click(screen.getByRole('checkbox',{name:'Assigned',exact:true}));fireEvent.click(screen.getByRole('button',{name:'Apply',exact:true}));await waitFor(()=>expect(mocks.list).toHaveBeenCalledWith(expect.objectContaining({status:['open','assigned'],page:1,pageSize:25})));});
it('current-page keyword filtering is labelled and recoverable without server queries',()=>{page();fireEvent.change(screen.getByLabelText('Search current review page'),{target:{value:'no match'}});expect(screen.queryByText('Synthetic first')).toBeNull();expect(mocks.list).not.toHaveBeenCalled();fireEvent.change(screen.getByLabelText('Search current review page'),{target:{value:''}});expect(screen.getByText('Synthetic first')).toBeTruthy();});
it('detail failures keep management actions disabled until retry succeeds',async()=>{mocks.detail.mockRejectedValueOnce(new Error('private'));page();fireEvent.click(screen.getByRole('button',{name:'View review item 17'}));const dialog=await screen.findByRole('dialog');await within(dialog).findByRole('alert');expect(within(dialog).queryByRole('button',{name:'Start Review'})).toBeNull();fireEvent.click(within(dialog).getByRole('button',{name:'Retry'}));await within(dialog).findByRole('button',{name:'Start Review'});});
it('a late response for closed item A cannot replace the open item B',async()=>{let resolve!:(v:unknown)=>void;mocks.detail.mockReturnValueOnce(new Promise(r=>{resolve=r;})).mockResolvedValueOnce({success:true,data:{...item,id:18,reasonMessage:'Synthetic second'}});page(true,[item,{...item,id:18,reasonMessage:'Synthetic second'}]);fireEvent.click(screen.getByRole('button',{name:'View review item 17'}));fireEvent.click(await screen.findByRole('button',{name:'Close review item'}));await waitFor(()=>expect(screen.queryByRole('dialog')).toBeNull());fireEvent.click(screen.getByRole('button',{name:'View review item 18'}));const dialog=await screen.findByRole('dialog');await within(dialog).findByRole('button',{name:'Start Review'});await act(async()=>resolve({success:true,data:item}));expect(within(dialog).getByText('Synthetic second')).toBeTruthy();expect(within(dialog).queryByText('Synthetic first')).toBeNull();});
it('dirty review entries can refuse dismissal without losing their content',async()=>{const confirm=vi.spyOn(window,'confirm').mockReturnValue(false);page();fireEvent.click(screen.getByRole('button',{name:'View review item 17'}));fireEvent.click(await screen.findByRole('button',{name:'Resolve',exact:true}));fireEvent.change(screen.getByLabelText('Resolution notes'),{target:{value:'Keep this review note'}});fireEvent.click(screen.getByRole('button',{name:'Close review item'}));expect(confirm).toHaveBeenCalledWith('Discard the unsaved review entries?');expect((screen.getByLabelText('Resolution notes') as HTMLTextAreaElement).value).toBe('Keep this review note');});
it('read-only review details have no business mutation controls',async()=>{page(false);fireEvent.click(screen.getByRole('button',{name:'View review item 17'}));await screen.findByText(/view-only access/);expect(screen.queryByRole('button',{name:'Resolve',exact:true})).toBeNull();expect(screen.queryByRole('button',{name:'Assign to Me'})).toBeNull();expect(mocks.action).not.toHaveBeenCalled();});
it('review action rejection preserves entries, announces a safe error and releases busy state',async()=>{mocks.action.mockRejectedValue(new Error('private provider detail'));const mutated=vi.fn(),busy=vi.fn();render(<DmsReviewQueueItemDrawer item={item} canManage onClose={vi.fn()} onMutated={mutated} onBusyChange={busy}/>);fireEvent.click(screen.getByRole('button',{name:'Resolve',exact:true}));fireEvent.change(screen.getByLabelText('Resolution notes'),{target:{value:'Synthetic review note'}});fireEvent.click(screen.getByRole('button',{name:'Confirm Resolve'}));await screen.findByRole('alert');expect(screen.getByRole('alert').textContent).toContain('could not be confirmed');expect(screen.queryByText('private provider detail')).toBeNull();expect((screen.getByLabelText('Resolution notes') as HTMLTextAreaElement).value).toBe('Synthetic review note');expect(mutated).not.toHaveBeenCalled();expect(busy).toHaveBeenLastCalledWith(false);});
it('empty dismissal cannot call the action and the reason is announced',async()=>{render(<DmsReviewQueueItemDrawer item={item} canManage onClose={vi.fn()} onMutated={vi.fn()}/>);fireEvent.click(screen.getByRole('button',{name:'Dismiss',exact:true}));fireEvent.click(screen.getByRole('button',{name:'Confirm Dismiss'}));expect(screen.getByRole('alert').textContent).toContain('dismissal reason');expect(mocks.action).not.toHaveBeenCalled();});
