// @vitest-environment jsdom
import './setup';
import { afterEach, beforeEach, expect, it, vi } from 'vitest';
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { FluentProvider, webLightTheme } from '@fluentui/react-components';
import { WorkspaceUiMemoryProvider } from '@/hooks/use-persistent-ui-state';
import { DmsDocumentMetadataSection } from '@/features/dms/documents/sections/dms-document-metadata-section';
import { DmsBatchReviewQueueClient } from '@/features/dms/upload/dms-batch-review-queue-client';
import { DmsUploadCleanupPanel } from '@/features/dms/upload/dms-upload-cleanup-panel';
import { DmsStandardFileNameBulkRenamePanel } from '@/features/dms/admin/dms-standard-file-name-bulk-rename-panel';
import type { ReactNode } from 'react';
import type { DmsUploadBatchRow, DmsBatchDraftRow } from '@/server/actions/dms/batch-intake';
const mocks=vi.hoisted(()=>({defs:vi.fn(),values:vi.fn(),save:vi.fn(),discard:vi.fn(),bulk:vi.fn(),rerun:vi.fn(),next:vi.fn(),orch:vi.fn(),refresh:vi.fn(),open:vi.fn(),preview:vi.fn(),clean:vi.fn(),mark:vi.fn(),rename:vi.fn()}));
vi.mock('@/server/actions/dms/document-metadata-values',()=>({getMetadataDefinitionsForType:mocks.defs,getDmsDocumentMetadataValues:mocks.values,saveDmsDocumentMetadataValues:mocks.save}));
vi.mock('@/server/actions/dms/batch-intake',()=>({discardDraftIntake:mocks.discard,discardDraftIntakeBulk:mocks.bulk,rerunBatchDraftAi:mocks.rerun,getNextPendingDraftInBatch:mocks.next}));
vi.mock('@/server/actions/dms/orchestration',()=>({runDmsBatchOrchestration:mocks.orch}));
vi.mock('@/server/actions/dms/session-cleanup',()=>({getDmsCleanupPreview:mocks.preview,cleanupDmsExpiredUploadSessions:mocks.clean,markExpiredDmsUploadSessions:mocks.mark}));
vi.mock('@/server/actions/dms/standard-file-name',()=>({bulkRenameDocumentsToStandardFileNames:mocks.rename}));
vi.mock('@/hooks/use-workspace',()=>({useWorkspace:()=>({openTab:mocks.open})}));
vi.mock('next/navigation',()=>({useRouter:()=>({refresh:mocks.refresh})}));
function Wrap({children}:{children:ReactNode}){return <FluentProvider theme={webLightTheme}><QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><WorkspaceUiMemoryProvider>{children}</WorkspaceUiMemoryProvider></QueryClientProvider></FluentProvider>;}
const defs=[{id:1,field_label_en:'Reference',field_type:'text',is_required:true},{id:2,field_label_en:'Structured details',field_type:'json',is_required:false}];
beforeEach(()=>{vi.resetAllMocks();mocks.defs.mockResolvedValue({success:true,data:defs});mocks.values.mockResolvedValue({success:true,data:[]});mocks.save.mockResolvedValue({success:true});});
afterEach(()=>{cleanup();vi.restoreAllMocks();});
function metadata(){return render(<Wrap><DmsDocumentMetadataSection documentId={100} documentTypeId={2} isViewing={false}/></Wrap>);}
async function edit(){fireEvent.click(await screen.findByRole('button',{name:'Edit metadata'}));return screen.getByRole('dialog');}
it('metadata failures are not empty metadata and a retry restores the editor',async()=>{mocks.values.mockRejectedValueOnce(new Error('private'));metadata();await screen.findByRole('alert');expect(screen.queryByRole('button',{name:'Edit metadata'})).toBeNull();fireEvent.click(screen.getByRole('button',{name:'Retry'}));await screen.findByRole('button',{name:'Edit metadata'});expect(screen.queryByText('private')).toBeNull();});
it('metadata required fields use the shared summary and cannot save empty values',async()=>{metadata();await edit();fireEvent.click(screen.getByRole('button',{name:'Save',exact:true}));expect(screen.getByRole('alert').textContent).toContain('Reference');expect(mocks.save).not.toHaveBeenCalled();expect(document.activeElement).toBe(screen.getByLabelText('Reference',{selector:'input'}));});
it('invalid JSON is reported and never silently converted to text',async()=>{metadata();await edit();fireEvent.change(screen.getByLabelText('Reference',{selector:'input'}),{target:{value:'Synthetic'}});fireEvent.change(screen.getByLabelText('Structured details',{selector:'textarea'}),{target:{value:'{broken'}});fireEvent.click(screen.getByRole('button',{name:'Save',exact:true}));expect(screen.getByRole('alert').textContent).toContain('valid JSON');expect(mocks.save).not.toHaveBeenCalled();});
it('metadata save response loss keeps the draft and releases Save',async()=>{mocks.save.mockRejectedValue(new Error('private'));metadata();await edit();fireEvent.change(screen.getByLabelText('Reference',{selector:'input'}),{target:{value:'Keep this'}});fireEvent.click(screen.getByRole('button',{name:'Save',exact:true}));await screen.findByText(/The save could not be confirmed/);expect((screen.getByLabelText('Reference',{selector:'input'}) as HTMLInputElement).value).toBe('Keep this');expect(screen.getByRole('button',{name:'Save',exact:true}).hasAttribute('disabled')).toBe(false);});
it('metadata confirmed save closes; valid JSON retains its typed value',async()=>{metadata();await edit();fireEvent.change(screen.getByLabelText('Reference',{selector:'input'}),{target:{value:'Synthetic'}});fireEvent.change(screen.getByLabelText('Structured details',{selector:'textarea'}),{target:{value:'{"safe":true}'}});fireEvent.click(screen.getByRole('button',{name:'Save',exact:true}));await waitFor(()=>expect(screen.queryByRole('dialog')).toBeNull());expect(mocks.save).toHaveBeenCalledWith(100,[{definition_id:1,value_text:'Synthetic'},{definition_id:2,value_json:{safe:true}}]);});
it('read-only metadata has no edit affordance',async()=>{render(<Wrap><DmsDocumentMetadataSection documentId={100} documentTypeId={2} isViewing/></Wrap>);await screen.findByText('Reference');expect(screen.queryByRole('button',{name:'Edit metadata'})).toBeNull();});
it('metadata document identity change does not expose the previous draft',async()=>{const view=metadata();await edit();fireEvent.change(screen.getByLabelText('Reference',{selector:'input'}),{target:{value:'Private draft A'}});view.rerender(<Wrap><DmsDocumentMetadataSection documentId={101} documentTypeId={2} isViewing={false}/></Wrap>);await edit();expect((screen.getByLabelText('Reference',{selector:'input'}) as HTMLInputElement).value).toBe('');});
const batch={id:12,batch_code:'SYNTHETIC',status:'processing',total_files:1,processed_files:1} as DmsUploadBatchRow;
const draft={sessionId:1,sessionCode:'SYN-1',originalFilename:'Synthetic first.pdf',intakeStatus:'failed',documentStatus:null} as DmsBatchDraftRow;
function batchView(){return render(<Wrap><DmsBatchReviewQueueClient batch={batch} initialDrafts={[draft]}/></Wrap>);}
it('batch refreshed props replace the original rows',()=>{const view=batchView();view.rerender(<Wrap><DmsBatchReviewQueueClient batch={batch} initialDrafts={[{...draft,originalFilename:'Synthetic refreshed.pdf'}]}/></Wrap>);expect(screen.queryByText('Synthetic first.pdf')).toBeNull();expect(screen.getAllByText('Synthetic refreshed.pdf').length).toBeGreaterThan(0);});
it('batch search narrows loaded records and required identity columns remain available',()=>{batchView();expect(screen.getByRole('button',{name:'Edit columns'})).toBeTruthy();fireEvent.change(screen.getByLabelText('Search loaded records'),{target:{value:'none'}});expect(screen.getByText('No loaded drafts match your filters.')).toBeTruthy();});
it('batch discard refusal makes no call; response loss is announced and allows retry',async()=>{const confirm=vi.spyOn(window,'confirm').mockReturnValueOnce(false).mockReturnValue(true);mocks.discard.mockRejectedValue(new Error('private'));batchView();fireEvent.click(screen.getByRole('button',{name:'Discard this draft'}));expect(mocks.discard).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Discard this draft'}));await screen.findByRole('alert');expect(confirm).toHaveBeenCalledTimes(2);expect(screen.queryByText('private')).toBeNull();await waitFor(()=>expect(screen.getByRole('button',{name:'Discard this draft'}).hasAttribute('disabled')).toBe(false));});
it('cleanup failure clears a stale preview and disables execution',async()=>{mocks.preview.mockResolvedValueOnce({success:true,data:{candidates:[{id:1,session_code:'SYN-1',original_filename:'Synthetic.pdf',status:'expired',file_size_bytes:20,uploaded_at:'2026-09-30T00:00:00Z'}],scanned:1}}).mockRejectedValueOnce(new Error('private'));render(<Wrap><DmsUploadCleanupPanel isAdmin/></Wrap>);fireEvent.click(screen.getByRole('button',{name:/Temp File Cleanup/}));expect(screen.getByRole('button',{name:'Run Cleanup'}).hasAttribute('disabled')).toBe(true);fireEvent.click(screen.getByRole('button',{name:'Preview Cleanup Candidates'}));await screen.findByText('Synthetic.pdf');fireEvent.click(screen.getByRole('button',{name:'Preview Cleanup Candidates'}));await screen.findByRole('alert');expect(screen.queryByText('Synthetic.pdf')).toBeNull();expect(screen.getByRole('button',{name:'Run Cleanup'}).hasAttribute('disabled')).toBe(true);});
it('cleanup is absent for non-administrators',()=>{render(<Wrap><DmsUploadCleanupPanel/></Wrap>);expect(screen.queryByRole('button',{name:/Cleanup/})).toBeNull();});
it('bulk rename validates size and requires an unchanged preview before confirmed execution',async()=>{mocks.rename.mockResolvedValue({success:true,data:{processed:1,updated:1,skipped:0,qualitySkipped:0,errors:[],samples:[{documentId:1,oldName:'Synthetic.pdf',newName:'Synthetic-new.pdf'}]}});const confirm=vi.spyOn(window,'confirm').mockReturnValue(true);render(<Wrap><DmsStandardFileNameBulkRenamePanel/></Wrap>);expect(screen.getByRole('button',{name:'Apply names'}).hasAttribute('disabled')).toBe(true);fireEvent.change(screen.getByLabelText('Batch size'),{target:{value:'501'}});fireEvent.click(screen.getByRole('button',{name:'Preview names'}));expect(mocks.rename).not.toHaveBeenCalled();fireEvent.change(screen.getByLabelText('Batch size'),{target:{value:'2'}});fireEvent.click(screen.getByRole('button',{name:'Preview names'}));await screen.findByText('Would rename');expect(mocks.rename).toHaveBeenLastCalledWith({limit:2,dryRun:true});fireEvent.click(screen.getByRole('button',{name:'Apply names'}));await waitFor(()=>expect(mocks.rename).toHaveBeenCalledTimes(2));expect(confirm).toHaveBeenCalledOnce();expect(mocks.rename).toHaveBeenLastCalledWith({limit:2,dryRun:false});await screen.findByText('Processed — see run totals');});
