// @vitest-environment jsdom
import './setup';
import { afterEach, beforeEach, expect, it, vi } from 'vitest';
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { FluentProvider, webLightTheme } from '@fluentui/react-components';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { DmsApprovalActionDialog } from '@/features/dms/approvals/dms-approval-action-dialog';
import { DmsApprovalsQueuePageClient } from '@/features/dms/approvals/dms-approvals-queue-page-client';
import { DmsUploadDropzone } from '@/features/dms/upload/dms-upload-dropzone';
const mocks=vi.hoisted(()=>({action:vi.fn(),queue:vi.fn()}));
vi.mock('@/server/actions/dms/document-approvals',()=>({submitDocumentForApproval:mocks.action,approveDocument:mocks.action,rejectDocument:mocks.action,withdrawDocumentApproval:mocks.action,listPendingDocumentApprovalsForCurrentUser:mocks.queue}));
afterEach(cleanup);beforeEach(()=>{vi.clearAllMocks();mocks.queue.mockResolvedValue({success:true,data:{rows:[],total:0}});});
it('reject requires a linked reason before calling the business action',()=>{render(<DmsApprovalActionDialog open onOpenChange={vi.fn()} mode="reject" documentId={1} approvalId={2} onSuccess={vi.fn()}/>);fireEvent.click(screen.getByRole('button',{name:'Reject',exact:true}));expect(mocks.action).not.toHaveBeenCalled();expect(screen.getByRole('alert').textContent).toContain('Reason');});
it('approval response loss preserves comment and never announces success',async()=>{mocks.action.mockRejectedValue(new Error('private'));const success=vi.fn();render(<DmsApprovalActionDialog open onOpenChange={vi.fn()} mode="approve" documentId={1} approvalId={2} onSuccess={success}/>);fireEvent.change(screen.getByLabelText(/Comment/),{target:{value:'Synthetic approval comment'}});fireEvent.click(screen.getByRole('button',{name:'Approve',exact:true}));await screen.findByText(/The result could not be confirmed/);expect((screen.getByLabelText(/Comment/) as HTMLTextAreaElement).value).toBe('Synthetic approval comment');expect(success).not.toHaveBeenCalled();});
function queue(){return render(<FluentProvider theme={webLightTheme}><QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><DmsApprovalsQueuePageClient canAct={false} isAdmin={false}/></QueryClientProvider></FluentProvider>);}
it('approval filters reach the server with page reset, not a partial client page',async()=>{queue();await screen.findByText('No pending approvals for you right now.');fireEvent.click(screen.getByRole('button',{name:/^Edit filters/}));fireEvent.change(screen.getByLabelText('Approval status'),{target:{value:'rejected'}});fireEvent.change(screen.getByLabelText('Search',{exact:true}),{target:{value:'Synthetic'}});fireEvent.click(screen.getByRole('button',{name:'Apply'}));await waitFor(()=>expect(mocks.queue).toHaveBeenLastCalledWith(expect.objectContaining({status:'rejected',search:'Synthetic',page:1,pageSize:20})));});
it('approval transport failure renders retry instead of a blank queue',async()=>{mocks.queue.mockRejectedValueOnce(new Error('private'));queue();await screen.findByRole('alert');expect(screen.queryByText('No pending approvals for you right now.')).toBeNull();fireEvent.click(screen.getByRole('button',{name:'Retry'}));await screen.findByText('No pending approvals for you right now.');});
it('unsupported file selection produces an announced validation message and no upload callback',async()=>{const callback=vi.fn();render(<DmsUploadDropzone onFileSelected={callback}/>);fireEvent.change(screen.getByLabelText('Choose document file'),{target:{files:[new File(['synthetic'],'test.exe',{type:'application/octet-stream'})]}});await screen.findByRole('alert');expect(callback).not.toHaveBeenCalled();expect(screen.getByRole('button',{name:'Browse files'}).getAttribute('type')).toBe('button');});
