// @vitest-environment jsdom
import './setup';
import {afterEach,beforeEach,expect,it,vi} from 'vitest';
import {cleanup,fireEvent,render,screen,waitFor,within} from '@testing-library/react';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {FluentProvider,webLightTheme} from '@fluentui/react-components';
import {WorkspaceUiMemoryProvider} from '@/hooks/use-persistent-ui-state';
import {QueryReadBoundary,readHasFailed} from '@/components/erp/query-read-boundary';
import {RecordCollection} from '@/components/erp/table/record-collection';
import {useGuardedTransition} from '@/hooks/use-guarded-transition';
import {useReasonDialog} from '@/hooks/use-reason-dialog';
import {HrSettingsLookupPage} from '@/features/hr/settings/hr-settings-lookup-page';
import {CandidateInterviewsTab} from '@/features/hr/recruitment/tabs/candidate-interviews-tab';
import type {ReactNode} from 'react';
const m=vi.hoisted(()=>({list:vi.fn(),create:vi.fn(),update:vi.fn(),archive:vi.fn(),toast:vi.fn()}));
vi.mock('next/navigation',()=>({usePathname:()=>'/synthetic'}));
vi.mock('@/components/erp/export/erp-export-menu',()=>({ERPExportMenu:()=>null}));
vi.mock('sonner',()=>({toast:{success:vi.fn(),error:m.toast}}));
vi.mock('@/server/actions/hr/recruitment',()=>({listCandidateInterviews:m.list,createInterview:m.create,updateInterview:m.update,archiveInterview:m.archive}));
function Wrap({children}:{children:ReactNode}){return <FluentProvider theme={webLightTheme}><QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><WorkspaceUiMemoryProvider>{children}</WorkspaceUiMemoryProvider></QueryClientProvider></FluentProvider>;}
beforeEach(()=>{vi.resetAllMocks();m.list.mockResolvedValue({success:true,data:[]});});afterEach(cleanup);
it.each([{isError:true},{isError:false,data:{success:false,error:'private'}}])('failed read states cannot become successful empties',q=>expect(readHasFailed({...q,refetch:vi.fn()})).toBe(true));
it.each([undefined,[],{success:true,data:[]}])('valid empty states remain empty, not errors',data=>expect(readHasFailed({isError:false,data,refetch:vi.fn()})).toBe(false));
it('failed reads retain draft DOM, pause actions, and offer retry without leaking provider errors',async()=>{
 const refetch=vi.fn().mockResolvedValue({}),ok={isError:false,refetch};const v=render(<QueryReadBoundary queries={[ok]}><input aria-label="Draft" defaultValue=""/></QueryReadBoundary>);fireEvent.change(screen.getByLabelText('Draft'),{target:{value:'keep'}});
 v.rerender(<QueryReadBoundary queries={[{...ok,isError:true,data:{error:'PRIVATE'}}]}><input aria-label="Draft" defaultValue=""/></QueryReadBoundary>);expect((screen.getByLabelText('Draft') as HTMLInputElement).value).toBe('keep');expect(screen.getByLabelText('Draft').parentElement?.hasAttribute('inert')).toBe(true);expect(screen.queryByText('PRIVATE')).toBeNull();fireEvent.click(screen.getByRole('button',{name:'Retry loading'}));await waitFor(()=>expect(refetch).toHaveBeenCalledOnce());
});
it('collection exposes only explicit scalars to filters, not confidential or object fields',()=>{
 render(<Wrap><RecordCollection id="safe" rows={[{id:1,name:'Synthetic',secret:'NEVER-INDEX-ME',hidden:{value:'private'}}]} fields={[{id:'name',label:'Name',path:'name'}]} renderRecord={()=>'Permitted detail'}/></Wrap>);expect(screen.getByRole('button',{name:'Edit columns'})).toBeTruthy();expect(screen.queryByText('NEVER-INDEX-ME')).toBeNull();fireEvent.change(screen.getByRole('textbox',{name:'Search loaded records…'}),{target:{value:'NEVER-INDEX-ME'}});expect(screen.queryByText('Synthetic')).toBeNull();
});
it('collection filter and clear do not mutate its supplied rows',async()=>{
 const rows=[{id:1,name:'Alpha'},{id:2,name:'Beta'}];render(<Wrap><RecordCollection id="safe2" rows={rows} fields={[{id:'name',label:'Name',path:'name'}]} renderRecord={r=>r.id}/></Wrap>);fireEvent.click(screen.getByRole('button',{name:'Edit filters'}));fireEvent.change(screen.getByRole('textbox',{name:'Name'}),{target:{value:'Alpha'}});fireEvent.click(screen.getByRole('button',{name:'Apply',exact:true}));await waitFor(()=>expect(screen.queryByText('Beta')).toBeNull());expect(rows).toHaveLength(2);fireEvent.click(screen.getByRole('button',{name:'Clear search and filters'}));expect(screen.getByText('Beta')).toBeTruthy();
});
function Action({run}:{run:()=>Promise<void>}){const [pending,start]=useGuardedTransition();return <button disabled={pending} onClick={()=>start(run)}>Run</button>;}
it('action admission prevents two synchronous submissions',async()=>{let done!:()=>void;const run=vi.fn(()=>new Promise<void>(r=>{done=r;}));render(<Action run={run}/>);fireEvent.click(screen.getByText('Run'));fireEvent.click(screen.getByText('Run'));expect(run).toHaveBeenCalledOnce();done();await waitFor(()=>expect(screen.getByText('Run').hasAttribute('disabled')).toBe(false));});
it('an uncertain mutation is not automatically retried',async()=>{const run=vi.fn().mockRejectedValue(Error('private'));render(<Action run={run}/>);fireEvent.click(screen.getByText('Run'));await waitFor(()=>expect(m.toast).toHaveBeenCalled());fireEvent.click(screen.getByText('Run'));expect(run).toHaveBeenCalledOnce();expect(m.toast.mock.calls.flat().join(' ')).not.toContain('private');});
function Reason({done}:{done:(value:string|null)=>void}){const {askReason,reasonDialog}=useReasonDialog();return <><button onClick={()=>void askReason('Reject request').then(done)}>Reject</button>{reasonDialog}</>;}
it('required reason uses global validation and cancel does not approve an action',async()=>{const done=vi.fn();render(<Wrap><Reason done={done}/></Wrap>);fireEvent.click(screen.getByRole('button',{name:'Reject',exact:true}));fireEvent.click(screen.getByRole('button',{name:'Continue',exact:true}));expect(done).not.toHaveBeenCalled();expect(await screen.findByRole('alert')).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'Cancel',exact:true}));await waitFor(()=>expect(done).toHaveBeenCalledWith(null));});
it('trimmed explicit reason is returned once',async()=>{const done=vi.fn();render(<Wrap><Reason done={done}/></Wrap>);fireEvent.click(screen.getByRole('button',{name:'Reject',exact:true}));fireEvent.change(screen.getByLabelText('Reason'),{target:{value:'  reviewed  '}});fireEvent.click(screen.getByRole('button',{name:'Continue',exact:true}));await waitFor(()=>expect(done).toHaveBeenCalledWith('reviewed'));expect(done).toHaveBeenCalledOnce();});
it('HR lookup required labels stop an invalid create and expose linked summary',async()=>{
 const create=vi.fn();render(<Wrap><HrSettingsLookupPage title="Grades" description="Synthetic" initialData={[]} canManage onList={vi.fn()} onCreate={create} onUpdate={vi.fn()}/></Wrap>);fireEvent.click(screen.getByRole('button',{name:'Add',exact:true}));fireEvent.click(screen.getByRole('button',{name:'Add',exact:true}));expect(create).not.toHaveBeenCalled();expect(await screen.findByRole('alert')).toBeTruthy();expect(screen.getByLabelText('Code').hasAttribute('required')).toBe(true);
});
it('read-only HR settings omit Add and retain list controls',()=>{render(<Wrap><HrSettingsLookupPage title="Grades" description="Synthetic" initialData={[{id:1,code:'SYN',name_en:'Synthetic',is_active:true,sort_order:0} as never]} canManage={false} onList={vi.fn()} onCreate={vi.fn()} onUpdate={vi.fn()}/></Wrap>);expect(screen.queryByRole('button',{name:'Add',exact:true})).toBeNull();expect(screen.getByRole('button',{name:'Edit columns'})).toBeTruthy();expect(screen.queryByRole('button',{name:'Edit record'})).toBeNull();});
it('rejected HR settings saves retain entries with durable safe feedback',async()=>{const create=vi.fn().mockResolvedValue({success:false,error:'PRIVATE SQL'});render(<Wrap><HrSettingsLookupPage title="Grades" description="Synthetic" initialData={[]} canManage onList={vi.fn()} onCreate={create} onUpdate={vi.fn()}/></Wrap>);fireEvent.click(screen.getByRole('button',{name:'Add',exact:true}));fireEvent.change(screen.getByLabelText('Code'),{target:{value:'SYN'}});fireEvent.change(screen.getByLabelText('Name (English)'),{target:{value:'Synthetic'}});fireEvent.click(screen.getByRole('button',{name:'Add',exact:true}));expect(await screen.findByText(/The record was not saved/)).toBeTruthy();expect(screen.getByLabelText('Code').getAttribute('value')).toBe('SYN');expect(screen.queryByText('PRIVATE SQL')).toBeNull();expect(screen.getByRole('dialog')).toBeTruthy();});
it('candidate interview read rejection is explicit and has retry',async()=>{m.list.mockRejectedValueOnce(Error('PRIVATE'));render(<Wrap><CandidateInterviewsTab candidateId={51} canManage/></Wrap>);await screen.findByRole('alert');expect(screen.queryByText('PRIVATE')).toBeNull();fireEvent.click(screen.getByRole('button',{name:'Retry loading'}));await waitFor(()=>expect(m.list).toHaveBeenCalledTimes(2));});
it('candidate interview score constraint prevents the server call',async()=>{render(<Wrap><CandidateInterviewsTab candidateId={51} canManage/></Wrap>);await screen.findByText('No interviews scheduled yet.');fireEvent.click(screen.getByRole('button',{name:'Schedule Interview'}));fireEvent.change(screen.getByLabelText('Score (0–100)'),{target:{value:'101'}});const d=screen.getByRole('dialog');fireEvent.click(within(d).getByRole('button',{name:'Add',exact:true}));expect(m.create).not.toHaveBeenCalled();expect(await within(d).findByRole('alert')).toBeTruthy();});
it('read-only candidate interviews omit mutation controls',async()=>{m.list.mockResolvedValue({success:true,data:[{id:1,interview_round:'first',interview_status:'scheduled',interview_datetime:null}]});render(<Wrap><CandidateInterviewsTab candidateId={51} canManage={false}/></Wrap>);await screen.findByRole('button',{name:'Edit columns'});for(const name of ['Schedule Interview','Edit record','Archive record'])expect(screen.queryByRole('button',{name})).toBeNull();});
