-- ============================================================================
-- ERP BASE 002F.5A — UNIFIED PARTY MASTER DRAFT MIGRATION
-- ============================================================================
-- STATUS: REVIEW ONLY — DO NOT APPLY TO LIVE DATABASE
-- PHASE: ERP BASE 002F.5A (Planning)
-- PROJECT: ALGT ERP
-- GENERATED: 2026-06-13
-- LOCATION: implementation_Review/Phase_002F_5A_Party_Master_Planning/
--            (NOT in supabase/migrations/ until Sameer approves)
--
-- PURPOSE:
--   Draft DDL for unified Party Master replacing siloed customer/vendor/etc.
--   tables. Coexists with legacy tables until phase 002F.5A.5 retirement.
--
-- ASSUMPTIONS:
--   - Existing tables: countries, emirates, cities, areas_zones, currencies,
--     payment_terms, tax_types, banks, user_profiles, permissions, roles,
--     global_numbering_rules, current_user_has_permission(), current_user_has_role()
--   - BIGINT identity PKs throughout (no UUID)
--   - Test data in legacy party tables is NOT migrated
--   - ICV/CICPA modeled as party_licenses + party_documents (not parties columns)
--
-- ROLLBACK (if applied to empty staging only — run in reverse dependency order):
--   DROP FUNCTION IF EXISTS find_possible_duplicate_parties CASCADE;
--   DROP TABLE IF EXISTS party_government_authority_profiles CASCADE;
--   DROP TABLE IF EXISTS party_recruitment_agency_profiles CASCADE;
--   DROP TABLE IF EXISTS party_consultant_profiles CASCADE;
--   DROP TABLE IF EXISTS party_subcontractor_profiles CASCADE;
--   DROP TABLE IF EXISTS party_vendor_profiles CASCADE;
--   DROP TABLE IF EXISTS party_customer_profiles CASCADE;
--   DROP TABLE IF EXISTS party_notes CASCADE;
--   DROP TABLE IF EXISTS party_relationships CASCADE;
--   DROP TABLE IF EXISTS party_relationship_types CASCADE;
--   DROP TABLE IF EXISTS party_service_category_assignments CASCADE;
--   DROP TABLE IF EXISTS party_service_categories_master CASCADE;
--   DROP TABLE IF EXISTS party_compliance_profiles CASCADE;
--   DROP TABLE IF EXISTS party_documents CASCADE;
--   DROP TABLE IF EXISTS party_bank_details CASCADE;
--   DROP TABLE IF EXISTS party_addresses CASCADE;
--   DROP TABLE IF EXISTS party_contacts CASCADE;
--   DROP TABLE IF EXISTS party_finance_profiles CASCADE;
--   DROP TABLE IF EXISTS party_tax_registrations CASCADE;
--   DROP TABLE IF EXISTS party_licenses CASCADE;
--   DROP TABLE IF EXISTS party_type_assignments CASCADE;
--   DROP TABLE IF EXISTS parties CASCADE;
--   DROP TABLE IF EXISTS party_types CASCADE;
--   -- + all party_* lookup masters (see section 1)
--   DELETE FROM global_numbering_rules WHERE rule_code LIKE 'MASTER_PARTY%';
--   DELETE FROM permissions WHERE permission_code LIKE 'master_data.parties.%';
-- ============================================================================

-- Optional: similarity search for duplicate names
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- ============================================================================
-- SECTION 1: PARTY LOOKUP MASTER TABLES
-- ============================================================================

CREATE TABLE IF NOT EXISTS party_natures (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nature_code text NOT NULL UNIQUE,
  nature_name_en text NOT NULL,
  nature_name_ar text,
  description text,
  is_system boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

CREATE TABLE IF NOT EXISTS party_statuses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status_code text NOT NULL UNIQUE,
  status_name_en text NOT NULL,
  status_name_ar text,
  description text,
  is_system boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

CREATE TABLE IF NOT EXISTS party_license_types (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  license_type_code text NOT NULL UNIQUE,
  license_type_name_en text NOT NULL,
  license_type_name_ar text,
  renewal_required_default boolean NOT NULL DEFAULT true,
  renewal_notice_days_default integer,
  description text,
  is_system boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

CREATE TABLE IF NOT EXISTS party_license_statuses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status_code text NOT NULL UNIQUE,
  status_name_en text NOT NULL,
  status_name_ar text,
  description text,
  is_system boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

CREATE TABLE IF NOT EXISTS party_tax_statuses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status_code text NOT NULL UNIQUE,
  status_name_en text NOT NULL,
  status_name_ar text,
  description text,
  is_system boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

CREATE TABLE IF NOT EXISTS party_contact_roles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_code text NOT NULL UNIQUE,
  role_name_en text NOT NULL,
  role_name_ar text,
  description text,
  is_system boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

CREATE TABLE IF NOT EXISTS party_contact_departments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  department_code text NOT NULL UNIQUE,
  department_name_en text NOT NULL,
  department_name_ar text,
  description text,
  is_system boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

CREATE TABLE IF NOT EXISTS party_address_types (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  address_type_code text NOT NULL UNIQUE,
  address_type_name_en text NOT NULL,
  address_type_name_ar text,
  description text,
  is_system boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

CREATE TABLE IF NOT EXISTS party_document_types (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_type_code text NOT NULL UNIQUE,
  document_type_name_en text NOT NULL,
  document_type_name_ar text,
  expiry_required_default boolean NOT NULL DEFAULT false,
  description text,
  is_system boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

CREATE TABLE IF NOT EXISTS party_document_statuses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status_code text NOT NULL UNIQUE,
  status_name_en text NOT NULL,
  status_name_ar text,
  description text,
  is_system boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

CREATE TABLE IF NOT EXISTS party_compliance_statuses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status_code text NOT NULL UNIQUE,
  status_name_en text NOT NULL,
  status_name_ar text,
  description text,
  is_system boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

CREATE TABLE IF NOT EXISTS party_approval_statuses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status_code text NOT NULL UNIQUE,
  status_name_en text NOT NULL,
  status_name_ar text,
  description text,
  is_system boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

CREATE TABLE IF NOT EXISTS party_blacklist_statuses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status_code text NOT NULL UNIQUE,
  status_name_en text NOT NULL,
  status_name_ar text,
  description text,
  is_system boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

CREATE TABLE IF NOT EXISTS party_risk_ratings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rating_code text NOT NULL UNIQUE,
  rating_name_en text NOT NULL,
  rating_name_ar text,
  description text,
  is_system boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

CREATE TABLE IF NOT EXISTS party_credit_ratings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rating_code text NOT NULL UNIQUE,
  rating_name_en text NOT NULL,
  rating_name_ar text,
  description text,
  is_system boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

CREATE TABLE IF NOT EXISTS party_note_types (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  note_type_code text NOT NULL UNIQUE,
  note_type_name_en text NOT NULL,
  note_type_name_ar text,
  description text,
  is_system boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

CREATE TABLE IF NOT EXISTS payment_methods (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  method_code text NOT NULL UNIQUE,
  method_name_en text NOT NULL,
  method_name_ar text,
  description text,
  is_system boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

-- ============================================================================
-- SECTION 2: PARTY TYPES & CORE PARTIES
-- ============================================================================

CREATE TABLE IF NOT EXISTS party_types (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type_code text NOT NULL UNIQUE,
  type_name text NOT NULL,
  type_name_ar text,
  description text,
  icon_name text,
  color_token text,
  is_system boolean NOT NULL DEFAULT true,
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

CREATE TABLE IF NOT EXISTS parties (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  party_code text NOT NULL UNIQUE,
  display_name text NOT NULL,
  legal_name_en text NOT NULL,
  legal_name_ar text,
  trade_name_en text,
  trade_name_ar text,
  short_name text,
  party_nature_id bigint NOT NULL REFERENCES party_natures(id),
  primary_party_type_id bigint REFERENCES party_types(id),
  parent_party_id bigint REFERENCES parties(id),
  main_phone text,
  main_mobile text,
  whatsapp text,
  main_email text CHECK (main_email IS NULL OR main_email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'),
  alternate_email text CHECK (alternate_email IS NULL OR alternate_email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'),
  website text,
  country_id bigint NOT NULL REFERENCES countries(id),
  emirate_id bigint REFERENCES emirates(id),
  city_id bigint REFERENCES cities(id),
  area_zone_id bigint REFERENCES areas_zones(id),
  po_box text,
  full_address_text text,
  google_map_url text,
  latitude numeric(10, 7),
  longitude numeric(10, 7),
  party_status_id bigint NOT NULL REFERENCES party_statuses(id),
  is_active boolean NOT NULL DEFAULT true,
  remarks text,
  is_locked boolean NOT NULL DEFAULT false,
  is_system boolean NOT NULL DEFAULT false,
  deactivated_at timestamptz,
  deactivated_by bigint REFERENCES user_profiles(id),
  deactivation_reason text,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

CREATE TABLE IF NOT EXISTS party_type_assignments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  party_id bigint NOT NULL REFERENCES parties(id) ON DELETE CASCADE,
  party_type_id bigint NOT NULL REFERENCES party_types(id),
  is_primary boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  assigned_date date NOT NULL DEFAULT CURRENT_DATE,
  assigned_by bigint REFERENCES user_profiles(id),
  remarks text,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

-- ============================================================================
-- SECTION 3: CHILD / TRANSACTIONAL TABLES
-- ============================================================================

CREATE TABLE IF NOT EXISTS party_documents (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_code text NOT NULL UNIQUE,
  party_id bigint NOT NULL REFERENCES parties(id) ON DELETE CASCADE,
  document_type_id bigint NOT NULL REFERENCES party_document_types(id),
  document_title text NOT NULL,
  document_number text,
  issue_date date,
  expiry_date date,
  issuing_authority_party_id bigint REFERENCES parties(id),
  file_path text,
  file_name text,
  file_mime_type text,
  file_size bigint,
  expiry_required boolean NOT NULL DEFAULT false,
  renewal_notice_days integer,
  document_status_id bigint NOT NULL REFERENCES party_document_statuses(id),
  uploaded_by bigint REFERENCES user_profiles(id),
  uploaded_at timestamptz,
  remarks text,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

CREATE TABLE IF NOT EXISTS party_licenses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  license_code text NOT NULL UNIQUE,
  party_id bigint NOT NULL REFERENCES parties(id) ON DELETE CASCADE,
  license_type_id bigint NOT NULL REFERENCES party_license_types(id),
  license_number text NOT NULL,
  license_name text,
  issuing_authority_party_id bigint REFERENCES parties(id),
  issuing_country_id bigint REFERENCES countries(id),
  issuing_emirate_id bigint REFERENCES emirates(id),
  issue_date date,
  expiry_date date,
  renewal_required boolean NOT NULL DEFAULT true,
  renewal_notice_days integer,
  license_status_id bigint NOT NULL REFERENCES party_license_statuses(id),
  license_activity_text text,
  license_document_id bigint REFERENCES party_documents(id),
  is_primary boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  remarks text,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

CREATE TABLE IF NOT EXISTS party_tax_registrations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tax_registration_code text NOT NULL UNIQUE,
  party_id bigint NOT NULL REFERENCES parties(id) ON DELETE CASCADE,
  tax_type_id bigint NOT NULL REFERENCES tax_types(id),
  tax_registration_number text CHECK (tax_registration_number IS NULL OR char_length(tax_registration_number) = 15),
  tax_country_id bigint NOT NULL REFERENCES countries(id),
  tax_status_id bigint NOT NULL REFERENCES party_tax_statuses(id),
  effective_from date,
  effective_to date,
  certificate_document_id bigint REFERENCES party_documents(id),
  reverse_charge_applicable boolean NOT NULL DEFAULT false,
  vat_exempt boolean NOT NULL DEFAULT false,
  is_primary boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  remarks text,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

CREATE TABLE IF NOT EXISTS party_finance_profiles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  party_id bigint NOT NULL UNIQUE REFERENCES parties(id) ON DELETE CASCADE,
  default_currency_id bigint REFERENCES currencies(id),
  default_payment_term_id bigint REFERENCES payment_terms(id),
  preferred_payment_method_id bigint REFERENCES payment_methods(id),
  credit_limit numeric(15, 2) CHECK (credit_limit IS NULL OR credit_limit >= 0),
  credit_currency_id bigint REFERENCES currencies(id),
  payment_hold boolean NOT NULL DEFAULT false,
  payment_hold_reason text,
  credit_hold boolean NOT NULL DEFAULT false,
  credit_hold_reason text,
  finance_remarks text,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

CREATE TABLE IF NOT EXISTS party_contacts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contact_code text NOT NULL UNIQUE,
  party_id bigint NOT NULL REFERENCES parties(id) ON DELETE CASCADE,
  full_name text NOT NULL,
  designation text,
  department_id bigint REFERENCES party_contact_departments(id),
  contact_role_id bigint REFERENCES party_contact_roles(id),
  email text CHECK (email IS NULL OR email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'),
  phone text,
  mobile text,
  whatsapp text,
  is_primary boolean NOT NULL DEFAULT false,
  is_accounts_contact boolean NOT NULL DEFAULT false,
  is_sales_contact boolean NOT NULL DEFAULT false,
  is_operations_contact boolean NOT NULL DEFAULT false,
  is_hse_contact boolean NOT NULL DEFAULT false,
  is_documents_contact boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

CREATE TABLE IF NOT EXISTS party_addresses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  address_code text NOT NULL UNIQUE,
  party_id bigint NOT NULL REFERENCES parties(id) ON DELETE CASCADE,
  address_type_id bigint NOT NULL REFERENCES party_address_types(id),
  address_name text,
  country_id bigint NOT NULL REFERENCES countries(id),
  emirate_id bigint REFERENCES emirates(id),
  city_id bigint REFERENCES cities(id),
  area_zone_id bigint REFERENCES areas_zones(id),
  street text,
  building text,
  floor text,
  office_no text,
  po_box text,
  landmark text,
  google_map_url text,
  latitude numeric(10, 7),
  longitude numeric(10, 7),
  is_primary boolean NOT NULL DEFAULT false,
  is_billing_address boolean NOT NULL DEFAULT false,
  is_shipping_address boolean NOT NULL DEFAULT false,
  is_site_address boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

CREATE TABLE IF NOT EXISTS party_bank_details (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bank_detail_code text NOT NULL UNIQUE,
  party_id bigint NOT NULL REFERENCES parties(id) ON DELETE CASCADE,
  bank_id bigint REFERENCES banks(id),
  bank_name_text text,
  account_holder_name text NOT NULL,
  account_number text,
  iban text,
  swift_code text,
  currency_id bigint REFERENCES currencies(id),
  branch_name text,
  country_id bigint REFERENCES countries(id),
  is_primary boolean NOT NULL DEFAULT false,
  is_verified boolean NOT NULL DEFAULT false,
  verified_by bigint REFERENCES user_profiles(id),
  verified_at timestamptz,
  verification_document_id bigint REFERENCES party_documents(id),
  is_active boolean NOT NULL DEFAULT true,
  remarks text,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

CREATE TABLE IF NOT EXISTS party_compliance_profiles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  party_id bigint NOT NULL UNIQUE REFERENCES parties(id) ON DELETE CASCADE,
  kyc_status_id bigint REFERENCES party_compliance_statuses(id),
  customer_approval_status_id bigint REFERENCES party_approval_statuses(id),
  vendor_approval_status_id bigint REFERENCES party_approval_statuses(id),
  subcontractor_approval_status_id bigint REFERENCES party_approval_statuses(id),
  hse_approval_status_id bigint REFERENCES party_approval_statuses(id),
  finance_approval_status_id bigint REFERENCES party_approval_statuses(id),
  legal_approval_status_id bigint REFERENCES party_approval_statuses(id),
  blacklist_status_id bigint REFERENCES party_blacklist_statuses(id),
  blacklist_reason text,
  risk_rating_id bigint REFERENCES party_risk_ratings(id),
  credit_rating_id bigint REFERENCES party_credit_ratings(id),
  payment_hold boolean NOT NULL DEFAULT false,
  payment_hold_reason text,
  work_hold boolean NOT NULL DEFAULT false,
  work_hold_reason text,
  approved_by bigint REFERENCES user_profiles(id),
  approved_at timestamptz,
  last_review_date date,
  next_review_date date,
  remarks text,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

CREATE TABLE IF NOT EXISTS party_service_categories_master (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_category_code text NOT NULL UNIQUE,
  service_category_name text NOT NULL,
  service_category_name_ar text,
  parent_category_id bigint REFERENCES party_service_categories_master(id),
  description text,
  is_system boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

CREATE TABLE IF NOT EXISTS party_service_category_assignments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  party_id bigint NOT NULL REFERENCES parties(id) ON DELETE CASCADE,
  service_category_id bigint NOT NULL REFERENCES party_service_categories_master(id),
  is_primary boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  remarks text,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

CREATE TABLE IF NOT EXISTS party_relationship_types (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  relationship_type_code text NOT NULL UNIQUE,
  relationship_type_name text NOT NULL,
  relationship_type_name_ar text,
  description text,
  is_system boolean NOT NULL DEFAULT true,
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

CREATE TABLE IF NOT EXISTS party_relationships (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_party_id bigint NOT NULL REFERENCES parties(id) ON DELETE CASCADE,
  child_party_id bigint NOT NULL REFERENCES parties(id) ON DELETE CASCADE,
  relationship_type_id bigint NOT NULL REFERENCES party_relationship_types(id),
  effective_from date,
  effective_to date,
  is_active boolean NOT NULL DEFAULT true,
  remarks text,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id),
  CONSTRAINT party_relationships_no_self CHECK (parent_party_id <> child_party_id)
);

CREATE TABLE IF NOT EXISTS party_notes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  party_id bigint NOT NULL REFERENCES parties(id) ON DELETE CASCADE,
  note_type_id bigint REFERENCES party_note_types(id),
  note_title text,
  note_body text NOT NULL,
  is_important boolean NOT NULL DEFAULT false,
  is_private boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

-- ============================================================================
-- SECTION 4: ROLE PROFILE TABLES (1:1 optional)
-- ============================================================================

CREATE TABLE IF NOT EXISTS party_customer_profiles (
  party_id bigint PRIMARY KEY REFERENCES parties(id) ON DELETE CASCADE,
  customer_category_code text,
  customer_type_code text,
  industry_sector_code text,
  sales_region_code text,
  payment_term_id bigint REFERENCES payment_terms(id),
  credit_limit numeric(15, 2) CHECK (credit_limit IS NULL OR credit_limit >= 0),
  credit_currency_id bigint REFERENCES currencies(id),
  sales_owner_user_id bigint REFERENCES user_profiles(id),
  requires_lpo boolean NOT NULL DEFAULT false,
  requires_contract boolean NOT NULL DEFAULT false,
  preferred_invoice_method_code text,
  customer_status_code text,
  remarks text,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

CREATE TABLE IF NOT EXISTS party_vendor_profiles (
  party_id bigint PRIMARY KEY REFERENCES parties(id) ON DELETE CASCADE,
  vendor_category_code text,
  vendor_type_code text,
  procurement_category_code text,
  payment_term_id bigint REFERENCES payment_terms(id),
  default_currency_id bigint REFERENCES currencies(id),
  preferred_vendor boolean NOT NULL DEFAULT false,
  vendor_rating_code text,
  vendor_approval_status_id bigint REFERENCES party_approval_statuses(id),
  can_create_po boolean NOT NULL DEFAULT true,
  requires_comparison boolean NOT NULL DEFAULT false,
  remarks text,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

CREATE TABLE IF NOT EXISTS party_subcontractor_profiles (
  party_id bigint PRIMARY KEY REFERENCES parties(id) ON DELETE CASCADE,
  subcontractor_category_code text,
  work_category_code text,
  hse_required boolean NOT NULL DEFAULT true,
  insurance_required boolean NOT NULL DEFAULT true,
  prequalification_required boolean NOT NULL DEFAULT false,
  max_contract_value numeric(15, 2),
  contract_currency_id bigint REFERENCES currencies(id),
  approved_for_site_work boolean NOT NULL DEFAULT false,
  approved_by_hse boolean NOT NULL DEFAULT false,
  remarks text,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

CREATE TABLE IF NOT EXISTS party_consultant_profiles (
  party_id bigint PRIMARY KEY REFERENCES parties(id) ON DELETE CASCADE,
  consultant_type_code text,
  specialization_code text,
  professional_license_required boolean NOT NULL DEFAULT false,
  approved_for_design boolean NOT NULL DEFAULT false,
  approved_for_supervision boolean NOT NULL DEFAULT false,
  remarks text,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

CREATE TABLE IF NOT EXISTS party_recruitment_agency_profiles (
  party_id bigint PRIMARY KEY REFERENCES parties(id) ON DELETE CASCADE,
  source_country_id bigint REFERENCES countries(id),
  recruitment_category_code text,
  agreement_required boolean NOT NULL DEFAULT true,
  agreement_expiry_date date,
  service_fee_terms text,
  approved_for_hiring boolean NOT NULL DEFAULT false,
  remarks text,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

CREATE TABLE IF NOT EXISTS party_government_authority_profiles (
  party_id bigint PRIMARY KEY REFERENCES parties(id) ON DELETE CASCADE,
  authority_type_code text,
  jurisdiction_country_id bigint REFERENCES countries(id),
  jurisdiction_emirate_id bigint REFERENCES emirates(id),
  service_category_id bigint REFERENCES party_service_categories_master(id),
  portal_url text,
  portal_username_reference text,
  remarks text,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES user_profiles(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by bigint REFERENCES user_profiles(id)
);

-- ============================================================================
-- SECTION 5: INDEXES
-- ============================================================================

CREATE INDEX IF NOT EXISTS idx_parties_party_code ON parties(party_code);
CREATE INDEX IF NOT EXISTS idx_parties_display_name ON parties(display_name);
CREATE INDEX IF NOT EXISTS idx_parties_legal_name_en ON parties USING gin (legal_name_en gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_parties_trade_name_en ON parties(trade_name_en);
CREATE INDEX IF NOT EXISTS idx_parties_country_id ON parties(country_id);
CREATE INDEX IF NOT EXISTS idx_parties_emirate_id ON parties(emirate_id);
CREATE INDEX IF NOT EXISTS idx_parties_city_id ON parties(city_id);
CREATE INDEX IF NOT EXISTS idx_parties_party_status_id ON parties(party_status_id);
CREATE INDEX IF NOT EXISTS idx_parties_is_active ON parties(is_active);

CREATE UNIQUE INDEX IF NOT EXISTS uq_party_type_assignments_primary
  ON party_type_assignments(party_id) WHERE is_primary AND is_active;
CREATE UNIQUE INDEX IF NOT EXISTS uq_party_type_assignments_active_pair
  ON party_type_assignments(party_id, party_type_id) WHERE is_active;

CREATE INDEX IF NOT EXISTS idx_party_licenses_party_id ON party_licenses(party_id);
CREATE INDEX IF NOT EXISTS idx_party_licenses_expiry ON party_licenses(expiry_date);
CREATE UNIQUE INDEX IF NOT EXISTS uq_party_licenses_number_active
  ON party_licenses(license_number) WHERE is_active;
CREATE UNIQUE INDEX IF NOT EXISTS uq_party_licenses_primary
  ON party_licenses(party_id) WHERE is_primary AND is_active;

CREATE UNIQUE INDEX IF NOT EXISTS uq_party_tax_trn_active
  ON party_tax_registrations(tax_registration_number)
  WHERE is_active AND tax_registration_number IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_party_contacts_primary
  ON party_contacts(party_id) WHERE is_primary AND is_active;
CREATE UNIQUE INDEX IF NOT EXISTS uq_party_addresses_primary
  ON party_addresses(party_id) WHERE is_primary AND is_active;
CREATE UNIQUE INDEX IF NOT EXISTS uq_party_bank_primary
  ON party_bank_details(party_id) WHERE is_primary AND is_active;

CREATE INDEX IF NOT EXISTS idx_party_bank_iban ON party_bank_details(iban);
CREATE INDEX IF NOT EXISTS idx_party_contacts_email ON party_contacts(email);
CREATE INDEX IF NOT EXISTS idx_party_service_assign_party ON party_service_category_assignments(party_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_party_service_assign_active
  ON party_service_category_assignments(party_id, service_category_id) WHERE is_active;

-- ============================================================================
-- SECTION 6: ROW LEVEL SECURITY (DRAFT)
-- ============================================================================

ALTER TABLE parties ENABLE ROW LEVEL SECURITY;
ALTER TABLE party_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE party_type_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE party_licenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE party_tax_registrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE party_finance_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE party_contacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE party_addresses ENABLE ROW LEVEL SECURITY;
ALTER TABLE party_bank_details ENABLE ROW LEVEL SECURITY;
ALTER TABLE party_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE party_compliance_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE party_service_categories_master ENABLE ROW LEVEL SECURITY;
ALTER TABLE party_service_category_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE party_relationship_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE party_relationships ENABLE ROW LEVEL SECURITY;
ALTER TABLE party_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE party_customer_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE party_vendor_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE party_subcontractor_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE party_consultant_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE party_recruitment_agency_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE party_government_authority_profiles ENABLE ROW LEVEL SECURITY;

-- parties policies (pattern matches existing customers)
DROP POLICY IF EXISTS parties_select_policy ON parties;
CREATE POLICY parties_select_policy ON parties FOR SELECT
  USING (
    is_active = true
    OR current_user_has_permission('master_data.parties.view')
    OR current_user_has_permission('master_data.party_master.view')
    OR current_user_has_role('system_admin')
  );

DROP POLICY IF EXISTS parties_insert_policy ON parties;
CREATE POLICY parties_insert_policy ON parties FOR INSERT
  WITH CHECK (
    current_user_has_permission('master_data.parties.create')
    OR current_user_has_permission('master_data.parties.edit')
    OR current_user_has_permission('master_data.party_master.manage')
    OR current_user_has_role('system_admin')
  );

DROP POLICY IF EXISTS parties_update_policy ON parties;
CREATE POLICY parties_update_policy ON parties FOR UPDATE
  USING (
    (current_user_has_permission('master_data.parties.edit') OR current_user_has_permission('master_data.party_master.manage') OR current_user_has_role('system_admin'))
    AND (is_locked = false OR current_user_has_role('system_admin'))
    AND (is_system = false OR current_user_has_role('system_admin'))
  );

DROP POLICY IF EXISTS parties_delete_policy ON parties;
CREATE POLICY parties_delete_policy ON parties FOR DELETE
  USING (current_user_has_role('system_admin'));

-- party_bank_details — stricter SELECT
DROP POLICY IF EXISTS party_bank_details_select_policy ON party_bank_details;
CREATE POLICY party_bank_details_select_policy ON party_bank_details FOR SELECT
  USING (
    current_user_has_permission('master_data.parties.manage_bank_details')
    OR current_user_has_role('system_admin')
  );

DROP POLICY IF EXISTS party_bank_details_write_policy ON party_bank_details;
CREATE POLICY party_bank_details_write_policy ON party_bank_details FOR ALL
  USING (
    current_user_has_permission('master_data.parties.manage_bank_details')
    OR current_user_has_role('system_admin')
  )
  WITH CHECK (
    current_user_has_permission('master_data.parties.manage_bank_details')
    OR current_user_has_role('system_admin')
  );

-- Generic child table policy template (apply similarly to contacts, addresses, licenses, etc.)
-- Example: party_contacts
DROP POLICY IF EXISTS party_contacts_select_policy ON party_contacts;
CREATE POLICY party_contacts_select_policy ON party_contacts FOR SELECT
  USING (
    current_user_has_permission('master_data.parties.view')
    OR current_user_has_permission('master_data.party_master.view')
    OR current_user_has_role('system_admin')
  );

DROP POLICY IF EXISTS party_contacts_write_policy ON party_contacts;
CREATE POLICY party_contacts_write_policy ON party_contacts FOR ALL
  USING (
    current_user_has_permission('master_data.parties.manage_contacts')
    OR current_user_has_permission('master_data.party_master.manage')
    OR current_user_has_role('system_admin')
  )
  WITH CHECK (
    current_user_has_permission('master_data.parties.manage_contacts')
    OR current_user_has_permission('master_data.party_master.manage')
    OR current_user_has_role('system_admin')
  );

-- party_notes private filter
DROP POLICY IF EXISTS party_notes_select_policy ON party_notes;
CREATE POLICY party_notes_select_policy ON party_notes FOR SELECT
  USING (
    is_private = false
    OR created_by = (SELECT id FROM user_profiles WHERE auth_user_id = auth.uid() LIMIT 1)
    OR current_user_has_permission('master_data.parties.manage_compliance')
    OR current_user_has_role('system_admin')
  );

-- NOTE: Remaining tables follow same view/edit permission pattern — complete in implementation migration.

-- ============================================================================
-- SECTION 7: SEED DATA — PARTY TYPES
-- ============================================================================

INSERT INTO party_types (type_code, type_name, is_system, sort_order) VALUES
  ('CUSTOMER', 'Customer', true, 10),
  ('VENDOR', 'Vendor', true, 20),
  ('SUBCONTRACTOR', 'Subcontractor', true, 30),
  ('CONSULTANT', 'Consultant', true, 40),
  ('RECRUITMENT_AGENCY', 'Recruitment Agency', true, 50),
  ('GOVERNMENT_AUTHORITY', 'Government Authority', true, 60),
  ('BANK', 'Bank', true, 70),
  ('INSURANCE_COMPANY', 'Insurance Company', true, 80),
  ('LICENSE_ISSUER', 'License Issuer', true, 90),
  ('FREE_ZONE_AUTHORITY', 'Free Zone Authority', true, 100),
  ('SCRAP_BUYER', 'Scrap Buyer', true, 110),
  ('SCRAP_SELLER', 'Scrap Seller', true, 120),
  ('TRANSPORT_SUPPLIER', 'Transport Supplier', true, 130),
  ('EQUIPMENT_SUPPLIER', 'Equipment Supplier', true, 140),
  ('FUEL_SUPPLIER', 'Fuel Supplier', true, 150),
  ('WORKSHOP_SUPPLIER', 'Workshop Supplier', true, 160),
  ('SPARE_PARTS_SUPPLIER', 'Spare Parts Supplier', true, 170),
  ('LAB_TESTING_COMPANY', 'Lab / Testing Company', true, 180),
  ('WASTE_DISPOSAL_FACILITY', 'Waste Disposal Facility', true, 190),
  ('TRAINING_PROVIDER', 'Training Provider', true, 200),
  ('MANPOWER_SUPPLIER', 'Manpower Supplier', true, 210),
  ('OWNER_LANDLORD', 'Owner / Landlord', true, 220),
  ('JOINT_VENTURE_PARTNER', 'Joint Venture Partner', true, 230)
ON CONFLICT (type_code) DO NOTHING;

-- ============================================================================
-- SECTION 8: SEED DATA — LOOKUP MASTERS (representative samples)
-- ============================================================================

INSERT INTO party_natures (nature_code, nature_name_en, is_system, sort_order) VALUES
  ('COMPANY', 'Company', true, 1),
  ('INDIVIDUAL', 'Individual', true, 2),
  ('GOVERNMENT_ENTITY', 'Government Entity', true, 3),
  ('FREE_ZONE_ENTITY', 'Free Zone Entity', true, 4),
  ('BRANCH', 'Branch Office', true, 5),
  ('JOINT_VENTURE', 'Joint Venture', true, 6)
ON CONFLICT (nature_code) DO NOTHING;

INSERT INTO party_statuses (status_code, status_name_en, is_system, sort_order) VALUES
  ('DRAFT', 'Draft', true, 1),
  ('ACTIVE', 'Active', true, 2),
  ('SUSPENDED', 'Suspended', true, 3),
  ('UNDER_REVIEW', 'Under Review', true, 4),
  ('INACTIVE', 'Inactive', true, 5),
  ('BLOCKED', 'Blocked', true, 6)
ON CONFLICT (status_code) DO NOTHING;

INSERT INTO party_blacklist_statuses (status_code, status_name_en, is_system, sort_order) VALUES
  ('NOT_BLACKLISTED', 'Not Blacklisted', true, 1),
  ('WATCHLIST', 'Watchlist', true, 2),
  ('BLACKLISTED', 'Blacklisted', true, 3),
  ('TEMPORARILY_BLOCKED', 'Temporarily Blocked', true, 4)
ON CONFLICT (status_code) DO NOTHING;

INSERT INTO party_risk_ratings (rating_code, rating_name_en, is_system, sort_order) VALUES
  ('LOW', 'Low', true, 1),
  ('MEDIUM', 'Medium', true, 2),
  ('HIGH', 'High', true, 3),
  ('CRITICAL', 'Critical', true, 4)
ON CONFLICT (rating_code) DO NOTHING;

-- Service categories (sample — full list in Database Field Map)
INSERT INTO party_service_categories_master (service_category_code, service_category_name, is_system, sort_order) VALUES
  ('HEAVY_EQUIPMENT_RENTAL', 'Heavy Equipment Rental', true, 10),
  ('TRANSPORT', 'Transport', true, 20),
  ('DIESEL_SUPPLY', 'Diesel Supply', true, 30),
  ('SCRAP_PURCHASE', 'Scrap Purchase', true, 40),
  ('WASTE_DISPOSAL', 'Waste Disposal', true, 50),
  ('MANPOWER_SUPPLY', 'Manpower Supply', true, 60),
  ('HSE_TRAINING', 'HSE Training', true, 70),
  ('GOVERNMENT_SERVICE', 'Government Service', true, 80)
ON CONFLICT (service_category_code) DO NOTHING;

-- ============================================================================
-- SECTION 9: NUMBERING RULES (DRAFT — idempotent pattern)
-- ============================================================================

INSERT INTO global_numbering_rules (
  rule_code, rule_name, description, module_code, module_name,
  document_type_code, document_type_name, document_prefix, separator,
  format_template, sequence_length, padding_character,
  starting_sequence_number, current_sequence_number, next_sequence_number,
  reset_policy, reserve_on_draft, reserve_on_submit,
  allow_manual_override, allow_gaps, is_active, is_locked
) VALUES (
  'MASTER_PARTY', 'Party Reference Number', 'Automatic numbering for unified party master',
  'MASTER_DATA', 'Master Data', 'PARTY', 'Party', 'PTY', '-',
  '{DOC}-{SEQ6}', 6, '0', 1, 0, 1,
  'NEVER', false, true, false, true, true, false
) ON CONFLICT (rule_code) DO UPDATE SET
  document_prefix = EXCLUDED.document_prefix,
  format_template = EXCLUDED.format_template,
  updated_at = now();

-- Additional child numbering rules: MASTER_PARTY_CONTACT, MASTER_PARTY_ADDRESS,
-- MASTER_PARTY_BANK, MASTER_PARTY_LICENSE, MASTER_PARTY_TAX, MASTER_PARTY_DOCUMENT,
-- MASTER_PARTY_NOTE — follow same INSERT pattern as MASTER_CUSTOMER in 002F.3E.2C.

-- ============================================================================
-- SECTION 10: PERMISSIONS (DRAFT)
-- ============================================================================

INSERT INTO permissions (permission_code, permission_name, action_code, description, module_code, is_system_permission, is_active, sort_order)
VALUES
  ('master_data.parties.view', 'View Parties', 'view', 'View party master records', 'master_data', true, true, 100),
  ('master_data.parties.create', 'Create Parties', 'create', 'Create new parties', 'master_data', true, true, 101),
  ('master_data.parties.edit', 'Edit Parties', 'edit', 'Edit party records', 'master_data', true, true, 102),
  ('master_data.parties.delete', 'Delete Parties', 'delete', 'Permanently delete parties', 'master_data', true, true, 103),
  ('master_data.parties.deactivate', 'Deactivate Parties', 'deactivate', 'Deactivate/reactivate parties', 'master_data', true, true, 104),
  ('master_data.parties.manage_types', 'Manage Party Types', 'manage', 'Administer party types master', 'master_data', true, true, 105),
  ('master_data.parties.manage_service_categories', 'Manage Service Categories', 'manage', 'Administer party service categories', 'master_data', true, true, 106),
  ('master_data.parties.manage_licenses', 'Manage Party Licenses', 'manage', 'Manage party license records', 'master_data', true, true, 107),
  ('master_data.parties.manage_tax', 'Manage Party Tax', 'manage', 'Manage tax registrations', 'master_data', true, true, 108),
  ('master_data.parties.manage_contacts', 'Manage Party Contacts', 'manage', 'Manage party contacts', 'master_data', true, true, 109),
  ('master_data.parties.manage_addresses', 'Manage Party Addresses', 'manage', 'Manage party addresses', 'master_data', true, true, 110),
  ('master_data.parties.manage_bank_details', 'Manage Bank Details', 'manage', 'View/edit party bank details', 'master_data', true, true, 111),
  ('master_data.parties.verify_bank_details', 'Verify Bank Details', 'verify', 'Verify party bank accounts', 'master_data', true, true, 112),
  ('master_data.parties.manage_documents', 'Manage Party Documents', 'manage', 'Manage party document metadata', 'master_data', true, true, 113),
  ('master_data.parties.manage_compliance', 'Manage Compliance', 'manage', 'Manage compliance profiles', 'master_data', true, true, 114),
  ('master_data.parties.approve', 'Approve Parties', 'approve', 'Approve party records', 'master_data', true, true, 115),
  ('master_data.parties.blacklist', 'Blacklist Parties', 'blacklist', 'Manage blacklist status', 'master_data', true, true, 116),
  ('master_data.parties.manage_relationships', 'Manage Relationships', 'manage', 'Manage party relationships', 'master_data', true, true, 117),
  ('master_data.parties.override_duplicate', 'Override Duplicate', 'override', 'Override duplicate detection blocks', 'master_data', true, true, 118),
  ('master_data.parties.export', 'Export Parties', 'export', 'Export party data', 'master_data', true, true, 119),
  ('master_data.parties.print', 'Print Parties', 'print', 'Print party lists', 'master_data', true, true, 120)
ON CONFLICT (permission_code) DO NOTHING;

-- Assign all new permissions to system_admin role (draft)
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
CROSS JOIN permissions p
WHERE r.role_code = 'system_admin'
  AND p.permission_code LIKE 'master_data.parties.%'
ON CONFLICT DO NOTHING;

-- ============================================================================
-- SECTION 11: DUPLICATE DETECTION FUNCTION (DRAFT)
-- ============================================================================

CREATE OR REPLACE FUNCTION find_possible_duplicate_parties(
  p_legal_name_en text DEFAULT NULL,
  p_legal_name_ar text DEFAULT NULL,
  p_trade_name_en text DEFAULT NULL,
  p_display_name text DEFAULT NULL,
  p_email text DEFAULT NULL,
  p_mobile text DEFAULT NULL,
  p_trn text DEFAULT NULL,
  p_license_number text DEFAULT NULL,
  p_iban text DEFAULT NULL,
  p_website text DEFAULT NULL,
  p_exclude_party_id bigint DEFAULT NULL
)
RETURNS TABLE (
  party_id bigint,
  party_code text,
  display_name text,
  match_type text,
  match_score numeric
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  -- Exact TRN
  IF p_trn IS NOT NULL AND btrim(p_trn) <> '' THEN
    RETURN QUERY
    SELECT p.id, p.party_code, p.display_name, 'EXACT_TRN'::text, 100::numeric
    FROM parties p
    JOIN party_tax_registrations ptr ON ptr.party_id = p.id AND ptr.is_active
    WHERE ptr.tax_registration_number = btrim(p_trn)
      AND (p_exclude_party_id IS NULL OR p.id <> p_exclude_party_id);
  END IF;

  -- Exact license number
  IF p_license_number IS NOT NULL AND btrim(p_license_number) <> '' THEN
    RETURN QUERY
    SELECT p.id, p.party_code, p.display_name, 'EXACT_LICENSE'::text, 100::numeric
    FROM parties p
    JOIN party_licenses pl ON pl.party_id = p.id AND pl.is_active
    WHERE pl.license_number = btrim(p_license_number)
      AND (p_exclude_party_id IS NULL OR p.id <> p_exclude_party_id);
  END IF;

  -- Exact IBAN
  IF p_iban IS NOT NULL AND btrim(p_iban) <> '' THEN
    RETURN QUERY
    SELECT p.id, p.party_code, p.display_name, 'EXACT_IBAN'::text, 95::numeric
    FROM parties p
    JOIN party_bank_details pbd ON pbd.party_id = p.id AND pbd.is_active
    WHERE upper(replace(pbd.iban, ' ', '')) = upper(replace(btrim(p_iban), ' ', ''))
      AND (p_exclude_party_id IS NULL OR p.id <> p_exclude_party_id);
  END IF;

  -- Similar legal name (trigram)
  IF p_legal_name_en IS NOT NULL AND btrim(p_legal_name_en) <> '' THEN
    RETURN QUERY
    SELECT p.id, p.party_code, p.display_name, 'SIMILAR_NAME'::text,
           (similarity(p.legal_name_en, btrim(p_legal_name_en)) * 100)::numeric
    FROM parties p
    WHERE p.legal_name_en % btrim(p_legal_name_en)
      AND similarity(p.legal_name_en, btrim(p_legal_name_en)) > 0.45
      AND (p_exclude_party_id IS NULL OR p.id <> p_exclude_party_id);
  END IF;

  RETURN;
END;
$$;

COMMENT ON FUNCTION find_possible_duplicate_parties IS
  'DRAFT: Returns possible duplicate parties for review. REVIEW ONLY migration.';

-- ============================================================================
-- END OF REVIEW-ONLY DRAFT MIGRATION
-- ============================================================================
