/**
 * Report Designer — Report Field Registry
 * Phase: REPORT DESIGNER UX.2
 *
 * This is the SINGLE SOURCE OF TRUTH for all fields available in the Report Designer.
 * Replaces the flat ERP_BINDING_REGISTRY — the legacy registry is auto-generated
 * from this file via legacy-binding-adapter.ts.
 *
 * RULES:
 *  - Every field must be EXPLICITLY listed here — no automatic DB scanning.
 *  - restricted/confidential fields: isActive: false — not insertable in UX.2.
 *  - Planned future-module fields: isPlanned: true — shown as "Coming Soon".
 *  - New fields need: fieldPath, resolverKey, sampleValue, sensitivityLevel.
 *  - When adding future module fields, mark isActive: false, isPlanned: true.
 *
 * EXCLUDED (must never appear as isActive: true in UX.2):
 *  - salary, iban, bank_account, account_number
 *  - passport raw number, eid raw number
 *  - visa raw details, medical data, health data, insurance details
 *  - ocr_text, extracted_text, prompt, embedding, vector
 *  - *_id internal FKs, created_by, updated_by
 *  - service_role, api_key, secret, token values
 */

import type { ReportFieldRegistryEntry } from "./types";

export const REPORT_FIELD_REGISTRY: ReportFieldRegistryEntry[] = [
  // ════════════════════════════════════════════════════════════════════════
  // MODULE: HR / Human Resources
  // ENTITY: Employee
  // ════════════════════════════════════════════════════════════════════════

  // ── Public fields ──────────────────────────────────────────────────────
  {
    moduleCode: "HR",
    moduleLabel: "HR / Human Resources",
    entityCode: "employee",
    entityLabel: "Employee",
    fieldPath: "employee.full_name_en",
    fieldLabel: "Full Name (English)",
    dataType: "string",
    sensitivityLevel: "public",
    resolverKey: "employee.full_name_en",
    sampleValue: "[SAMPLE] Ahmed Al Mansoori",
    isActive: true,
    isPlanned: false,
    sortOrder: 10,
    description: "Employee full legal name in English",
  },
  {
    moduleCode: "HR",
    moduleLabel: "HR / Human Resources",
    entityCode: "employee",
    entityLabel: "Employee",
    fieldPath: "employee.full_name_ar",
    fieldLabel: "Full Name (Arabic)",
    dataType: "string",
    sensitivityLevel: "public",
    resolverKey: "employee.full_name_ar",
    sampleValue: "[SAMPLE] أحمد المنصوري",
    isActive: true,
    isPlanned: false,
    sortOrder: 11,
    description: "Employee full legal name in Arabic",
  },
  {
    moduleCode: "HR",
    moduleLabel: "HR / Human Resources",
    entityCode: "employee",
    entityLabel: "Employee",
    fieldPath: "employee.employee_code",
    fieldLabel: "Employee Code / ID",
    dataType: "string",
    sensitivityLevel: "public",
    resolverKey: "employee.employee_code",
    sampleValue: "[SAMPLE] EMP-2026-001",
    isActive: true,
    isPlanned: false,
    sortOrder: 12,
  },
  {
    moduleCode: "HR",
    moduleLabel: "HR / Human Resources",
    entityCode: "employee",
    entityLabel: "Employee",
    fieldPath: "employee.designation",
    fieldLabel: "Designation / Job Title",
    dataType: "string",
    sensitivityLevel: "public",
    resolverKey: "employee.designation",
    sampleValue: "[SAMPLE] Senior Analyst",
    isActive: true,
    isPlanned: false,
    sortOrder: 13,
  },
  {
    moduleCode: "HR",
    moduleLabel: "HR / Human Resources",
    entityCode: "employee",
    entityLabel: "Employee",
    fieldPath: "employee.department",
    fieldLabel: "Department",
    dataType: "string",
    sensitivityLevel: "public",
    resolverKey: "employee.department",
    sampleValue: "[SAMPLE] Finance Department",
    isActive: true,
    isPlanned: false,
    sortOrder: 14,
  },
  {
    moduleCode: "HR",
    moduleLabel: "HR / Human Resources",
    entityCode: "employee",
    entityLabel: "Employee",
    fieldPath: "employee.known_name",
    fieldLabel: "Known / Preferred Name",
    dataType: "string",
    sensitivityLevel: "public",
    resolverKey: "employee.known_name",
    sampleValue: "[SAMPLE] Ahmed",
    isActive: true,
    isPlanned: false,
    sortOrder: 15,
    description:
      "Preferred or known name (may differ from legal full name). Safe for display.",
  },

  // ── Internal fields ────────────────────────────────────────────────────
  {
    moduleCode: "HR",
    moduleLabel: "HR / Human Resources",
    entityCode: "employee",
    entityLabel: "Employee",
    fieldPath: "employee.branch",
    fieldLabel: "Branch / Work Location",
    dataType: "string",
    sensitivityLevel: "internal",
    resolverKey: "employee.branch",
    sampleValue: "[SAMPLE] Head Office",
    isActive: true,
    isPlanned: false,
    sortOrder: 20,
  },
  {
    moduleCode: "HR",
    moduleLabel: "HR / Human Resources",
    entityCode: "employee",
    entityLabel: "Employee",
    fieldPath: "employee.owner_company",
    fieldLabel: "Company (Employer)",
    dataType: "string",
    sensitivityLevel: "internal",
    resolverKey: "employee.owner_company",
    sampleValue: "[SAMPLE] ALGT Holdings LLC",
    isActive: true,
    isPlanned: false,
    sortOrder: 21,
  },
  {
    moduleCode: "HR",
    moduleLabel: "HR / Human Resources",
    entityCode: "employee",
    entityLabel: "Employee",
    fieldPath: "employee.joining_date",
    fieldLabel: "Date of Joining",
    dataType: "date",
    sensitivityLevel: "internal",
    resolverKey: "employee.joining_date",
    sampleValue: "[SAMPLE] 01 Jan 2022",
    isActive: true,
    isPlanned: false,
    sortOrder: 22,
  },
  {
    moduleCode: "HR",
    moduleLabel: "HR / Human Resources",
    entityCode: "employee",
    entityLabel: "Employee",
    fieldPath: "employee.nationality",
    fieldLabel: "Nationality",
    dataType: "string",
    sensitivityLevel: "internal",
    resolverKey: "employee.nationality",
    sampleValue: "[SAMPLE] UAE",
    isActive: true,
    isPlanned: false,
    sortOrder: 23,
  },
  {
    moduleCode: "HR",
    moduleLabel: "HR / Human Resources",
    entityCode: "employee",
    entityLabel: "Employee",
    fieldPath: "employee.employment_type",
    fieldLabel: "Employment Type",
    dataType: "string",
    sensitivityLevel: "internal",
    resolverKey: "employee.employment_type",
    sampleValue: "[SAMPLE] Full-Time Permanent",
    isActive: true,
    isPlanned: false,
    sortOrder: 24,
  },
  {
    moduleCode: "HR",
    moduleLabel: "HR / Human Resources",
    entityCode: "employee",
    entityLabel: "Employee",
    fieldPath: "employee.contract_end_date",
    fieldLabel: "Contract End Date",
    dataType: "date",
    sensitivityLevel: "internal",
    resolverKey: "employee.contract_end_date",
    sampleValue: "[SAMPLE] 31 Dec 2027",
    isActive: true,
    isPlanned: false,
    sortOrder: 25,
  },
  {
    moduleCode: "HR",
    moduleLabel: "HR / Human Resources",
    entityCode: "employee",
    entityLabel: "Employee",
    fieldPath: "employee.employment_status",
    fieldLabel: "Employment Status",
    dataType: "string",
    sensitivityLevel: "internal",
    resolverKey: "employee.employment_status",
    sampleValue: "[SAMPLE] Active",
    isActive: true,
    isPlanned: false,
    sortOrder: 26,
  },
  {
    moduleCode: "HR",
    moduleLabel: "HR / Human Resources",
    entityCode: "employee",
    entityLabel: "Employee",
    fieldPath: "employee.work_site",
    fieldLabel: "Primary Work Site",
    dataType: "string",
    sensitivityLevel: "internal",
    resolverKey: "employee.work_site",
    sampleValue: "[SAMPLE] Main Office — Dubai",
    isActive: true,
    isPlanned: false,
    sortOrder: 27,
  },
  {
    moduleCode: "HR",
    moduleLabel: "HR / Human Resources",
    entityCode: "employee",
    entityLabel: "Employee",
    fieldPath: "employee.gender",
    fieldLabel: "Gender",
    dataType: "string",
    sensitivityLevel: "internal",
    resolverKey: "employee.gender",
    sampleValue: "[SAMPLE] Male",
    isActive: true,
    isPlanned: false,
    sortOrder: 28,
    description: "Employee gender (Male / Female). Internal HR data.",
  },
  {
    moduleCode: "HR",
    moduleLabel: "HR / Human Resources",
    entityCode: "employee",
    entityLabel: "Employee",
    fieldPath: "employee.marital_status",
    fieldLabel: "Marital Status",
    dataType: "string",
    sensitivityLevel: "internal",
    resolverKey: "employee.marital_status",
    sampleValue: "[SAMPLE] Single",
    isActive: true,
    isPlanned: false,
    sortOrder: 29,
    description: "Employee marital status. Internal HR data.",
  },
  {
    moduleCode: "HR",
    moduleLabel: "HR / Human Resources",
    entityCode: "employee",
    entityLabel: "Employee",
    fieldPath: "employee.contract_start_date",
    fieldLabel: "Contract Start Date",
    dataType: "date",
    sensitivityLevel: "internal",
    resolverKey: "employee.contract_start_date",
    sampleValue: "[SAMPLE] 01 Jan 2022",
    isActive: true,
    isPlanned: false,
    sortOrder: 30,
  },
  {
    moduleCode: "HR",
    moduleLabel: "HR / Human Resources",
    entityCode: "employee",
    entityLabel: "Employee",
    fieldPath: "employee.probation_end_date",
    fieldLabel: "Probation End Date",
    dataType: "date",
    sensitivityLevel: "internal",
    resolverKey: "employee.probation_end_date",
    sampleValue: "[SAMPLE] 01 Apr 2022",
    isActive: true,
    isPlanned: false,
    sortOrder: 31,
  },
  {
    moduleCode: "HR",
    moduleLabel: "HR / Human Resources",
    entityCode: "employee",
    entityLabel: "Employee",
    fieldPath: "employee.mobile_number",
    fieldLabel: "Mobile Number",
    dataType: "string",
    sensitivityLevel: "internal",
    resolverKey: "employee.mobile_number",
    sampleValue: "[SAMPLE] +971 50 XXX XXXX",
    isActive: true,
    isPlanned: false,
    sortOrder: 32,
    description:
      "Employee mobile number. Internal — use only for official correspondence documents.",
  },
  {
    moduleCode: "HR",
    moduleLabel: "HR / Human Resources",
    entityCode: "employee",
    entityLabel: "Employee",
    fieldPath: "employee.last_working_date",
    fieldLabel: "Last Working Date",
    dataType: "date",
    sensitivityLevel: "internal",
    resolverKey: "employee.last_working_date",
    sampleValue: "",
    isActive: true,
    isPlanned: false,
    sortOrder: 33,
    description:
      "Inactive / last working date. Empty for active employees.",
  },

  // ── Restricted / Planned (pre-UX.3) ─────────────────────────────────────
  {
    moduleCode: "HR",
    moduleLabel: "HR / Human Resources",
    entityCode: "employee",
    entityLabel: "Employee",
    fieldPath: "employee.end_of_service_date",
    fieldLabel: "End of Service Date",
    dataType: "date",
    sensitivityLevel: "restricted",
    resolverKey: "employee.end_of_service_date",
    sampleValue: "",
    isActive: false,
    isPlanned: true,
    sortOrder: 40,
    description:
      "End of service date — requires UX.3 governance unlock before use.",
  },

  // ── UX.3 — Salary / Compensation (restricted) ───────────────────────────
  {
    moduleCode: "HR",
    moduleLabel: "HR / Human Resources",
    entityCode: "employee",
    entityLabel: "Employee",
    fieldPath: "employee.basic_salary",
    fieldLabel: "Basic Salary",
    dataType: "money",
    sensitivityLevel: "restricted",
    requiredPermission: "reports.sensitive_fields.use",
    allowedTemplateTypes: ["salary_certificate", "offer_letter", "certificate", "letter"],
    allowedOutputModes: ["official"],
    resolverKey: "employee.basic_salary",
    sampleValue: "[Restricted — not shown in preview]",
    maskingStrategy: "label",
    fieldGroup: "salary",
    isActive: true,
    isPlanned: false,
    sortOrder: 50,
    description:
      "Employee basic salary. Requires reports.sensitive_fields.use and salary_certificate/offer_letter template type. Official output only.",
  },
  {
    moduleCode: "HR",
    moduleLabel: "HR / Human Resources",
    entityCode: "employee",
    entityLabel: "Employee",
    fieldPath: "employee.total_salary",
    fieldLabel: "Total Salary (Gross)",
    dataType: "money",
    sensitivityLevel: "restricted",
    requiredPermission: "reports.sensitive_fields.use",
    allowedTemplateTypes: ["salary_certificate", "offer_letter", "certificate", "letter"],
    allowedOutputModes: ["official"],
    resolverKey: "employee.total_salary",
    sampleValue: "[Restricted — not shown in preview]",
    maskingStrategy: "label",
    fieldGroup: "salary",
    isActive: true,
    isPlanned: false,
    sortOrder: 51,
    description:
      "Employee total gross salary. Requires reports.sensitive_fields.use and salary_certificate/offer_letter template type. Official output only.",
  },
  {
    moduleCode: "HR",
    moduleLabel: "HR / Human Resources",
    entityCode: "employee",
    entityLabel: "Employee",
    fieldPath: "employee.net_salary",
    fieldLabel: "Net Salary",
    dataType: "money",
    sensitivityLevel: "restricted",
    requiredPermission: "reports.sensitive_fields.use",
    allowedTemplateTypes: ["salary_certificate", "offer_letter", "certificate", "letter"],
    allowedOutputModes: ["official"],
    resolverKey: "employee.net_salary",
    sampleValue: "[Restricted — not shown in preview]",
    maskingStrategy: "label",
    fieldGroup: "salary",
    isActive: true,
    isPlanned: false,
    sortOrder: 52,
    description:
      "Employee net salary (after deductions). Requires reports.sensitive_fields.use. Official output only.",
  },
  {
    moduleCode: "HR",
    moduleLabel: "HR / Human Resources",
    entityCode: "employee",
    entityLabel: "Employee",
    fieldPath: "employee.last_salary",
    fieldLabel: "Last Drawn Salary",
    dataType: "money",
    sensitivityLevel: "restricted",
    requiredPermission: "reports.sensitive_fields.use",
    allowedTemplateTypes: ["salary_certificate", "offer_letter", "experience_letter", "certificate", "letter"],
    allowedOutputModes: ["official"],
    resolverKey: "employee.last_salary",
    sampleValue: "[Restricted — not shown in preview]",
    maskingStrategy: "label",
    fieldGroup: "salary",
    isActive: true,
    isPlanned: false,
    sortOrder: 53,
    description:
      "Last drawn salary for ex-employees. Requires reports.sensitive_fields.use. Official output only.",
  },

  // ── UX.3 — Banking / IBAN (confidential) ─────────────────────────────────
  {
    moduleCode: "HR",
    moduleLabel: "HR / Human Resources",
    entityCode: "employee",
    entityLabel: "Employee",
    fieldPath: "employee.iban",
    fieldLabel: "IBAN",
    dataType: "string",
    sensitivityLevel: "confidential",
    requiredPermission: "reports.sensitive_fields.use",
    allowedTemplateTypes: ["salary_certificate", "bank_confirmation_letter"],
    allowedOutputModes: ["official"],
    resolverKey: "employee.iban",
    sampleValue: "[Confidential — not shown in preview]",
    maskingStrategy: "label",
    fieldGroup: "banking",
    isActive: true,
    isPlanned: false,
    sortOrder: 60,
    description:
      "Employee IBAN from WPS profile. Requires reports.sensitive_fields.use. Confidential — official output only.",
  },
  {
    moduleCode: "HR",
    moduleLabel: "HR / Human Resources",
    entityCode: "employee",
    entityLabel: "Employee",
    fieldPath: "employee.bank_account_number",
    fieldLabel: "Bank Account Number",
    dataType: "string",
    sensitivityLevel: "confidential",
    requiredPermission: "reports.sensitive_fields.use",
    allowedTemplateTypes: ["salary_certificate", "bank_confirmation_letter"],
    allowedOutputModes: ["official"],
    resolverKey: "employee.bank_account_number",
    sampleValue: "[Confidential — not shown in preview]",
    maskingStrategy: "label",
    fieldGroup: "banking",
    isActive: true,
    isPlanned: false,
    sortOrder: 61,
    description:
      "Employee bank account number from WPS profile. Requires reports.sensitive_fields.use. Confidential — official output only.",
  },

  // ── UX.3 — Identity Documents (restricted) ──────────────────────────────
  {
    moduleCode: "HR",
    moduleLabel: "HR / Human Resources",
    entityCode: "employee",
    entityLabel: "Employee",
    fieldPath: "employee.passport_number",
    fieldLabel: "Passport Number",
    dataType: "string",
    sensitivityLevel: "restricted",
    requiredPermission: "reports.sensitive_fields.use",
    allowedTemplateTypes: ["government_forms", "visa_letter", "experience_letter", "certificate", "letter"],
    allowedOutputModes: ["official"],
    resolverKey: "employee.passport_number",
    sampleValue: "[Restricted — not shown in preview]",
    maskingStrategy: "label",
    fieldGroup: "identity",
    isActive: true,
    isPlanned: false,
    sortOrder: 70,
    description:
      "Employee passport number. Requires reports.sensitive_fields.use. Official output only.",
  },
  {
    moduleCode: "HR",
    moduleLabel: "HR / Human Resources",
    entityCode: "employee",
    entityLabel: "Employee",
    fieldPath: "employee.emirates_id_number",
    fieldLabel: "Emirates ID Number",
    dataType: "string",
    sensitivityLevel: "restricted",
    requiredPermission: "reports.sensitive_fields.use",
    allowedTemplateTypes: ["government_forms", "visa_letter", "experience_letter", "certificate", "letter"],
    allowedOutputModes: ["official"],
    resolverKey: "employee.emirates_id_number",
    sampleValue: "[Restricted — not shown in preview]",
    maskingStrategy: "label",
    fieldGroup: "identity",
    isActive: true,
    isPlanned: false,
    sortOrder: 71,
    description:
      "Employee Emirates ID number. Requires reports.sensitive_fields.use and government_forms/visa_letter template. Official output only.",
  },

  // ── UX.3 — Visa (restricted) ──────────────────────────────────────────────
  {
    moduleCode: "HR",
    moduleLabel: "HR / Human Resources",
    entityCode: "employee",
    entityLabel: "Employee",
    fieldPath: "employee.residence_visa_number",
    fieldLabel: "Residence Visa Number",
    dataType: "string",
    sensitivityLevel: "restricted",
    requiredPermission: "reports.sensitive_fields.use",
    allowedTemplateTypes: ["government_forms", "visa_letter", "experience_letter", "certificate", "letter"],
    allowedOutputModes: ["official"],
    resolverKey: "employee.residence_visa_number",
    sampleValue: "[Restricted — not shown in preview]",
    maskingStrategy: "label",
    fieldGroup: "visa",
    isActive: true,
    isPlanned: false,
    sortOrder: 80,
    description:
      "Employee UAE residence visa number. Requires reports.sensitive_fields.use and government_forms/visa_letter template. Official output only.",
  },
  {
    moduleCode: "HR",
    moduleLabel: "HR / Human Resources",
    entityCode: "employee",
    entityLabel: "Employee",
    fieldPath: "employee.visa_expiry_date",
    fieldLabel: "Visa Expiry Date",
    dataType: "date",
    sensitivityLevel: "restricted",
    requiredPermission: "reports.sensitive_fields.use",
    allowedTemplateTypes: ["government_forms", "visa_letter", "experience_letter", "certificate", "letter"],
    allowedOutputModes: ["official"],
    resolverKey: "employee.visa_expiry_date",
    sampleValue: "[Restricted — not shown in preview]",
    maskingStrategy: "label",
    fieldGroup: "visa",
    isActive: true,
    isPlanned: false,
    sortOrder: 81,
    description:
      "Employee UAE visa expiry date. Requires reports.sensitive_fields.use and government_forms/visa_letter template. Official output only.",
  },

  // ── UX.3 — Medical (confidential, planned) ────────────────────────────────
  {
    moduleCode: "HR",
    moduleLabel: "HR / Human Resources",
    entityCode: "employee",
    entityLabel: "Employee",
    fieldPath: "employee.medical_insurance_number",
    fieldLabel: "Medical Insurance Number",
    dataType: "string",
    sensitivityLevel: "confidential",
    requiredPermission: "reports.sensitive_fields.use",
    allowedTemplateTypes: ["medical_fitness_letter"],
    allowedOutputModes: ["official"],
    resolverKey: "employee.medical_insurance_number",
    sampleValue: "[Confidential — not shown in preview]",
    maskingStrategy: "label",
    fieldGroup: "medical",
    isActive: false,
    isPlanned: true,
    sortOrder: 90,
    description:
      "Employee medical insurance number — confidential. Planned for future implementation with hr.medical.view permission gate.",
  },

  // ════════════════════════════════════════════════════════════════════════
  // MODULE: COMPANY
  // ENTITY: Company
  // ════════════════════════════════════════════════════════════════════════

  {
    moduleCode: "COMPANY",
    moduleLabel: "Company",
    entityCode: "company",
    entityLabel: "Company",
    fieldPath: "company.legal_name_en",
    fieldLabel: "Legal Name (English)",
    dataType: "string",
    sensitivityLevel: "public",
    resolverKey: "company.legal_name_en",
    sampleValue: "[SAMPLE] ALGT Holdings LLC",
    isActive: true,
    isPlanned: false,
    sortOrder: 10,
  },
  {
    moduleCode: "COMPANY",
    moduleLabel: "Company",
    entityCode: "company",
    entityLabel: "Company",
    fieldPath: "company.legal_name_ar",
    fieldLabel: "Legal Name (Arabic)",
    dataType: "string",
    sensitivityLevel: "public",
    resolverKey: "company.legal_name_ar",
    sampleValue: "[SAMPLE] شركة الجت القابضة ذ.م.م",
    isActive: true,
    isPlanned: false,
    sortOrder: 11,
  },
  {
    moduleCode: "COMPANY",
    moduleLabel: "Company",
    entityCode: "company",
    entityLabel: "Company",
    fieldPath: "company.address_block_en",
    fieldLabel: "Address (English)",
    dataType: "string",
    sensitivityLevel: "public",
    resolverKey: "company.address_block_en",
    sampleValue: "[SAMPLE] Level 12, Business Bay Tower, Dubai, UAE",
    isActive: true,
    isPlanned: false,
    sortOrder: 12,
  },
  {
    moduleCode: "COMPANY",
    moduleLabel: "Company",
    entityCode: "company",
    entityLabel: "Company",
    fieldPath: "company.phone",
    fieldLabel: "Phone",
    dataType: "string",
    sensitivityLevel: "public",
    resolverKey: "company.phone",
    sampleValue: "[SAMPLE] +971 4 123 4567",
    isActive: true,
    isPlanned: false,
    sortOrder: 13,
  },
  {
    moduleCode: "COMPANY",
    moduleLabel: "Company",
    entityCode: "company",
    entityLabel: "Company",
    fieldPath: "company.email",
    fieldLabel: "Email",
    dataType: "string",
    sensitivityLevel: "public",
    resolverKey: "company.email",
    sampleValue: "[SAMPLE] info@algt.example.com",
    isActive: true,
    isPlanned: false,
    sortOrder: 14,
  },
  {
    moduleCode: "COMPANY",
    moduleLabel: "Company",
    entityCode: "company",
    entityLabel: "Company",
    fieldPath: "company.website",
    fieldLabel: "Website",
    dataType: "url",
    sensitivityLevel: "public",
    resolverKey: "company.website",
    sampleValue: "[SAMPLE] www.algt.example.com",
    isActive: true,
    isPlanned: false,
    sortOrder: 15,
  },
  {
    moduleCode: "COMPANY",
    moduleLabel: "Company",
    entityCode: "company",
    entityLabel: "Company",
    fieldPath: "company.trn",
    fieldLabel: "Tax Registration Number (TRN)",
    dataType: "string",
    sensitivityLevel: "internal",
    resolverKey: "company.trn",
    sampleValue: "[SAMPLE] 100123456700003",
    isActive: true,
    isPlanned: false,
    sortOrder: 20,
  },
  {
    moduleCode: "COMPANY",
    moduleLabel: "Company",
    entityCode: "company",
    entityLabel: "Company",
    fieldPath: "company.trade_license_no",
    fieldLabel: "Trade License Number",
    dataType: "string",
    sensitivityLevel: "internal",
    resolverKey: "company.trade_license_no",
    sampleValue: "[SAMPLE] DED-2022-12345",
    isActive: true,
    isPlanned: false,
    sortOrder: 21,
  },

  // ════════════════════════════════════════════════════════════════════════
  // MODULE: DOCUMENT
  // ENTITY: Document
  // ════════════════════════════════════════════════════════════════════════

  {
    moduleCode: "DOCUMENT",
    moduleLabel: "Document",
    entityCode: "document",
    entityLabel: "Document",
    fieldPath: "document.title",
    fieldLabel: "Document Title",
    dataType: "string",
    sensitivityLevel: "public",
    resolverKey: "document.title",
    sampleValue: "[SAMPLE] Experience Letter",
    isActive: true,
    isPlanned: false,
    sortOrder: 10,
  },
  {
    moduleCode: "DOCUMENT",
    moduleLabel: "Document",
    entityCode: "document",
    entityLabel: "Document",
    fieldPath: "document.ref",
    fieldLabel: "Document Reference Number",
    dataType: "string",
    sensitivityLevel: "public",
    resolverKey: "document.ref",
    sampleValue: "[SAMPLE] EXP/2026/001",
    isActive: true,
    isPlanned: false,
    sortOrder: 11,
  },
  {
    moduleCode: "DOCUMENT",
    moduleLabel: "Document",
    entityCode: "document",
    entityLabel: "Document",
    fieldPath: "document.generated_at",
    fieldLabel: "Document Generated Date",
    dataType: "date",
    sensitivityLevel: "public",
    resolverKey: "document.generated_at",
    sampleValue: "[SAMPLE] 01 Jul 2026",
    isActive: true,
    isPlanned: false,
    sortOrder: 12,
  },
  {
    moduleCode: "DOCUMENT",
    moduleLabel: "Document",
    entityCode: "document",
    entityLabel: "Document",
    fieldPath: "document.issue_date",
    fieldLabel: "Document Issue Date",
    dataType: "date",
    sensitivityLevel: "public",
    resolverKey: "document.issue_date",
    sampleValue: "[SAMPLE] 01 Jul 2026",
    isActive: true,
    isPlanned: false,
    sortOrder: 13,
  },
  {
    moduleCode: "DOCUMENT",
    moduleLabel: "Document",
    entityCode: "document",
    entityLabel: "Document",
    fieldPath: "document.qr_verification_url",
    fieldLabel: "QR Verification URL",
    dataType: "url",
    sensitivityLevel: "internal",
    resolverKey: "document.qr_verification_url",
    sampleValue: "[SAMPLE] https://app.example.com/verify/SAMPLE_TOKEN",
    isActive: true,
    isPlanned: false,
    sortOrder: 14,
    description:
      "QR verification URL — only issued on official output, shows placeholder in preview/test.",
  },

  // ════════════════════════════════════════════════════════════════════════
  // MODULE: REPORT
  // ENTITY: Report
  // ════════════════════════════════════════════════════════════════════════

  {
    moduleCode: "REPORT",
    moduleLabel: "Report",
    entityCode: "report",
    entityLabel: "Report",
    fieldPath: "report.title",
    fieldLabel: "Report Title",
    dataType: "string",
    sensitivityLevel: "public",
    resolverKey: "report.title",
    sampleValue: "[SAMPLE] HR Employee Report",
    isActive: true,
    isPlanned: false,
    sortOrder: 10,
  },
  {
    moduleCode: "REPORT",
    moduleLabel: "Report",
    entityCode: "report",
    entityLabel: "Report",
    fieldPath: "report.code",
    fieldLabel: "Report Code",
    dataType: "string",
    sensitivityLevel: "public",
    resolverKey: "report.code",
    sampleValue: "[SAMPLE] HR_EMPLOYEE_LIST",
    isActive: true,
    isPlanned: false,
    sortOrder: 11,
  },
  {
    moduleCode: "REPORT",
    moduleLabel: "Report",
    entityCode: "report",
    entityLabel: "Report",
    fieldPath: "report.total_rows",
    fieldLabel: "Report Total Rows",
    dataType: "number",
    sensitivityLevel: "public",
    resolverKey: "report.total_rows",
    sampleValue: "[SAMPLE] 42",
    isActive: true,
    isPlanned: false,
    sortOrder: 12,
  },
  {
    moduleCode: "REPORT",
    moduleLabel: "Report",
    entityCode: "report",
    entityLabel: "Report",
    fieldPath: "report.generated_at",
    fieldLabel: "Report Generated At",
    dataType: "date",
    sensitivityLevel: "public",
    resolverKey: "report.generated_at",
    sampleValue: "[SAMPLE] 01 Jul 2026",
    isActive: true,
    isPlanned: false,
    sortOrder: 13,
  },

  // ════════════════════════════════════════════════════════════════════════
  // FUTURE MODULES — Planned placeholders (isActive: false, isPlanned: true)
  // These show as "Coming Soon" in the picker — not insertable.
  // When a module is implemented, set isActive: true and add resolver.
  // ════════════════════════════════════════════════════════════════════════

  {
    moduleCode: "FLEET",
    moduleLabel: "Fleet",
    entityCode: "vehicle",
    entityLabel: "Vehicle",
    fieldPath: "fleet.vehicle_number",
    fieldLabel: "Vehicle / Plate Number",
    dataType: "string",
    sensitivityLevel: "internal",
    resolverKey: "fleet.vehicle_number",
    sampleValue: "",
    isActive: false,
    isPlanned: true,
    sortOrder: 10,
    description: "Fleet module — not yet implemented.",
  },
  {
    moduleCode: "PROCUREMENT",
    moduleLabel: "Procurement",
    entityCode: "purchase_order",
    entityLabel: "Purchase Order",
    fieldPath: "procurement.po_number",
    fieldLabel: "Purchase Order Number",
    dataType: "string",
    sensitivityLevel: "internal",
    resolverKey: "procurement.po_number",
    sampleValue: "",
    isActive: false,
    isPlanned: true,
    sortOrder: 10,
    description: "Procurement module — not yet implemented.",
  },
  {
    moduleCode: "FINANCE",
    moduleLabel: "Finance",
    entityCode: "invoice",
    entityLabel: "Invoice",
    fieldPath: "finance.invoice_number",
    fieldLabel: "Invoice Number",
    dataType: "string",
    sensitivityLevel: "internal",
    resolverKey: "finance.invoice_number",
    sampleValue: "",
    isActive: false,
    isPlanned: true,
    sortOrder: 10,
    description: "Finance module — not yet implemented.",
  },
  {
    moduleCode: "INVENTORY",
    moduleLabel: "Inventory",
    entityCode: "item",
    entityLabel: "Item",
    fieldPath: "inventory.item_code",
    fieldLabel: "Item Code",
    dataType: "string",
    sensitivityLevel: "internal",
    resolverKey: "inventory.item_code",
    sampleValue: "",
    isActive: false,
    isPlanned: true,
    sortOrder: 10,
    description: "Inventory module — not yet implemented.",
  },
  {
    moduleCode: "TRANSPORT",
    moduleLabel: "Transport",
    entityCode: "trip",
    entityLabel: "Trip",
    fieldPath: "transport.trip_number",
    fieldLabel: "Trip Number",
    dataType: "string",
    sensitivityLevel: "internal",
    resolverKey: "transport.trip_number",
    sampleValue: "",
    isActive: false,
    isPlanned: true,
    sortOrder: 10,
    description: "Transport module — not yet implemented.",
  },
  {
    moduleCode: "HSE",
    moduleLabel: "HSE",
    entityCode: "incident",
    entityLabel: "Incident",
    fieldPath: "hse.incident_number",
    fieldLabel: "Incident Number",
    dataType: "string",
    sensitivityLevel: "internal",
    resolverKey: "hse.incident_number",
    sampleValue: "",
    isActive: false,
    isPlanned: true,
    sortOrder: 10,
    description: "HSE module — not yet implemented.",
  },
  {
    moduleCode: "WORKSHOP",
    moduleLabel: "Workshop",
    entityCode: "work_order",
    entityLabel: "Work Order",
    fieldPath: "workshop.work_order_number",
    fieldLabel: "Work Order Number",
    dataType: "string",
    sensitivityLevel: "internal",
    resolverKey: "workshop.work_order_number",
    sampleValue: "",
    isActive: false,
    isPlanned: true,
    sortOrder: 10,
    description: "Workshop module — not yet implemented.",
  },
  {
    moduleCode: "WEIGHBRIDGE",
    moduleLabel: "Weighbridge",
    entityCode: "ticket",
    entityLabel: "Ticket",
    fieldPath: "weighbridge.ticket_number",
    fieldLabel: "Ticket Number",
    dataType: "string",
    sensitivityLevel: "internal",
    resolverKey: "weighbridge.ticket_number",
    sampleValue: "",
    isActive: false,
    isPlanned: true,
    sortOrder: 10,
    description: "Weighbridge module — not yet implemented.",
  },
];
