-- ============================================================================
-- ERP BASE 002F.3C.2 — Finance Basics / Commercial Readiness
-- ============================================================================
-- Created: 2026-06-06
-- Purpose: Currencies, payment terms, tax types, banks, cost/profit centers
--          + lookup categories + permissions + RLS + seed data
-- ============================================================================

-- ============================================================================
-- TABLE: currencies
-- ============================================================================

create table if not exists public.currencies (
  id bigint generated by default as identity primary key,
  currency_code text not null unique,
  currency_name_en text not null,
  currency_name_ar text,
  symbol text,
  decimal_places integer not null default 2,
  is_base_currency boolean not null default false,
  description_en text,
  description_ar text,
  notes text,
  is_system boolean not null default false,
  is_locked boolean not null default false,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  created_by bigint references public.user_profiles(id),
  updated_at timestamptz not null default now(),
  updated_by bigint references public.user_profiles(id),
  deactivated_at timestamptz,
  deactivated_by bigint references public.user_profiles(id),
  deactivation_reason text,
  check (currency_code = upper(currency_code)),
  check (currency_code ~ '^[A-Z]{3}$'),
  check (decimal_places between 0 and 4),
  check (
    (is_active = true and deactivated_at is null) or
    (is_active = false and deactivated_at is not null)
  )
);

create unique index if not exists idx_currencies_single_base
  on public.currencies (is_base_currency)
  where is_base_currency = true;

create index if not exists idx_currencies_code on public.currencies(currency_code);
create index if not exists idx_currencies_active on public.currencies(is_active);
create index if not exists idx_currencies_sort on public.currencies(sort_order);

create trigger trigger_currencies_updated_at
  before update on public.currencies
  for each row execute function public.set_updated_at();

-- ============================================================================
-- TABLE: payment_terms
-- ============================================================================

create table if not exists public.payment_terms (
  id bigint generated by default as identity primary key,
  term_code text not null unique,
  term_name_en text not null,
  term_name_ar text,
  due_days integer not null default 0,
  advance_percentage numeric(5, 2) not null default 0,
  retention_percentage numeric(5, 2) not null default 0,
  calculation_notes text,
  description_en text,
  description_ar text,
  notes text,
  is_system boolean not null default false,
  is_locked boolean not null default false,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  created_by bigint references public.user_profiles(id),
  updated_at timestamptz not null default now(),
  updated_by bigint references public.user_profiles(id),
  deactivated_at timestamptz,
  deactivated_by bigint references public.user_profiles(id),
  deactivation_reason text,
  check (term_code = upper(term_code)),
  check (term_code ~ '^[A-Z0-9_]+$'),
  check (due_days >= 0),
  check (advance_percentage between 0 and 100),
  check (retention_percentage between 0 and 100),
  check (
    (is_active = true and deactivated_at is null) or
    (is_active = false and deactivated_at is not null)
  )
);

create index if not exists idx_payment_terms_code on public.payment_terms(term_code);
create index if not exists idx_payment_terms_active on public.payment_terms(is_active);
create index if not exists idx_payment_terms_sort on public.payment_terms(sort_order);

create trigger trigger_payment_terms_updated_at
  before update on public.payment_terms
  for each row execute function public.set_updated_at();

-- ============================================================================
-- TABLE: tax_types
-- ============================================================================

create table if not exists public.tax_types (
  id bigint generated by default as identity primary key,
  tax_code text not null unique,
  tax_name_en text not null,
  tax_name_ar text,
  tax_rate numeric(7, 4) not null default 0,
  tax_treatment_code text not null,
  is_vat boolean not null default false,
  is_reverse_charge boolean not null default false,
  applies_to_sales boolean not null default true,
  applies_to_purchases boolean not null default true,
  applies_to_scrap boolean not null default false,
  effective_from date not null default '2018-01-01',
  effective_to date,
  description_en text,
  description_ar text,
  notes text,
  is_system boolean not null default false,
  is_locked boolean not null default false,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  created_by bigint references public.user_profiles(id),
  updated_at timestamptz not null default now(),
  updated_by bigint references public.user_profiles(id),
  deactivated_at timestamptz,
  deactivated_by bigint references public.user_profiles(id),
  deactivation_reason text,
  check (tax_code = upper(tax_code)),
  check (tax_code ~ '^[A-Z0-9_]+$'),
  check (tax_rate >= 0 and tax_rate <= 100),
  check (effective_to is null or effective_to >= effective_from),
  check (
    (is_active = true and deactivated_at is null) or
    (is_active = false and deactivated_at is not null)
  )
);

create index if not exists idx_tax_types_code on public.tax_types(tax_code);
create index if not exists idx_tax_types_treatment on public.tax_types(tax_treatment_code);
create index if not exists idx_tax_types_active on public.tax_types(is_active);

create trigger trigger_tax_types_updated_at
  before update on public.tax_types
  for each row execute function public.set_updated_at();

-- ============================================================================
-- TABLE: banks
-- ============================================================================

create table if not exists public.banks (
  id bigint generated by default as identity primary key,
  bank_code text not null unique,
  bank_name_en text not null,
  bank_name_ar text,
  short_name text,
  country_id bigint references public.countries(id),
  bank_type_code text,
  swift_code text,
  website_url text,
  contact_phone text,
  contact_email text,
  description_en text,
  description_ar text,
  notes text,
  is_system boolean not null default false,
  is_locked boolean not null default false,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  created_by bigint references public.user_profiles(id),
  updated_at timestamptz not null default now(),
  updated_by bigint references public.user_profiles(id),
  deactivated_at timestamptz,
  deactivated_by bigint references public.user_profiles(id),
  deactivation_reason text,
  check (bank_code = upper(bank_code)),
  check (bank_code ~ '^[A-Z0-9_]+$'),
  check (
    (is_active = true and deactivated_at is null) or
    (is_active = false and deactivated_at is not null)
  )
);

create index if not exists idx_banks_code on public.banks(bank_code);
create index if not exists idx_banks_country on public.banks(country_id);
create index if not exists idx_banks_active on public.banks(is_active);

create trigger trigger_banks_updated_at
  before update on public.banks
  for each row execute function public.set_updated_at();

-- ============================================================================
-- TABLE: cost_centers
-- ============================================================================

create table if not exists public.cost_centers (
  id bigint generated by default as identity primary key,
  cost_center_code text not null,
  cost_center_name_en text not null,
  cost_center_name_ar text,
  cost_center_type_code text,
  parent_cost_center_id bigint references public.cost_centers(id),
  owner_company_id bigint references public.owner_companies(id),
  branch_id bigint references public.branches(id),
  description_en text,
  description_ar text,
  notes text,
  is_system boolean not null default false,
  is_locked boolean not null default false,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  created_by bigint references public.user_profiles(id),
  updated_at timestamptz not null default now(),
  updated_by bigint references public.user_profiles(id),
  deactivated_at timestamptz,
  deactivated_by bigint references public.user_profiles(id),
  deactivation_reason text,
  check (cost_center_code = upper(cost_center_code)),
  check (cost_center_code ~ '^[A-Z0-9_\-]+$'),
  check (parent_cost_center_id is null or parent_cost_center_id <> id),
  check (
    (is_active = true and deactivated_at is null) or
    (is_active = false and deactivated_at is not null)
  )
);

create unique index if not exists idx_cost_centers_code_company
  on public.cost_centers(cost_center_code, owner_company_id)
  where owner_company_id is not null;

create unique index if not exists idx_cost_centers_code_global
  on public.cost_centers(cost_center_code)
  where owner_company_id is null;

create index if not exists idx_cost_centers_parent on public.cost_centers(parent_cost_center_id);
create index if not exists idx_cost_centers_company on public.cost_centers(owner_company_id);
create index if not exists idx_cost_centers_active on public.cost_centers(is_active);

create trigger trigger_cost_centers_updated_at
  before update on public.cost_centers
  for each row execute function public.set_updated_at();

-- ============================================================================
-- TABLE: profit_centers
-- ============================================================================

create table if not exists public.profit_centers (
  id bigint generated by default as identity primary key,
  profit_center_code text not null,
  profit_center_name_en text not null,
  profit_center_name_ar text,
  profit_center_type_code text,
  parent_profit_center_id bigint references public.profit_centers(id),
  owner_company_id bigint references public.owner_companies(id),
  branch_id bigint references public.branches(id),
  description_en text,
  description_ar text,
  notes text,
  is_system boolean not null default false,
  is_locked boolean not null default false,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  created_by bigint references public.user_profiles(id),
  updated_at timestamptz not null default now(),
  updated_by bigint references public.user_profiles(id),
  deactivated_at timestamptz,
  deactivated_by bigint references public.user_profiles(id),
  deactivation_reason text,
  check (profit_center_code = upper(profit_center_code)),
  check (profit_center_code ~ '^[A-Z0-9_\-]+$'),
  check (parent_profit_center_id is null or parent_profit_center_id <> id),
  check (
    (is_active = true and deactivated_at is null) or
    (is_active = false and deactivated_at is not null)
  )
);

create unique index if not exists idx_profit_centers_code_company
  on public.profit_centers(profit_center_code, owner_company_id)
  where owner_company_id is not null;

create unique index if not exists idx_profit_centers_code_global
  on public.profit_centers(profit_center_code)
  where owner_company_id is null;

create index if not exists idx_profit_centers_parent on public.profit_centers(parent_profit_center_id);
create index if not exists idx_profit_centers_company on public.profit_centers(owner_company_id);
create index if not exists idx_profit_centers_active on public.profit_centers(is_active);

create trigger trigger_profit_centers_updated_at
  before update on public.profit_centers
  for each row execute function public.set_updated_at();

-- ============================================================================
-- PERMISSIONS
-- ============================================================================

insert into public.permissions (permission_code, permission_name, module_code, action_code, description, is_active)
values
  ('master_data.finance_basics.view', 'View Finance Basics', 'master_data', 'view', 'View currencies, payment terms, tax types, banks, cost/profit centers', true),
  ('master_data.finance_basics.manage', 'Manage Finance Basics', 'master_data', 'manage', 'Create, update, activate/deactivate finance basics master data', true),
  ('master_data.finance_basics.export', 'Export Finance Basics', 'master_data', 'export', 'Export finance basics master data', true),
  ('master_data.finance_basics.audit_view', 'View Finance Basics Audit Logs', 'master_data', 'audit_view', 'View audit logs for finance basics changes', true)
on conflict (permission_code) do nothing;

-- ============================================================================
-- ROLE ASSIGNMENTS
-- ============================================================================

do $$
declare
  v_system_admin_role_id bigint;
  v_group_admin_role_id bigint;
  v_company_admin_role_id bigint;
  v_branch_admin_role_id bigint;
begin
  select id into v_system_admin_role_id from public.roles where role_code = 'system_admin' limit 1;
  select id into v_group_admin_role_id from public.roles where role_code = 'group_admin' limit 1;
  select id into v_company_admin_role_id from public.roles where role_code = 'company_admin' limit 1;
  select id into v_branch_admin_role_id from public.roles where role_code = 'branch_admin' limit 1;

  if v_system_admin_role_id is not null then
    insert into public.role_permissions (role_id, permission_id)
    select v_system_admin_role_id, id from public.permissions
    where permission_code in (
      'master_data.finance_basics.view',
      'master_data.finance_basics.manage',
      'master_data.finance_basics.export',
      'master_data.finance_basics.audit_view'
    )
    on conflict (role_id, permission_id) do nothing;
  end if;

  if v_group_admin_role_id is not null then
    insert into public.role_permissions (role_id, permission_id)
    select v_group_admin_role_id, id from public.permissions
    where permission_code in (
      'master_data.finance_basics.view',
      'master_data.finance_basics.manage',
      'master_data.finance_basics.export',
      'master_data.finance_basics.audit_view'
    )
    on conflict (role_id, permission_id) do nothing;
  end if;

  if v_company_admin_role_id is not null then
    insert into public.role_permissions (role_id, permission_id)
    select v_company_admin_role_id, id from public.permissions
    where permission_code in (
      'master_data.finance_basics.view',
      'master_data.finance_basics.export'
    )
    on conflict (role_id, permission_id) do nothing;
  end if;

  if v_branch_admin_role_id is not null then
    insert into public.role_permissions (role_id, permission_id)
    select v_branch_admin_role_id, id from public.permissions
    where permission_code in (
      'master_data.finance_basics.view'
    )
    on conflict (role_id, permission_id) do nothing;
  end if;
end $$;

-- ============================================================================
-- RLS POLICIES
-- ============================================================================

alter table public.currencies enable row level security;
alter table public.payment_terms enable row level security;
alter table public.tax_types enable row level security;
alter table public.banks enable row level security;
alter table public.cost_centers enable row level security;
alter table public.profit_centers enable row level security;

-- CURRENCIES
create policy select_currencies_authenticated on public.currencies for select
  using (is_active = true or public.current_user_has_permission('master_data.finance_basics.view'));
create policy insert_currencies on public.currencies for insert
  with check (public.current_user_has_permission('master_data.finance_basics.manage'));
create policy update_currencies on public.currencies for update
  using (
    public.current_user_has_permission('master_data.finance_basics.manage')
    and (not is_locked or public.current_user_has_role('system_admin'))
  );
create policy delete_currencies on public.currencies for delete
  using (
    exists (
      select 1 from public.user_roles ur
      join public.roles r on r.id = ur.role_id
      where ur.user_profile_id = public.current_user_profile_id()
        and r.role_code = 'system_admin' and ur.is_active = true
    )
  );

-- PAYMENT_TERMS
create policy select_payment_terms_authenticated on public.payment_terms for select
  using (is_active = true or public.current_user_has_permission('master_data.finance_basics.view'));
create policy insert_payment_terms on public.payment_terms for insert
  with check (public.current_user_has_permission('master_data.finance_basics.manage'));
create policy update_payment_terms on public.payment_terms for update
  using (
    public.current_user_has_permission('master_data.finance_basics.manage')
    and (not is_locked or public.current_user_has_role('system_admin'))
  );
create policy delete_payment_terms on public.payment_terms for delete
  using (
    exists (
      select 1 from public.user_roles ur join public.roles r on r.id = ur.role_id
      where ur.user_profile_id = public.current_user_profile_id()
        and r.role_code = 'system_admin' and ur.is_active = true
    )
  );

-- TAX_TYPES
create policy select_tax_types_authenticated on public.tax_types for select
  using (is_active = true or public.current_user_has_permission('master_data.finance_basics.view'));
create policy insert_tax_types on public.tax_types for insert
  with check (public.current_user_has_permission('master_data.finance_basics.manage'));
create policy update_tax_types on public.tax_types for update
  using (
    public.current_user_has_permission('master_data.finance_basics.manage')
    and (not is_locked or public.current_user_has_role('system_admin'))
  );
create policy delete_tax_types on public.tax_types for delete
  using (
    exists (
      select 1 from public.user_roles ur join public.roles r on r.id = ur.role_id
      where ur.user_profile_id = public.current_user_profile_id()
        and r.role_code = 'system_admin' and ur.is_active = true
    )
  );

-- BANKS
create policy select_banks_authenticated on public.banks for select
  using (is_active = true or public.current_user_has_permission('master_data.finance_basics.view'));
create policy insert_banks on public.banks for insert
  with check (public.current_user_has_permission('master_data.finance_basics.manage'));
create policy update_banks on public.banks for update
  using (
    public.current_user_has_permission('master_data.finance_basics.manage')
    and (not is_locked or public.current_user_has_role('system_admin'))
  );
create policy delete_banks on public.banks for delete
  using (
    exists (
      select 1 from public.user_roles ur join public.roles r on r.id = ur.role_id
      where ur.user_profile_id = public.current_user_profile_id()
        and r.role_code = 'system_admin' and ur.is_active = true
    )
  );

-- COST_CENTERS
create policy select_cost_centers_authenticated on public.cost_centers for select
  using (is_active = true or public.current_user_has_permission('master_data.finance_basics.view'));
create policy insert_cost_centers on public.cost_centers for insert
  with check (public.current_user_has_permission('master_data.finance_basics.manage'));
create policy update_cost_centers on public.cost_centers for update
  using (
    public.current_user_has_permission('master_data.finance_basics.manage')
    and (not is_locked or public.current_user_has_role('system_admin'))
  );
create policy delete_cost_centers on public.cost_centers for delete
  using (
    exists (
      select 1 from public.user_roles ur join public.roles r on r.id = ur.role_id
      where ur.user_profile_id = public.current_user_profile_id()
        and r.role_code = 'system_admin' and ur.is_active = true
    )
  );

-- PROFIT_CENTERS
create policy select_profit_centers_authenticated on public.profit_centers for select
  using (is_active = true or public.current_user_has_permission('master_data.finance_basics.view'));
create policy insert_profit_centers on public.profit_centers for insert
  with check (public.current_user_has_permission('master_data.finance_basics.manage'));
create policy update_profit_centers on public.profit_centers for update
  using (
    public.current_user_has_permission('master_data.finance_basics.manage')
    and (not is_locked or public.current_user_has_role('system_admin'))
  );
create policy delete_profit_centers on public.profit_centers for delete
  using (
    exists (
      select 1 from public.user_roles ur join public.roles r on r.id = ur.role_id
      where ur.user_profile_id = public.current_user_profile_id()
        and r.role_code = 'system_admin' and ur.is_active = true
    )
  );

-- ============================================================================
-- LOOKUP CATEGORIES AND VALUES
-- ============================================================================

do $$
declare
  v_user_id bigint;
  v_cat_id bigint;
begin
  select id into v_user_id from public.user_profiles where auth_user_id = auth.uid() limit 1;

  -- PAYMENT_METHODS
  insert into public.global_lookup_categories (
    category_code, category_name_en, category_name_ar, description, module_code,
    category_scope, supports_hierarchy, supports_color, supports_icon,
    supports_effective_dates, supports_metadata, is_system, is_locked, is_active, sort_order, created_by
  ) values (
    'PAYMENT_METHODS', 'Payment Methods', 'طرق الدفع',
    'Payment method options for commercial documents', 'MASTER_DATA', 'GLOBAL',
    false, false, false, false, true, true, true, true, 200, v_user_id
  ) on conflict (category_code) do nothing;

  select id into v_cat_id from public.global_lookup_categories where category_code = 'PAYMENT_METHODS' limit 1;
  if v_cat_id is not null then
    insert into public.global_lookup_values (category_id, value_code, value_label_en, value_label_ar, sort_order, is_system, is_locked, is_default, created_by)
    values
      (v_cat_id, 'CASH', 'Cash', 'نقد', 10, true, true, false, v_user_id),
      (v_cat_id, 'BANK_TRANSFER', 'Bank Transfer', 'تحويل بنكي', 20, true, true, false, v_user_id),
      (v_cat_id, 'CHEQUE', 'Cheque', 'شيك', 30, true, true, false, v_user_id),
      (v_cat_id, 'LETTER_OF_CREDIT', 'Letter of Credit', 'اعتماد مستندي', 40, true, true, false, v_user_id),
      (v_cat_id, 'CREDIT_CARD', 'Credit Card', 'بطاقة ائتمان', 50, false, false, false, v_user_id),
      (v_cat_id, 'DEBIT_CARD', 'Debit Card', 'بطاقة خصم', 60, false, false, false, v_user_id),
      (v_cat_id, 'ONLINE_PAYMENT', 'Online Payment', 'دفع إلكتروني', 70, false, false, false, v_user_id)
    on conflict (category_id, value_code) do nothing;
  end if;

  -- TAX_TREATMENT_TYPES
  insert into public.global_lookup_categories (
    category_code, category_name_en, category_name_ar, description, module_code,
    category_scope, supports_hierarchy, supports_color, supports_icon,
    supports_effective_dates, supports_metadata, is_system, is_locked, is_active, sort_order, created_by
  ) values (
    'TAX_TREATMENT_TYPES', 'Tax Treatment Types', 'أنواع المعاملة الضريبية',
    'VAT/tax treatment classification', 'MASTER_DATA', 'GLOBAL',
    false, false, false, false, true, true, true, true, 210, v_user_id
  ) on conflict (category_code) do nothing;

  select id into v_cat_id from public.global_lookup_categories where category_code = 'TAX_TREATMENT_TYPES' limit 1;
  if v_cat_id is not null then
    insert into public.global_lookup_values (category_id, value_code, value_label_en, value_label_ar, sort_order, is_system, is_locked, is_default, created_by)
    values
      (v_cat_id, 'STANDARD', 'Standard Rated', 'خاضع للضريبة', 10, true, true, false, v_user_id),
      (v_cat_id, 'ZERO_RATED', 'Zero Rated', 'نسبة صفر', 20, true, true, false, v_user_id),
      (v_cat_id, 'EXEMPT', 'Exempt', 'معفى', 30, true, true, false, v_user_id),
      (v_cat_id, 'OUT_OF_SCOPE', 'Out of Scope', 'خارج النطاق', 40, true, true, false, v_user_id),
      (v_cat_id, 'REVERSE_CHARGE', 'Reverse Charge', 'رسوم عكسية', 50, true, true, false, v_user_id)
    on conflict (category_id, value_code) do nothing;
  end if;

  -- BANK_ACCOUNT_TYPES
  insert into public.global_lookup_categories (
    category_code, category_name_en, category_name_ar, description, module_code,
    category_scope, supports_hierarchy, supports_color, supports_icon,
    supports_effective_dates, supports_metadata, is_system, is_locked, is_active, sort_order, created_by
  ) values (
    'BANK_ACCOUNT_TYPES', 'Bank Account Types', 'أنواع الحسابات البنكية',
    'Bank account type classification', 'MASTER_DATA', 'GLOBAL',
    false, false, false, false, true, true, true, true, 220, v_user_id
  ) on conflict (category_code) do nothing;

  select id into v_cat_id from public.global_lookup_categories where category_code = 'BANK_ACCOUNT_TYPES' limit 1;
  if v_cat_id is not null then
    insert into public.global_lookup_values (category_id, value_code, value_label_en, value_label_ar, sort_order, is_system, is_locked, is_default, created_by)
    values
      (v_cat_id, 'CURRENT', 'Current Account', 'حساب جاري', 10, true, true, false, v_user_id),
      (v_cat_id, 'SAVINGS', 'Savings Account', 'حساب توفير', 20, true, true, false, v_user_id),
      (v_cat_id, 'ESCROW', 'Escrow Account', 'حساب ضمان', 30, true, true, false, v_user_id),
      (v_cat_id, 'CALL', 'Call Account', 'حساب اتصال', 40, false, false, false, v_user_id)
    on conflict (category_id, value_code) do nothing;
  end if;

  -- BANK_TYPES
  insert into public.global_lookup_categories (
    category_code, category_name_en, category_name_ar, description, module_code,
    category_scope, supports_hierarchy, supports_color, supports_icon,
    supports_effective_dates, supports_metadata, is_system, is_locked, is_active, sort_order, created_by
  ) values (
    'BANK_TYPES', 'Bank Types', 'أنواع البنوك',
    'Bank institution type', 'MASTER_DATA', 'GLOBAL',
    false, false, false, false, true, true, true, true, 230, v_user_id
  ) on conflict (category_code) do nothing;

  select id into v_cat_id from public.global_lookup_categories where category_code = 'BANK_TYPES' limit 1;
  if v_cat_id is not null then
    insert into public.global_lookup_values (category_id, value_code, value_label_en, value_label_ar, sort_order, is_system, is_locked, is_default, created_by)
    values
      (v_cat_id, 'COMMERCIAL', 'Commercial Bank', 'بنك تجاري', 10, true, true, false, v_user_id),
      (v_cat_id, 'ISLAMIC', 'Islamic Bank', 'بنك إسلامي', 20, true, true, false, v_user_id),
      (v_cat_id, 'CENTRAL', 'Central Bank', 'بنك مركزي', 30, true, true, false, v_user_id),
      (v_cat_id, 'CORRESPONDENT', 'Correspondent Bank', 'بنك مراسل', 40, false, false, false, v_user_id)
    on conflict (category_id, value_code) do nothing;
  end if;

  -- COST_CENTER_TYPES
  insert into public.global_lookup_categories (
    category_code, category_name_en, category_name_ar, description, module_code,
    category_scope, supports_hierarchy, supports_color, supports_icon,
    supports_effective_dates, supports_metadata, is_system, is_locked, is_active, sort_order, created_by
  ) values (
    'COST_CENTER_TYPES', 'Cost Center Types', 'أنواع مراكز التكلفة',
    'Cost center classification', 'MASTER_DATA', 'GLOBAL',
    false, false, false, false, true, true, true, true, 240, v_user_id
  ) on conflict (category_code) do nothing;

  select id into v_cat_id from public.global_lookup_categories where category_code = 'COST_CENTER_TYPES' limit 1;
  if v_cat_id is not null then
    insert into public.global_lookup_values (category_id, value_code, value_label_en, value_label_ar, sort_order, is_system, is_locked, is_default, created_by)
    values
      (v_cat_id, 'DEPARTMENT', 'Department', 'قسم', 10, true, true, false, v_user_id),
      (v_cat_id, 'PROJECT', 'Project', 'مشروع', 20, true, true, false, v_user_id),
      (v_cat_id, 'WAREHOUSE', 'Warehouse', 'مستودع', 30, true, true, false, v_user_id),
      (v_cat_id, 'PRODUCTION', 'Production Line', 'خط إنتاج', 40, false, false, false, v_user_id),
      (v_cat_id, 'ADMIN', 'Administration', 'إدارة', 50, true, true, false, v_user_id)
    on conflict (category_id, value_code) do nothing;
  end if;

  -- PROFIT_CENTER_TYPES
  insert into public.global_lookup_categories (
    category_code, category_name_en, category_name_ar, description, module_code,
    category_scope, supports_hierarchy, supports_color, supports_icon,
    supports_effective_dates, supports_metadata, is_system, is_locked, is_active, sort_order, created_by
  ) values (
    'PROFIT_CENTER_TYPES', 'Profit Center Types', 'أنواع مراكز الربح',
    'Profit center classification', 'MASTER_DATA', 'GLOBAL',
    false, false, false, false, true, true, true, true, 250, v_user_id
  ) on conflict (category_code) do nothing;

  select id into v_cat_id from public.global_lookup_categories where category_code = 'PROFIT_CENTER_TYPES' limit 1;
  if v_cat_id is not null then
    insert into public.global_lookup_values (category_id, value_code, value_label_en, value_label_ar, sort_order, is_system, is_locked, is_default, created_by)
    values
      (v_cat_id, 'BUSINESS_UNIT', 'Business Unit', 'وحدة أعمال', 10, true, true, false, v_user_id),
      (v_cat_id, 'PRODUCT_LINE', 'Product Line', 'خط منتج', 20, true, true, false, v_user_id),
      (v_cat_id, 'REGION', 'Region', 'منطقة', 30, true, true, false, v_user_id),
      (v_cat_id, 'DIVISION', 'Division', 'شعبة', 40, false, false, false, v_user_id)
    on conflict (category_id, value_code) do nothing;
  end if;
end $$;

-- ============================================================================
-- SEED DATA: currencies, payment_terms, tax_types, banks
-- ============================================================================

do $$
declare
  v_user_id bigint;
  v_ae_country_id bigint;
begin
  select id into v_user_id from public.user_profiles limit 1;
  select id into v_ae_country_id from public.countries where country_code = 'AE' limit 1;

  insert into public.currencies (
    currency_code, currency_name_en, currency_name_ar, symbol, decimal_places,
    is_base_currency, is_system, is_locked, is_active, sort_order, created_by, updated_by
  ) values
    ('AED', 'UAE Dirham', 'درهم إماراتي', 'د.إ', 2, true, true, true, true, 10, v_user_id, v_user_id),
    ('USD', 'US Dollar', 'دولار أمريكي', '$', 2, false, true, false, true, 20, v_user_id, v_user_id),
    ('EUR', 'Euro', 'يورو', '€', 2, false, true, false, true, 30, v_user_id, v_user_id),
    ('GBP', 'British Pound', 'جنيه إسترليني', '£', 2, false, false, false, true, 40, v_user_id, v_user_id),
    ('SAR', 'Saudi Riyal', 'ريال سعودي', '﷼', 2, false, true, false, true, 50, v_user_id, v_user_id),
    ('QAR', 'Qatari Riyal', 'ريال قطري', '﷼', 2, false, false, false, true, 60, v_user_id, v_user_id),
    ('OMR', 'Omani Rial', 'ريال عماني', '﷼', 3, false, false, false, true, 70, v_user_id, v_user_id),
    ('BHD', 'Bahraini Dinar', 'دينار بحريني', '.د.ب', 3, false, false, false, true, 80, v_user_id, v_user_id),
    ('KWD', 'Kuwaiti Dinar', 'دينار كويتي', 'د.ك', 3, false, false, false, true, 90, v_user_id, v_user_id),
    ('INR', 'Indian Rupee', 'روبية هندية', '₹', 2, false, false, false, true, 100, v_user_id, v_user_id)
  on conflict (currency_code) do nothing;

  insert into public.payment_terms (
    term_code, term_name_en, due_days, advance_percentage, retention_percentage,
    is_system, is_locked, is_active, sort_order, created_by, updated_by
  ) values
    ('IMMEDIATE', 'Immediate Payment', 0, 0, 0, true, true, true, 10, v_user_id, v_user_id),
    ('NET_15', 'Net 15 Days', 15, 0, 0, true, true, true, 20, v_user_id, v_user_id),
    ('NET_30', 'Net 30 Days', 30, 0, 0, true, true, true, 30, v_user_id, v_user_id),
    ('NET_60', 'Net 60 Days', 60, 0, 0, true, true, true, 40, v_user_id, v_user_id),
    ('ADVANCE_50_BALANCE_30', '50% Advance, Balance Net 30', 30, 50, 0, true, true, true, 50, v_user_id, v_user_id),
    ('ADVANCE_30_RETENTION_10', '30% Advance, 10% Retention', 30, 30, 10, false, false, true, 60, v_user_id, v_user_id),
    ('COD', 'Cash on Delivery', 0, 100, 0, true, true, true, 70, v_user_id, v_user_id)
  on conflict (term_code) do nothing;

  insert into public.tax_types (
    tax_code, tax_name_en, tax_rate, tax_treatment_code,
    is_vat, is_reverse_charge, applies_to_sales, applies_to_purchases, applies_to_scrap,
    effective_from, is_system, is_locked, is_active, sort_order, created_by, updated_by
  ) values
    ('VAT_5', 'UAE VAT 5%', 5.0000, 'STANDARD', true, false, true, true, false, '2018-01-01', true, true, true, 10, v_user_id, v_user_id),
    ('VAT_ZERO', 'Zero Rated Supply', 0.0000, 'ZERO_RATED', true, false, true, true, false, '2018-01-01', true, true, true, 20, v_user_id, v_user_id),
    ('VAT_EXEMPT', 'Exempt Supply', 0.0000, 'EXEMPT', true, false, true, true, false, '2018-01-01', true, true, true, 30, v_user_id, v_user_id),
    ('VAT_OUT_OF_SCOPE', 'Out of Scope', 0.0000, 'OUT_OF_SCOPE', false, false, true, true, false, '2018-01-01', true, true, true, 40, v_user_id, v_user_id),
    ('RCM_SCRAP', 'Reverse Charge — Scrap Metal', 5.0000, 'REVERSE_CHARGE', true, true, false, true, true, '2018-01-01', true, true, true, 50, v_user_id, v_user_id)
  on conflict (tax_code) do nothing;

  if v_ae_country_id is not null then
    insert into public.banks (
      bank_code, bank_name_en, short_name, country_id, bank_type_code,
      is_system, is_locked, is_active, sort_order, created_by, updated_by
    ) values
      ('FAB', 'First Abu Dhabi Bank', 'FAB', v_ae_country_id, 'COMMERCIAL', true, true, true, 10, v_user_id, v_user_id),
      ('ENBD', 'Emirates NBD', 'ENBD', v_ae_country_id, 'COMMERCIAL', true, true, true, 20, v_user_id, v_user_id),
      ('ADCB', 'Abu Dhabi Commercial Bank', 'ADCB', v_ae_country_id, 'COMMERCIAL', true, true, true, 30, v_user_id, v_user_id),
      ('DIB', 'Dubai Islamic Bank', 'DIB', v_ae_country_id, 'ISLAMIC', true, true, true, 40, v_user_id, v_user_id),
      ('MASHREQ', 'Mashreq Bank', 'Mashreq', v_ae_country_id, 'COMMERCIAL', true, true, true, 50, v_user_id, v_user_id)
    on conflict (bank_code) do nothing;
  end if;
end $$;

-- ============================================================================
-- END OF MIGRATION
-- ============================================================================
