-- ============================================================================
-- ERP BASE 002F.3C.3 — Units & Measurements
-- ============================================================================
-- Created: 2026-06-07
-- Purpose: UOM categories, units of measure, conversions
--          + permissions + RLS + seed data
-- ============================================================================

-- ============================================================================
-- TABLE: uom_categories
-- ============================================================================

create table if not exists public.uom_categories (
  id bigint generated by default as identity primary key,
  
  category_code text not null unique,
  category_name_en text not null,
  category_name_ar text,
  
  description_en text,
  description_ar text,
  notes text,
  
  is_system boolean not null default false,
  is_locked boolean not null default false,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  
  created_at timestamptz not null default now(),
  created_by bigint references public.user_profiles(id),
  updated_at timestamptz not null default now(),
  updated_by bigint references public.user_profiles(id),
  deactivated_at timestamptz,
  deactivated_by bigint references public.user_profiles(id),
  deactivation_reason text,
  
  check (category_code = upper(category_code)),
  check (category_code ~ '^[A-Z_]+$'),
  check (
    (is_active = true and deactivated_at is null) or
    (is_active = false and deactivated_at is not null)
  )
);

create index if not exists idx_uom_categories_code on public.uom_categories(category_code);
create index if not exists idx_uom_categories_active on public.uom_categories(is_active);
create index if not exists idx_uom_categories_sort on public.uom_categories(sort_order);

create trigger trigger_uom_categories_updated_at
  before update on public.uom_categories
  for each row execute function public.set_updated_at();

comment on table public.uom_categories is 'Unit of Measure categories (WEIGHT, LENGTH, VOLUME, FUEL, AREA, TIME, COUNT, PACKAGING)';

-- ============================================================================
-- TABLE: units_of_measure
-- ============================================================================

create table if not exists public.units_of_measure (
  id bigint generated by default as identity primary key,
  
  uom_category_id bigint not null references public.uom_categories(id) on delete restrict,
  
  unit_code text not null,
  unit_name_en text not null,
  unit_name_ar text,
  symbol text,
  
  conversion_factor_to_base numeric(20, 10) not null default 1,
  is_base_unit boolean not null default false,
  
  decimal_places integer not null default 2,
  allow_fraction boolean not null default true,
  
  description_en text,
  description_ar text,
  notes text,
  
  is_system boolean not null default false,
  is_locked boolean not null default false,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  
  created_at timestamptz not null default now(),
  created_by bigint references public.user_profiles(id),
  updated_at timestamptz not null default now(),
  updated_by bigint references public.user_profiles(id),
  deactivated_at timestamptz,
  deactivated_by bigint references public.user_profiles(id),
  deactivation_reason text,
  
  unique (uom_category_id, unit_code),
  check (unit_code = upper(unit_code)),
  check (unit_code ~ '^[A-Z0-9_]+$'),
  check (conversion_factor_to_base > 0),
  check (decimal_places between 0 and 6),
  check (
    (is_active = true and deactivated_at is null) or
    (is_active = false and deactivated_at is not null)
  )
);

create unique index if not exists idx_units_one_base_per_category
  on public.units_of_measure (uom_category_id)
  where is_base_unit = true;

create index if not exists idx_units_category on public.units_of_measure(uom_category_id);
create index if not exists idx_units_code on public.units_of_measure(unit_code);
create index if not exists idx_units_active on public.units_of_measure(is_active);
create index if not exists idx_units_base on public.units_of_measure(is_base_unit);

create trigger trigger_units_of_measure_updated_at
  before update on public.units_of_measure
  for each row execute function public.set_updated_at();

comment on table public.units_of_measure is 'Individual units of measure within categories. Conversion factor relative to base unit.';
comment on column public.units_of_measure.conversion_factor_to_base is 'Factor to convert this unit to the category base unit. Base unit has factor = 1.';

-- ============================================================================
-- TABLE: uom_conversions
-- ============================================================================

create table if not exists public.uom_conversions (
  id bigint generated by default as identity primary key,
  
  from_uom_id bigint not null references public.units_of_measure(id) on delete restrict,
  to_uom_id bigint not null references public.units_of_measure(id) on delete restrict,
  
  conversion_factor numeric(20, 10) not null,
  conversion_formula_code text,
  is_bidirectional boolean not null default false,
  
  notes text,
  
  is_system boolean not null default false,
  is_locked boolean not null default false,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  
  created_at timestamptz not null default now(),
  created_by bigint references public.user_profiles(id),
  updated_at timestamptz not null default now(),
  updated_by bigint references public.user_profiles(id),
  deactivated_at timestamptz,
  deactivated_by bigint references public.user_profiles(id),
  deactivation_reason text,
  
  unique (from_uom_id, to_uom_id),
  check (from_uom_id <> to_uom_id),
  check (conversion_factor > 0),
  check (
    (is_active = true and deactivated_at is null) or
    (is_active = false and deactivated_at is not null)
  )
);

create index if not exists idx_uom_conversions_from on public.uom_conversions(from_uom_id);
create index if not exists idx_uom_conversions_to on public.uom_conversions(to_uom_id);
create index if not exists idx_uom_conversions_active on public.uom_conversions(is_active);

create trigger trigger_uom_conversions_updated_at
  before update on public.uom_conversions
  for each row execute function public.set_updated_at();

comment on table public.uom_conversions is 'Reserved for special, cross-category, legacy exception, or item-specific conversions. Normal same-category conversion uses units_of_measure.conversion_factor_to_base.';

-- ============================================================================
-- PERMISSIONS
-- ============================================================================

insert into public.permissions (permission_code, permission_name, module_code, action_code, description)
values
  ('master_data.uom.view', 'View UOM Master Data', 'master_data', 'view', 'View UOM categories, units, and conversions'),
  ('master_data.uom.manage', 'Manage UOM Master Data', 'master_data', 'manage', 'Create, update, lock/unlock UOM master data'),
  ('master_data.uom.export', 'Export UOM Master Data', 'master_data', 'export', 'Export UOM data to Excel/CSV'),
  ('master_data.uom.audit_view', 'View UOM Audit Logs', 'master_data', 'audit_view', 'View audit trail for UOM changes')
on conflict (permission_code) do nothing;

-- ============================================================================
-- ROLE PERMISSIONS
-- ============================================================================

-- system_admin: all permissions
insert into public.role_permissions (role_id, permission_id)
select r.id, p.id
from public.roles r
cross join public.permissions p
where r.role_code = 'system_admin'
  and p.permission_code like 'master_data.uom.%'
on conflict (role_id, permission_id) do nothing;

-- group_admin: view, manage, export, audit_view
insert into public.role_permissions (role_id, permission_id)
select r.id, p.id
from public.roles r
cross join public.permissions p
where r.role_code = 'group_admin'
  and p.permission_code in (
    'master_data.uom.view',
    'master_data.uom.manage',
    'master_data.uom.export',
    'master_data.uom.audit_view'
  )
on conflict (role_id, permission_id) do nothing;

-- company_admin: view, export
insert into public.role_permissions (role_id, permission_id)
select r.id, p.id
from public.roles r
cross join public.permissions p
where r.role_code = 'company_admin'
  and p.permission_code in (
    'master_data.uom.view',
    'master_data.uom.export'
  )
on conflict (role_id, permission_id) do nothing;

-- branch_admin: view only
insert into public.role_permissions (role_id, permission_id)
select r.id, p.id
from public.roles r
cross join public.permissions p
where r.role_code = 'branch_admin'
  and p.permission_code = 'master_data.uom.view'
on conflict (role_id, permission_id) do nothing;

-- ============================================================================
-- RLS POLICIES
-- ============================================================================

alter table public.uom_categories enable row level security;
alter table public.units_of_measure enable row level security;
alter table public.uom_conversions enable row level security;

-- UOM CATEGORIES
create policy select_uom_categories_authenticated on public.uom_categories for select
  using (is_active = true or public.current_user_has_permission('master_data.uom.view'));

create policy insert_uom_categories on public.uom_categories for insert
  with check (public.current_user_has_permission('master_data.uom.manage'));

create policy update_uom_categories on public.uom_categories for update
  using (
    public.current_user_has_permission('master_data.uom.manage')
    and (not is_locked or public.current_user_has_role('system_admin'))
  );

create policy delete_uom_categories on public.uom_categories for delete
  using (public.current_user_has_role('system_admin'));

-- UNITS OF MEASURE
create policy select_units_authenticated on public.units_of_measure for select
  using (is_active = true or public.current_user_has_permission('master_data.uom.view'));

create policy insert_units on public.units_of_measure for insert
  with check (public.current_user_has_permission('master_data.uom.manage'));

create policy update_units on public.units_of_measure for update
  using (
    public.current_user_has_permission('master_data.uom.manage')
    and (not is_locked or public.current_user_has_role('system_admin'))
  );

create policy delete_units on public.units_of_measure for delete
  using (public.current_user_has_role('system_admin'));

-- UOM CONVERSIONS
create policy select_conversions_authenticated on public.uom_conversions for select
  using (is_active = true or public.current_user_has_permission('master_data.uom.view'));

create policy insert_conversions on public.uom_conversions for insert
  with check (public.current_user_has_permission('master_data.uom.manage'));

create policy update_conversions on public.uom_conversions for update
  using (
    public.current_user_has_permission('master_data.uom.manage')
    and (not is_locked or public.current_user_has_role('system_admin'))
  );

create policy delete_conversions on public.uom_conversions for delete
  using (public.current_user_has_role('system_admin'));

-- ============================================================================
-- SEED DATA: UOM CATEGORIES
-- ============================================================================

insert into public.uom_categories (category_code, category_name_en, category_name_ar, description_en, is_system, is_locked, sort_order)
values
  ('WEIGHT', 'Weight', 'الوزن', 'Mass and weight measurements', true, true, 10),
  ('LENGTH', 'Length', 'الطول', 'Linear distance measurements', true, true, 20),
  ('VOLUME', 'Volume', 'الحجم', 'Volumetric capacity measurements', true, true, 30),
  ('FUEL', 'Fuel', 'الوقود', 'Fuel volume measurements (UAE diesel in Imperial gallons)', true, true, 40),
  ('AREA', 'Area', 'المساحة', 'Surface area measurements', true, true, 50),
  ('TIME', 'Time', 'الوقت', 'Duration and time measurements', true, true, 60),
  ('COUNT', 'Count', 'العدد', 'Quantity count measurements', true, true, 70),
  ('PACKAGING', 'Packaging', 'التعبئة', 'Packaging and container units (item-specific conversions)', true, true, 80)
on conflict (category_code) do nothing;

-- ============================================================================
-- SEED DATA: UNITS OF MEASURE
-- ============================================================================

-- WEIGHT UNITS
insert into public.units_of_measure (uom_category_id, unit_code, unit_name_en, unit_name_ar, symbol, conversion_factor_to_base, is_base_unit, decimal_places, is_system, is_locked, sort_order)
select c.id, 'KG', 'Kilogram', 'كيلوغرام', 'kg', 1, true, 3, true, true, 10
from public.uom_categories c where c.category_code = 'WEIGHT'
union all
select c.id, 'G', 'Gram', 'غرام', 'g', 0.001, false, 3, true, true, 20
from public.uom_categories c where c.category_code = 'WEIGHT'
union all
select c.id, 'T', 'Metric Ton', 'طن متري', 't', 1000, false, 3, true, true, 30
from public.uom_categories c where c.category_code = 'WEIGHT'
union all
select c.id, 'LB', 'Pound', 'رطل', 'lb', 0.453592, false, 3, true, true, 40
from public.uom_categories c where c.category_code = 'WEIGHT'
on conflict (uom_category_id, unit_code) do nothing;

-- LENGTH UNITS
insert into public.units_of_measure (uom_category_id, unit_code, unit_name_en, unit_name_ar, symbol, conversion_factor_to_base, is_base_unit, decimal_places, is_system, is_locked, sort_order)
select c.id, 'M', 'Meter', 'متر', 'm', 1, true, 2, true, true, 10
from public.uom_categories c where c.category_code = 'LENGTH'
union all
select c.id, 'CM', 'Centimeter', 'سنتيمتر', 'cm', 0.01, false, 2, true, true, 20
from public.uom_categories c where c.category_code = 'LENGTH'
union all
select c.id, 'MM', 'Millimeter', 'ميليمتر', 'mm', 0.001, false, 2, true, true, 30
from public.uom_categories c where c.category_code = 'LENGTH'
union all
select c.id, 'KM', 'Kilometer', 'كيلومتر', 'km', 1000, false, 2, true, true, 40
from public.uom_categories c where c.category_code = 'LENGTH'
union all
select c.id, 'IN', 'Inch', 'بوصة', 'in', 0.0254, false, 2, true, true, 50
from public.uom_categories c where c.category_code = 'LENGTH'
union all
select c.id, 'FT', 'Foot', 'قدم', 'ft', 0.3048, false, 2, true, true, 60
from public.uom_categories c where c.category_code = 'LENGTH'
on conflict (uom_category_id, unit_code) do nothing;

-- VOLUME UNITS
insert into public.units_of_measure (uom_category_id, unit_code, unit_name_en, unit_name_ar, symbol, conversion_factor_to_base, is_base_unit, decimal_places, is_system, is_locked, sort_order)
select c.id, 'L', 'Liter', 'لتر', 'L', 1, true, 2, true, true, 10
from public.uom_categories c where c.category_code = 'VOLUME'
union all
select c.id, 'ML', 'Milliliter', 'ميليلتر', 'ml', 0.001, false, 2, true, true, 20
from public.uom_categories c where c.category_code = 'VOLUME'
union all
select c.id, 'M3', 'Cubic Meter', 'متر مكعب', 'm³', 1000, false, 2, true, true, 30
from public.uom_categories c where c.category_code = 'VOLUME'
union all
select c.id, 'GAL_US', 'US Gallon', 'جالون أمريكي', 'gal (US)', 3.78541, false, 2, true, true, 40
from public.uom_categories c where c.category_code = 'VOLUME'
union all
select c.id, 'GAL_IMP', 'Imperial Gallon', 'جالون إمبراطوري', 'gal (Imp)', 4.54609, false, 2, true, true, 50
from public.uom_categories c where c.category_code = 'VOLUME'
on conflict (uom_category_id, unit_code) do nothing;

-- FUEL UNITS
-- Base unit is GAL_IMP (Imperial Gallon) because UAE diesel operations use Imperial gallons.
-- 1 GAL_IMP = 4.54609 L
-- Therefore: 1 L = 1 / 4.54609 = 0.21997 GAL_IMP
-- And: 1 GAL_US = 3.78541 L = 3.78541 / 4.54609 = 0.832674 GAL_IMP
insert into public.units_of_measure (uom_category_id, unit_code, unit_name_en, unit_name_ar, symbol, conversion_factor_to_base, is_base_unit, decimal_places, is_system, is_locked, sort_order, notes)
select c.id, 'GAL_IMP', 'Imperial Gallon', 'جالون إمبراطوري', 'gal', 1, true, 2, true, true, 10, 'UAE diesel standard. 1 GAL_IMP = 4.54609 L'
from public.uom_categories c where c.category_code = 'FUEL'
union all
select c.id, 'L', 'Liter', 'لتر', 'L', 0.21997, false, 2, true, true, 20, '1 L = 0.21997 GAL_IMP (or 4.54609 L per GAL_IMP)'
from public.uom_categories c where c.category_code = 'FUEL'
union all
select c.id, 'GAL_US', 'US Gallon', 'جالون أمريكي', 'gal (US)', 0.832674, false, 2, true, true, 30, '1 GAL_US = 0.832674 GAL_IMP (or 3.78541 L)'
from public.uom_categories c where c.category_code = 'FUEL'
on conflict (uom_category_id, unit_code) do nothing;

-- AREA UNITS
insert into public.units_of_measure (uom_category_id, unit_code, unit_name_en, unit_name_ar, symbol, conversion_factor_to_base, is_base_unit, decimal_places, is_system, is_locked, sort_order)
select c.id, 'M2', 'Square Meter', 'متر مربع', 'm²', 1, true, 2, true, true, 10
from public.uom_categories c where c.category_code = 'AREA'
union all
select c.id, 'CM2', 'Square Centimeter', 'سنتيمتر مربع', 'cm²', 0.0001, false, 2, true, true, 20
from public.uom_categories c where c.category_code = 'AREA'
union all
select c.id, 'FT2', 'Square Foot', 'قدم مربع', 'ft²', 0.092903, false, 2, true, true, 30
from public.uom_categories c where c.category_code = 'AREA'
union all
select c.id, 'KM2', 'Square Kilometer', 'كيلومتر مربع', 'km²', 1000000, false, 2, true, true, 40
from public.uom_categories c where c.category_code = 'AREA'
on conflict (uom_category_id, unit_code) do nothing;

-- TIME UNITS
insert into public.units_of_measure (uom_category_id, unit_code, unit_name_en, unit_name_ar, symbol, conversion_factor_to_base, is_base_unit, decimal_places, is_system, is_locked, sort_order, notes)
select c.id, 'HOUR', 'Hour', 'ساعة', 'hr', 1, true, 2, true, true, 10, null
from public.uom_categories c where c.category_code = 'TIME'
union all
select c.id, 'MIN', 'Minute', 'دقيقة', 'min', 0.0166667, false, 2, true, true, 20, '1 MIN = 1/60 HOUR'
from public.uom_categories c where c.category_code = 'TIME'
union all
select c.id, 'DAY', 'Day', 'يوم', 'day', 24, false, 2, true, true, 30, '1 DAY = 24 HOUR'
from public.uom_categories c where c.category_code = 'TIME'
union all
select c.id, 'MONTH', 'Month', 'شهر', 'month', 730, false, 2, true, true, 40, 'Approximate monthly unit (30.42 days). Exact month billing/rental logic must be handled in future billing/rental modules.'
from public.uom_categories c where c.category_code = 'TIME'
union all
select c.id, 'YEAR', 'Year', 'سنة', 'year', 8760, false, 2, true, true, 50, '1 YEAR = 365 DAYS = 8760 HOUR'
from public.uom_categories c where c.category_code = 'TIME'
on conflict (uom_category_id, unit_code) do nothing;

-- COUNT UNITS
insert into public.units_of_measure (uom_category_id, unit_code, unit_name_en, unit_name_ar, symbol, conversion_factor_to_base, is_base_unit, decimal_places, is_system, is_locked, sort_order)
select c.id, 'EA', 'Each', 'قطعة', 'ea', 1, true, 0, true, true, 10
from public.uom_categories c where c.category_code = 'COUNT'
union all
select c.id, 'PCS', 'Pieces', 'قطع', 'pcs', 1, false, 0, true, true, 20
from public.uom_categories c where c.category_code = 'COUNT'
union all
select c.id, 'SET', 'Set', 'مجموعة', 'set', 1, false, 0, true, true, 30
from public.uom_categories c where c.category_code = 'COUNT'
union all
select c.id, 'PAIR', 'Pair', 'زوج', 'pair', 2, false, 0, true, true, 40
from public.uom_categories c where c.category_code = 'COUNT'
union all
select c.id, 'DOZEN', 'Dozen', 'دزينة', 'dz', 12, false, 0, true, true, 50
from public.uom_categories c where c.category_code = 'COUNT'
on conflict (uom_category_id, unit_code) do nothing;

-- PACKAGING UNITS
-- Note: Packaging conversions are NOT universal. 1 BOX is not always equal to a fixed number of EA.
-- Item-specific packaging conversions must be handled later in Inventory Item Master.
insert into public.units_of_measure (uom_category_id, unit_code, unit_name_en, unit_name_ar, symbol, conversion_factor_to_base, is_base_unit, decimal_places, is_system, is_locked, sort_order, notes)
select c.id, 'EA', 'Each', 'قطعة', 'ea', 1, true, 0, true, true, 10, null
from public.uom_categories c where c.category_code = 'PACKAGING'
union all
select c.id, 'BOX', 'Box', 'صندوق', 'box', 1, false, 0, true, false, 20, 'Packaging conversion is not universal. Item-specific conversion must be defined later in Inventory Item Master.'
from public.uom_categories c where c.category_code = 'PACKAGING'
union all
select c.id, 'BAG', 'Bag', 'كيس', 'bag', 1, false, 0, true, false, 30, 'Packaging conversion is not universal. Item-specific conversion must be defined later in Inventory Item Master.'
from public.uom_categories c where c.category_code = 'PACKAGING'
union all
select c.id, 'BUNDLE', 'Bundle', 'حزمة', 'bundle', 1, false, 0, true, false, 40, 'Packaging conversion is not universal. Item-specific conversion must be defined later in Inventory Item Master.'
from public.uom_categories c where c.category_code = 'PACKAGING'
union all
select c.id, 'ROLL', 'Roll', 'لفة', 'roll', 1, false, 0, true, false, 50, 'Packaging conversion is not universal. Item-specific conversion must be defined later in Inventory Item Master.'
from public.uom_categories c where c.category_code = 'PACKAGING'
union all
select c.id, 'DRUM', 'Drum', 'برميل', 'drum', 1, false, 0, true, false, 60, 'Packaging conversion is not universal. Item-specific conversion must be defined later in Inventory Item Master.'
from public.uom_categories c where c.category_code = 'PACKAGING'
union all
select c.id, 'PALLET', 'Pallet', 'طبلية', 'pallet', 1, false, 0, true, false, 70, 'Packaging conversion is not universal. Item-specific conversion must be defined later in Inventory Item Master.'
from public.uom_categories c where c.category_code = 'PACKAGING'
union all
select c.id, 'CONTAINER', 'Container', 'حاوية', 'container', 1, false, 0, true, false, 80, 'Packaging conversion is not universal. Item-specific conversion must be defined later in Inventory Item Master.'
from public.uom_categories c where c.category_code = 'PACKAGING'
on conflict (uom_category_id, unit_code) do nothing;

-- ============================================================================
-- SEED DATA: UOM CONVERSIONS
-- ============================================================================

-- uom_conversions table is created but intentionally seeded empty.
-- Reserved for special, future, cross-category, legacy exception, or item-specific conversions.
-- Normal same-category conversion uses units_of_measure.conversion_factor_to_base.

-- ============================================================================
-- END OF MIGRATION
-- ============================================================================
