-- ERP Base Foundation Migration
-- All ERP application tables use BIGINT identity primary keys.
-- UUID is only used for auth_user_id linking to auth.users.

-- ---------------------------------------------------------------------------
-- Extensions & utilities
-- ---------------------------------------------------------------------------

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------

create table public.owner_companies (
  id bigint generated by default as identity primary key,
  legal_name_en text not null,
  legal_name_ar text,
  short_name text,
  company_code text not null unique,
  legal_form text,
  country text,
  emirate text,
  trade_license_no text,
  trn text,
  corporate_tax_no text,
  default_currency text not null default 'AED',
  status text not null default 'active' check (status in ('active', 'inactive', 'suspended')),
  primary_email text,
  primary_phone text,
  website text,
  logo_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by bigint,
  updated_by bigint
);

create table public.branches (
  id bigint generated by default as identity primary key,
  owner_company_id bigint not null references public.owner_companies(id) on delete restrict,
  branch_code text not null,
  branch_name_en text not null,
  branch_name_ar text,
  emirate text,
  area text,
  address_line_1 text,
  address_line_2 text,
  po_box text,
  phone text,
  email text,
  status text not null default 'active' check (status in ('active', 'inactive', 'suspended')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by bigint,
  updated_by bigint,
  unique (owner_company_id, branch_code)
);

create table public.user_profiles (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null unique references auth.users(id) on delete cascade,
  user_code text unique,
  full_name text,
  display_name text,
  phone text,
  job_title text,
  department text,
  owner_company_id bigint references public.owner_companies(id) on delete set null,
  branch_id bigint references public.branches(id) on delete set null,
  status text not null default 'active' check (status in ('active', 'inactive', 'suspended')),
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.roles (
  id bigint generated by default as identity primary key,
  role_code text not null unique,
  role_name text not null,
  description text,
  is_system_role boolean not null default true,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.permissions (
  id bigint generated by default as identity primary key,
  permission_code text not null unique,
  permission_name text not null,
  module_code text not null,
  action_code text not null,
  description text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.role_permissions (
  id bigint generated by default as identity primary key,
  role_id bigint not null references public.roles(id) on delete cascade,
  permission_id bigint not null references public.permissions(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (role_id, permission_id)
);

create table public.user_roles (
  id bigint generated by default as identity primary key,
  user_profile_id bigint not null references public.user_profiles(id) on delete cascade,
  role_id bigint not null references public.roles(id) on delete cascade,
  owner_company_id bigint references public.owner_companies(id) on delete cascade,
  branch_id bigint references public.branches(id) on delete cascade,
  is_active boolean not null default true,
  assigned_at timestamptz not null default now(),
  assigned_by bigint references public.user_profiles(id) on delete set null,
  unique (user_profile_id, role_id, owner_company_id, branch_id)
);

create table public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_user_profile_id bigint references public.user_profiles(id) on delete set null,
  owner_company_id bigint references public.owner_companies(id) on delete set null,
  branch_id bigint references public.branches(id) on delete set null,
  module_code text,
  entity_name text,
  entity_id bigint,
  entity_reference text,
  action text not null,
  old_values jsonb,
  new_values jsonb,
  ip_address text,
  user_agent text,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------------------------

create index idx_branches_owner_company_id on public.branches(owner_company_id);
create index idx_user_profiles_auth_user_id on public.user_profiles(auth_user_id);
create index idx_user_profiles_owner_company_id on public.user_profiles(owner_company_id);
create index idx_user_profiles_branch_id on public.user_profiles(branch_id);
create index idx_user_profiles_status on public.user_profiles(status);
create index idx_user_roles_user_profile_id on public.user_roles(user_profile_id);
create index idx_user_roles_role_id on public.user_roles(role_id);
create index idx_role_permissions_role_id on public.role_permissions(role_id);
create index idx_audit_logs_created_at on public.audit_logs(created_at desc);
create index idx_audit_logs_owner_company_id on public.audit_logs(owner_company_id);

-- ---------------------------------------------------------------------------
-- Updated-at triggers
-- ---------------------------------------------------------------------------

create trigger trg_owner_companies_updated_at
  before update on public.owner_companies
  for each row execute function public.set_updated_at();

create trigger trg_branches_updated_at
  before update on public.branches
  for each row execute function public.set_updated_at();

create trigger trg_user_profiles_updated_at
  before update on public.user_profiles
  for each row execute function public.set_updated_at();

create trigger trg_roles_updated_at
  before update on public.roles
  for each row execute function public.set_updated_at();

create trigger trg_permissions_updated_at
  before update on public.permissions
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Auth user profile bootstrap (minimal trigger)
-- ---------------------------------------------------------------------------

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.user_profiles (auth_user_id, full_name, display_name)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', split_part(coalesce(new.email, ''), '@', 1)),
    coalesce(new.raw_user_meta_data->>'display_name', split_part(coalesce(new.email, 'user'), '@', 1))
  )
  on conflict (auth_user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_auth_user();

-- ---------------------------------------------------------------------------
-- RLS helper functions (SECURITY DEFINER, fixed search_path)
-- ---------------------------------------------------------------------------

create or replace function public.current_user_profile_id()
returns bigint
language sql
stable
security definer
set search_path = public
as $$
  select id from public.user_profiles where auth_user_id = auth.uid() limit 1;
$$;

create or replace function public.current_user_owner_company_id()
returns bigint
language sql
stable
security definer
set search_path = public
as $$
  select owner_company_id from public.user_profiles where auth_user_id = auth.uid() limit 1;
$$;

create or replace function public.current_user_branch_id()
returns bigint
language sql
stable
security definer
set search_path = public
as $$
  select branch_id from public.user_profiles where auth_user_id = auth.uid() limit 1;
$$;

create or replace function public.current_user_has_role(role_code text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.user_roles ur
    join public.roles r on r.id = ur.role_id
    join public.user_profiles up on up.id = ur.user_profile_id
    where up.auth_user_id = auth.uid()
      and ur.is_active = true
      and r.is_active = true
      and r.role_code = role_code
  );
$$;

create or replace function public.current_user_has_permission(permission_code text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.user_roles ur
    join public.roles r on r.id = ur.role_id
    join public.role_permissions rp on rp.role_id = r.id
    join public.permissions p on p.id = rp.permission_id
    join public.user_profiles up on up.id = ur.user_profile_id
    where up.auth_user_id = auth.uid()
      and ur.is_active = true
      and r.is_active = true
      and p.is_active = true
      and p.permission_code = permission_code
  )
  or public.current_user_has_role('system_admin');
$$;

revoke all on function public.current_user_profile_id() from public;
revoke all on function public.current_user_owner_company_id() from public;
revoke all on function public.current_user_branch_id() from public;
revoke all on function public.current_user_has_role(text) from public;
revoke all on function public.current_user_has_permission(text) from public;

grant execute on function public.current_user_profile_id() to authenticated;
grant execute on function public.current_user_owner_company_id() to authenticated;
grant execute on function public.current_user_branch_id() to authenticated;
grant execute on function public.current_user_has_role(text) to authenticated;
grant execute on function public.current_user_has_permission(text) to authenticated;

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------

alter table public.owner_companies enable row level security;
alter table public.branches enable row level security;
alter table public.user_profiles enable row level security;
alter table public.roles enable row level security;
alter table public.permissions enable row level security;
alter table public.role_permissions enable row level security;
alter table public.user_roles enable row level security;
alter table public.audit_logs enable row level security;

-- owner_companies
create policy owner_companies_select on public.owner_companies
  for select to authenticated
  using (
    public.current_user_has_permission('organizations.view')
    or public.current_user_has_role('system_admin')
    or public.current_user_has_role('group_admin')
  );

create policy owner_companies_manage on public.owner_companies
  for all to authenticated
  using (
    public.current_user_has_permission('organizations.manage')
    or public.current_user_has_role('system_admin')
    or public.current_user_has_role('group_admin')
  )
  with check (
    public.current_user_has_permission('organizations.manage')
    or public.current_user_has_role('system_admin')
    or public.current_user_has_role('group_admin')
  );

-- branches
create policy branches_select on public.branches
  for select to authenticated
  using (
    public.current_user_has_permission('branches.view')
    or public.current_user_has_role('system_admin')
    or public.current_user_has_role('group_admin')
    or (
      public.current_user_has_role('company_admin')
      and owner_company_id = public.current_user_owner_company_id()
    )
    or (
      public.current_user_has_role('branch_admin')
      and id = public.current_user_branch_id()
    )
  );

create policy branches_manage on public.branches
  for all to authenticated
  using (
    public.current_user_has_permission('branches.manage')
    or public.current_user_has_role('system_admin')
    or public.current_user_has_role('group_admin')
  )
  with check (
    public.current_user_has_permission('branches.manage')
    or public.current_user_has_role('system_admin')
    or public.current_user_has_role('group_admin')
  );

-- user_profiles
create policy user_profiles_select_own on public.user_profiles
  for select to authenticated
  using (auth_user_id = auth.uid());

create policy user_profiles_select_admin on public.user_profiles
  for select to authenticated
  using (public.current_user_has_permission('users.view'));

create policy user_profiles_update_own on public.user_profiles
  for update to authenticated
  using (auth_user_id = auth.uid())
  with check (auth_user_id = auth.uid());

create policy user_profiles_manage on public.user_profiles
  for all to authenticated
  using (public.current_user_has_permission('users.update'))
  with check (public.current_user_has_permission('users.update'));

-- roles (read for authenticated with roles.view; manage for admins)
create policy roles_select on public.roles
  for select to authenticated
  using (
    public.current_user_has_permission('roles.view')
    or public.current_user_has_role('system_admin')
  );

create policy roles_manage on public.roles
  for all to authenticated
  using (public.current_user_has_permission('roles.manage'))
  with check (public.current_user_has_permission('roles.manage'));

-- permissions
create policy permissions_select on public.permissions
  for select to authenticated
  using (
    public.current_user_has_permission('permissions.view')
    or public.current_user_has_role('system_admin')
  );

create policy permissions_manage on public.permissions
  for all to authenticated
  using (public.current_user_has_permission('permissions.manage'))
  with check (public.current_user_has_permission('permissions.manage'));

-- role_permissions
create policy role_permissions_select on public.role_permissions
  for select to authenticated
  using (
    public.current_user_has_permission('roles.view')
    or public.current_user_has_role('system_admin')
  );

create policy role_permissions_manage on public.role_permissions
  for all to authenticated
  using (public.current_user_has_permission('roles.manage'))
  with check (public.current_user_has_permission('roles.manage'));

-- user_roles
create policy user_roles_select on public.user_roles
  for select to authenticated
  using (
    public.current_user_has_permission('users.view')
    or user_profile_id = public.current_user_profile_id()
  );

create policy user_roles_manage on public.user_roles
  for all to authenticated
  using (public.current_user_has_permission('users.update'))
  with check (public.current_user_has_permission('users.update'));

-- audit_logs
create policy audit_logs_select on public.audit_logs
  for select to authenticated
  using (
    public.current_user_has_permission('audit.view')
    or public.current_user_has_role('system_admin')
  );

create policy audit_logs_insert on public.audit_logs
  for insert to authenticated
  with check (
    public.current_user_has_permission('audit.view')
    or public.current_user_has_role('system_admin')
  );

-- ---------------------------------------------------------------------------
-- Seed roles
-- ---------------------------------------------------------------------------

insert into public.roles (role_code, role_name, description, is_system_role) values
  ('system_admin', 'System Administrator', 'Full platform administration', true),
  ('group_admin', 'Group Administrator', 'Multi-company group administration', true),
  ('company_admin', 'Company Administrator', 'Owner company administration', true),
  ('branch_admin', 'Branch Administrator', 'Branch-level administration', true),
  ('hr_manager', 'HR Manager', 'Human resources module manager', true),
  ('fleet_manager', 'Fleet Manager', 'Fleet module manager', true),
  ('workshop_manager', 'Workshop Manager', 'Workshop module manager', true),
  ('operations_manager', 'Operations Manager', 'Operations module manager', true),
  ('rental_manager', 'Rental Manager', 'Equipment rental module manager', true),
  ('hse_manager', 'HSE Manager', 'Health, safety, and environment manager', true),
  ('finance_manager', 'Finance Manager', 'Finance module manager', true),
  ('procurement_manager', 'Procurement Manager', 'Procurement module manager', true),
  ('inventory_manager', 'Inventory Manager', 'Inventory module manager', true),
  ('dms_manager', 'DMS Manager', 'Document management module manager', true),
  ('employee_self_service', 'Employee Self Service', 'Limited self-service access', true),
  ('read_only_user', 'Read Only User', 'Read-only ERP access', true);

-- ---------------------------------------------------------------------------
-- Seed permissions
-- ---------------------------------------------------------------------------

insert into public.permissions (permission_code, permission_name, module_code, action_code, description) values
  ('users.view', 'View Users', 'users', 'view', 'View user profiles'),
  ('users.create', 'Create Users', 'users', 'create', 'Create user profiles'),
  ('users.update', 'Update Users', 'users', 'update', 'Update user profiles'),
  ('users.delete', 'Delete Users', 'users', 'delete', 'Deactivate or remove users'),
  ('roles.view', 'View Roles', 'roles', 'view', 'View roles'),
  ('roles.manage', 'Manage Roles', 'roles', 'manage', 'Manage roles and assignments'),
  ('permissions.view', 'View Permissions', 'permissions', 'view', 'View permissions'),
  ('permissions.manage', 'Manage Permissions', 'permissions', 'manage', 'Manage permissions'),
  ('organizations.view', 'View Organizations', 'organizations', 'view', 'View owner companies'),
  ('organizations.manage', 'Manage Organizations', 'organizations', 'manage', 'Manage owner companies'),
  ('branches.view', 'View Branches', 'branches', 'view', 'View branches'),
  ('branches.manage', 'Manage Branches', 'branches', 'manage', 'Manage branches'),
  ('audit.view', 'View Audit Logs', 'audit', 'view', 'View audit logs'),
  ('dashboard.view', 'View Dashboard', 'dashboard', 'view', 'View ERP dashboard'),
  ('erp.admin', 'ERP Administration', 'erp', 'admin', 'Full ERP administration'),
  ('hse.view', 'View HSE', 'hse', 'view', 'View HSE module'),
  ('fleet.view', 'View Fleet', 'fleet', 'view', 'View fleet module'),
  ('hr.view', 'View HR', 'hr', 'view', 'View HR module'),
  ('dms.view', 'View DMS', 'dms', 'view', 'View DMS module'),
  ('workshop.view', 'View Workshop', 'workshop', 'view', 'View workshop module'),
  ('operations.view', 'View Operations', 'operations', 'view', 'View operations module'),
  ('rental.view', 'View Rental', 'rental', 'view', 'View rental module'),
  ('finance.view', 'View Finance', 'finance', 'view', 'View finance module'),
  ('procurement.view', 'View Procurement', 'procurement', 'view', 'View procurement module'),
  ('inventory.view', 'View Inventory', 'inventory', 'view', 'View inventory module'),
  ('settings.view', 'View Settings', 'settings', 'view', 'View settings'),
  ('settings.manage', 'Manage Settings', 'settings', 'manage', 'Manage settings');

-- ---------------------------------------------------------------------------
-- Seed role_permissions (system_admin gets all; group_admin gets most admin perms)
-- ---------------------------------------------------------------------------

insert into public.role_permissions (role_id, permission_id)
select r.id, p.id
from public.roles r
cross join public.permissions p
where r.role_code = 'system_admin';

insert into public.role_permissions (role_id, permission_id)
select r.id, p.id
from public.roles r
join public.permissions p on p.permission_code in (
  'users.view', 'users.update', 'roles.view', 'permissions.view',
  'organizations.view', 'organizations.manage', 'branches.view', 'branches.manage',
  'audit.view', 'dashboard.view', 'settings.view', 'settings.manage'
)
where r.role_code = 'group_admin';

insert into public.role_permissions (role_id, permission_id)
select r.id, p.id
from public.roles r
join public.permissions p on p.permission_code in (
  'users.view', 'users.update', 'roles.view', 'organizations.view',
  'branches.view', 'branches.manage', 'dashboard.view', 'settings.view'
)
where r.role_code = 'company_admin';

insert into public.role_permissions (role_id, permission_id)
select r.id, p.id
from public.roles r
join public.permissions p on p.permission_code in (
  'users.view', 'branches.view', 'dashboard.view', 'settings.view'
)
where r.role_code = 'branch_admin';

insert into public.role_permissions (role_id, permission_id)
select r.id, p.id
from public.roles r
join public.permissions p on p.permission_code = 'dashboard.view'
where r.role_code = 'read_only_user';

insert into public.role_permissions (role_id, permission_id)
select r.id, p.id
from public.roles r
join public.permissions p on p.permission_code in ('dashboard.view', 'settings.view')
where r.role_code = 'employee_self_service';
