-- ============================================================================
-- ERP HR.2 — Employee Master and Profile Shell
-- Migration: 20260618200000_erp_hr_2_employee_master_profile_shell.sql
-- Scope: employees, employee_status_events, employee_document_links
--        RLS helper functions, indexes, RLS policies, triggers
-- ============================================================================

-- ── Ensure pg_trgm extension exists ─────────────────────────────────────────
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- ============================================================================
-- 1. employees table
-- ============================================================================

CREATE TABLE IF NOT EXISTS employees (
  id                                    BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

  -- Code (generated by numbering engine)
  employee_code                         TEXT NOT NULL UNIQUE,

  -- Personal
  full_name_en                          TEXT NOT NULL,
  full_name_ar                          TEXT,
  known_name                            TEXT,
  gender                                TEXT NOT NULL CHECK (gender IN ('male','female')),
  nationality_id                        BIGINT REFERENCES countries(id),
  date_of_birth                         DATE NOT NULL,
  marital_status                        TEXT CHECK (marital_status IN ('single','married','divorced','widowed')),
  mobile_number                         TEXT NOT NULL,
  personal_email                        TEXT,
  uae_address                           TEXT,
  home_country_address                  TEXT,
  blood_group                           TEXT CHECK (blood_group IN ('A+','A-','B+','B-','O+','O-','AB+','AB-')),
  photo_dms_document_id                 BIGINT REFERENCES dms_documents(id),

  -- Employment
  owner_company_id                      BIGINT NOT NULL REFERENCES owner_companies(id),
  branch_id                             BIGINT REFERENCES branches(id),
  department_id                         BIGINT REFERENCES departments(id),
  designation_id                        BIGINT REFERENCES designations(id),
  employee_category_id                  BIGINT REFERENCES hr_employee_categories(id),
  employment_type_id                    BIGINT REFERENCES hr_employment_types(id),
  joining_date                          DATE NOT NULL,
  actual_joining_date                   DATE,
  employee_status                       TEXT NOT NULL DEFAULT 'active'
                                          CHECK (employee_status IN ('active','inactive','on_leave','probation','suspended','terminated','archived')),
  reporting_manager_id                  BIGINT REFERENCES employees(id),
  supervisor_id                         BIGINT REFERENCES employees(id),
  primary_work_site_id                  BIGINT REFERENCES work_sites(id),
  sponsor_company_id                    BIGINT REFERENCES owner_companies(id),
  mohre_establishment_id                BIGINT REFERENCES hr_mohre_establishments(id),

  -- Contract / Probation
  probation_start_date                  DATE,
  probation_end_date                    DATE,
  contract_type                         TEXT CHECK (contract_type IN ('limited','unlimited')),
  contract_start_date                   DATE,
  contract_end_date                     DATE,
  notice_period_days                    INT,

  -- Status extras
  inactive_date                         DATE,
  inactive_reason                       TEXT,

  -- Emergency contact
  emergency_contact_name                TEXT NOT NULL,
  emergency_contact_mobile              TEXT NOT NULL,
  emergency_contact_relationship_type_id BIGINT REFERENCES hr_relationship_types(id),

  -- Metadata
  created_at                            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at                            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by                            BIGINT REFERENCES user_profiles(id),
  updated_by                            BIGINT REFERENCES user_profiles(id),
  deleted_at                            TIMESTAMPTZ,
  deleted_by                            BIGINT REFERENCES user_profiles(id)
);

-- ============================================================================
-- 2. employee_status_events table (append-only)
-- ============================================================================

CREATE TABLE IF NOT EXISTS employee_status_events (
  id           BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  employee_id  BIGINT NOT NULL REFERENCES employees(id),
  old_status   TEXT,
  new_status   TEXT NOT NULL,
  reason       TEXT,
  effective_date DATE,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by   BIGINT REFERENCES user_profiles(id)
);

-- ============================================================================
-- 3. employee_document_links table (readiness only — functional DMS in HR.3+)
-- ============================================================================

CREATE TABLE IF NOT EXISTS employee_document_links (
  id                   BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  employee_id          BIGINT NOT NULL REFERENCES employees(id),
  dms_document_id      BIGINT NOT NULL REFERENCES dms_documents(id),
  related_record_type  TEXT,
  related_record_id    BIGINT,
  relation_purpose     TEXT,
  verification_status  TEXT NOT NULL DEFAULT 'unverified'
                         CHECK (verification_status IN ('unverified','verified','failed')),
  created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by           BIGINT REFERENCES user_profiles(id),
  deleted_at           TIMESTAMPTZ,
  deleted_by           BIGINT REFERENCES user_profiles(id),
  UNIQUE (employee_id, dms_document_id)
);

-- ============================================================================
-- 4. updated_at triggers
-- ============================================================================

CREATE OR REPLACE TRIGGER set_employees_updated_at
  BEFORE UPDATE ON employees
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ============================================================================
-- 5. Indexes
-- ============================================================================

CREATE INDEX IF NOT EXISTS idx_employees_employee_code
  ON employees (employee_code);

CREATE INDEX IF NOT EXISTS idx_employees_full_name_en_trgm
  ON employees USING GIN (full_name_en gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_employees_full_name_ar_trgm
  ON employees USING GIN (full_name_ar gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_employees_mobile_number
  ON employees (mobile_number);

CREATE INDEX IF NOT EXISTS idx_employees_owner_company_id
  ON employees (owner_company_id);

CREATE INDEX IF NOT EXISTS idx_employees_branch_id
  ON employees (branch_id);

CREATE INDEX IF NOT EXISTS idx_employees_department_id
  ON employees (department_id);

CREATE INDEX IF NOT EXISTS idx_employees_designation_id
  ON employees (designation_id);

CREATE INDEX IF NOT EXISTS idx_employees_employee_category_id
  ON employees (employee_category_id);

CREATE INDEX IF NOT EXISTS idx_employees_employment_type_id
  ON employees (employment_type_id);

CREATE INDEX IF NOT EXISTS idx_employees_employee_status
  ON employees (employee_status) WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_employees_joining_date
  ON employees (joining_date);

CREATE INDEX IF NOT EXISTS idx_employees_nationality_id
  ON employees (nationality_id);

CREATE INDEX IF NOT EXISTS idx_employees_primary_work_site_id
  ON employees (primary_work_site_id);

CREATE INDEX IF NOT EXISTS idx_employees_reporting_manager_id
  ON employees (reporting_manager_id);

CREATE INDEX IF NOT EXISTS idx_employees_supervisor_id
  ON employees (supervisor_id);

CREATE INDEX IF NOT EXISTS idx_employee_status_events_employee_id
  ON employee_status_events (employee_id);

CREATE INDEX IF NOT EXISTS idx_employee_status_events_created_at
  ON employee_status_events (created_at);

CREATE INDEX IF NOT EXISTS idx_employee_document_links_employee_id
  ON employee_document_links (employee_id) WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_employee_document_links_dms_document_id
  ON employee_document_links (dms_document_id);

CREATE INDEX IF NOT EXISTS idx_employee_document_links_related_record
  ON employee_document_links (related_record_type, related_record_id);

-- ============================================================================
-- 6. RLS — Enable and Force
-- ============================================================================

ALTER TABLE employees              ENABLE ROW LEVEL SECURITY;
ALTER TABLE employees              FORCE ROW LEVEL SECURITY;
ALTER TABLE employee_status_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE employee_status_events FORCE ROW LEVEL SECURITY;
ALTER TABLE employee_document_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE employee_document_links FORCE ROW LEVEL SECURITY;

-- ============================================================================
-- 7. RLS Helper Functions
-- ============================================================================

CREATE OR REPLACE FUNCTION current_user_can_view_employee(p_employee_id BIGINT)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
AS $$
  SELECT (
    current_user_is_global_admin()
    OR EXISTS (
      SELECT 1 FROM employees e
      WHERE e.id = p_employee_id
        AND current_user_has_permission_in_company('hr.employees.view', e.owner_company_id)
    )
    OR EXISTS (
      SELECT 1 FROM employees e
      WHERE e.id = p_employee_id
        AND current_user_has_permission_in_company('hr.employee_profile.view', e.owner_company_id)
    )
  );
$$;

CREATE OR REPLACE FUNCTION current_user_can_manage_employee(p_employee_id BIGINT)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
AS $$
  SELECT (
    current_user_is_global_admin()
    OR EXISTS (
      SELECT 1 FROM employees e
      WHERE e.id = p_employee_id
        AND current_user_has_permission_in_company('hr.employees.update', e.owner_company_id)
    )
    OR EXISTS (
      SELECT 1 FROM employees e
      WHERE e.id = p_employee_id
        AND current_user_has_permission_in_company('hr.employee_profile.manage', e.owner_company_id)
    )
  );
$$;

-- ============================================================================
-- 8. RLS Policies — employees
-- ============================================================================

CREATE POLICY employees_select
  ON employees FOR SELECT
  USING (
    current_user_is_global_admin()
    OR current_user_has_permission_in_company('hr.employees.view', owner_company_id)
    OR current_user_has_permission_in_company('hr.employee_profile.view', owner_company_id)
  );

CREATE POLICY employees_insert
  ON employees FOR INSERT
  WITH CHECK (
    current_user_is_global_admin()
    OR current_user_has_permission('hr.employees.create')
  );

CREATE POLICY employees_update
  ON employees FOR UPDATE
  USING (
    current_user_is_global_admin()
    OR current_user_has_permission_in_company('hr.employees.update', owner_company_id)
    OR current_user_has_permission_in_company('hr.employee_profile.manage', owner_company_id)
  )
  WITH CHECK (
    current_user_is_global_admin()
    OR current_user_has_permission_in_company('hr.employees.update', owner_company_id)
    OR current_user_has_permission_in_company('hr.employee_profile.manage', owner_company_id)
  );

-- No hard-delete policy — soft-delete only via UPDATE

-- ============================================================================
-- 9. RLS Policies — employee_status_events (append-only: SELECT + INSERT only)
-- ============================================================================

CREATE POLICY employee_status_events_select
  ON employee_status_events FOR SELECT
  USING (current_user_can_view_employee(employee_id));

CREATE POLICY employee_status_events_insert
  ON employee_status_events FOR INSERT
  WITH CHECK (current_user_can_manage_employee(employee_id));

-- No UPDATE or DELETE policy intentionally

-- ============================================================================
-- 10. RLS Policies — employee_document_links
-- ============================================================================

CREATE POLICY employee_document_links_select
  ON employee_document_links FOR SELECT
  USING (current_user_can_view_employee(employee_id));

CREATE POLICY employee_document_links_insert
  ON employee_document_links FOR INSERT
  WITH CHECK (current_user_can_manage_employee(employee_id));

CREATE POLICY employee_document_links_update
  ON employee_document_links FOR UPDATE
  USING (current_user_can_manage_employee(employee_id))
  WITH CHECK (current_user_can_manage_employee(employee_id));
