-- ============================================================================
-- ERP BASE 002F.2 — Global Numbering Engine
-- ============================================================================
-- Created: 2026-06-04
-- Purpose: Simple ERP reference number generation (EMP-0001, PO-0025, INV-0312)
-- Format: {DOC}-{SEQ4} (No company/branch/city/year/month codes)
-- ============================================================================

-- ============================================================================
-- TABLE: global_numbering_rules
-- ============================================================================
-- Stores configuration for document numbering sequences

create table if not exists public.global_numbering_rules (
  id bigint generated by default as identity primary key,
  
  -- Rule identification
  rule_code text not null unique,
  rule_name text not null,
  description text,
  
  -- Module and document type
  module_code text not null,
  module_name text not null,
  document_type_code text not null,
  document_type_name text not null,
  document_prefix text not null,
  
  -- Format configuration
  separator text not null default '-',
  format_template text not null default '{DOC}-{SEQ4}',
  sequence_length int not null default 4 check (sequence_length between 1 and 12),
  padding_character text not null default '0',
  
  -- Sequence state
  starting_sequence_number bigint not null default 1 check (starting_sequence_number >= 1),
  current_sequence_number bigint not null default 0 check (current_sequence_number >= 0),
  next_sequence_number bigint not null default 1 check (next_sequence_number >= 1),
  
  -- Reset policy
  reset_policy text not null default 'never' check (reset_policy in ('never', 'yearly', 'monthly')),
  
  -- Generation policies
  reserve_on_draft boolean not null default false,
  reserve_on_submit boolean not null default true,
  allow_manual_override boolean not null default false,
  manual_override_requires_permission boolean not null default true,
  allow_gaps boolean not null default true,
  cancelled_number_policy text not null default 'never_reuse' check (cancelled_number_policy in ('never_reuse', 'allow_reuse')),
  duplicate_prevention_scope text not null default 'document_type',
  
  -- Status
  is_active boolean not null default true,
  is_locked boolean not null default false,
  effective_from timestamptz,
  effective_to timestamptz,
  
  -- Audit
  notes text,
  created_at timestamptz not null default now(),
  created_by bigint,
  updated_at timestamptz not null default now(),
  updated_by bigint,
  
  -- Constraints
  check (document_prefix = upper(document_prefix)),
  check (document_prefix ~ '^[A-Z0-9_]+$'),
  check (format_template like '%{DOC}%'),
  check (format_template ~ '\{SEQ[0-9]*\}'),
  check (effective_to is null or effective_to >= effective_from)
);

comment on table public.global_numbering_rules is 'Configuration for simple ERP reference number generation (EMP-0001, PO-0025)';
comment on column public.global_numbering_rules.format_template is 'Template tokens: {DOC}, {SEQ}, {SEQ3}, {SEQ4}, {SEQ5}, {SEQ6}. Example: {DOC}-{SEQ4}';
comment on column public.global_numbering_rules.reset_policy is 'never = continuous sequence, yearly/monthly = future enhancement';

-- ============================================================================
-- TABLE: global_numbering_sequence_states
-- ============================================================================
-- Tracks actual sequence state (separate for concurrency safety)

create table if not exists public.global_numbering_sequence_states (
  id bigint generated by default as identity primary key,
  
  -- Link to rule
  numbering_rule_id bigint not null references public.global_numbering_rules(id) on delete restrict,
  
  -- Document identification
  module_code text not null,
  document_type_code text not null,
  document_prefix text not null,
  
  -- Reset period key for future yearly/monthly resets
  reset_period_key text not null default 'GLOBAL',
  
  -- Sequence tracking
  last_sequence_number bigint not null default 0 check (last_sequence_number >= 0),
  next_sequence_number bigint not null default 1 check (next_sequence_number >= 1),
  last_generated_reference text,
  last_generated_at timestamptz,
  
  -- Audit
  created_at timestamptz not null default now(),
  created_by bigint,
  updated_at timestamptz not null default now(),
  updated_by bigint,
  
  -- Constraints
  unique (numbering_rule_id, reset_period_key)
);

comment on table public.global_numbering_sequence_states is 'Actual sequence state for concurrency-safe number generation';

-- ============================================================================
-- TABLE: global_numbering_generated_references
-- ============================================================================
-- Audit trail of all generated/reserved/consumed/cancelled numbers

create table if not exists public.global_numbering_generated_references (
  id bigint generated by default as identity primary key,
  
  -- Links
  numbering_rule_id bigint not null references public.global_numbering_rules(id) on delete restrict,
  sequence_state_id bigint references public.global_numbering_sequence_states(id) on delete restrict,
  
  -- Generated reference
  generated_reference_number text not null unique,
  generated_sequence_number bigint not null check (generated_sequence_number >= 1),
  
  -- Document identification
  module_code text not null,
  document_type_code text not null,
  document_prefix text not null,
  
  -- Target record linkage
  target_table_name text,
  target_record_id bigint,
  
  -- Status tracking
  generation_status text not null default 'consumed' check (
    generation_status in ('preview_only', 'reserved', 'consumed', 'cancelled', 'manual_override')
  ),
  generation_reason text,
  
  -- Lifecycle timestamps
  reserved_at timestamptz,
  consumed_at timestamptz,
  cancelled_at timestamptz,
  cancelled_reason text,
  
  -- Manual override tracking
  manual_override_used boolean not null default false,
  manual_override_reason text,
  
  -- Audit
  generated_by bigint,
  generated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  created_by bigint,
  updated_at timestamptz not null default now(),
  updated_by bigint
);

comment on table public.global_numbering_generated_references is 'Complete audit trail of all generated reference numbers';

-- ============================================================================
-- INDEXES
-- ============================================================================

create index if not exists idx_numbering_rules_rule_code on public.global_numbering_rules(rule_code);
create index if not exists idx_numbering_rules_module_code on public.global_numbering_rules(module_code);
create index if not exists idx_numbering_rules_document_type_code on public.global_numbering_rules(document_type_code);
create index if not exists idx_numbering_rules_is_active on public.global_numbering_rules(is_active);

create index if not exists idx_sequence_states_rule_id on public.global_numbering_sequence_states(numbering_rule_id);

create index if not exists idx_generated_refs_reference_number on public.global_numbering_generated_references(generated_reference_number);
create index if not exists idx_generated_refs_rule_id on public.global_numbering_generated_references(numbering_rule_id);
create index if not exists idx_generated_refs_status on public.global_numbering_generated_references(generation_status);
create index if not exists idx_generated_refs_target on public.global_numbering_generated_references(target_table_name, target_record_id);

-- ============================================================================
-- FUNCTION: preview_next_reference_number
-- ============================================================================
-- Preview the next number without consuming sequence

create or replace function public.preview_next_reference_number(
  p_rule_code text default null,
  p_document_type_code text default null,
  p_next_sequence_number bigint default null
)
returns table(
  preview_reference_number text,
  document_prefix text,
  sequence_number bigint,
  format_template text,
  rule_id bigint
)
language plpgsql
security definer
as $$
declare
  v_rule record;
  v_next_seq bigint;
  v_formatted_seq text;
  v_preview text;
begin
  -- Get rule by rule_code or document_type_code
  select * into v_rule
  from public.global_numbering_rules
  where (p_rule_code is not null and rule_code = p_rule_code)
     or (p_document_type_code is not null and document_type_code = p_document_type_code)
     and is_active = true
     and (effective_from is null or effective_from <= now())
     and (effective_to is null or effective_to >= now())
  order by id desc
  limit 1;

  if not found then
    raise exception 'No active numbering rule found for rule_code=% or document_type_code=%', p_rule_code, p_document_type_code;
  end if;

  -- Determine sequence number to preview
  v_next_seq := coalesce(p_next_sequence_number, v_rule.next_sequence_number);

  -- Format sequence with padding
  v_formatted_seq := lpad(v_next_seq::text, v_rule.sequence_length, v_rule.padding_character);

  -- Build preview based on format_template
  v_preview := v_rule.format_template;
  v_preview := replace(v_preview, '{DOC}', v_rule.document_prefix);
  v_preview := replace(v_preview, '{SEQ}', v_formatted_seq);
  v_preview := replace(v_preview, '{SEQ3}', lpad(v_next_seq::text, 3, v_rule.padding_character));
  v_preview := replace(v_preview, '{SEQ4}', lpad(v_next_seq::text, 4, v_rule.padding_character));
  v_preview := replace(v_preview, '{SEQ5}', lpad(v_next_seq::text, 5, v_rule.padding_character));
  v_preview := replace(v_preview, '{SEQ6}', lpad(v_next_seq::text, 6, v_rule.padding_character));
  v_preview := replace(v_preview, '{SEQ12}', lpad(v_next_seq::text, 12, v_rule.padding_character));

  return query select
    v_preview,
    v_rule.document_prefix,
    v_next_seq,
    v_rule.format_template,
    v_rule.id;
end;
$$;

comment on function public.preview_next_reference_number is 'Preview next reference number without consuming sequence. Example: EMP-0001';

-- ============================================================================
-- FUNCTION: generate_next_reference_number
-- ============================================================================
-- Generate and consume the next sequence number (concurrency-safe)

create or replace function public.generate_next_reference_number(
  p_rule_code text default null,
  p_document_type_code text default null,
  p_target_table_name text default null,
  p_target_record_id bigint default null,
  p_generation_reason text default null,
  p_generated_by bigint default null
)
returns table(
  generated_reference_number text,
  generated_sequence_number bigint,
  numbering_rule_id bigint,
  sequence_state_id bigint,
  generation_status text
)
language plpgsql
security definer
as $$
declare
  v_rule record;
  v_state record;
  v_next_seq bigint;
  v_formatted_seq text;
  v_generated_ref text;
  v_state_id bigint;
  v_gen_id bigint;
begin
  -- 1. Get and lock the rule
  select * into v_rule
  from public.global_numbering_rules
  where (p_rule_code is not null and rule_code = p_rule_code)
     or (p_document_type_code is not null and document_type_code = p_document_type_code)
     and is_active = true
     and (effective_from is null or effective_from <= now())
     and (effective_to is null or effective_to >= now())
  order by id desc
  limit 1
  for update;

  if not found then
    raise exception 'No active numbering rule found for rule_code=% or document_type_code=%', p_rule_code, p_document_type_code;
  end if;

  -- 2. Get or create sequence state (locked for update)
  select * into v_state
  from public.global_numbering_sequence_states
  where numbering_rule_id = v_rule.id
    and reset_period_key = 'GLOBAL'
  for update;

  if not found then
    -- Create new sequence state
    insert into public.global_numbering_sequence_states (
      numbering_rule_id,
      module_code,
      document_type_code,
      document_prefix,
      reset_period_key,
      last_sequence_number,
      next_sequence_number,
      created_by,
      updated_by
    ) values (
      v_rule.id,
      v_rule.module_code,
      v_rule.document_type_code,
      v_rule.document_prefix,
      'GLOBAL',
      0,
      v_rule.starting_sequence_number,
      p_generated_by,
      p_generated_by
    )
    returning * into v_state;
  end if;

  -- 3. Get next sequence number
  v_next_seq := v_state.next_sequence_number;

  -- 4. Format sequence with padding
  v_formatted_seq := lpad(v_next_seq::text, v_rule.sequence_length, v_rule.padding_character);

  -- 5. Build generated reference based on format_template
  v_generated_ref := v_rule.format_template;
  v_generated_ref := replace(v_generated_ref, '{DOC}', v_rule.document_prefix);
  v_generated_ref := replace(v_generated_ref, '{SEQ}', v_formatted_seq);
  v_generated_ref := replace(v_generated_ref, '{SEQ3}', lpad(v_next_seq::text, 3, v_rule.padding_character));
  v_generated_ref := replace(v_generated_ref, '{SEQ4}', lpad(v_next_seq::text, 4, v_rule.padding_character));
  v_generated_ref := replace(v_generated_ref, '{SEQ5}', lpad(v_next_seq::text, 5, v_rule.padding_character));
  v_generated_ref := replace(v_generated_ref, '{SEQ6}', lpad(v_next_seq::text, 6, v_rule.padding_character));
  v_generated_ref := replace(v_generated_ref, '{SEQ12}', lpad(v_next_seq::text, 12, v_rule.padding_character));

  -- 6. Check for duplicate (should never happen due to unique constraint, but defensive)
  if exists (
    select 1 from public.global_numbering_generated_references
    where generated_reference_number = v_generated_ref
  ) then
    raise exception 'Duplicate reference number detected: %', v_generated_ref;
  end if;

  -- 7. Insert audit record
  insert into public.global_numbering_generated_references (
    numbering_rule_id,
    sequence_state_id,
    generated_reference_number,
    generated_sequence_number,
    module_code,
    document_type_code,
    document_prefix,
    target_table_name,
    target_record_id,
    generation_status,
    generation_reason,
    consumed_at,
    generated_by,
    generated_at,
    created_by,
    updated_by
  ) values (
    v_rule.id,
    v_state.id,
    v_generated_ref,
    v_next_seq,
    v_rule.module_code,
    v_rule.document_type_code,
    v_rule.document_prefix,
    p_target_table_name,
    p_target_record_id,
    'consumed',
    p_generation_reason,
    now(),
    p_generated_by,
    now(),
    p_generated_by,
    p_generated_by
  )
  returning id into v_gen_id;

  -- 8. Update sequence state
  update public.global_numbering_sequence_states
  set
    last_sequence_number = v_next_seq,
    next_sequence_number = v_next_seq + 1,
    last_generated_reference = v_generated_ref,
    last_generated_at = now(),
    updated_at = now(),
    updated_by = p_generated_by
  where id = v_state.id;

  -- 9. Update rule's current/next sequence for UI display
  update public.global_numbering_rules
  set
    current_sequence_number = v_next_seq,
    next_sequence_number = v_next_seq + 1,
    updated_at = now(),
    updated_by = p_generated_by
  where id = v_rule.id;

  -- 10. Return result
  return query select
    v_generated_ref,
    v_next_seq,
    v_rule.id,
    v_state.id,
    'consumed'::text;
end;
$$;

comment on function public.generate_next_reference_number is 'Generate and consume next reference number. Concurrency-safe. Example: EMP-0001, EMP-0002';

-- ============================================================================
-- RLS POLICIES
-- ============================================================================

alter table public.global_numbering_rules enable row level security;
alter table public.global_numbering_sequence_states enable row level security;
alter table public.global_numbering_generated_references enable row level security;

-- Policy: View numbering rules
create policy "Allow viewing numbering rules for authenticated users"
  on public.global_numbering_rules
  for select
  using (true);

-- Policy: Manage numbering rules (admin only via application layer)
create policy "Allow managing numbering rules for authenticated users"
  on public.global_numbering_rules
  for all
  using (true)
  with check (true);

-- Policy: View sequence states (read-only for users)
create policy "Allow viewing sequence states for authenticated users"
  on public.global_numbering_sequence_states
  for select
  using (true);

-- Policy: Sequence states managed only by functions (no direct user updates)
create policy "Sequence states managed by functions only"
  on public.global_numbering_sequence_states
  for all
  using (false)
  with check (false);

-- Policy: View generated references audit trail
create policy "Allow viewing generated references for authenticated users"
  on public.global_numbering_generated_references
  for select
  using (true);

-- Policy: Generated references managed only by functions
create policy "Generated references managed by functions only"
  on public.global_numbering_generated_references
  for all
  using (false)
  with check (false);

-- ============================================================================
-- PERMISSIONS SEED
-- ============================================================================

-- Insert numbering permissions
insert into public.permissions (permission_code, permission_name, description, module_code, action_code)
values
  ('numbering.rules.view', 'View Numbering Rules', 'View numbering rule configurations', 'numbering', 'view'),
  ('numbering.rules.manage', 'Manage Numbering Rules', 'Create, edit, activate/deactivate numbering rules', 'numbering', 'manage'),
  ('numbering.rules.lock', 'Lock/Unlock Numbering Rules', 'Lock or unlock numbering rules', 'numbering', 'lock'),
  ('numbering.rules.generate', 'Generate Reference Numbers', 'Generate reference numbers from rules', 'numbering', 'generate'),
  ('numbering.rules.preview', 'Preview Reference Numbers', 'Preview next reference number without consuming', 'numbering', 'preview')
on conflict (permission_code) do nothing;

-- Grant numbering permissions to system_admin role
insert into public.role_permissions (role_id, permission_id)
select r.id, p.id
from public.roles r
cross join public.permissions p
where r.role_code = 'system_admin'
  and p.permission_code like 'numbering.%'
on conflict do nothing;

-- Grant view and preview permissions to group_admin
insert into public.role_permissions (role_id, permission_id)
select r.id, p.id
from public.roles r
cross join public.permissions p
where r.role_code = 'group_admin'
  and p.permission_code in ('numbering.rules.view', 'numbering.rules.preview')
on conflict do nothing;

-- ============================================================================
-- SEED DATA (Sample Rules)
-- ============================================================================

-- Sample numbering rules for common document types
insert into public.global_numbering_rules (
  rule_code,
  rule_name,
  description,
  module_code,
  module_name,
  document_type_code,
  document_type_name,
  document_prefix,
  separator,
  format_template,
  sequence_length,
  padding_character,
  starting_sequence_number,
  current_sequence_number,
  next_sequence_number,
  reset_policy,
  is_active,
  is_locked
) values
  (
    'HR_EMPLOYEE',
    'Employee Number',
    'Human resources employee reference number',
    'HR',
    'Human Resources',
    'EMPLOYEE',
    'Employee',
    'EMP',
    '-',
    '{DOC}-{SEQ4}',
    4,
    '0',
    1,
    0,
    1,
    'never',
    true,
    false
  ),
  (
    'PROCUREMENT_PO',
    'Purchase Order Number',
    'Procurement purchase order reference number',
    'PROCUREMENT',
    'Procurement',
    'PURCHASE_ORDER',
    'Purchase Order',
    'PO',
    '-',
    '{DOC}-{SEQ4}',
    4,
    '0',
    1,
    0,
    1,
    'never',
    true,
    false
  ),
  (
    'FINANCE_INV',
    'Invoice Number',
    'Finance invoice reference number',
    'FINANCE',
    'Finance',
    'INVOICE',
    'Invoice',
    'INV',
    '-',
    '{DOC}-{SEQ4}',
    4,
    '0',
    1,
    0,
    1,
    'never',
    true,
    false
  ),
  (
    'WORKSHOP_JO',
    'Job Order Number',
    'Workshop job order reference number',
    'WORKSHOP',
    'Workshop',
    'JOB_ORDER',
    'Job Order',
    'JO',
    '-',
    '{DOC}-{SEQ4}',
    4,
    '0',
    1,
    0,
    1,
    'never',
    true,
    false
  ),
  (
    'WAREHOUSE_GRN',
    'Goods Receipt Note Number',
    'Warehouse goods receipt note reference number',
    'WAREHOUSE',
    'Warehouse',
    'GOODS_RECEIPT_NOTE',
    'Goods Receipt Note',
    'GRN',
    '-',
    '{DOC}-{SEQ4}',
    4,
    '0',
    1,
    0,
    1,
    'never',
    true,
    false
  )
on conflict (rule_code) do nothing;

-- ============================================================================
-- UPDATED_AT TRIGGER
-- ============================================================================

-- Create trigger function if it doesn't exist
create or replace function public.update_updated_at_column()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- Apply updated_at triggers
drop trigger if exists update_numbering_rules_updated_at on public.global_numbering_rules;
create trigger update_numbering_rules_updated_at
  before update on public.global_numbering_rules
  for each row
  execute function public.update_updated_at_column();

drop trigger if exists update_numbering_sequence_states_updated_at on public.global_numbering_sequence_states;
create trigger update_numbering_sequence_states_updated_at
  before update on public.global_numbering_sequence_states
  for each row
  execute function public.update_updated_at_column();

drop trigger if exists update_numbering_generated_references_updated_at on public.global_numbering_generated_references;
create trigger update_numbering_generated_references_updated_at
  before update on public.global_numbering_generated_references
  for each row
  execute function public.update_updated_at_column();

-- ============================================================================
-- END OF MIGRATION
-- ============================================================================
