-- ============================================================================
-- ERP BASE 002F.3C.1 — Geography & Locations
-- ============================================================================
-- Created: 2026-06-05
-- Purpose: Core UAE geography master data (countries, emirates, cities, areas/zones, ports)
-- Features:
--   - Countries with ISO codes, GCC/UAE flags, phone codes
--   - UAE Emirates (7 emirates)
--   - Cities (municipalities) within emirates
--   - Areas/Zones (districts, industrial areas) within cities
--   - Ports (maritime, air, land) with type classification
--   - Bilingual support (EN/AR)
--   - Full audit trail and RLS
-- ============================================================================

-- ============================================================================
-- LOOKUP CATEGORIES: AREA_TYPES, PORT_TYPES
-- ============================================================================

do $$
declare
  v_cat_id bigint;
  v_user_id bigint;
begin
  -- Get current user profile ID for audit
  select id into v_user_id from public.user_profiles where auth_user_id = auth.uid() limit 1;

  -- Insert AREA_TYPES category
  insert into public.global_lookup_categories (
    category_code,
    category_name_en,
    category_name_ar,
    description,
    module_code,
    category_scope,
    supports_hierarchy,
    supports_color,
    supports_icon,
    supports_effective_dates,
    supports_metadata,
    is_system,
    is_locked,
    is_active,
    sort_order,
    created_by
  ) values (
    'AREA_TYPES',
    'Area Types',
    'أنواع المناطق',
    'Classification of geographic areas (e.g., Residential, Commercial, Industrial)',
    'MASTER_DATA',
    'GLOBAL',
    false,
    false,
    false,
    false,
    true,
    true,
    true,
    true,
    100,
    v_user_id
  )
  returning id into v_cat_id;

  -- Insert AREA_TYPES values
  insert into public.global_lookup_values (category_id, value_code, value_label_en, value_label_ar, sort_order, is_system, is_locked, is_default, created_by)
  values
    (v_cat_id, 'RESIDENTIAL', 'Residential', 'سكني', 10, true, true, false, v_user_id),
    (v_cat_id, 'COMMERCIAL', 'Commercial', 'تجاري', 20, true, true, false, v_user_id),
    (v_cat_id, 'INDUSTRIAL', 'Industrial', 'صناعي', 30, true, true, false, v_user_id),
    (v_cat_id, 'MIXED_USE', 'Mixed Use', 'استخدام مختلط', 40, true, true, false, v_user_id),
    (v_cat_id, 'FREE_ZONE', 'Free Zone', 'منطقة حرة', 50, true, true, false, v_user_id),
    (v_cat_id, 'GOVERNMENT', 'Government', 'حكومي', 60, true, true, false, v_user_id),
    (v_cat_id, 'TOURISM', 'Tourism', 'سياحي', 70, true, true, false, v_user_id),
    (v_cat_id, 'AGRICULTURAL', 'Agricultural', 'زراعي', 80, true, true, false, v_user_id);

  -- Insert PORT_TYPES category
  insert into public.global_lookup_categories (
    category_code,
    category_name_en,
    category_name_ar,
    description,
    module_code,
    category_scope,
    supports_hierarchy,
    supports_color,
    supports_icon,
    supports_effective_dates,
    supports_metadata,
    is_system,
    is_locked,
    is_active,
    sort_order,
    created_by
  ) values (
    'PORT_TYPES',
    'Port Types',
    'أنواع الموانئ',
    'Classification of ports (Maritime, Air, Land Border)',
    'MASTER_DATA',
    'GLOBAL',
    false,
    false,
    false,
    false,
    true,
    true,
    true,
    true,
    101,
    v_user_id
  )
  returning id into v_cat_id;

  -- Insert PORT_TYPES values
  insert into public.global_lookup_values (category_id, value_code, value_label_en, value_label_ar, sort_order, is_system, is_locked, is_default, created_by)
  values
    (v_cat_id, 'MARITIME', 'Maritime Port', 'ميناء بحري', 10, true, true, true, v_user_id),
    (v_cat_id, 'AIR', 'Airport', 'مطار', 20, true, true, false, v_user_id),
    (v_cat_id, 'LAND_BORDER', 'Land Border Crossing', 'معبر حدودي بري', 30, true, true, false, v_user_id);

end $$;

-- ============================================================================
-- TABLE: countries
-- ============================================================================

create table if not exists public.countries (
  id bigint generated by default as identity primary key,
  
  -- Country identification
  country_code text not null unique,
  iso3_code text not null unique,
  name_en text not null,
  name_ar text,
  nationality_en text not null,
  nationality_ar text,
  phone_code text,
  default_currency_code text,
  
  -- Classification flags
  is_gcc boolean not null default false,
  is_uae boolean not null default false,
  
  -- Status and governance
  is_system boolean not null default false,
  is_locked boolean not null default false,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  
  -- Audit fields
  created_at timestamptz not null default now(),
  created_by bigint,
  updated_at timestamptz not null default now(),
  updated_by bigint,
  deactivated_at timestamptz,
  deactivated_by bigint,
  deactivation_reason text,
  
  -- Constraints
  check (country_code = upper(country_code)),
  check (country_code ~ '^[A-Z]{2}$'),
  check (iso3_code = upper(iso3_code)),
  check (iso3_code ~ '^[A-Z]{3}$'),
  check (
    (is_active = true and deactivated_at is null) or
    (is_active = false and deactivated_at is not null)
  )
);

-- Comments
comment on table public.countries is 'Master data for countries with ISO codes, GCC/UAE classification';
comment on column public.countries.country_code is 'ISO 3166-1 alpha-2 code (2 letters, e.g., AE, SA)';
comment on column public.countries.iso3_code is 'ISO 3166-1 alpha-3 code (3 letters, e.g., ARE, SAU)';
comment on column public.countries.is_gcc is 'True if country is a GCC member (UAE, SA, KW, QA, BH, OM)';
comment on column public.countries.is_uae is 'True if country is UAE (should be unique)';

-- Indexes
create index if not exists idx_countries_code on public.countries(country_code);
create index if not exists idx_countries_iso3 on public.countries(iso3_code);
create index if not exists idx_countries_gcc on public.countries(is_gcc) where is_gcc = true;
create index if not exists idx_countries_uae on public.countries(is_uae) where is_uae = true;
create index if not exists idx_countries_active on public.countries(is_active);
create index if not exists idx_countries_sort on public.countries(sort_order);

-- Trigger for updated_at
create trigger trigger_countries_updated_at
  before update on public.countries
  for each row
  execute function public.set_updated_at();

-- ============================================================================
-- TABLE: emirates
-- ============================================================================

create table if not exists public.emirates (
  id bigint generated by default as identity primary key,
  
  -- Emirate identification
  emirate_code text not null unique,
  name_en text not null unique,
  name_ar text unique,
  abbreviation_en text not null,
  abbreviation_ar text,
  
  -- Status and governance
  is_system boolean not null default false,
  is_locked boolean not null default false,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  
  -- Audit fields
  created_at timestamptz not null default now(),
  created_by bigint,
  updated_at timestamptz not null default now(),
  updated_by bigint,
  deactivated_at timestamptz,
  deactivated_by bigint,
  deactivation_reason text,
  
  -- Constraints
  check (emirate_code = upper(emirate_code)),
  check (emirate_code ~ '^[A-Z]{3}$'),
  check (
    (is_active = true and deactivated_at is null) or
    (is_active = false and deactivated_at is not null)
  )
);

-- Comments
comment on table public.emirates is 'UAE Emirates (7 emirates)';
comment on column public.emirates.emirate_code is '3-letter uppercase code (e.g., AUH, DXB, SHJ)';

-- Indexes
create index if not exists idx_emirates_code on public.emirates(emirate_code);
create index if not exists idx_emirates_active on public.emirates(is_active);
create index if not exists idx_emirates_sort on public.emirates(sort_order);

-- Trigger for updated_at
create trigger trigger_emirates_updated_at
  before update on public.emirates
  for each row
  execute function public.set_updated_at();

-- ============================================================================
-- TABLE: cities
-- ============================================================================

create table if not exists public.cities (
  id bigint generated by default as identity primary key,
  
  -- City identification
  city_code text not null unique,
  name_en text not null,
  name_ar text,
  
  -- Parent relationship
  emirate_id bigint not null references public.emirates(id) on delete restrict,
  
  -- Status and governance
  is_system boolean not null default false,
  is_locked boolean not null default false,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  
  -- Audit fields
  created_at timestamptz not null default now(),
  created_by bigint,
  updated_at timestamptz not null default now(),
  updated_by bigint,
  deactivated_at timestamptz,
  deactivated_by bigint,
  deactivation_reason text,
  
  -- Constraints
  check (city_code = upper(city_code)),
  check (city_code ~ '^[A-Z0-9_]+$'),
  check (
    (is_active = true and deactivated_at is null) or
    (is_active = false and deactivated_at is not null)
  )
);

-- Comments
comment on table public.cities is 'Cities and municipalities within UAE emirates';
comment on column public.cities.city_code is 'Unique uppercase code for city (e.g., AUH_CITY, ALAIN)';

-- Indexes
create index if not exists idx_cities_code on public.cities(city_code);
create index if not exists idx_cities_emirate on public.cities(emirate_id);
create index if not exists idx_cities_active on public.cities(is_active);
create index if not exists idx_cities_sort on public.cities(sort_order);

-- Trigger for updated_at
create trigger trigger_cities_updated_at
  before update on public.cities
  for each row
  execute function public.set_updated_at();

-- ============================================================================
-- TABLE: areas_zones
-- ============================================================================

create table if not exists public.areas_zones (
  id bigint generated by default as identity primary key,
  
  -- Area/Zone identification
  area_code text not null unique,
  name_en text not null,
  name_ar text,
  
  -- Parent relationships
  city_id bigint not null references public.cities(id) on delete restrict,
  
  -- Area type (lookup reference)
  area_type_code text,
  
  -- Status and governance
  is_system boolean not null default false,
  is_locked boolean not null default false,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  
  -- Audit fields
  created_at timestamptz not null default now(),
  created_by bigint,
  updated_at timestamptz not null default now(),
  updated_by bigint,
  deactivated_at timestamptz,
  deactivated_by bigint,
  deactivation_reason text,
  
  -- Constraints
  check (area_code = upper(area_code)),
  check (area_code ~ '^[A-Z0-9_]+$'),
  check (
    (is_active = true and deactivated_at is null) or
    (is_active = false and deactivated_at is not null)
  )
);

-- Comments
comment on table public.areas_zones is 'Areas, zones, districts, and industrial areas within cities';
comment on column public.areas_zones.area_code is 'Unique uppercase code for area (e.g., MUSAFFAH, KHALIFA_CITY)';
comment on column public.areas_zones.area_type_code is 'Optional reference to AREA_TYPES lookup (RESIDENTIAL, COMMERCIAL, INDUSTRIAL, etc.)';

-- Indexes
create index if not exists idx_areas_zones_code on public.areas_zones(area_code);
create index if not exists idx_areas_zones_city on public.areas_zones(city_id);
create index if not exists idx_areas_zones_type on public.areas_zones(area_type_code) where area_type_code is not null;
create index if not exists idx_areas_zones_active on public.areas_zones(is_active);
create index if not exists idx_areas_zones_sort on public.areas_zones(sort_order);

-- Trigger for updated_at
create trigger trigger_areas_zones_updated_at
  before update on public.areas_zones
  for each row
  execute function public.set_updated_at();

-- ============================================================================
-- TABLE: ports
-- ============================================================================

create table if not exists public.ports (
  id bigint generated by default as identity primary key,
  
  -- Port identification
  port_code text not null unique,
  name_en text not null,
  name_ar text,
  
  -- Parent relationship
  emirate_id bigint not null references public.emirates(id) on delete restrict,
  
  -- Port type (lookup reference)
  port_type_code text not null,
  
  -- Optional ICAO/IATA codes for airports
  icao_code text,
  iata_code text,
  
  -- Status and governance
  is_system boolean not null default false,
  is_locked boolean not null default false,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  
  -- Audit fields
  created_at timestamptz not null default now(),
  created_by bigint,
  updated_at timestamptz not null default now(),
  updated_by bigint,
  deactivated_at timestamptz,
  deactivated_by bigint,
  deactivation_reason text,
  
  -- Constraints
  check (port_code = upper(port_code)),
  check (port_code ~ '^[A-Z0-9_]+$'),
  check (icao_code is null or icao_code = upper(icao_code)),
  check (iata_code is null or iata_code = upper(iata_code)),
  check (
    (is_active = true and deactivated_at is null) or
    (is_active = false and deactivated_at is not null)
  )
);

-- Comments
comment on table public.ports is 'Ports (maritime, air, land border) within UAE';
comment on column public.ports.port_code is 'Unique uppercase code for port (e.g., JEBEL_ALI, DXB_AIRPORT)';
comment on column public.ports.port_type_code is 'Reference to PORT_TYPES lookup (MARITIME, AIR, LAND_BORDER)';
comment on column public.ports.icao_code is '4-letter ICAO code for airports (e.g., OMDB)';
comment on column public.ports.iata_code is '3-letter IATA code for airports (e.g., DXB)';

-- Indexes
create index if not exists idx_ports_code on public.ports(port_code);
create index if not exists idx_ports_emirate on public.ports(emirate_id);
create index if not exists idx_ports_type on public.ports(port_type_code);
create index if not exists idx_ports_icao on public.ports(icao_code) where icao_code is not null;
create index if not exists idx_ports_iata on public.ports(iata_code) where iata_code is not null;
create index if not exists idx_ports_active on public.ports(is_active);
create index if not exists idx_ports_sort on public.ports(sort_order);

-- Trigger for updated_at
create trigger trigger_ports_updated_at
  before update on public.ports
  for each row
  execute function public.set_updated_at();

-- ============================================================================
-- PERMISSIONS: master_data.geography.*
-- ============================================================================

insert into public.permissions (permission_code, permission_name, module_code, action_code, description, is_active)
values
  ('master_data.geography.view', 'View Geography & Locations', 'master_data', 'view', 'View countries, emirates, cities, areas, ports', true),
  ('master_data.geography.manage', 'Manage Geography & Locations', 'master_data', 'manage', 'Create, update, deactivate geography and location master data', true)
on conflict (permission_code) do nothing;

-- Assign permissions to system_admin role
do $$
declare
  v_role_id bigint;
begin
  select id into v_role_id from public.roles where role_code = 'system_admin' limit 1;
  if v_role_id is not null then
    insert into public.role_permissions (role_id, permission_id)
    select v_role_id, id from public.permissions where permission_code in (
      'master_data.geography.view',
      'master_data.geography.manage'
    )
    on conflict (role_id, permission_id) do nothing;
  end if;
end $$;

-- ============================================================================
-- RLS POLICIES
-- ============================================================================

alter table public.countries enable row level security;
alter table public.emirates enable row level security;
alter table public.cities enable row level security;
alter table public.areas_zones enable row level security;
alter table public.ports enable row level security;

-- COUNTRIES policies
create policy select_countries_authenticated
  on public.countries
  for select
  using (
    is_active = true
    or public.current_user_has_permission('master_data.geography.view')
  );

create policy insert_countries
  on public.countries
  for insert
  with check (public.current_user_has_permission('master_data.geography.manage'));

create policy update_countries
  on public.countries
  for update
  using (public.current_user_has_permission('master_data.geography.manage'));

create policy delete_countries
  on public.countries
  for delete
  using (
    not is_system
    and not is_locked
    and public.current_user_has_permission('master_data.geography.manage')
  );

-- EMIRATES policies
create policy select_emirates_authenticated
  on public.emirates
  for select
  using (
    is_active = true
    or public.current_user_has_permission('master_data.geography.view')
  );

create policy insert_emirates
  on public.emirates
  for insert
  with check (public.current_user_has_permission('master_data.geography.manage'));

create policy update_emirates
  on public.emirates
  for update
  using (public.current_user_has_permission('master_data.geography.manage'));

create policy delete_emirates
  on public.emirates
  for delete
  using (
    not is_system
    and not is_locked
    and public.current_user_has_permission('master_data.geography.manage')
  );

-- CITIES policies
create policy select_cities_authenticated
  on public.cities
  for select
  using (
    is_active = true
    or public.current_user_has_permission('master_data.geography.view')
  );

create policy insert_cities
  on public.cities
  for insert
  with check (public.current_user_has_permission('master_data.geography.manage'));

create policy update_cities
  on public.cities
  for update
  using (public.current_user_has_permission('master_data.geography.manage'));

create policy delete_cities
  on public.cities
  for delete
  using (
    not is_system
    and not is_locked
    and public.current_user_has_permission('master_data.geography.manage')
  );

-- AREAS_ZONES policies
create policy select_areas_zones_authenticated
  on public.areas_zones
  for select
  using (
    is_active = true
    or public.current_user_has_permission('master_data.geography.view')
  );

create policy insert_areas_zones
  on public.areas_zones
  for insert
  with check (public.current_user_has_permission('master_data.geography.manage'));

create policy update_areas_zones
  on public.areas_zones
  for update
  using (public.current_user_has_permission('master_data.geography.manage'));

create policy delete_areas_zones
  on public.areas_zones
  for delete
  using (
    not is_system
    and not is_locked
    and public.current_user_has_permission('master_data.geography.manage')
  );

-- PORTS policies
create policy select_ports_authenticated
  on public.ports
  for select
  using (
    is_active = true
    or public.current_user_has_permission('master_data.geography.view')
  );

create policy insert_ports
  on public.ports
  for insert
  with check (public.current_user_has_permission('master_data.geography.manage'));

create policy update_ports
  on public.ports
  for update
  using (public.current_user_has_permission('master_data.geography.manage'));

create policy delete_ports
  on public.ports
  for delete
  using (
    not is_system
    and not is_locked
    and public.current_user_has_permission('master_data.geography.manage')
  );

-- ============================================================================
-- SEED DATA: GCC Countries
-- ============================================================================

do $$
declare
  v_user_id bigint;
begin
  -- Get current user profile ID for audit
  select id into v_user_id from public.user_profiles where auth_user_id = auth.uid() limit 1;

  -- Insert GCC countries
  insert into public.countries (country_code, iso3_code, name_en, name_ar, nationality_en, nationality_ar, phone_code, default_currency_code, is_gcc, is_uae, is_system, is_locked, sort_order, created_by)
  values
    ('AE', 'ARE', 'United Arab Emirates', 'الإمارات العربية المتحدة', 'Emirati', 'إماراتي', '+971', 'AED', true, true, true, true, 10, v_user_id),
    ('SA', 'SAU', 'Saudi Arabia', 'المملكة العربية السعودية', 'Saudi', 'سعودي', '+966', 'SAR', true, false, true, true, 20, v_user_id),
    ('KW', 'KWT', 'Kuwait', 'الكويت', 'Kuwaiti', 'كويتي', '+965', 'KWD', true, false, true, true, 30, v_user_id),
    ('QA', 'QAT', 'Qatar', 'قطر', 'Qatari', 'قطري', '+974', 'QAR', true, false, true, true, 40, v_user_id),
    ('BH', 'BHR', 'Bahrain', 'البحرين', 'Bahraini', 'بحريني', '+973', 'BHD', true, false, true, true, 50, v_user_id),
    ('OM', 'OMN', 'Oman', 'عمان', 'Omani', 'عماني', '+968', 'OMR', true, false, true, true, 60, v_user_id)
  on conflict (country_code) do nothing;

  -- Insert other common countries
  insert into public.countries (country_code, iso3_code, name_en, name_ar, nationality_en, nationality_ar, phone_code, is_gcc, is_uae, is_system, is_locked, sort_order, created_by)
  values
    ('US', 'USA', 'United States', 'الولايات المتحدة', 'American', 'أمريكي', '+1', false, false, false, false, 100, v_user_id),
    ('GB', 'GBR', 'United Kingdom', 'المملكة المتحدة', 'British', 'بريطاني', '+44', false, false, false, false, 110, v_user_id),
    ('IN', 'IND', 'India', 'الهند', 'Indian', 'هندي', '+91', false, false, false, false, 120, v_user_id),
    ('PK', 'PAK', 'Pakistan', 'باكستان', 'Pakistani', 'باكستاني', '+92', false, false, false, false, 130, v_user_id),
    ('EG', 'EGY', 'Egypt', 'مصر', 'Egyptian', 'مصري', '+20', false, false, false, false, 140, v_user_id),
    ('JO', 'JOR', 'Jordan', 'الأردن', 'Jordanian', 'أردني', '+962', false, false, false, false, 150, v_user_id),
    ('LB', 'LBN', 'Lebanon', 'لبنان', 'Lebanese', 'لبناني', '+961', false, false, false, false, 160, v_user_id),
    ('SY', 'SYR', 'Syria', 'سوريا', 'Syrian', 'سوري', '+963', false, false, false, false, 170, v_user_id),
    ('IQ', 'IRQ', 'Iraq', 'العراق', 'Iraqi', 'عراقي', '+964', false, false, false, false, 180, v_user_id)
  on conflict (country_code) do nothing;

end $$;

-- ============================================================================
-- SEED DATA: UAE Emirates
-- ============================================================================

do $$
declare
  v_user_id bigint;
begin
  -- Get current user profile ID for audit
  select id into v_user_id from public.user_profiles where auth_user_id = auth.uid() limit 1;

  -- Insert 7 UAE emirates
  insert into public.emirates (emirate_code, name_en, name_ar, abbreviation_en, abbreviation_ar, is_system, is_locked, sort_order, created_by)
  values
    ('AUH', 'Abu Dhabi', 'أبوظبي', 'AD', 'أ.ظ', true, true, 10, v_user_id),
    ('DXB', 'Dubai', 'دبي', 'DXB', 'دبي', true, true, 20, v_user_id),
    ('SHJ', 'Sharjah', 'الشارقة', 'SHJ', 'شج', true, true, 30, v_user_id),
    ('AJM', 'Ajman', 'عجمان', 'AJM', 'عج', true, true, 40, v_user_id),
    ('UAQ', 'Umm Al Quwain', 'أم القيوين', 'UAQ', 'أ.ق', true, true, 50, v_user_id),
    ('RAK', 'Ras Al Khaimah', 'رأس الخيمة', 'RAK', 'ر.خ', true, true, 60, v_user_id),
    ('FUJ', 'Fujairah', 'الفجيرة', 'FUJ', 'فج', true, true, 70, v_user_id)
  on conflict (emirate_code) do nothing;

end $$;

-- ============================================================================
-- SEED DATA: UAE Cities (Major Cities for Each Emirate)
-- ============================================================================

do $$
declare
  v_user_id bigint;
  v_emirate_id_auh bigint;
  v_emirate_id_dxb bigint;
  v_emirate_id_shj bigint;
  v_emirate_id_ajm bigint;
  v_emirate_id_uaq bigint;
  v_emirate_id_rak bigint;
  v_emirate_id_fuj bigint;
begin
  -- Get current user profile ID for audit
  select id into v_user_id from public.user_profiles where auth_user_id = auth.uid() limit 1;

  -- Get emirate IDs
  select id into v_emirate_id_auh from public.emirates where emirate_code = 'AUH';
  select id into v_emirate_id_dxb from public.emirates where emirate_code = 'DXB';
  select id into v_emirate_id_shj from public.emirates where emirate_code = 'SHJ';
  select id into v_emirate_id_ajm from public.emirates where emirate_code = 'AJM';
  select id into v_emirate_id_uaq from public.emirates where emirate_code = 'UAQ';
  select id into v_emirate_id_rak from public.emirates where emirate_code = 'RAK';
  select id into v_emirate_id_fuj from public.emirates where emirate_code = 'FUJ';

  -- Insert cities for Abu Dhabi
  insert into public.cities (city_code, name_en, name_ar, emirate_id, is_system, is_locked, sort_order, created_by)
  values
    ('AUH_CITY', 'Abu Dhabi City', 'مدينة أبوظبي', v_emirate_id_auh, true, true, 10, v_user_id),
    ('ALAIN', 'Al Ain', 'العين', v_emirate_id_auh, true, true, 20, v_user_id),
    ('MADINAT_ZAYED', 'Madinat Zayed', 'مدينة زايد', v_emirate_id_auh, true, true, 30, v_user_id)
  on conflict (city_code) do nothing;

  -- Insert cities for Dubai
  insert into public.cities (city_code, name_en, name_ar, emirate_id, is_system, is_locked, sort_order, created_by)
  values
    ('DXB_CITY', 'Dubai City', 'مدينة دبي', v_emirate_id_dxb, true, true, 10, v_user_id),
    ('HATTA', 'Hatta', 'حتا', v_emirate_id_dxb, true, true, 20, v_user_id)
  on conflict (city_code) do nothing;

  -- Insert cities for Sharjah
  insert into public.cities (city_code, name_en, name_ar, emirate_id, is_system, is_locked, sort_order, created_by)
  values
    ('SHJ_CITY', 'Sharjah City', 'مدينة الشارقة', v_emirate_id_shj, true, true, 10, v_user_id),
    ('KALBA', 'Kalba', 'كلباء', v_emirate_id_shj, true, true, 20, v_user_id),
    ('KHOR_FAKKAN', 'Khor Fakkan', 'خورفكان', v_emirate_id_shj, true, true, 30, v_user_id),
    ('DIBBA_AL_HISN', 'Dibba Al Hisn', 'دبا الحصن', v_emirate_id_shj, true, true, 40, v_user_id)
  on conflict (city_code) do nothing;

  -- Insert cities for Ajman
  insert into public.cities (city_code, name_en, name_ar, emirate_id, is_system, is_locked, sort_order, created_by)
  values
    ('AJM_CITY', 'Ajman City', 'مدينة عجمان', v_emirate_id_ajm, true, true, 10, v_user_id)
  on conflict (city_code) do nothing;

  -- Insert cities for Umm Al Quwain
  insert into public.cities (city_code, name_en, name_ar, emirate_id, is_system, is_locked, sort_order, created_by)
  values
    ('UAQ_CITY', 'Umm Al Quwain City', 'مدينة أم القيوين', v_emirate_id_uaq, true, true, 10, v_user_id)
  on conflict (city_code) do nothing;

  -- Insert cities for Ras Al Khaimah
  insert into public.cities (city_code, name_en, name_ar, emirate_id, is_system, is_locked, sort_order, created_by)
  values
    ('RAK_CITY', 'Ras Al Khaimah City', 'مدينة رأس الخيمة', v_emirate_id_rak, true, true, 10, v_user_id),
    ('DIBBA_AL_BAY', 'Dibba Al Bay', 'دبا البيعة', v_emirate_id_rak, true, true, 20, v_user_id)
  on conflict (city_code) do nothing;

  -- Insert cities for Fujairah
  insert into public.cities (city_code, name_en, name_ar, emirate_id, is_system, is_locked, sort_order, created_by)
  values
    ('FUJ_CITY', 'Fujairah City', 'مدينة الفجيرة', v_emirate_id_fuj, true, true, 10, v_user_id),
    ('DIBBA_AL_FUJAIRAH', 'Dibba Al Fujairah', 'دبا الفجيرة', v_emirate_id_fuj, true, true, 20, v_user_id)
  on conflict (city_code) do nothing;

end $$;

-- ============================================================================
-- SEED DATA: UAE Areas/Zones (Sample for Abu Dhabi & Dubai)
-- ============================================================================

do $$
declare
  v_user_id bigint;
  v_city_id_auh bigint;
  v_city_id_dxb bigint;
begin
  -- Get current user profile ID for audit
  select id into v_user_id from public.user_profiles where auth_user_id = auth.uid() limit 1;

  -- Get city IDs
  select id into v_city_id_auh from public.cities where city_code = 'AUH_CITY';
  select id into v_city_id_dxb from public.cities where city_code = 'DXB_CITY';

  -- Insert areas/zones for Abu Dhabi City
  insert into public.areas_zones (area_code, name_en, name_ar, city_id, area_type_code, is_system, is_locked, sort_order, created_by)
  values
    ('MUSAFFAH', 'Musaffah', 'مصفح', v_city_id_auh, 'INDUSTRIAL', true, true, 10, v_user_id),
    ('KHALIFA_CITY', 'Khalifa City', 'مدينة خليفة', v_city_id_auh, 'RESIDENTIAL', true, true, 20, v_user_id),
    ('KHALIDIYA', 'Al Khalidiya', 'الخالدية', v_city_id_auh, 'MIXED_USE', true, true, 30, v_user_id),
    ('MARINA', 'Al Marina', 'المارينا', v_city_id_auh, 'COMMERCIAL', true, true, 40, v_user_id),
    ('REEM_ISLAND', 'Al Reem Island', 'جزيرة الريم', v_city_id_auh, 'MIXED_USE', true, true, 50, v_user_id),
    ('YAS_ISLAND', 'Yas Island', 'جزيرة ياس', v_city_id_auh, 'TOURISM', true, true, 60, v_user_id),
    ('SAADIYAT_ISLAND', 'Saadiyat Island', 'جزيرة السعديات', v_city_id_auh, 'TOURISM', true, true, 70, v_user_id),
    ('MASDAR_CITY', 'Masdar City', 'مدينة مصدر', v_city_id_auh, 'MIXED_USE', true, true, 80, v_user_id),
    ('ICAD', 'ICAD (Industrial City of Abu Dhabi)', 'المدينة الصناعية أبوظبي', v_city_id_auh, 'INDUSTRIAL', true, true, 90, v_user_id),
    ('MUSSAFAH_SHABIYA', 'Mussafah Shabiya', 'مصفح شعبية', v_city_id_auh, 'RESIDENTIAL', true, true, 100, v_user_id)
  on conflict (area_code) do nothing;

  -- Insert areas/zones for Dubai City
  insert into public.areas_zones (area_code, name_en, name_ar, city_id, area_type_code, is_system, is_locked, sort_order, created_by)
  values
    ('JEBEL_ALI', 'Jebel Ali', 'جبل علي', v_city_id_dxb, 'INDUSTRIAL', true, true, 10, v_user_id),
    ('DUBAI_MARINA', 'Dubai Marina', 'مارينا دبي', v_city_id_dxb, 'RESIDENTIAL', true, true, 20, v_user_id),
    ('DOWNTOWN_DUBAI', 'Downtown Dubai', 'وسط مدينة دبي', v_city_id_dxb, 'MIXED_USE', true, true, 30, v_user_id),
    ('DEIRA', 'Deira', 'ديرة', v_city_id_dxb, 'COMMERCIAL', true, true, 40, v_user_id),
    ('BUR_DUBAI', 'Bur Dubai', 'بر دبي', v_city_id_dxb, 'COMMERCIAL', true, true, 50, v_user_id),
    ('JUMEIRAH', 'Jumeirah', 'جميرا', v_city_id_dxb, 'RESIDENTIAL', true, true, 60, v_user_id),
    ('BUSINESS_BAY', 'Business Bay', 'الخليج التجاري', v_city_id_dxb, 'COMMERCIAL', true, true, 70, v_user_id),
    ('AL_QUOZ', 'Al Quoz', 'القوز', v_city_id_dxb, 'INDUSTRIAL', true, true, 80, v_user_id),
    ('DUBAI_INVESTMENT_PARK', 'Dubai Investment Park', 'حديقة دبي للاستثمار', v_city_id_dxb, 'INDUSTRIAL', true, true, 90, v_user_id),
    ('DUBAI_SILICON_OASIS', 'Dubai Silicon Oasis', 'واحة دبي للسيليكون', v_city_id_dxb, 'FREE_ZONE', true, true, 100, v_user_id),
    ('DUBAI_INTERNET_CITY', 'Dubai Internet City', 'مدينة دبي للإنترنت', v_city_id_dxb, 'FREE_ZONE', true, true, 110, v_user_id),
    ('DUBAI_MEDIA_CITY', 'Dubai Media City', 'مدينة دبي للإعلام', v_city_id_dxb, 'FREE_ZONE', true, true, 120, v_user_id)
  on conflict (area_code) do nothing;

end $$;

-- ============================================================================
-- SEED DATA: UAE Ports (Major Maritime, Air, and Land Border Ports)
-- ============================================================================

do $$
declare
  v_user_id bigint;
  v_emirate_id_auh bigint;
  v_emirate_id_dxb bigint;
  v_emirate_id_shj bigint;
  v_emirate_id_ajm bigint;
  v_emirate_id_uaq bigint;
  v_emirate_id_rak bigint;
  v_emirate_id_fuj bigint;
begin
  -- Get current user profile ID for audit
  select id into v_user_id from public.user_profiles where auth_user_id = auth.uid() limit 1;

  -- Get emirate IDs
  select id into v_emirate_id_auh from public.emirates where emirate_code = 'AUH';
  select id into v_emirate_id_dxb from public.emirates where emirate_code = 'DXB';
  select id into v_emirate_id_shj from public.emirates where emirate_code = 'SHJ';
  select id into v_emirate_id_ajm from public.emirates where emirate_code = 'AJM';
  select id into v_emirate_id_uaq from public.emirates where emirate_code = 'UAQ';
  select id into v_emirate_id_rak from public.emirates where emirate_code = 'RAK';
  select id into v_emirate_id_fuj from public.emirates where emirate_code = 'FUJ';

  -- Insert maritime ports
  insert into public.ports (port_code, name_en, name_ar, emirate_id, port_type_code, icao_code, iata_code, is_system, is_locked, sort_order, created_by)
  values
    ('JEBEL_ALI_PORT', 'Jebel Ali Port', 'ميناء جبل علي', v_emirate_id_dxb, 'MARITIME', null, null, true, true, 10, v_user_id),
    ('PORT_RASHID', 'Port Rashid', 'ميناء راشد', v_emirate_id_dxb, 'MARITIME', null, null, true, true, 20, v_user_id),
    ('KHALIFA_PORT', 'Khalifa Port', 'ميناء خليفة', v_emirate_id_auh, 'MARITIME', null, null, true, true, 30, v_user_id),
    ('ZAYED_PORT', 'Zayed Port', 'ميناء زايد', v_emirate_id_auh, 'MARITIME', null, null, true, true, 40, v_user_id),
    ('MINA_SAQR', 'Mina Saqr (RAK Port)', 'ميناء صقر', v_emirate_id_rak, 'MARITIME', null, null, true, true, 50, v_user_id),
    ('SHARJAH_PORT', 'Sharjah Port (Hamriyah)', 'ميناء الشارقة', v_emirate_id_shj, 'MARITIME', null, null, true, true, 60, v_user_id),
    ('KHOR_FAKKAN_PORT', 'Khor Fakkan Port', 'ميناء خورفكان', v_emirate_id_shj, 'MARITIME', null, null, true, true, 70, v_user_id),
    ('FUJAIRAH_PORT', 'Fujairah Port', 'ميناء الفجيرة', v_emirate_id_fuj, 'MARITIME', null, null, true, true, 80, v_user_id),
    ('AJMAN_PORT', 'Ajman Port', 'ميناء عجمان', v_emirate_id_ajm, 'MARITIME', null, null, true, true, 90, v_user_id)
  on conflict (port_code) do nothing;

  -- Insert airports
  insert into public.ports (port_code, name_en, name_ar, emirate_id, port_type_code, icao_code, iata_code, is_system, is_locked, sort_order, created_by)
  values
    ('DXB_AIRPORT', 'Dubai International Airport', 'مطار دبي الدولي', v_emirate_id_dxb, 'AIR', 'OMDB', 'DXB', true, true, 100, v_user_id),
    ('DWC_AIRPORT', 'Al Maktoum International Airport (DWC)', 'مطار آل مكتوم الدولي', v_emirate_id_dxb, 'AIR', 'OMDW', 'DWC', true, true, 110, v_user_id),
    ('AUH_AIRPORT', 'Abu Dhabi International Airport', 'مطار أبوظبي الدولي', v_emirate_id_auh, 'AIR', 'OMAA', 'AUH', true, true, 120, v_user_id),
    ('AAN_AIRPORT', 'Al Ain International Airport', 'مطار العين الدولي', v_emirate_id_auh, 'AIR', 'OMAL', 'AAN', true, true, 130, v_user_id),
    ('SHJ_AIRPORT', 'Sharjah International Airport', 'مطار الشارقة الدولي', v_emirate_id_shj, 'AIR', 'OMSJ', 'SHJ', true, true, 140, v_user_id),
    ('RAK_AIRPORT', 'Ras Al Khaimah International Airport', 'مطار رأس الخيمة الدولي', v_emirate_id_rak, 'AIR', 'OMRK', 'RKT', true, true, 150, v_user_id),
    ('FJR_AIRPORT', 'Fujairah International Airport', 'مطار الفجيرة الدولي', v_emirate_id_fuj, 'AIR', 'OMFJ', 'FJR', true, true, 160, v_user_id)
  on conflict (port_code) do nothing;

  -- Insert land border crossings
  insert into public.ports (port_code, name_en, name_ar, emirate_id, port_type_code, icao_code, iata_code, is_system, is_locked, sort_order, created_by)
  values
    ('AL_GHUWAIFAT', 'Al Ghuwaifat Border (UAE-SA)', 'منفذ الغويفات', v_emirate_id_auh, 'LAND_BORDER', null, null, true, true, 200, v_user_id),
    ('HATTA_BORDER', 'Hatta Border (UAE-OM)', 'منفذ حتا', v_emirate_id_dxb, 'LAND_BORDER', null, null, true, true, 210, v_user_id),
    ('KHATM_AL_SHAKLAH', 'Khatm Al Shaklah Border (UAE-OM)', 'منفذ ختم الشكلة', v_emirate_id_fuj, 'LAND_BORDER', null, null, true, true, 220, v_user_id)
  on conflict (port_code) do nothing;

end $$;

-- ============================================================================
-- END OF MIGRATION
-- ============================================================================
