-- ============================================================================
-- ERP COMMON AI.1B — DB Tables, RLS, Permissions, Server Action Skeleton
-- Migration: erp_common_ai_1b_field_suggestions_tables
-- Date: 2026-06-16
-- Scope:
--   1. erp_ai_field_suggestions  — field suggestion persistence
--   2. erp_ai_field_suggestion_events — append-only audit trail
--   3. Explicit pilot entity permission helper functions
--   4. RLS ENABLED + FORCED on both tables
--
-- Does NOT:
--   - Call OpenAI
--   - Create DMS evidence loader
--   - Build UI
--   - Apply suggestions to ERP records
--   - Create erp_ai_record_ai_status (deferred to UI phase if needed)
-- ============================================================================

-- ============================================================================
-- SECTION 1: erp_ai_field_suggestions
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.erp_ai_field_suggestions (
  id                    BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

  -- Target entity (pilot: company | party | branch | site)
  entity_type           TEXT NOT NULL,
  entity_id             BIGINT NOT NULL,

  -- Target field
  target_table          TEXT NOT NULL,
  target_field          TEXT NOT NULL,
  field_label           TEXT NOT NULL,
  field_type            TEXT NOT NULL,

  -- Values
  current_value         TEXT,
  suggested_value       TEXT,
  suggested_value_json  JSONB,

  -- AI metadata
  suggestion_type       TEXT NOT NULL,
  confidence_score      NUMERIC(5,4),

  -- Evidence references (links to DMS)
  source_document_id    BIGINT REFERENCES public.dms_documents(id) ON DELETE SET NULL,
  source_file_id        BIGINT REFERENCES public.dms_document_files(id) ON DELETE SET NULL,
  source_document_type  TEXT,
  source_excerpt        TEXT,
  ai_reason             TEXT,

  -- Lifecycle
  status                TEXT NOT NULL DEFAULT 'pending',

  -- Human action tracking
  accepted_by           BIGINT REFERENCES public.user_profiles(id) ON DELETE SET NULL,
  accepted_at           TIMESTAMPTZ,
  rejected_by           BIGINT REFERENCES public.user_profiles(id) ON DELETE SET NULL,
  rejected_at           TIMESTAMPTZ,
  applied_by            BIGINT REFERENCES public.user_profiles(id) ON DELETE SET NULL,
  applied_at            TIMESTAMPTZ,

  -- Error tracking
  apply_error           TEXT,

  -- Generation metadata
  generation_batch_id   BIGINT,
  prompt_version        TEXT,

  -- Standard audit columns
  created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by            BIGINT REFERENCES public.user_profiles(id) ON DELETE SET NULL,
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_by            BIGINT REFERENCES public.user_profiles(id) ON DELETE SET NULL,
  deleted_at            TIMESTAMPTZ,

  -- Constraints
  CONSTRAINT erp_ai_field_suggestions_entity_type_chk CHECK (
    entity_type IN ('company','party','branch','site')
  ),
  CONSTRAINT erp_ai_field_suggestions_field_type_chk CHECK (
    field_type IN ('text','date','number','boolean','fk','json')
  ),
  CONSTRAINT erp_ai_field_suggestions_type_chk CHECK (
    suggestion_type IN (
      'fill_missing','correct_value','update_existing',
      'clear_wrong_value','conflict_detected','needs_human_review'
    )
  ),
  CONSTRAINT erp_ai_field_suggestions_status_chk CHECK (
    status IN ('pending','accepted','rejected','superseded','applied','failed')
  ),
  CONSTRAINT erp_ai_field_suggestions_confidence_chk CHECK (
    confidence_score IS NULL
    OR (confidence_score >= 0 AND confidence_score <= 1)
  ),
  CONSTRAINT erp_ai_field_suggestions_excerpt_len_chk CHECK (
    source_excerpt IS NULL OR char_length(source_excerpt) <= 500
  ),
  CONSTRAINT erp_ai_field_suggestions_reason_len_chk CHECK (
    ai_reason IS NULL OR char_length(ai_reason) <= 1000
  )
);

COMMENT ON TABLE public.erp_ai_field_suggestions IS
  'Common AI.1B — Field suggestion records generated by the Universal Internal AI Engine. '
  'All suggestions require human review before apply. No auto-apply.';

-- Indexes
CREATE INDEX IF NOT EXISTS idx_erp_ai_field_suggestions_entity_status
  ON public.erp_ai_field_suggestions(entity_type, entity_id, status)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_erp_ai_field_suggestions_source_document
  ON public.erp_ai_field_suggestions(source_document_id)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_erp_ai_field_suggestions_generation_batch
  ON public.erp_ai_field_suggestions(generation_batch_id)
  WHERE generation_batch_id IS NOT NULL AND deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_erp_ai_field_suggestions_created_by
  ON public.erp_ai_field_suggestions(created_by)
  WHERE deleted_at IS NULL;

-- Unique index: prevents duplicate PENDING suggestions for the same field on the same entity.
-- Does NOT block multiple conflict_detected or needs_human_review suggestions from different
-- generation runs (those are already in pending before supersede logic runs in Phase 1D).
CREATE UNIQUE INDEX IF NOT EXISTS uq_erp_ai_field_suggestions_pending_field
  ON public.erp_ai_field_suggestions(entity_type, entity_id, target_table, target_field)
  WHERE status = 'pending' AND deleted_at IS NULL;

-- updated_at auto-maintenance via existing project trigger function
DROP TRIGGER IF EXISTS trg_erp_ai_field_suggestions_updated_at ON public.erp_ai_field_suggestions;
CREATE TRIGGER trg_erp_ai_field_suggestions_updated_at
  BEFORE UPDATE ON public.erp_ai_field_suggestions
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ============================================================================
-- SECTION 2: erp_ai_field_suggestion_events (append-only audit trail)
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.erp_ai_field_suggestion_events (
  id              BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  suggestion_id   BIGINT NOT NULL
    REFERENCES public.erp_ai_field_suggestions(id) ON DELETE CASCADE,
  event_type      TEXT NOT NULL,
  event_data_json JSONB,
  actor_user_id   BIGINT REFERENCES public.user_profiles(id) ON DELETE SET NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT erp_ai_field_suggestion_events_type_chk CHECK (
    event_type IN (
      'generated','accepted','rejected','applied',
      'apply_failed','superseded','status_changed'
    )
  )
);

COMMENT ON TABLE public.erp_ai_field_suggestion_events IS
  'Common AI.1B — Append-only audit trail for field suggestion lifecycle events. '
  'No UPDATE or DELETE. event_data_json contains safe metadata only (no OCR/prompts/keys).';

CREATE INDEX IF NOT EXISTS idx_erp_ai_field_suggestion_events_suggestion
  ON public.erp_ai_field_suggestion_events(suggestion_id);

CREATE INDEX IF NOT EXISTS idx_erp_ai_field_suggestion_events_actor
  ON public.erp_ai_field_suggestion_events(actor_user_id);

CREATE INDEX IF NOT EXISTS idx_erp_ai_field_suggestion_events_created
  ON public.erp_ai_field_suggestion_events(created_at DESC);

-- ============================================================================
-- SECTION 3: RLS — erp_ai_field_suggestions
-- ============================================================================

ALTER TABLE public.erp_ai_field_suggestions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.erp_ai_field_suggestions FORCE ROW LEVEL SECURITY;

-- SELECT: ai.field_suggestions.view + entity view access, OR admin
DROP POLICY IF EXISTS erp_ai_field_suggestions_select ON public.erp_ai_field_suggestions;
CREATE POLICY erp_ai_field_suggestions_select
  ON public.erp_ai_field_suggestions FOR SELECT
  USING (
    deleted_at IS NULL
    AND (
      (
        current_user_has_permission('ai.field_suggestions.view')
        AND current_user_can_view_ai_entity(entity_type, entity_id)
      )
      OR current_user_has_permission('ai.common.admin')
      OR current_user_has_role('system_admin')
    )
  );

-- INSERT: ai.field_suggestions.generate + entity view access + own row
DROP POLICY IF EXISTS erp_ai_field_suggestions_insert ON public.erp_ai_field_suggestions;
CREATE POLICY erp_ai_field_suggestions_insert
  ON public.erp_ai_field_suggestions FOR INSERT
  WITH CHECK (
    (
      current_user_has_permission('ai.field_suggestions.generate')
      AND current_user_can_view_ai_entity(entity_type, entity_id)
      AND created_by = current_user_profile_id()
    )
    OR current_user_has_permission('ai.common.admin')
    OR current_user_has_role('system_admin')
  );

-- UPDATE: ai.field_suggestions.apply + entity manage access, OR admin
DROP POLICY IF EXISTS erp_ai_field_suggestions_update ON public.erp_ai_field_suggestions;
CREATE POLICY erp_ai_field_suggestions_update
  ON public.erp_ai_field_suggestions FOR UPDATE
  USING (
    deleted_at IS NULL
    AND (
      (
        current_user_has_permission('ai.field_suggestions.apply')
        AND current_user_can_manage_ai_entity(entity_type, entity_id)
      )
      OR current_user_has_permission('ai.common.admin')
      OR current_user_has_role('system_admin')
    )
  )
  WITH CHECK (
    (
      current_user_has_permission('ai.field_suggestions.apply')
      AND current_user_can_manage_ai_entity(entity_type, entity_id)
    )
    OR current_user_has_permission('ai.common.admin')
    OR current_user_has_role('system_admin')
  );

-- No DELETE policy — soft delete only via UPDATE deleted_at.

-- ============================================================================
-- SECTION 4: RLS — erp_ai_field_suggestion_events
-- ============================================================================

ALTER TABLE public.erp_ai_field_suggestion_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.erp_ai_field_suggestion_events FORCE ROW LEVEL SECURITY;

-- SELECT: ai.field_suggestions.view + can view parent suggestion entity, OR admin
DROP POLICY IF EXISTS erp_ai_field_suggestion_events_select ON public.erp_ai_field_suggestion_events;
CREATE POLICY erp_ai_field_suggestion_events_select
  ON public.erp_ai_field_suggestion_events FOR SELECT
  USING (
    (
      current_user_has_permission('ai.field_suggestions.view')
      AND EXISTS (
        SELECT 1 FROM public.erp_ai_field_suggestions s
        WHERE s.id = suggestion_id
          AND s.deleted_at IS NULL
          AND current_user_can_view_ai_entity(s.entity_type, s.entity_id)
      )
    )
    OR current_user_has_permission('ai.common.admin')
    OR current_user_has_role('system_admin')
  );

-- INSERT: actor must be current user + can view parent entity + relevant permission
DROP POLICY IF EXISTS erp_ai_field_suggestion_events_insert ON public.erp_ai_field_suggestion_events;
CREATE POLICY erp_ai_field_suggestion_events_insert
  ON public.erp_ai_field_suggestion_events FOR INSERT
  WITH CHECK (
    (
      actor_user_id = current_user_profile_id()
      AND (
        current_user_has_permission('ai.field_suggestions.view')
        OR current_user_has_permission('ai.field_suggestions.generate')
        OR current_user_has_permission('ai.field_suggestions.apply')
      )
      AND EXISTS (
        SELECT 1 FROM public.erp_ai_field_suggestions s
        WHERE s.id = suggestion_id
          AND s.deleted_at IS NULL
          AND current_user_can_view_ai_entity(s.entity_type, s.entity_id)
      )
    )
    OR current_user_has_permission('ai.common.admin')
    OR current_user_has_role('system_admin')
  );

-- No UPDATE or DELETE — append-only audit trail.

-- ============================================================================
-- SECTION 5: Explicit Pilot Entity Permission Helper Functions
--
-- Rules:
-- - Explicit CASE mapping only — no dynamic SQL
-- - Return false for any entity_type outside company/party/branch/site
-- - Uses existing current_user_has_permission()
-- - Checks entity row exists (soft-delete aware)
-- ============================================================================

CREATE OR REPLACE FUNCTION public.current_user_can_view_ai_entity(
  p_entity_type TEXT,
  p_entity_id   BIGINT
)
RETURNS BOOLEAN
LANGUAGE plpgsql
STABLE
SECURITY INVOKER
AS $$
DECLARE
  v_has_permission BOOLEAN := false;
  v_entity_exists  BOOLEAN := false;
BEGIN
  -- Map entity_type to required view permission
  CASE p_entity_type
    WHEN 'company' THEN
      v_has_permission := current_user_has_permission('organizations.view')
                          OR current_user_has_role('system_admin');
      SELECT EXISTS(
        SELECT 1 FROM public.owner_companies
        WHERE id = p_entity_id AND deleted_at IS NULL
      ) INTO v_entity_exists;

    WHEN 'party' THEN
      v_has_permission := current_user_has_permission('master_data.party_master.view')
                          OR current_user_has_role('system_admin');
      SELECT EXISTS(
        SELECT 1 FROM public.parties
        WHERE id = p_entity_id AND deleted_at IS NULL
      ) INTO v_entity_exists;

    WHEN 'branch' THEN
      v_has_permission := current_user_has_permission('branches.view')
                          OR current_user_has_role('system_admin');
      SELECT EXISTS(
        SELECT 1 FROM public.branches
        WHERE id = p_entity_id AND deleted_at IS NULL
      ) INTO v_entity_exists;

    WHEN 'site' THEN
      v_has_permission := current_user_has_permission('common_md.work_sites.view')
                          OR current_user_has_role('system_admin');
      SELECT EXISTS(
        SELECT 1 FROM public.work_sites
        WHERE id = p_entity_id AND deleted_at IS NULL
      ) INTO v_entity_exists;

    ELSE
      -- Unregistered entity type — always deny
      RETURN false;
  END CASE;

  RETURN v_has_permission AND v_entity_exists;
END;
$$;

COMMENT ON FUNCTION public.current_user_can_view_ai_entity(TEXT, BIGINT) IS
  'Common AI.1B — Returns true if the current user has view permission for the given AI entity type and the entity row exists. '
  'Explicit CASE mapping only — no dynamic SQL. Returns false for unregistered entity types.';

CREATE OR REPLACE FUNCTION public.current_user_can_manage_ai_entity(
  p_entity_type TEXT,
  p_entity_id   BIGINT
)
RETURNS BOOLEAN
LANGUAGE plpgsql
STABLE
SECURITY INVOKER
AS $$
DECLARE
  v_has_permission BOOLEAN := false;
  v_entity_exists  BOOLEAN := false;
BEGIN
  -- Map entity_type to required manage permission
  CASE p_entity_type
    WHEN 'company' THEN
      v_has_permission := current_user_has_permission('organizations.manage')
                          OR current_user_has_role('system_admin');
      SELECT EXISTS(
        SELECT 1 FROM public.owner_companies
        WHERE id = p_entity_id AND deleted_at IS NULL
      ) INTO v_entity_exists;

    WHEN 'party' THEN
      v_has_permission := current_user_has_permission('master_data.party_master.manage')
                          OR current_user_has_role('system_admin');
      SELECT EXISTS(
        SELECT 1 FROM public.parties
        WHERE id = p_entity_id AND deleted_at IS NULL
      ) INTO v_entity_exists;

    WHEN 'branch' THEN
      v_has_permission := current_user_has_permission('branches.manage')
                          OR current_user_has_role('system_admin');
      SELECT EXISTS(
        SELECT 1 FROM public.branches
        WHERE id = p_entity_id AND deleted_at IS NULL
      ) INTO v_entity_exists;

    WHEN 'site' THEN
      v_has_permission := current_user_has_permission('common_md.work_sites.manage')
                          OR current_user_has_role('system_admin');
      SELECT EXISTS(
        SELECT 1 FROM public.work_sites
        WHERE id = p_entity_id AND deleted_at IS NULL
      ) INTO v_entity_exists;

    ELSE
      -- Unregistered entity type — always deny
      RETURN false;
  END CASE;

  RETURN v_has_permission AND v_entity_exists;
END;
$$;

COMMENT ON FUNCTION public.current_user_can_manage_ai_entity(TEXT, BIGINT) IS
  'Common AI.1B — Returns true if the current user has manage permission for the given AI entity type and the entity row exists. '
  'Explicit CASE mapping only — no dynamic SQL. Returns false for unregistered entity types.';
