-- =============================================================================
-- BRANDING.6 — Public QR Verification System
-- Date: 2026-07-02
-- Depends on: BRANDING.1 (erp_branding_assets), REPORT.2 (erp_report_branding_profiles),
--             REPORT.5 (erp_report_runs, erp_report_templates), ERP base (owner_companies)
-- =============================================================================
-- HARD RULES:
--   1. BIGINT GENERATED BY DEFAULT AS IDENTITY PKs — no UUID, no SERIAL
--   2. RLS enabled and forced on all new tables
--   3. No public storage bucket
--   4. Public verification must never expose internal IDs in API responses
--   5. Public lookup via SECURITY DEFINER RPC only — not via broad anon SELECT
-- =============================================================================

-- ─────────────────────────────────────────────────────────────────────────────
-- 1. PERMISSIONS
-- ─────────────────────────────────────────────────────────────────────────────

INSERT INTO public.permissions (
  permission_code, permission_name, module_code, action_code, description,
  is_active, is_system_permission, is_visible, sort_order
)
VALUES
  (
    'reports.publish', 'Publish Output Verification Links', 'REPORTS', 'publish',
    'Create and manage public verification links for issued ERP outputs (letters, certificates, reports)',
    true, true, true, 562
  ),
  (
    'reports.verify.admin', 'Administer Verification Links', 'REPORTS', 'admin',
    'Manage, cancel, and override status of public verification links',
    true, true, true, 563
  )
ON CONFLICT (permission_code) DO NOTHING;

-- Grant to system_admin (all)
INSERT INTO public.role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM public.roles r
CROSS JOIN public.permissions p
WHERE r.role_code = 'system_admin'
  AND p.permission_code IN ('reports.publish', 'reports.verify.admin')
ON CONFLICT DO NOTHING;

-- Grant to group_admin (publish only — verify.admin via system_admin escalation)
INSERT INTO public.role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM public.roles r
CROSS JOIN public.permissions p
WHERE r.role_code = 'group_admin'
  AND p.permission_code IN ('reports.publish', 'reports.verify.admin')
ON CONFLICT DO NOTHING;

-- Grant to company_admin (publish — consistent with reports.manage)
INSERT INTO public.role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM public.roles r
CROSS JOIN public.permissions p
WHERE r.role_code = 'company_admin'
  AND p.permission_code = 'reports.publish'
ON CONFLICT DO NOTHING;

-- ─────────────────────────────────────────────────────────────────────────────
-- 2. MAIN TABLE: erp_output_public_links
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.erp_output_public_links (
  id                              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- Public verification token — never expose internal IDs in URLs
  public_token                    TEXT NOT NULL,
  public_url_path                 TEXT NOT NULL,  -- e.g. /verify/abc123...

  -- Document classification
  output_type                     TEXT NOT NULL,
  source_module                   TEXT NOT NULL,
  source_entity_type              TEXT NULL,
  source_entity_id                BIGINT NULL,
  source_record_ref               TEXT NULL,

  -- Safe document identity (stored here; never look up from source at verification time)
  document_title                  TEXT NOT NULL,
  document_subtitle               TEXT NULL,
  document_ref                    TEXT NULL,
  document_date                   DATE NULL,

  -- Relations (nullable for external/standalone outputs)
  owner_company_id                BIGINT NULL REFERENCES public.owner_companies(id),
  branding_profile_id             BIGINT NULL REFERENCES public.erp_report_branding_profiles(id),
  template_id                     BIGINT NULL REFERENCES public.erp_report_templates(id),
  report_run_id                   BIGINT NULL REFERENCES public.erp_report_runs(id),

  -- Issuance tracking
  issued_by_user_profile_id       BIGINT NULL REFERENCES public.user_profiles(id),
  issued_at                       TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at                      TIMESTAMPTZ NULL,

  -- Cancellation
  cancelled_at                    TIMESTAMPTZ NULL,
  cancelled_by_user_profile_id    BIGINT NULL REFERENCES public.user_profiles(id),
  cancel_reason                   TEXT NULL,

  -- Supersession (chain linking for reissue workflows)
  superseded_by_link_id           BIGINT NULL REFERENCES public.erp_output_public_links(id),

  -- Status / access
  status                          TEXT NOT NULL DEFAULT 'valid',
  access_level                    TEXT NOT NULL DEFAULT 'verify_only',

  -- Safe public data snapshots (JSON — never raw internal DB rows)
  verification_summary_json       JSONB NOT NULL DEFAULT '{}'::jsonb,
  public_payload_json             JSONB NOT NULL DEFAULT '{}'::jsonb,

  -- Optional download
  download_file_path              TEXT NULL,
  download_file_mime_type         TEXT NULL,
  download_file_name              TEXT NULL,
  download_enabled                BOOLEAN NOT NULL DEFAULT false,

  -- Analytics
  view_count                      INTEGER NOT NULL DEFAULT 0,
  last_viewed_at                  TIMESTAMPTZ NULL,

  -- Standard audit columns
  created_at                      TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by                      BIGINT NULL REFERENCES public.user_profiles(id),
  updated_at                      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_by                      BIGINT NULL REFERENCES public.user_profiles(id),
  deleted_at                      TIMESTAMPTZ NULL,

  -- CHECK constraints
  CONSTRAINT chk_output_link_status
    CHECK (status IN ('valid', 'expired', 'cancelled', 'superseded')),
  CONSTRAINT chk_output_link_access_level
    CHECK (access_level IN ('verify_only', 'summary', 'full_view', 'full_view_download_ready')),
  CONSTRAINT chk_output_link_type
    CHECK (output_type IN ('report', 'letter', 'certificate', 'form', 'external_submission', 'executive_ledger', 'other')),
  CONSTRAINT chk_output_token_min_length
    CHECK (length(public_token) >= 32),
  CONSTRAINT chk_view_count_non_negative
    CHECK (view_count >= 0)
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 3. INDEXES
-- ─────────────────────────────────────────────────────────────────────────────

-- Primary lookup: token → record (partial unique: only one active token per value)
CREATE UNIQUE INDEX IF NOT EXISTS uq_output_public_links_token_active
  ON public.erp_output_public_links (public_token)
  WHERE deleted_at IS NULL;

-- Status + expiry (for background expiry jobs)
CREATE INDEX IF NOT EXISTS idx_output_public_links_status_expires
  ON public.erp_output_public_links (status, expires_at)
  WHERE deleted_at IS NULL;

-- Owner company filter (admin list)
CREATE INDEX IF NOT EXISTS idx_output_public_links_owner_company
  ON public.erp_output_public_links (owner_company_id)
  WHERE deleted_at IS NULL;

-- Source entity lookup (revoke all links for an entity)
CREATE INDEX IF NOT EXISTS idx_output_public_links_source
  ON public.erp_output_public_links (source_module, source_entity_type, source_entity_id)
  WHERE deleted_at IS NULL;

-- Template / report run
CREATE INDEX IF NOT EXISTS idx_output_public_links_template
  ON public.erp_output_public_links (template_id)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_output_public_links_report_run
  ON public.erp_output_public_links (report_run_id)
  WHERE deleted_at IS NULL;

-- Recent first
CREATE INDEX IF NOT EXISTS idx_output_public_links_issued_at
  ON public.erp_output_public_links (issued_at DESC)
  WHERE deleted_at IS NULL;

-- ─────────────────────────────────────────────────────────────────────────────
-- 4. RLS
-- ─────────────────────────────────────────────────────────────────────────────

ALTER TABLE public.erp_output_public_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.erp_output_public_links FORCE ROW LEVEL SECURITY;

-- Policy: authenticated users with reports.view or reports.manage can SELECT
CREATE POLICY "output_public_links_select"
  ON public.erp_output_public_links
  FOR SELECT
  TO authenticated
  USING (
    deleted_at IS NULL
    AND (
      public.current_user_has_permission('reports.view')
      OR public.current_user_has_permission('reports.manage')
      OR public.current_user_has_permission('reports.publish')
      OR public.current_user_has_permission('reports.verify.admin')
      OR public.current_user_is_global_admin()
    )
  );

-- Policy: authenticated users with reports.publish or reports.manage can INSERT
CREATE POLICY "output_public_links_insert"
  ON public.erp_output_public_links
  FOR INSERT
  TO authenticated
  WITH CHECK (
    public.current_user_has_permission('reports.publish')
    OR public.current_user_has_permission('reports.manage')
    OR public.current_user_is_global_admin()
  );

-- Policy: authenticated users with reports.publish or reports.manage can UPDATE
CREATE POLICY "output_public_links_update"
  ON public.erp_output_public_links
  FOR UPDATE
  TO authenticated
  USING (
    deleted_at IS NULL
    AND (
      public.current_user_has_permission('reports.publish')
      OR public.current_user_has_permission('reports.manage')
      OR public.current_user_has_permission('reports.verify.admin')
      OR public.current_user_is_global_admin()
    )
  )
  WITH CHECK (
    public.current_user_has_permission('reports.publish')
    OR public.current_user_has_permission('reports.manage')
    OR public.current_user_has_permission('reports.verify.admin')
    OR public.current_user_is_global_admin()
  );

-- NO DELETE policy — soft delete only via deleted_at

-- ─────────────────────────────────────────────────────────────────────────────
-- 5. PUBLIC LOOKUP RPC (SECURITY DEFINER — safe for anon access)
--    Returns only sanitized public fields. Never exposes internal IDs.
--    Also increments view_count as a side effect.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.get_public_verification_by_token(p_token TEXT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_link public.erp_output_public_links%ROWTYPE;
  v_superseded_token TEXT;
  v_payload JSONB;
BEGIN
  -- Basic token sanity check (length >= 32 is enforced by DB constraint, but be safe)
  IF p_token IS NULL OR length(trim(p_token)) < 32 THEN
    RETURN NULL;
  END IF;

  SELECT * INTO v_link
  FROM public.erp_output_public_links
  WHERE public_token = p_token
    AND deleted_at IS NULL
  LIMIT 1;

  IF NOT FOUND THEN
    RETURN NULL;
  END IF;

  -- Auto-expire: if expires_at has passed and status is still valid, return expired state
  IF v_link.status = 'valid' AND v_link.expires_at IS NOT NULL AND v_link.expires_at < now() THEN
    UPDATE public.erp_output_public_links
    SET status = 'expired', updated_at = now()
    WHERE id = v_link.id;
    v_link.status := 'expired';
  END IF;

  -- Increment view count safely (non-blocking; ignore errors)
  BEGIN
    UPDATE public.erp_output_public_links
    SET view_count = view_count + 1,
        last_viewed_at = now()
    WHERE id = v_link.id;
  EXCEPTION WHEN OTHERS THEN
    NULL; -- Never fail the public page due to analytics error
  END;

  -- Lookup superseded_by token (safe: only public_token, no internal IDs)
  IF v_link.superseded_by_link_id IS NOT NULL THEN
    SELECT sub.public_token INTO v_superseded_token
    FROM public.erp_output_public_links sub
    WHERE sub.id = v_link.superseded_by_link_id
      AND sub.deleted_at IS NULL;
  END IF;

  -- Determine safe public_payload based on access_level and status
  v_payload := CASE
    WHEN v_link.status != 'valid' THEN '{}'::jsonb
    WHEN v_link.access_level IN ('full_view', 'full_view_download_ready') THEN v_link.public_payload_json
    WHEN v_link.access_level = 'summary' THEN v_link.verification_summary_json
    ELSE '{}'::jsonb
  END;

  RETURN jsonb_build_object(
    'status',                  v_link.status,
    'access_level',            v_link.access_level,
    'output_type',             v_link.output_type,
    'document_title',          v_link.document_title,
    'document_subtitle',       v_link.document_subtitle,
    'document_ref',            v_link.document_ref,
    'document_date',           v_link.document_date,
    'issued_at',               v_link.issued_at,
    'expires_at',              v_link.expires_at,
    'cancelled_at',            v_link.cancelled_at,
    'cancel_reason',           CASE WHEN v_link.status = 'cancelled' THEN v_link.cancel_reason ELSE NULL END,
    'verification_summary',    v_link.verification_summary_json,
    'public_payload',          v_payload,
    'download_enabled',        (v_link.download_enabled AND v_link.access_level = 'full_view_download_ready' AND v_link.status = 'valid'),
    'superseded_by_token',     v_superseded_token
  );
END;
$$;

-- Grant execute to anon and authenticated (SECURITY DEFINER makes this safe)
GRANT EXECUTE ON FUNCTION public.get_public_verification_by_token(TEXT) TO anon, authenticated;

-- ─────────────────────────────────────────────────────────────────────────────
-- 6. updated_at trigger
-- ─────────────────────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.set_updated_at_output_public_links()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_output_public_links_updated_at
  BEFORE UPDATE ON public.erp_output_public_links
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_output_public_links();
