-- ============================================================================
-- ERP BASE 002F.3B — Global Lookup / Dropdown Engine
-- ============================================================================
-- Created: 2026-06-05
-- Purpose: Master data lookup categories and values for standardized dropdowns
-- Features:
--   - Global lookup categories with scope/module support
--   - Lookup values with hierarchy, sort order, effective dates
--   - Color/icon/badge metadata for UI display
--   - Default value support
--   - System-locked values for critical data
--   - Active/inactive status management
--   - Full audit trail
-- ============================================================================

-- ============================================================================
-- TABLE: global_lookup_categories
-- ============================================================================
-- Stores lookup category definitions that can be used across the ERP

create table if not exists public.global_lookup_categories (
  id bigint generated by default as identity primary key,
  
  -- Category identification
  category_code text not null unique,
  category_name_en text not null,
  category_name_ar text,
  description text,
  module_code text,
  
  -- Scope and behavior
  category_scope text not null default 'GLOBAL' check (category_scope in ('GLOBAL', 'COMPANY', 'BRANCH', 'MODULE')),
  supports_hierarchy boolean not null default false,
  supports_color boolean not null default false,
  supports_icon boolean not null default false,
  supports_effective_dates boolean not null default false,
  supports_metadata boolean not null default true,
  
  -- Status and governance
  is_system boolean not null default false,
  is_locked boolean not null default false,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  
  -- Audit fields
  created_at timestamptz not null default now(),
  created_by bigint,
  updated_at timestamptz not null default now(),
  updated_by bigint,
  deactivated_at timestamptz,
  deactivated_by bigint,
  deactivation_reason text,
  
  -- Constraints
  check (category_code = upper(category_code)),
  check (category_code ~ '^[A-Z0-9_]+$'),
  check (
    (is_active = true and deactivated_at is null) or
    (is_active = false and deactivated_at is not null)
  )
);

-- Comments
comment on table public.global_lookup_categories is 'Master data lookup categories for standardized ERP dropdowns';
comment on column public.global_lookup_categories.category_code is 'Unique uppercase code for programmatic reference (e.g., STATUS_TYPES)';
comment on column public.global_lookup_categories.category_scope is 'GLOBAL = enterprise-wide, COMPANY = per-company, BRANCH = per-branch, MODULE = module-specific';
comment on column public.global_lookup_categories.supports_hierarchy is 'True if values can have parent-child relationships';
comment on column public.global_lookup_categories.supports_color is 'True if values can have color metadata (e.g., for status badges)';
comment on column public.global_lookup_categories.supports_icon is 'True if values can have icon metadata';
comment on column public.global_lookup_categories.supports_effective_dates is 'True if values can have effective date ranges';
comment on column public.global_lookup_categories.is_system is 'True if category is system-managed and critical';
comment on column public.global_lookup_categories.is_locked is 'True if category cannot be modified (requires special permission)';

-- Indexes
create index if not exists idx_global_lookup_categories_code on public.global_lookup_categories(category_code);
create index if not exists idx_global_lookup_categories_module on public.global_lookup_categories(module_code) where module_code is not null;
create index if not exists idx_global_lookup_categories_active on public.global_lookup_categories(is_active);
create index if not exists idx_global_lookup_categories_system on public.global_lookup_categories(is_system);
create index if not exists idx_global_lookup_categories_locked on public.global_lookup_categories(is_locked);
create index if not exists idx_global_lookup_categories_sort on public.global_lookup_categories(sort_order);

-- Trigger for updated_at
create trigger trigger_global_lookup_categories_updated_at
  before update on public.global_lookup_categories
  for each row
  execute function public.set_updated_at();

-- ============================================================================
-- TABLE: global_lookup_values
-- ============================================================================
-- Stores individual lookup values within categories

create table if not exists public.global_lookup_values (
  id bigint generated by default as identity primary key,
  
  -- Category reference
  category_id bigint not null references public.global_lookup_categories(id) on delete restrict,
  
  -- Value identification
  value_code text not null,
  value_label_en text not null,
  value_label_ar text,
  description text,
  
  -- Hierarchy
  parent_value_id bigint references public.global_lookup_values(id) on delete restrict,
  
  -- Display metadata
  color_hex text,
  icon_name text,
  badge_variant text,
  sort_order integer not null default 0,
  
  -- Value properties
  is_default boolean not null default false,
  is_system boolean not null default false,
  is_locked boolean not null default false,
  is_active boolean not null default true,
  
  -- Effective dates
  effective_from date,
  effective_to date,
  
  -- Extensibility
  metadata_json jsonb not null default '{}'::jsonb,
  
  -- Audit fields
  created_at timestamptz not null default now(),
  created_by bigint,
  updated_at timestamptz not null default now(),
  updated_by bigint,
  deactivated_at timestamptz,
  deactivated_by bigint,
  deactivation_reason text,
  
  -- Constraints
  unique(category_id, value_code),
  check (value_code = upper(value_code)),
  check (value_code ~ '^[A-Z0-9_]+$'),
  check (parent_value_id is null or parent_value_id != id),
  check (color_hex is null or color_hex ~ '^#[0-9A-Fa-f]{6}$'),
  check (effective_to is null or effective_from is null or effective_to >= effective_from),
  check (
    (is_active = true and deactivated_at is null) or
    (is_active = false and deactivated_at is not null)
  )
);

-- Comments
comment on table public.global_lookup_values is 'Individual lookup values within categories';
comment on column public.global_lookup_values.value_code is 'Unique code within category (e.g., ACTIVE, PENDING)';
comment on column public.global_lookup_values.parent_value_id is 'Parent value ID for hierarchical lookups (must be same category)';
comment on column public.global_lookup_values.color_hex is 'Color for UI badges (e.g., #22C55E for success/active)';
comment on column public.global_lookup_values.icon_name is 'Icon name from UI icon library';
comment on column public.global_lookup_values.badge_variant is 'Badge variant for UI (e.g., success, warning, danger)';
comment on column public.global_lookup_values.is_default is 'True if this is the default value for new records';
comment on column public.global_lookup_values.effective_from is 'Value becomes active on this date';
comment on column public.global_lookup_values.effective_to is 'Value becomes inactive after this date';
comment on column public.global_lookup_values.metadata_json is 'Flexible JSONB for module-specific metadata';

-- Indexes
create index if not exists idx_global_lookup_values_category on public.global_lookup_values(category_id);
create index if not exists idx_global_lookup_values_parent on public.global_lookup_values(parent_value_id) where parent_value_id is not null;
create index if not exists idx_global_lookup_values_active on public.global_lookup_values(is_active);
create index if not exists idx_global_lookup_values_system on public.global_lookup_values(is_system);
create index if not exists idx_global_lookup_values_locked on public.global_lookup_values(is_locked);
create index if not exists idx_global_lookup_values_default on public.global_lookup_values(is_default) where is_default = true;
create index if not exists idx_global_lookup_values_effective on public.global_lookup_values(effective_from, effective_to);
create index if not exists idx_global_lookup_values_category_sort on public.global_lookup_values(category_id, sort_order);

-- Trigger for updated_at
create trigger trigger_global_lookup_values_updated_at
  before update on public.global_lookup_values
  for each row
  execute function public.set_updated_at();

-- ============================================================================
-- VALIDATION FUNCTION: Check parent value belongs to same category
-- ============================================================================

create or replace function public.validate_lookup_value_parent()
returns trigger
language plpgsql
as $$
begin
  -- Check that parent value belongs to the same category
  if new.parent_value_id is not null then
    if not exists (
      select 1 from public.global_lookup_values
      where id = new.parent_value_id
      and category_id = new.category_id
    ) then
      raise exception 'Parent value must belong to the same category';
    end if;
  end if;
  
  return new;
end;
$$;

-- Trigger for parent validation
create trigger trigger_validate_lookup_value_parent
  before insert or update on public.global_lookup_values
  for each row
  execute function public.validate_lookup_value_parent();

-- ============================================================================
-- PERMISSIONS SEED
-- ============================================================================

-- Insert permissions for master data lookups
insert into public.permissions (permission_code, permission_name, module_code, action_code, description, is_active)
values
  ('master_data.dashboard.view', 'View Master Data Dashboard', 'master_data', 'view', 'Access master data dashboard and statistics', true),
  ('master_data.lookups.view', 'View Global Lookups', 'master_data', 'view', 'View lookup categories and values', true),
  ('master_data.lookups.manage', 'Manage Global Lookups', 'master_data', 'manage', 'Create, edit, and deactivate lookup categories and values', true),
  ('master_data.lookups.lock', 'Lock/Unlock Lookups', 'master_data', 'lock', 'Lock or unlock system-critical lookup values', true),
  ('master_data.lookups.import', 'Import Lookup Data', 'master_data', 'import', 'Import lookup data from external files (future)', true),
  ('master_data.lookups.export', 'Export Lookup Data', 'master_data', 'export', 'Export lookup data to files', true),
  ('master_data.lookups.audit_view', 'View Lookup Audit Logs', 'master_data', 'audit_view', 'View audit history for lookup changes', true)
on conflict (permission_code) do nothing;

-- ============================================================================
-- ROLE PERMISSIONS SEED
-- ============================================================================

-- Assign permissions to roles
do $$
declare
  v_system_admin_role_id bigint;
  v_group_admin_role_id bigint;
  v_company_admin_role_id bigint;
  v_branch_admin_role_id bigint;
  v_permission_id bigint;
begin
  -- Get role IDs
  select id into v_system_admin_role_id from public.roles where role_code = 'system_admin';
  select id into v_group_admin_role_id from public.roles where role_code = 'group_admin';
  select id into v_company_admin_role_id from public.roles where role_code = 'company_admin';
  select id into v_branch_admin_role_id from public.roles where role_code = 'branch_admin';
  
  -- system_admin: all 7 permissions
  for v_permission_id in
    select id from public.permissions
    where permission_code like 'master_data.%'
  loop
    insert into public.role_permissions (role_id, permission_id)
    values (v_system_admin_role_id, v_permission_id)
    on conflict (role_id, permission_id) do nothing;
  end loop;
  
  -- group_admin: dashboard, view, manage, export, audit_view
  for v_permission_id in
    select id from public.permissions
    where permission_code in (
      'master_data.dashboard.view',
      'master_data.lookups.view',
      'master_data.lookups.manage',
      'master_data.lookups.export',
      'master_data.lookups.audit_view'
    )
  loop
    insert into public.role_permissions (role_id, permission_id)
    values (v_group_admin_role_id, v_permission_id)
    on conflict (role_id, permission_id) do nothing;
  end loop;
  
  -- company_admin: dashboard, view, export
  for v_permission_id in
    select id from public.permissions
    where permission_code in (
      'master_data.dashboard.view',
      'master_data.lookups.view',
      'master_data.lookups.export'
    )
  loop
    insert into public.role_permissions (role_id, permission_id)
    values (v_company_admin_role_id, v_permission_id)
    on conflict (role_id, permission_id) do nothing;
  end loop;
  
  -- branch_admin: view only
  select id into v_permission_id from public.permissions where permission_code = 'master_data.lookups.view';
  insert into public.role_permissions (role_id, permission_id)
  values (v_branch_admin_role_id, v_permission_id)
  on conflict (role_id, permission_id) do nothing;
end $$;

-- ============================================================================
-- ROW LEVEL SECURITY (RLS)
-- ============================================================================

-- Enable RLS
alter table public.global_lookup_categories enable row level security;
alter table public.global_lookup_values enable row level security;

-- RLS Policy: SELECT - Admin page access requires permission
create policy select_lookup_categories_admin
  on public.global_lookup_categories
  for select
  to authenticated
  using (
    exists (
      select 1 from public.user_profiles up
      join public.user_roles ur on ur.user_profile_id = up.id and ur.is_active = true
      join public.role_permissions rp on rp.role_id = ur.role_id
      join public.permissions p on p.id = rp.permission_id and p.is_active = true
      where up.auth_user_id = auth.uid()
      and p.permission_code = 'master_data.lookups.view'
    )
  );

create policy select_lookup_values_admin
  on public.global_lookup_values
  for select
  to authenticated
  using (
    exists (
      select 1 from public.user_profiles up
      join public.user_roles ur on ur.user_profile_id = up.id and ur.is_active = true
      join public.role_permissions rp on rp.role_id = ur.role_id
      join public.permissions p on p.id = rp.permission_id and p.is_active = true
      where up.auth_user_id = auth.uid()
      and p.permission_code = 'master_data.lookups.view'
    )
  );

-- RLS Policy: INSERT - Requires manage permission
create policy insert_lookup_categories
  on public.global_lookup_categories
  for insert
  to authenticated
  with check (
    exists (
      select 1 from public.user_profiles up
      join public.user_roles ur on ur.user_profile_id = up.id and ur.is_active = true
      join public.role_permissions rp on rp.role_id = ur.role_id
      join public.permissions p on p.id = rp.permission_id and p.is_active = true
      where up.auth_user_id = auth.uid()
      and p.permission_code = 'master_data.lookups.manage'
    )
  );

create policy insert_lookup_values
  on public.global_lookup_values
  for insert
  to authenticated
  with check (
    exists (
      select 1 from public.user_profiles up
      join public.user_roles ur on ur.user_profile_id = up.id and ur.is_active = true
      join public.role_permissions rp on rp.role_id = ur.role_id
      join public.permissions p on p.id = rp.permission_id and p.is_active = true
      where up.auth_user_id = auth.uid()
      and p.permission_code = 'master_data.lookups.manage'
    )
  );

-- RLS Policy: UPDATE - Non-locked rows require manage, locked rows require lock permission
create policy update_lookup_categories
  on public.global_lookup_categories
  for update
  to authenticated
  using (
    case
      when is_locked = true then
        exists (
          select 1 from public.user_profiles up
          join public.user_roles ur on ur.user_profile_id = up.id and ur.is_active = true
          join public.role_permissions rp on rp.role_id = ur.role_id
          join public.permissions p on p.id = rp.permission_id and p.is_active = true
          where up.auth_user_id = auth.uid()
          and p.permission_code = 'master_data.lookups.lock'
        )
      else
        exists (
          select 1 from public.user_profiles up
          join public.user_roles ur on ur.user_profile_id = up.id and ur.is_active = true
          join public.role_permissions rp on rp.role_id = ur.role_id
          join public.permissions p on p.id = rp.permission_id and p.is_active = true
          where up.auth_user_id = auth.uid()
          and p.permission_code = 'master_data.lookups.manage'
        )
    end
  );

create policy update_lookup_values
  on public.global_lookup_values
  for update
  to authenticated
  using (
    case
      when is_locked = true then
        exists (
          select 1 from public.user_profiles up
          join public.user_roles ur on ur.user_profile_id = up.id and ur.is_active = true
          join public.role_permissions rp on rp.role_id = ur.role_id
          join public.permissions p on p.id = rp.permission_id and p.is_active = true
          where up.auth_user_id = auth.uid()
          and p.permission_code = 'master_data.lookups.lock'
        )
      else
        exists (
          select 1 from public.user_profiles up
          join public.user_roles ur on ur.user_profile_id = up.id and ur.is_active = true
          join public.role_permissions rp on rp.role_id = ur.role_id
          join public.permissions p on p.id = rp.permission_id and p.is_active = true
          where up.auth_user_id = auth.uid()
          and p.permission_code = 'master_data.lookups.manage'
        )
    end
  );

-- RLS Policy: DELETE - Completely blocked
-- No delete policies = no one can delete

-- ============================================================================
-- SEED LOOKUP CATEGORIES
-- ============================================================================

insert into public.global_lookup_categories (
  category_code, category_name_en, category_name_ar, description, module_code,
  category_scope, supports_hierarchy, supports_color, supports_icon,
  supports_effective_dates, supports_metadata,
  is_system, is_locked, is_active, sort_order
) values
  ('STATUS_TYPES', 'Status Types', 'أنواع الحالة', 'Generic status values (Active, Inactive, Pending, etc.)', null, 'GLOBAL', false, true, true, false, true, true, true, true, 10),
  ('PRIORITY_LEVELS', 'Priority Levels', 'مستويات الأولوية', 'Priority levels for tasks, tickets, and requests', null, 'GLOBAL', false, true, true, false, true, true, true, true, 20),
  ('APPROVAL_STATUS_TYPES', 'Approval Status Types', 'أنواع حالة الموافقة', 'Approval workflow statuses', null, 'GLOBAL', false, true, true, false, true, true, true, true, 30),
  ('RECORD_VISIBILITY_TYPES', 'Record Visibility Types', 'أنواع رؤية السجل', 'Record visibility and sharing levels', null, 'GLOBAL', false, false, true, false, true, true, true, true, 40),
  ('YES_NO_TYPES', 'Yes/No Types', 'نعم/لا', 'Simple yes/no boolean values', null, 'GLOBAL', false, false, false, false, true, true, true, true, 50),
  ('PHONE_TYPES', 'Phone Types', 'أنواع الهاتف', 'Phone number types (Mobile, Office, Home, Fax)', null, 'GLOBAL', false, false, true, false, true, true, true, true, 60),
  ('EMAIL_TYPES', 'Email Types', 'أنواع البريد الإلكتروني', 'Email address types (Primary, Work, Personal)', null, 'GLOBAL', false, false, true, false, true, true, true, true, 70),
  ('ADDRESS_TYPES', 'Address Types', 'أنواع العنوان', 'Address types (Registered, Physical, Billing, Shipping)', null, 'GLOBAL', false, false, true, false, true, true, true, true, 80),
  ('GENDER_TYPES', 'Gender Types', 'أنواع الجنس', 'Gender identification values', 'HR', 'GLOBAL', false, false, false, false, true, true, true, true, 90),
  ('RELATIONSHIP_TYPES', 'Relationship Types', 'أنواع العلاقة', 'Relationship types for contacts and emergency contacts', 'HR', 'GLOBAL', false, false, false, false, true, true, true, true, 100),
  ('DOCUMENT_STATUS_TYPES', 'Document Status Types', 'أنواع حالة الوثيقة', 'Document lifecycle statuses', 'DMS', 'GLOBAL', false, true, true, false, true, true, true, true, 110),
  ('RISK_LEVELS', 'Risk Levels', 'مستويات المخاطر', 'Risk assessment levels', 'HSE', 'GLOBAL', false, true, true, false, true, true, true, true, 120),
  ('SEVERITY_LEVELS', 'Severity Levels', 'مستويات الخطورة', 'Incident severity levels', 'HSE', 'GLOBAL', false, true, true, false, true, true, true, true, 130)
on conflict (category_code) do nothing;

-- ============================================================================
-- SEED LOOKUP VALUES
-- ============================================================================

-- Get category IDs for seeding values
do $$
declare
  v_cat_id bigint;
begin
  -- STATUS_TYPES
  select id into v_cat_id from public.global_lookup_categories where category_code = 'STATUS_TYPES';
  insert into public.global_lookup_values (category_id, value_code, value_label_en, value_label_ar, color_hex, badge_variant, sort_order, is_default, is_system, is_locked, is_active)
  values
    (v_cat_id, 'ACTIVE', 'Active', 'نشط', '#22C55E', 'success', 10, true, true, true, true),
    (v_cat_id, 'INACTIVE', 'Inactive', 'غير نشط', '#94A3B8', 'secondary', 20, false, true, true, true),
    (v_cat_id, 'PENDING', 'Pending', 'قيد الانتظار', '#F59E0B', 'warning', 30, false, true, true, true),
    (v_cat_id, 'SUSPENDED', 'Suspended', 'معلق', '#EF4444', 'destructive', 40, false, true, true, true),
    (v_cat_id, 'DRAFT', 'Draft', 'مسودة', '#64748B', 'outline', 50, false, true, true, true),
    (v_cat_id, 'ARCHIVED', 'Archived', 'مؤرشف', '#475569', 'secondary', 60, false, true, true, true)
  on conflict (category_id, value_code) do nothing;

  -- PRIORITY_LEVELS
  select id into v_cat_id from public.global_lookup_categories where category_code = 'PRIORITY_LEVELS';
  insert into public.global_lookup_values (category_id, value_code, value_label_en, value_label_ar, color_hex, badge_variant, sort_order, is_default, is_system, is_locked, is_active)
  values
    (v_cat_id, 'CRITICAL', 'Critical', 'حرج', '#DC2626', 'destructive', 10, false, true, true, true),
    (v_cat_id, 'HIGH', 'High', 'عالي', '#EA580C', 'destructive', 20, false, true, true, true),
    (v_cat_id, 'MEDIUM', 'Medium', 'متوسط', '#F59E0B', 'warning', 30, true, true, true, true),
    (v_cat_id, 'LOW', 'Low', 'منخفض', '#3B82F6', 'default', 40, false, true, true, true),
    (v_cat_id, 'MINIMAL', 'Minimal', 'ضئيل', '#94A3B8', 'secondary', 50, false, true, true, true)
  on conflict (category_id, value_code) do nothing;

  -- APPROVAL_STATUS_TYPES
  select id into v_cat_id from public.global_lookup_categories where category_code = 'APPROVAL_STATUS_TYPES';
  insert into public.global_lookup_values (category_id, value_code, value_label_en, value_label_ar, color_hex, badge_variant, sort_order, is_default, is_system, is_locked, is_active)
  values
    (v_cat_id, 'DRAFT', 'Draft', 'مسودة', '#64748B', 'outline', 10, true, true, true, true),
    (v_cat_id, 'PENDING_APPROVAL', 'Pending Approval', 'قيد الموافقة', '#F59E0B', 'warning', 20, false, true, true, true),
    (v_cat_id, 'APPROVED', 'Approved', 'موافق عليه', '#22C55E', 'success', 30, false, true, true, true),
    (v_cat_id, 'REJECTED', 'Rejected', 'مرفوض', '#EF4444', 'destructive', 40, false, true, true, true),
    (v_cat_id, 'RETURNED', 'Returned for Revision', 'أعيد للمراجعة', '#3B82F6', 'default', 50, false, true, true, true),
    (v_cat_id, 'CANCELLED', 'Cancelled', 'ملغى', '#94A3B8', 'secondary', 60, false, true, true, true)
  on conflict (category_id, value_code) do nothing;

  -- RECORD_VISIBILITY_TYPES
  select id into v_cat_id from public.global_lookup_categories where category_code = 'RECORD_VISIBILITY_TYPES';
  insert into public.global_lookup_values (category_id, value_code, value_label_en, value_label_ar, description, sort_order, is_default, is_system, is_locked, is_active)
  values
    (v_cat_id, 'PRIVATE', 'Private', 'خاص', 'Visible only to creator', 10, false, true, true, true),
    (v_cat_id, 'BRANCH', 'Branch', 'الفرع', 'Visible to branch users', 20, false, true, true, true),
    (v_cat_id, 'COMPANY', 'Company', 'الشركة', 'Visible to company users', 30, true, true, true, true),
    (v_cat_id, 'GROUP', 'Group', 'المجموعة', 'Visible to group users', 40, false, true, true, true),
    (v_cat_id, 'PUBLIC', 'Public', 'عام', 'Visible to all users', 50, false, true, true, true)
  on conflict (category_id, value_code) do nothing;

  -- YES_NO_TYPES
  select id into v_cat_id from public.global_lookup_categories where category_code = 'YES_NO_TYPES';
  insert into public.global_lookup_values (category_id, value_code, value_label_en, value_label_ar, sort_order, is_default, is_system, is_locked, is_active)
  values
    (v_cat_id, 'YES', 'Yes', 'نعم', 10, false, true, true, true),
    (v_cat_id, 'NO', 'No', 'لا', 20, true, true, true, true)
  on conflict (category_id, value_code) do nothing;

  -- PHONE_TYPES
  select id into v_cat_id from public.global_lookup_categories where category_code = 'PHONE_TYPES';
  insert into public.global_lookup_values (category_id, value_code, value_label_en, value_label_ar, icon_name, sort_order, is_default, is_system, is_locked, is_active)
  values
    (v_cat_id, 'MOBILE', 'Mobile', 'جوال', 'smartphone', 10, true, true, true, true),
    (v_cat_id, 'OFFICE', 'Office', 'مكتب', 'phone', 20, false, true, true, true),
    (v_cat_id, 'HOME', 'Home', 'منزل', 'home', 30, false, true, true, true),
    (v_cat_id, 'FAX', 'Fax', 'فاكس', 'printer', 40, false, true, true, true)
  on conflict (category_id, value_code) do nothing;

  -- EMAIL_TYPES
  select id into v_cat_id from public.global_lookup_categories where category_code = 'EMAIL_TYPES';
  insert into public.global_lookup_values (category_id, value_code, value_label_en, value_label_ar, icon_name, sort_order, is_default, is_system, is_locked, is_active)
  values
    (v_cat_id, 'PRIMARY', 'Primary', 'أساسي', 'mail', 10, true, true, true, true),
    (v_cat_id, 'WORK', 'Work', 'عمل', 'briefcase', 20, false, true, true, true),
    (v_cat_id, 'PERSONAL', 'Personal', 'شخصي', 'user', 30, false, true, true, true)
  on conflict (category_id, value_code) do nothing;

  -- ADDRESS_TYPES
  select id into v_cat_id from public.global_lookup_categories where category_code = 'ADDRESS_TYPES';
  insert into public.global_lookup_values (category_id, value_code, value_label_en, value_label_ar, icon_name, sort_order, is_default, is_system, is_locked, is_active)
  values
    (v_cat_id, 'REGISTERED', 'Registered Office', 'المكتب المسجل', 'landmark', 10, true, true, true, true),
    (v_cat_id, 'PHYSICAL', 'Physical Location', 'الموقع الفعلي', 'map-pin', 20, false, true, true, true),
    (v_cat_id, 'BILLING', 'Billing Address', 'عنوان الفواتير', 'receipt', 30, false, true, true, true),
    (v_cat_id, 'SHIPPING', 'Shipping Address', 'عنوان الشحن', 'truck', 40, false, true, true, true)
  on conflict (category_id, value_code) do nothing;

  -- GENDER_TYPES
  select id into v_cat_id from public.global_lookup_categories where category_code = 'GENDER_TYPES';
  insert into public.global_lookup_values (category_id, value_code, value_label_en, value_label_ar, sort_order, is_default, is_system, is_locked, is_active)
  values
    (v_cat_id, 'MALE', 'Male', 'ذكر', 10, false, true, true, true),
    (v_cat_id, 'FEMALE', 'Female', 'أنثى', 20, false, true, true, true),
    (v_cat_id, 'OTHER', 'Other', 'آخر', 30, false, true, true, true),
    (v_cat_id, 'PREFER_NOT_TO_SAY', 'Prefer Not to Say', 'أفضل عدم الإفصاح', 40, false, true, true, true)
  on conflict (category_id, value_code) do nothing;

  -- RELATIONSHIP_TYPES
  select id into v_cat_id from public.global_lookup_categories where category_code = 'RELATIONSHIP_TYPES';
  insert into public.global_lookup_values (category_id, value_code, value_label_en, value_label_ar, sort_order, is_default, is_system, is_locked, is_active)
  values
    (v_cat_id, 'SPOUSE', 'Spouse', 'الزوج/الزوجة', 10, false, true, true, true),
    (v_cat_id, 'PARENT', 'Parent', 'الوالد/الوالدة', 20, false, true, true, true),
    (v_cat_id, 'CHILD', 'Child', 'طفل', 30, false, true, true, true),
    (v_cat_id, 'SIBLING', 'Sibling', 'شقيق/شقيقة', 40, false, true, true, true),
    (v_cat_id, 'FRIEND', 'Friend', 'صديق', 50, false, true, true, true),
    (v_cat_id, 'COLLEAGUE', 'Colleague', 'زميل', 60, false, true, true, true),
    (v_cat_id, 'OTHER', 'Other', 'آخر', 70, false, true, true, true)
  on conflict (category_id, value_code) do nothing;

  -- DOCUMENT_STATUS_TYPES
  select id into v_cat_id from public.global_lookup_categories where category_code = 'DOCUMENT_STATUS_TYPES';
  insert into public.global_lookup_values (category_id, value_code, value_label_en, value_label_ar, color_hex, badge_variant, sort_order, is_default, is_system, is_locked, is_active)
  values
    (v_cat_id, 'DRAFT', 'Draft', 'مسودة', '#64748B', 'outline', 10, true, true, true, true),
    (v_cat_id, 'UNDER_REVIEW', 'Under Review', 'قيد المراجعة', '#3B82F6', 'default', 20, false, true, true, true),
    (v_cat_id, 'APPROVED', 'Approved', 'موافق عليه', '#22C55E', 'success', 30, false, true, true, true),
    (v_cat_id, 'PUBLISHED', 'Published', 'منشور', '#10B981', 'success', 40, false, true, true, true),
    (v_cat_id, 'EXPIRED', 'Expired', 'منتهي الصلاحية', '#F59E0B', 'warning', 50, false, true, true, true),
    (v_cat_id, 'ARCHIVED', 'Archived', 'مؤرشف', '#475569', 'secondary', 60, false, true, true, true)
  on conflict (category_id, value_code) do nothing;

  -- RISK_LEVELS
  select id into v_cat_id from public.global_lookup_categories where category_code = 'RISK_LEVELS';
  insert into public.global_lookup_values (category_id, value_code, value_label_en, value_label_ar, color_hex, badge_variant, sort_order, is_default, is_system, is_locked, is_active)
  values
    (v_cat_id, 'EXTREME', 'Extreme', 'شديد الخطورة', '#7F1D1D', 'destructive', 10, false, true, true, true),
    (v_cat_id, 'HIGH', 'High', 'عالي', '#DC2626', 'destructive', 20, false, true, true, true),
    (v_cat_id, 'MEDIUM', 'Medium', 'متوسط', '#F59E0B', 'warning', 30, true, true, true, true),
    (v_cat_id, 'LOW', 'Low', 'منخفض', '#3B82F6', 'default', 40, false, true, true, true),
    (v_cat_id, 'MINIMAL', 'Minimal', 'ضئيل', '#22C55E', 'success', 50, false, true, true, true)
  on conflict (category_id, value_code) do nothing;

  -- SEVERITY_LEVELS
  select id into v_cat_id from public.global_lookup_categories where category_code = 'SEVERITY_LEVELS';
  insert into public.global_lookup_values (category_id, value_code, value_label_en, value_label_ar, color_hex, badge_variant, sort_order, is_default, is_system, is_locked, is_active)
  values
    (v_cat_id, 'FATAL', 'Fatal', 'قاتل', '#7F1D1D', 'destructive', 10, false, true, true, true),
    (v_cat_id, 'MAJOR', 'Major', 'كبير', '#DC2626', 'destructive', 20, false, true, true, true),
    (v_cat_id, 'MODERATE', 'Moderate', 'معتدل', '#F59E0B', 'warning', 30, true, true, true, true),
    (v_cat_id, 'MINOR', 'Minor', 'بسيط', '#3B82F6', 'default', 40, false, true, true, true),
    (v_cat_id, 'NEGLIGIBLE', 'Negligible', 'ضئيل', '#22C55E', 'success', 50, false, true, true, true)
  on conflict (category_id, value_code) do nothing;

end $$;

-- ============================================================================
-- MIGRATION COMPLETE
-- ============================================================================
-- ERP BASE 002F.3B — Global Lookup / Dropdown Engine
-- Tables: global_lookup_categories, global_lookup_values
-- Permissions: 7 master_data permissions
-- RLS: Enabled with admin access control
-- Seed Data: 13 foundation categories, 70+ values
-- ============================================================================
